/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Claude Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This test verifies that _txm_module_manager_object_deallocate() correctly
   detects and cleans up live kernel objects before releasing their backing
   memory to the module object pool.

   Covered object types: TX_TIMER, TX_THREAD, TX_SEMAPHORE, TX_MUTEX,
   TX_QUEUE, TX_EVENT_FLAGS_GROUP, TX_BLOCK_POOL, TX_BYTE_POOL.

   Also covered:
   - TXM_MODULE_OBJECT_DEALLOC_STRICT mode: TX_DELETE_ERROR returned for
     live objects, TX_SUCCESS returned for already-deleted objects.
   - Already-deleted object (ID == TX_CLEAR_ID): no double-delete, pool
     memory is safely released.
*/

#include <stdio.h>
#include "tx_api.h"
#include "tx_thread.h"
#include "tx_timer.h"
#include "tx_semaphore.h"
#include "tx_mutex.h"
#include "tx_queue.h"
#include "tx_event_flags.h"
#include "tx_block_pool.h"
#include "tx_byte_pool.h"
#include "txm_module.h"

/* Module manager internal symbols needed for direct testing.  */
extern UINT   _txm_module_manager_object_pool_created;
extern UINT   _txm_module_manager_ready;
extern TX_MUTEX _txm_module_manager_mutex;

UINT _txm_module_manager_object_allocate(VOID **object_ptr_ptr, ULONG object_size, TXM_MODULE_INSTANCE *module_instance);
UINT _txm_module_manager_object_deallocate(VOID *object_ptr);
UINT _txm_module_manager_object_pool_create(VOID *object_memory, ULONG object_memory_size);
UINT _txm_module_manager_initialize(VOID *module_memory_start, ULONG module_memory_size);

/* Prototype for test control return.  */
void test_control_return(UINT status);


/* ---- Static test resources -------------------------------------------- */

static TX_THREAD    test_thread_0;

/* Stack for the main test thread.  */
static ULONG        thread_0_stack[TEST_STACK_SIZE_PRINTF / sizeof(ULONG)];

/* Pool backing the module object allocator.  */
#define OBJECT_POOL_SIZE    8192U
static ULONG        object_pool_area[OBJECT_POOL_SIZE / sizeof(ULONG)];

/* Dummy module data area (required by _txm_module_manager_initialize).  */
#define MODULE_MEM_SIZE     4096U
static ULONG        module_mem_area[MODULE_MEM_SIZE / sizeof(ULONG)];

/* Backing memory for a TX_QUEUE allocated from the module object pool.  */
#define QUEUE_STORAGE_WORDS 16U
static ULONG        queue_storage[QUEUE_STORAGE_WORDS];

/* Backing memory for a TX_BLOCK_POOL allocated from the module object pool. */
#define BLOCK_POOL_SIZE     512U
static ULONG        block_pool_mem[BLOCK_POOL_SIZE / sizeof(ULONG)];

/* Backing memory for a TX_BYTE_POOL allocated from the module object pool.  */
#define BYTE_POOL_SIZE      512U
static ULONG        byte_pool_mem[BYTE_POOL_SIZE / sizeof(ULONG)];

/* Stack for the module-allocated test thread.  */
#define MODULE_THREAD_STACK_SIZE  1024U
static ULONG        module_thread_stack[MODULE_THREAD_STACK_SIZE / sizeof(ULONG)];

/* Synthetic module instance used as the owner of all allocated objects.  */
static TXM_MODULE_INSTANCE  test_module_instance;

static ULONG        error_count = 0;

/* Forward declarations.  */
static void thread_0_entry(ULONG thread_input);
static void module_thread_entry(ULONG thread_input);


/* ---- Application define ----------------------------------------------- */

#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void threadx_module_object_dealloc_live_application_define(void *first_unused_memory)
#endif
{
UINT status;

    /* Suppress unused parameter warning.  */
    (VOID) first_unused_memory;

    status = tx_thread_create(&test_thread_0, "test thread 0",
                              thread_0_entry, 0,
                              thread_0_stack, sizeof(thread_0_stack),
                              4, 4, TX_NO_TIME_SLICE, TX_AUTO_START);
    if (status != TX_SUCCESS)
    {
        printf("Running Module Object Dealloc Live Test........................... ERROR #0\n");
        test_control_return(1);
    }
}


/* ---- Helpers ---------------------------------------------------------- */

/* Allocate one object from the module pool and verify the allocation.  */
static VOID *alloc_object(ULONG size)
{
VOID  *obj = TX_NULL;
UINT   status;

    status = _txm_module_manager_object_allocate(&obj, size, &test_module_instance);
    if ((status != TX_SUCCESS) || (obj == TX_NULL))
    {
        error_count++;
    }
    return obj;
}

/* Deallocate an object and verify the expected return value.  */
static void dealloc_object_expect(VOID *obj, UINT expected)
{
UINT status;

    status = _txm_module_manager_object_deallocate(obj);
    if (status != expected)
    {
        error_count++;
    }
}


/* ---- Main test thread -------------------------------------------------- */

static void thread_0_entry(ULONG thread_input)
{
UINT  status;

    (VOID) thread_input;

    /* ------------------------------------------------------------------ */
    /* Setup: initialise the module manager and create the object pool.   */
    /* ------------------------------------------------------------------ */

    status = _txm_module_manager_initialize(module_mem_area, MODULE_MEM_SIZE);
    if (status != TX_SUCCESS)
    {
        printf("Running Module Object Dealloc Live Test........................... ERROR #1\n");
        test_control_return(1);
    }

    status = _txm_module_manager_object_pool_create(object_pool_area, OBJECT_POOL_SIZE);
    if (status != TX_SUCCESS)
    {
        printf("Running Module Object Dealloc Live Test........................... ERROR #2\n");
        test_control_return(1);
    }

    /* Initialise the synthetic module instance used as object owner.  */
    TX_MEMSET(&test_module_instance, 0, sizeof(test_module_instance));
    test_module_instance.txm_module_instance_id    = TXM_MODULE_ID;
    test_module_instance.txm_module_instance_state = TXM_MODULE_STARTED;

    /* Point the running thread's module instance pointer at our synthetic
       module so that the object deallocator can find it.  */
    _tx_thread_current_ptr->tx_thread_module_instance_ptr = &test_module_instance;


    /* ================================================================== */
    /* TEST 1: Deallocate an already-dead TX_TIMER (ID == TX_CLEAR_ID).   */
    /* Expected: pool memory is freed, TX_SUCCESS returned.               */
    /* ================================================================== */
    {
    TX_TIMER *timer_ptr = (TX_TIMER *) alloc_object(sizeof(TX_TIMER));

        if (timer_ptr != TX_NULL)
        {
            /* Create and then properly delete the timer before pool-freeing it.  */
            status = tx_timer_create(timer_ptr, "t1", TX_NULL, 0,
                                     100, 0, TX_NO_ACTIVATE);
            if (status == TX_SUCCESS)
            {
                tx_timer_delete(timer_ptr);
            }

            /* ID should be TX_CLEAR_ID now; dealloc must not call delete again.  */
            if (timer_ptr->tx_timer_id != TX_CLEAR_ID)
            {
                error_count++;
            }

            dealloc_object_expect(timer_ptr, TX_SUCCESS);
        }
    }


    /* ================================================================== */
    /* TEST 2: Deallocate a LIVE TX_TIMER (still active in timer wheel).  */
    /* Expected: timer cleaned up, TX_CLEAR_ID set, pool freed.           */
    /* ================================================================== */
    {
    TX_TIMER *timer_ptr = (TX_TIMER *) alloc_object(sizeof(TX_TIMER));

        if (timer_ptr != TX_NULL)
        {
            status = tx_timer_create(timer_ptr, "t2", TX_NULL, 0,
                                     100, 100, TX_AUTO_ACTIVATE);
            if (status != TX_SUCCESS)
            {
                error_count++;
            }
            else
            {
                /* Timer wheel entry is live at this point.  */
                if (timer_ptr->tx_timer_id != TX_TIMER_ID)
                {
                    error_count++;
                }

#ifdef TXM_MODULE_OBJECT_DEALLOC_STRICT
                dealloc_object_expect(timer_ptr, TX_DELETE_ERROR);
#else
                dealloc_object_expect(timer_ptr, TX_SUCCESS);
#endif
                /* After dealloc, the kernel must have cleared the ID.  */
                if (timer_ptr->tx_timer_id != TX_CLEAR_ID)
                {
                    error_count++;
                }
            }
        }
    }


    /* ================================================================== */
    /* TEST 3: Deallocate a LIVE TX_SEMAPHORE.                            */
    /* ================================================================== */
    {
    TX_SEMAPHORE *sem_ptr = (TX_SEMAPHORE *) alloc_object(sizeof(TX_SEMAPHORE));

        if (sem_ptr != TX_NULL)
        {
            status = tx_semaphore_create(sem_ptr, "s1", 0);
            if (status != TX_SUCCESS)
            {
                error_count++;
            }
            else
            {
                if (sem_ptr->tx_semaphore_id != TX_SEMAPHORE_ID)
                {
                    error_count++;
                }

#ifdef TXM_MODULE_OBJECT_DEALLOC_STRICT
                dealloc_object_expect(sem_ptr, TX_DELETE_ERROR);
#else
                dealloc_object_expect(sem_ptr, TX_SUCCESS);
#endif
                if (sem_ptr->tx_semaphore_id != TX_CLEAR_ID)
                {
                    error_count++;
                }
            }
        }
    }


    /* ================================================================== */
    /* TEST 4: Deallocate a LIVE TX_MUTEX.                                */
    /* ================================================================== */
    {
    TX_MUTEX *mutex_ptr = (TX_MUTEX *) alloc_object(sizeof(TX_MUTEX));

        if (mutex_ptr != TX_NULL)
        {
            status = tx_mutex_create(mutex_ptr, "m1", TX_NO_INHERIT);
            if (status != TX_SUCCESS)
            {
                error_count++;
            }
            else
            {
                if (mutex_ptr->tx_mutex_id != TX_MUTEX_ID)
                {
                    error_count++;
                }

#ifdef TXM_MODULE_OBJECT_DEALLOC_STRICT
                dealloc_object_expect(mutex_ptr, TX_DELETE_ERROR);
#else
                dealloc_object_expect(mutex_ptr, TX_SUCCESS);
#endif
                if (mutex_ptr->tx_mutex_id != TX_CLEAR_ID)
                {
                    error_count++;
                }
            }
        }
    }


    /* ================================================================== */
    /* TEST 5: Deallocate a LIVE TX_QUEUE.                                */
    /* ================================================================== */
    {
    TX_QUEUE *queue_ptr = (TX_QUEUE *) alloc_object(sizeof(TX_QUEUE));

        if (queue_ptr != TX_NULL)
        {
            status = tx_queue_create(queue_ptr, "q1", TX_1_ULONG,
                                     queue_storage, sizeof(queue_storage));
            if (status != TX_SUCCESS)
            {
                error_count++;
            }
            else
            {
                if (queue_ptr->tx_queue_id != TX_QUEUE_ID)
                {
                    error_count++;
                }

#ifdef TXM_MODULE_OBJECT_DEALLOC_STRICT
                dealloc_object_expect(queue_ptr, TX_DELETE_ERROR);
#else
                dealloc_object_expect(queue_ptr, TX_SUCCESS);
#endif
                if (queue_ptr->tx_queue_id != TX_CLEAR_ID)
                {
                    error_count++;
                }
            }
        }
    }


    /* ================================================================== */
    /* TEST 6: Deallocate a LIVE TX_EVENT_FLAGS_GROUP.                    */
    /* ================================================================== */
    {
    TX_EVENT_FLAGS_GROUP *ef_ptr =
        (TX_EVENT_FLAGS_GROUP *) alloc_object(sizeof(TX_EVENT_FLAGS_GROUP));

        if (ef_ptr != TX_NULL)
        {
            status = tx_event_flags_create(ef_ptr, "ef1");
            if (status != TX_SUCCESS)
            {
                error_count++;
            }
            else
            {
                if (ef_ptr->tx_event_flags_group_id != TX_EVENT_FLAGS_ID)
                {
                    error_count++;
                }

#ifdef TXM_MODULE_OBJECT_DEALLOC_STRICT
                dealloc_object_expect(ef_ptr, TX_DELETE_ERROR);
#else
                dealloc_object_expect(ef_ptr, TX_SUCCESS);
#endif
                if (ef_ptr->tx_event_flags_group_id != TX_CLEAR_ID)
                {
                    error_count++;
                }
            }
        }
    }


    /* ================================================================== */
    /* TEST 7: Deallocate a LIVE TX_BLOCK_POOL.                           */
    /* ================================================================== */
    {
    TX_BLOCK_POOL *bp_ptr = (TX_BLOCK_POOL *) alloc_object(sizeof(TX_BLOCK_POOL));

        if (bp_ptr != TX_NULL)
        {
            status = tx_block_pool_create(bp_ptr, "bp1", 16,
                                          block_pool_mem, sizeof(block_pool_mem));
            if (status != TX_SUCCESS)
            {
                error_count++;
            }
            else
            {
                if (bp_ptr->tx_block_pool_id != TX_BLOCK_POOL_ID)
                {
                    error_count++;
                }

#ifdef TXM_MODULE_OBJECT_DEALLOC_STRICT
                dealloc_object_expect(bp_ptr, TX_DELETE_ERROR);
#else
                dealloc_object_expect(bp_ptr, TX_SUCCESS);
#endif
                if (bp_ptr->tx_block_pool_id != TX_CLEAR_ID)
                {
                    error_count++;
                }
            }
        }
    }


    /* ================================================================== */
    /* TEST 8: Deallocate a LIVE TX_BYTE_POOL.                            */
    /* ================================================================== */
    {
    TX_BYTE_POOL *byp_ptr = (TX_BYTE_POOL *) alloc_object(sizeof(TX_BYTE_POOL));

        if (byp_ptr != TX_NULL)
        {
            status = tx_byte_pool_create(byp_ptr, "byp1",
                                         byte_pool_mem, sizeof(byte_pool_mem));
            if (status != TX_SUCCESS)
            {
                error_count++;
            }
            else
            {
                if (byp_ptr->tx_byte_pool_id != TX_BYTE_POOL_ID)
                {
                    error_count++;
                }

#ifdef TXM_MODULE_OBJECT_DEALLOC_STRICT
                dealloc_object_expect(byp_ptr, TX_DELETE_ERROR);
#else
                dealloc_object_expect(byp_ptr, TX_SUCCESS);
#endif
                if (byp_ptr->tx_byte_pool_id != TX_CLEAR_ID)
                {
                    error_count++;
                }
            }
        }
    }


    /* ================================================================== */
    /* TEST 9: Deallocate a LIVE TX_THREAD.                               */
    /* The thread must be in terminated or completed state before          */
    /* tx_thread_delete() is called.  The deallocator calls               */
    /* _tx_thread_terminate() first, mirroring the stop path.             */
    /* ================================================================== */
    {
    TX_THREAD *mod_thread = (TX_THREAD *) alloc_object(sizeof(TX_THREAD));

        if (mod_thread != TX_NULL)
        {
            status = tx_thread_create(mod_thread, "mt1",
                                      module_thread_entry, 0,
                                      module_thread_stack,
                                      sizeof(module_thread_stack),
                                      10, 10, TX_NO_TIME_SLICE,
                                      TX_DONT_START);
            if (status != TX_SUCCESS)
            {
                error_count++;
            }
            else
            {
                if (mod_thread->tx_thread_id != TX_THREAD_ID)
                {
                    error_count++;
                }

#ifdef TXM_MODULE_OBJECT_DEALLOC_STRICT
                dealloc_object_expect(mod_thread, TX_DELETE_ERROR);
#else
                dealloc_object_expect(mod_thread, TX_SUCCESS);
#endif
                if (mod_thread->tx_thread_id != TX_CLEAR_ID)
                {
                    error_count++;
                }
            }
        }
    }


    /* ================================================================== */
    /* TEST 10: Deallocate uninitialized memory (first ULONG != any known */
    /* object ID).  Expected: no spurious delete call, TX_SUCCESS.        */
    /* ================================================================== */
    {
    ULONG *raw_ptr = (ULONG *) alloc_object(sizeof(TX_TIMER));

        if (raw_ptr != TX_NULL)
        {
            /* Write a value that is not any TX_*_ID constant.  */
            *raw_ptr = 0xDEADBEEFUL;

            dealloc_object_expect(raw_ptr, TX_SUCCESS);
        }
    }


    /* ================================================================== */
    /* Result                                                              */
    /* ================================================================== */
    if (error_count != 0)
    {
        printf("Running Module Object Dealloc Live Test........................... ERROR #%lu\n",
               (unsigned long) error_count);
        test_control_return(1);
    }
    else
    {
        printf("Running Module Object Dealloc Live Test........................... PASSED\n");
        test_control_return(0);
    }
}


/* Stub entry for the module-allocated test thread (never runs).  */
static void module_thread_entry(ULONG thread_input)
{
    (VOID) thread_input;
}
