# Copyright (c) 2026 Eclipse ThreadX contributors
# SPDX-License-Identifier: MIT
# Some portions generated by Claude Code (Opus 5).
#
# Load s32z280_module.elf onto the S32Z280-594EVB, run it, and report what the
# protection boundary did.
#
# Usage, normally through run_module_demo.sh which computes the addresses:
#   S32Z280_ELF=<path to s32z280_module.elf> \
#   S32Z280_MODULE_ELF=<path to s32z280_demo_module.elf> \
#       arm-none-eabi-gdb-py -batch -x tools/run_module_demo.gdb
#
# Requires, and does not do for you:
#   * a CCS listening on 41475 -- the *Windows* CCS ("ccs.exe -noportquit").
#     The Linux CCS's pushes to the probe stall after "Sending code ... done",
#     and under WSL2 mirrored networking a stray Linux CCS holds the port and
#     blocks the Windows one ("pkill -x ccs", not -f: it runs as ./ccs).
#   * GTA on 45000: Server/gta/gta -p 45000 -k
#   * PYTHONHOME pointing at a source-built Python 3.10.11.
#   * The UART already being captured to a file BEFORE this runs.  The console
#     is the test method here, not a convenience: this script reports the same
#     verdict from memory, but only the console shows the ordering of events
#     that produced it.
#
# WHAT A PASS LOOKS LIKE, and why it is a fault
#
# The sample module writes its own data, calls the kernel through SVC, and then
# deliberately violates its protection.  The expected end state is therefore an
# abort taken in User mode, captured by the abort vector, reported through the
# fault-notify callback, and terminating the module thread -- with the manager
# still alive to report it.  A run with no fault is a FAILURE: it means a module
# reached kernel memory and was not stopped.
#
#   module_progress bit 0x01  wrote and summed its own scratch     expect SET
#                   bit 0x02  reached the kernel through SVC       expect SET
#                   bit 0x04  about to READ the forbidden address  data pass only
#                   bit 0x08  survived the forbidden read          expect CLEAR
#                   bit 0x10  about to BRANCH to it                prefetch pass only
#                   bit 0x20  survived the forbidden branch        expect CLEAR
#                   bit 0x40  wrote and read back every granted
#                             shared granule                      shared pass only
#                   bit 0x80  about to write the UNGRANTED granule shared pass only
#                  bit 0x100  survived writing it                  expect CLEAR
#
# so module_progress == 0x7 for a data-abort pass, 0x13 for the prefetch pass and
# 0xC3 for the shared pass.
#
# The manager records the same word a second time, out of the first shared
# granule, and this script reads the module's own copy out of its data area.  Two
# independent readings of one event: if they disagree, one of the two channels is
# lying and the run says which.
#
# FOUR PASSES, because one run proves neither relocation nor both abort types
#
# The module is position independent, so a single run at the address it was
# linked for would prove nothing: the GOT rebase would map every address to
# itself and a rebase that did nothing would look the same.  So passes 1 and 2
# run the same blob from two addresses -- once where the linker put it, once from
# a staging area -- and this script compares them.
#
# Pass 3 faults the other way.  Passes 1 and 2 read an address they do not own,
# which is a DATA abort reported through DFSR and DFAR.  Pass 3 branches outside
# its code region, which is a PREFETCH abort reported through IFSR and IFAR and
# arrives at the handler by a different vector.  It runs after passes 1 and 2 have
# been unloaded, so it also shows that a module fault leaves the manager able to
# load and run the next module.
#
# Pass 4 is the shared regions.  Passes 1 to 3 are each granted ONE shared
# region -- the granule they report progress through -- which exercises the first
# of the five shared entries the port provides and nothing about the other four.
# Pass 4 is granted all five, one 64-byte granule each, and is deliberately NOT
# granted the granule that sits between two of them; it writes every granule it
# was given, reads them all back, and then writes the gap, which must fault.  A
# limit register masked the wrong way, or a base off by a granule, reaches into
# that gap from one side or the other.  The same pass probes the two refusals --
# an unaligned grant must come back TXM_MODULE_ALIGNMENT_ERROR (0xF0) and one
# grant past the entry count must come back TX_NO_MEMORY (0x10).
#
# THE NOTIFY CALLBACK IS A CHECK NOW, not a note
#
# It used to be dead on this port: the shared fault handler terminates the
# offending thread and only then calls the hook, and _tx_thread_terminate returns
# for the running thread only if the abort vector has told the kernel it is inside
# an exception -- which this port's vector did not do.  It does now, so every pass
# must see the callback run exactly once, with the faulting thread and the right
# module instance.  Zero notifications next to a captured fault is a regression in
# that bracket and nothing else.
#
# Finding module_progress is no longer a matter of reading the module's ELF.  A
# relocated module's data lives wherever the manager allocated it, so the address
# is (this pass's data base) + (the nominal offset of module_progress within the
# module's data segment).  The first number is read from the module instance on
# the target, the second from the module's ELF, and neither is a constant that
# can be written down here.
#
# AND IT HAS TO BE READ WHILE THE PASS STILL OWNS THE MEMORY.  The byte pool
# reuses freed blocks, so pass 3 -- which loads after passes 1 and 2 are unloaded
# -- lands exactly where pass 1 was.  Reading all three at the end of the run
# therefore reports pass 3's progress as pass 1's, and pass 1 looks like it took
# the wrong branch.  So this script breaks on pass_done once per pass and reads
# that pass's word there, before anything is unloaded.

# The probe and the S32DS installation, from the environment when
# run_module_demo.sh set them and from the same defaults it uses when this
# script is run by hand.  Mirrored in run_module_demo.gdb and
# diagnose_module.gdb rather than shared, because gdb resolves a relative
# "source" against the working directory and these are run from anywhere.
python
import os

_PROBE_IP = os.environ.get("S32Z280_PROBE", "s32dbg:192.168.50.238")

_S32DS_ROOT = os.environ.get("S32DS_ROOT")
if not _S32DS_ROOT:
    for _candidate in ("/opt/nxp/S32DS.3.6.10",
                       os.path.expanduser("~/NXP/S32DS.3.6.10")):
        if os.path.isdir(_candidate):
            _S32DS_ROOT = _candidate
            break

_S32DS_SCRIPT = os.path.join(
    _S32DS_ROOT or "",
    "S32DS/tools/S32Debugger/Debugger/scripts/s32z2e2",
    "s32z2e2_generic_bareboard_all_cores.py")

if not os.path.isfile(_S32DS_SCRIPT):
    raise gdb.GdbError(
        "S32DS core script not found at %s\n"
        "Set S32DS_ROOT to your S32 Design Studio installation."
        % (_S32DS_SCRIPT or "<unset>"))

gdb.execute("source " + _S32DS_SCRIPT)
end

py _SOC_NAME = "S32Z280"
py _CORE_NAME = "R52_0_0"
py _GDB_SERVER_PORT = 45000

py board_init()
py s32z2e2_cores.init(_CORE_NAME)
py s32z2e2_cores.start_debug_by_core_name(_CORE_NAME)

# Select the core context before asking about core state.  NXP's core_init()
# omits this and then stop_core() reads the mode of the SoC context, which has
# none, and reports "Core can't be stopped. State is undefined/unknown".
py gta_lib.set_context(context.CORE_CTX[_SOC_NAME + "_" + _CORE_NAME]).unwrap()
py gta_lib.stop_core().unwrap()
py gta_lib.attach().unwrap()

python
import gdb, os

# ---------------------------------------------------------------------------
# Release the core from the debugger's external debug request.
#
# _reset_to_first_instruction() asserts MDM_AP CONTROL2[19:16] =
# CR52_RTU0_{3,2,1,0}_EDBGREQ (0x000F0000) and nothing clears them, so every
# RTU0 core is pinned in debug state and executes nothing -- registers and
# memory still respond, which is what makes it look like working hardware.
# ---------------------------------------------------------------------------
CONTROL2 = 0x4DC11044
EDBGREQ_CORE0 = 0x00010000

def rd(addr):
    return int(gdb.parse_and_eval("*(unsigned int *)0x%x" % addr)) & 0xFFFFFFFF

c2 = rd(CONTROL2)
gdb.execute("set *(unsigned int *)0x%x = 0x%x" % (CONTROL2, c2 & ~EDBGREQ_CORE0))
if rd(CONTROL2) & EDBGREQ_CORE0:
    raise gdb.GdbError("CR52_RTU0_0_EDBGREQ is still set; the core will not run")
print("EDBGREQ cleared: CONTROL2 0x%08X -> 0x%08X" % (c2, rd(CONTROL2)))

elf = os.environ.get("S32Z280_ELF", "s32z280_module.elf")
gdb.execute("file %s" % elf)
gdb.execute("load")

# The core resets in Thumb state and CPSR cannot be written through this
# connection, so entry must be the T32 _start.  Mask bit 0: GDB reports a Thumb
# function's address with it set, but PC itself must be even.
start = int(gdb.parse_and_eval("(unsigned int)&_start")) & ~1
gdb.execute("set $pc = 0x%x" % start)
print("PC set to 0x%08X" % start)

# Stop after the manager has printed its whole report.  manager_done exists for
# this and nothing else: the previous version of this script broke on
# sample_threadx_module_manager.c:259, and every edit to that file moved the line
# out from under the breakpoint, after which the run stopped somewhere arbitrary
# and reported whatever memory happened to hold.
#
# hbreak, not break: the code region is mapped read-only by the MPU, so a
# software breakpoint would have to write to it.
gdb.execute("hbreak pass_done")
gdb.execute("hbreak manager_done")

# Each pass's module_progress, read at pass_done while that pass still holds its
# data.  Kept in a global the reporting block below picks up; gdb's python runs in
# one persistent namespace, and the reader falls back to "skipped" rather than a
# traceback if that ever stops being true.
PROGRESS_BY_PASS = []

_offset = os.environ.get("S32Z280_MODULE_PROGRESS_OFFSET")
_offset = int(_offset, 0) if _offset else None

for _i in range(4):
    gdb.execute("continue")
    if _offset is None:
        PROGRESS_BY_PASS.append(None)
        continue
    _base = int(gdb.parse_and_eval("pass_results[%d].pass_data_base" % _i)) & 0xFFFFFFFF
    if _base == 0:
        # The pass never loaded, so there is no data base and nothing to read.
        PROGRESS_BY_PASS.append(None)
    else:
        _addr = _base + _offset
        PROGRESS_BY_PASS.append(
            int(gdb.parse_and_eval("*(unsigned int *)0x%x" % _addr)) & 0xFFFFFFFF)
        print("pass %d: module_progress 0x%08X at 0x%08X (read while loaded)"
              % (_i + 1, PROGRESS_BY_PASS[-1], _addr))

# On to the report the manager prints for itself.
gdb.execute("continue")
end

echo \n===== module manager run: what memory says =====\n
python
import gdb, os

def rd(addr):
    return int(gdb.parse_and_eval("*(unsigned int *)0x%x" % addr)) & 0xFFFFFFFF

def ev(expr):
    return int(gdb.parse_and_eval(expr)) & 0xFFFFFFFF

failures = 0

OWN_DATA, KERNEL_CALL = 0x01, 0x02
ATTEMPTED_STEAL, SURVIVED_STEAL = 0x04, 0x08
ATTEMPTED_JUMP, SURVIVED_JUMP = 0x10, 0x20
SHARED_WROTE = 0x40
ATTEMPTED_GAP, SURVIVED_GAP = 0x80, 0x100
FORBIDDEN = 0x31780000

# The shared area, mirrored from S32Z_MODULE_STATUS_* in platform.h.  Five of the
# six granules are granted, one entry each; index 2 never is, and the marks go at
# word 1 because word 0 of granule 0 is the progress word.
STATUS_BASE, STATUS_GRANULE, STATUS_GRANULES = 0x317F0000, 0x40, 6
STATUS_UNGRANTED, STATUS_MARK_OFFSET = 2, 4
SHARED_SIGNATURE = 0x5A5A0000
ALIGNMENT_ERROR, NO_MEMORY = 0xF0, 0x10
SUCCESS, SIZE_ERROR = 0x00, 0x05
MODE = {0x10: "User", 0x13: "Supervisor", 0x1A: "Hyp", 0x1F: "System"}

# Which violation each pass was told to commit, from the low byte of the module ID
# the manager writes into the instance before starting it.
TEST_DATA_ABORT, TEST_PREFETCH_ABORT, TEST_SHARED_ABORT = 0x1, 0x2, 0x3
PASSES = 4
RELOCATION_PASSES = 2

# The nominal offset of module_progress inside the module's data segment.  Both
# halves come from the module's own ELF and neither is an address the module ever
# runs at -- see link_demo_module.lds.  The run-time address is this offset plus
# whatever data base the manager handed the module, which differs per pass.
progress_offset = os.environ.get("S32Z280_MODULE_PROGRESS_OFFSET")
progress_offset = int(progress_offset, 0) if progress_offset else None

if progress_offset is None:
    print("  NOTE S32Z280_MODULE_PROGRESS_OFFSET unset; skipping the progress checks")
else:
    print("  module_progress sits %d bytes into the module's data segment" % progress_offset)

passes = []
for i in range(PASSES):
    p = {}
    for field in ("pass_test", "pass_load_status", "pass_share_status",
                  "pass_start_status", "pass_stop_status",
                  "pass_code_start", "pass_code_end", "pass_data_start",
                  "pass_data_end", "pass_data_base", "pass_faults",
                  "pass_captured", "pass_fault_r9",
                  "pass_dfsr", "pass_dfar", "pass_ifsr", "pass_ifar",
                  "pass_spsr", "pass_code_location",
                  "pass_notify_thread", "pass_notify_instance",
                  "pass_expect_thread", "pass_expect_instance",
                  "pass_progress", "pass_expect_progress", "pass_expect_fault",
                  "pass_shared_grants", "pass_shared_count",
                  "pass_align_status", "pass_exhaust_status"):
        p[field] = ev("pass_results[%d].%s" % (i, field))
    p["marks"] = [ev("pass_results[%d].pass_marks[%d]" % (i, g))
                  for g in range(STATUS_GRANULES)]
    try:
        p["name"] = gdb.parse_and_eval("pass_results[%d].pass_name" % i).string()
    except gdb.error:
        p["name"] = "pass %d" % (i + 1)
    passes.append(p)

for i, p in enumerate(passes):
    prefetch = (p["pass_test"] == TEST_PREFETCH_ABORT)
    shared = (p["pass_test"] == TEST_SHARED_ABORT)
    print("")
    print("  --- pass %d: %s ---" % (i + 1, p["name"]))
    if prefetch:
        print("    expected abort        = prefetch, through IFSR/IFAR")
    elif shared:
        print("    expected abort        = data, through DFSR/DFAR, writing an")
        print("                            ungranted shared granule")
    else:
        print("    expected abort        = data, through DFSR/DFAR")
    print("    load / share / start / stop = 0x%08X / 0x%08X / 0x%08X / 0x%08X"
          % (p["pass_load_status"], p["pass_share_status"],
             p["pass_start_status"], p["pass_stop_status"]))
    print("    code region           = 0x%08X .. 0x%08X"
          % (p["pass_code_start"], p["pass_code_end"]))
    print("    data region           = 0x%08X .. 0x%08X"
          % (p["pass_data_start"], p["pass_data_end"]))
    print("    data base (r9)        = 0x%08X" % p["pass_data_base"])

    if (p["pass_load_status"] != 0 or p["pass_share_status"] != 0
            or p["pass_start_status"] != 0):
        print("    *** FAIL: did not load, share and start")
        failures += 1
        continue

    # Code and data regions are enabled together and PMSAv8-R has no region
    # priority, so an access hitting both takes a translation fault (TRM 8.1)
    # rather than merely being untidy.  Checked here as well as on the target
    # because a debugger can say which two regions met, and the target can only
    # say that something did.
    if (p["pass_code_start"] <= p["pass_data_end"]
            and p["pass_data_start"] <= p["pass_code_end"]):
        print("    *** FAIL: this module's code and data regions overlap")
        failures += 1

    progress = globals().get("PROGRESS_BY_PASS", [None] * PASSES)[i]
    if progress is None:
        print("    module_progress       = not read")
    else:
        addr = p["pass_data_base"] + progress_offset
        print("    module_progress       = 0x%08X  (read at 0x%08X while this pass"
              % (progress, addr))
        print("                            still held that memory)")

        # Every bit is checked, including the ones belonging to the violations
        # this pass was NOT told to commit: a module that took more than one
        # route, or the wrong one, is not the module this pass asked for and the
        # result would not mean what the register checks below claim.
        data = not (prefetch or shared)
        wanted = [(OWN_DATA, "wrote its own data", True),
                  (KERNEL_CALL, "reached the kernel through SVC", True),
                  (ATTEMPTED_STEAL, "attempted the forbidden read", data),
                  (SURVIVED_STEAL, "SURVIVED the forbidden read", False),
                  (ATTEMPTED_JUMP, "attempted the forbidden branch", prefetch),
                  (SURVIVED_JUMP, "SURVIVED the forbidden branch", False),
                  (SHARED_WROTE, "wrote and read back every granted granule", shared),
                  (ATTEMPTED_GAP, "attempted the ungranted granule", shared),
                  (SURVIVED_GAP, "SURVIVED the ungranted granule", False)]
        for bit, name, want_set in wanted:
            got = bool(progress & bit)
            ok = (got == want_set)
            if not ok:
                failures += 1
            print("      0x%03X %-42s %-5s  %s"
                  % (bit, name, "set" if got else "clear",
                     "ok" if ok else "*** WRONG ***"))
        if progress & (SURVIVED_STEAL | SURVIVED_JUMP | SURVIVED_GAP):
            print("      ISOLATION FAILURE: the module reached memory it was never granted.")

        # The manager's own reading of the same word, out of the first shared
        # granule.  Two independent channels for one event: the module writes
        # both, this script reads its private copy and the manager read the
        # shared one, so a disagreement means one of the two paths is lying and
        # neither result should be trusted until it is explained.
        if p["pass_progress"] != progress:
            print("    *** FAIL: the manager read progress 0x%08X out of the shared"
                  % p["pass_progress"])
            print("              granule, the module's own copy says 0x%08X" % progress)
            failures += 1
        if p["pass_progress"] != p["pass_expect_progress"]:
            print("    *** FAIL: progress 0x%08X, expected 0x%08X"
                  % (p["pass_progress"], p["pass_expect_progress"]))
            failures += 1

    # "captured" and "notified" are different events: the abort vector records the
    # fault registers before anything else runs, and the notify callback is a
    # later consequence of the same fault.  Both are required.  Reporting them
    # apart is what keeps a broken notify path from being read as "no fault
    # occurred", which is the opposite of the truth.
    print("    fault captured        = %d" % p["pass_captured"])
    print("    notify callbacks      = %d" % p["pass_faults"])
    if p["pass_captured"] == 0:
        print("    *** FAIL: no fault was captured.  The module reached outside its")
        print("              memory and was not stopped, or never got that far.")
        failures += 1
        continue

    # The callback is a public API of the module manager, so its arguments are
    # checked and not merely counted.  Zero notifications beside a captured fault
    # means the fault reached the hardware's evidence and never reached the
    # application: on this port that is the system-state bracket in
    # txm_module_manager_fault_capture.S having gone missing again.
    if p["pass_faults"] != 1:
        print("    *** FAIL: the notify callback ran %d times, not once."
              % p["pass_faults"])
        failures += 1
    elif (p["pass_notify_thread"] != p["pass_expect_thread"]
            or p["pass_notify_instance"] != p["pass_expect_instance"]):
        print("    *** FAIL: notified about thread 0x%08X / module 0x%08X,"
              % (p["pass_notify_thread"], p["pass_notify_instance"]))
        print("              expected thread 0x%08X / module 0x%08X"
              % (p["pass_expect_thread"], p["pass_expect_instance"]))
        failures += 1
    else:
        print("    notified about        = thread 0x%08X, module 0x%08X (both correct)"
              % (p["pass_notify_thread"], p["pass_notify_instance"]))

    dfsr, dfar, spsr, pc = (p["pass_dfsr"], p["pass_dfar"],
                            p["pass_spsr"], p["pass_code_location"])
    ifsr, ifar = p["pass_ifsr"], p["pass_ifar"]

    # Both pairs are printed for both kinds of pass, because the capture records
    # both and the pair that does not belong to this fault is a leftover the
    # hardware never cleared -- worth seeing, and worth not mistaking for a
    # result.  Which pair is meaningful is decided by the expected abort type,
    # not by which of them looks plausible.
    print("    DFSR                  = 0x%08X  status 0x%02X  WnR %d%s"
          % (dfsr, dfsr & 0x3F, (dfsr >> 11) & 1,
             "" if not prefetch else "   (stale: this pass took a prefetch abort)"))
    print("    DFAR                  = 0x%08X" % dfar)
    print("    IFSR                  = 0x%08X  status 0x%02X%s"
          % (ifsr, ifsr & 0x3F,
             "   (stale: this pass took a data abort)" if not prefetch else ""))
    print("    IFAR                  = 0x%08X" % ifar)
    print("    SPSR                  = 0x%08X  mode 0x%02X (%s)"
          % (spsr, spsr & 0x1F, MODE.get(spsr & 0x1F, "?")))
    print("    faulting pc           = 0x%08X" % pc)
    if prefetch:
        # The fault is on the fetch AT the branch target, so the faulting pc is
        # the target and not a place inside the module.
        print("    (the faulting pc is the branch target, outside the module)")
    else:
        print("    pc - code base        = 0x%08X" % ((pc - p["pass_code_start"]) & 0xFFFFFFFF))
    print("    r9 at the fault       = 0x%08X" % p["pass_fault_r9"])

    # r9 is the module's PIC base, seeded by the manager's thread stack build from
    # the thread entry info.  Before T3 it was left at 0, which is what made every
    # module data reference resolve to a small absolute address.  Checking it
    # directly turns that class of bug into one line instead of a fault to explain.
    if p["pass_fault_r9"] != p["pass_data_base"]:
        print("    *** FAIL: r9 should be the data base 0x%08X" % p["pass_data_base"])
        failures += 1

    if (spsr & 0x1F) != 0x10:
        print("    *** FAIL: the fault did not come from User mode, so it is not")
        print("              a module being stopped at the boundary.")
        failures += 1

    # The faulting address is the strongest single check in this script.  The
    # module obtained it by reading one of its own initialised globals through the
    # rebased GOT, so the right value here means the GOT was rewritten AND .data
    # was copied out of the image.  A wrong value usually means the module faulted
    # on its own data instead, which is what a bad rebase looks like.
    #
    # A data abort reports it in DFAR, a prefetch abort in IFAR.  Both registers
    # are sticky, so checking the pair that does not belong to this fault would
    # pass on a value some earlier fault left behind -- including the boot probes,
    # which take a prefetch abort of their own before ThreadX starts.
    #
    # The shared pass is the exception: the address it faults on is the mark word
    # of the granule it was not granted, which it computes from a literal rather
    # than out of .data -- so for that pass this is a check on the grant and not
    # on the rebase.  Which is why the expectation is carried per pass.
    reg_name, reg_value = ("IFAR", ifar) if prefetch else ("DFAR", dfar)
    expect_fault = p["pass_expect_fault"] or FORBIDDEN
    if reg_value != expect_fault:
        print("    *** FAIL: expected %s 0x%08X, the address the module was told"
              % (reg_name, expect_fault))
        print("              not to touch.  A different one means .data was not")
        print("              copied or the GOT was not rebased.")
        failures += 1

    # A prefetch abort with nothing in IFSR would mean the vector reached the
    # capture without the core having recorded an instruction fault, which is the
    # one way this pass could look right and be meaningless.
    if prefetch and (ifsr & 0x3F) == 0:
        print("    *** FAIL: IFSR reports no instruction fault status")
        failures += 1

    # The shared-region results, for the one pass that produces them.  Read out
    # of the manager's own record rather than out of the MPU: what the hardware
    # holds is checked by the module having faulted, and what is checked here is
    # that the manager granted what it meant to and refused what it should.
    if shared:
        print("    shared grants         = %d (expected %d)"
              % (p["pass_shared_grants"], STATUS_GRANULES - 1))
        print("    entries held          = %d" % p["pass_shared_count"])
        print("    unaligned grant       = 0x%02X (expected 0x%02X, TXM_MODULE_ALIGNMENT_ERROR)"
              % (p["pass_align_status"], ALIGNMENT_ERROR))
        print("    one grant too many    = 0x%02X (expected 0x%02X, TX_NO_MEMORY)"
              % (p["pass_exhaust_status"], NO_MEMORY))

        if p["pass_shared_grants"] != STATUS_GRANULES - 1:
            print("    *** FAIL: not every shared entry could be granted")
            failures += 1
        if p["pass_shared_count"] != STATUS_GRANULES - 1:
            print("    *** FAIL: the instance does not hold the entries it granted")
            failures += 1
        if p["pass_align_status"] != ALIGNMENT_ERROR:
            print("    *** FAIL: an unaligned shared grant was not refused as such.")
            print("              Accepting one does not fault -- the low six bits of")
            print("              PRBAR are permissions, so it changes what the region")
            print("              allows instead of where it is.")
            failures += 1
        if p["pass_exhaust_status"] != NO_MEMORY:
            print("    *** FAIL: one grant too many was not refused.  The entry index")
            print("              is TXM_MODULE_MPU_SHARED_INDEX plus the count, so a")
            print("              sixth grant writes past the end of the region table.")
            failures += 1

        # And what the module managed to write where.  A granted granule holding
        # something other than its own mark means that entry was programmed with
        # the wrong base -- the store was accepted and landed elsewhere -- and a
        # non-zero gap means a grant covered a granule nobody asked for.
        for g in range(STATUS_GRANULES):
            addr = STATUS_BASE + g * STATUS_GRANULE + STATUS_MARK_OFFSET
            want = 0 if g == STATUS_UNGRANTED else (SHARED_SIGNATURE | g)
            got = p["marks"][g]
            tag = "ungranted" if g == STATUS_UNGRANTED else "granted  "
            ok = (got == want)
            if not ok:
                failures += 1
            print("      granule %d %s at 0x%08X = 0x%08X (expected 0x%08X)  %s"
                  % (g, tag, addr, got, want, "ok" if ok else "*** WRONG ***"))

# --- the relocation result, which is the comparison between the passes --------
print("")
print("  ===== both abort types =====")
data_passes = [q for q in passes if q["pass_test"] != TEST_PREFETCH_ABORT
               and q["pass_captured"] and (q["pass_dfsr"] & 0x3F)]
pabt_passes = [q for q in passes if q["pass_test"] == TEST_PREFETCH_ABORT
               and q["pass_captured"] and (q["pass_ifsr"] & 0x3F)]
print("    data aborts captured     = %d" % len(data_passes))
print("    prefetch aborts captured = %d" % len(pabt_passes))
if not data_passes or not pabt_passes:
    print("    *** FAIL: only one kind of abort was exercised, so half of the")
    print("              port's fault path never ran")
    failures += 1
else:
    print("    PASS: both vectors were taken and both register pairs reported")

print("")
print("  ===== relocation =====")
a, b = passes[0], passes[1]
off_a = (a["pass_code_location"] - a["pass_code_start"]) & 0xFFFFFFFF
off_b = (b["pass_code_location"] - b["pass_code_start"]) & 0xFFFFFFFF

if a["pass_captured"] == 0 or b["pass_captured"] == 0:
    print("    *** FAIL: a pass did not fault, so there is nothing to compare")
    failures += 1
elif a["pass_code_start"] == b["pass_code_start"]:
    print("    *** FAIL: both passes ran from the same address 0x%08X"
          % a["pass_code_start"])
    failures += 1
elif off_a != off_b:
    print("    *** FAIL: the passes faulted at different offsets, 0x%08X and 0x%08X"
          % (off_a, off_b))
    failures += 1
else:
    print("    code bases 0x%08X and 0x%08X, %d bytes apart"
          % (a["pass_code_start"], b["pass_code_start"],
             (b["pass_code_start"] - a["pass_code_start"]) & 0xFFFFFFFF))
    print("    both faulted at offset 0x%08X into their own image" % off_a)
    print("    PASS: the same blob ran correctly from two different addresses")
    if a["pass_data_base"] == b["pass_data_base"]:
        print("    NOTE both passes shared a data base 0x%08X, so the data half of"
              % a["pass_data_base"])
        print("         the rebase produced the same numbers twice")

print("")
print("  ===== shared-grant size guards =====")

# The manager's own record for the fifth module, which is loaded after the four
# passes and unloaded again without ever being started.  Read from memory for the
# same reason everything above is: the console says what the manager believes,
# and this says what it actually stored.
#
# A grant of no bytes, and one whose inclusive end wraps past 0xFFFFFFFF, both
# used to describe a region whose limit lay below its base -- and both were
# programmed, charged an entry and reported as TX_SUCCESS.  What is checked here
# is the pair: the status, and that the entry count did not move.  A guard that
# returned the right code and still spent an entry would look correct on the
# console and would silently cost an application one of its five.
try:
    g = {f: ev("guard_result.guard_%s" % f) for f in
         ("load_status", "count_start",
          "zero_status", "count_zero",
          "wrap_status", "count_wrap",
          "top_status", "count_top",
          "unload_status")}
except gdb.error as e:
    print("    *** FAIL: guard_result unreadable (%s)" % e)
    failures += 1
    g = None

if g is not None:
    print("    probe module load     = 0x%02X (expected 0x%02X)"
          % (g["load_status"], SUCCESS))
    print("    entries at start      = %d (expected 0)" % g["count_start"])
    print("    zero length           = 0x%02X (expected 0x%02X, TX_SIZE_ERROR), "
          "entries after = %d" % (g["zero_status"], SIZE_ERROR, g["count_zero"]))
    print("    wrapping end          = 0x%02X (expected 0x%02X, TX_SIZE_ERROR), "
          "entries after = %d" % (g["wrap_status"], SIZE_ERROR, g["count_wrap"]))
    print("    ends at 0xFFFFFFFF    = 0x%02X (expected 0x%02X, TX_SUCCESS), "
          "entries after = %d" % (g["top_status"], SUCCESS, g["count_top"]))
    print("    probe module unload   = 0x%02X (expected 0x%02X)"
          % (g["unload_status"], SUCCESS))

    if g["load_status"] != SUCCESS:
        print("    *** FAIL: the probe module did not load, so nothing below ran")
        failures += 1
    else:
        if g["count_start"] != 0:
            print("    *** FAIL: a freshly loaded instance already held shared entries")
            failures += 1
        if g["zero_status"] != SIZE_ERROR:
            print("    *** FAIL: a zero-length grant was not refused as a size error.")
            print("              Its limit is base - 1, which lies below its base.")
            failures += 1
        if g["wrap_status"] != SIZE_ERROR:
            print("    *** FAIL: a grant running off the top of memory was not refused.")
            print("              base + length - 1 wraps to a low address.")
            failures += 1
        if g["count_zero"] != 0 or g["count_wrap"] != 0:
            print("    *** FAIL: a refused grant still consumed one of the five entries")
            failures += 1
        if g["top_status"] != SUCCESS:
            print("    *** FAIL: a grant whose last byte is 0xFFFFFFFF was refused.")
            print("              It needs exactly the room there is; the overflow")
            print("              guard has overreached into a legal case.")
            failures += 1
        elif g["count_top"] != 1:
            print("    *** FAIL: the accepted grant did not consume exactly one entry")
            failures += 1
        if g["unload_status"] != SUCCESS:
            print("    *** FAIL: the probe module did not unload")
            failures += 1

print("")
# Cast, because this symbol has no debug type in the manager image and gdb
# refuses to read an untyped symbol without being told its width.
try:
    print("  boot_stage      = %d" % ev("*(unsigned int *)&boot_stage"))
except gdb.error as e:
    print("  boot_stage      = unavailable (%s)" % e)
print("")
if failures == 0:
    print("===== PASS: relocated, stopped at the boundary both ways, and reported =====")
else:
    print("===== FAIL: %d check(s) wrong =====" % failures)
end
