/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026-present Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/

// Some portions generated by Claude Code (Opus 5).


/**************************************************************************/
/**************************************************************************/
/**                                                                       */
/** ThreadX Component                                                     */
/**                                                                       */
/**   Module Manager                                                      */
/**                                                                       */
/**************************************************************************/
/**************************************************************************/

#define TX_SOURCE_CODE

#include "tx_api.h"
#include "tx_mutex.h"
#include "tx_queue.h"
#include "tx_thread.h"
#include "txm_module.h"


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    _txm_module_manager_external_memory_enable         Cortex-R52       */
/*                                                           6.1.8        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Scott Larson, Microsoft Corporation                                 */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    This function creates an entry in the MPU table for a shared        */
/*    memory space. The start_address must be aligned to the PMSAv8-R     */
/*    protection granule, which is 64 bytes on Cortex-R52 -- the comment  */
/*    inherited from the Armv8-M port says 32, and TXM_MODULE_MPU_ALIGNMENT*/
/*    below is what is actually enforced.                                 */
/*                                                                        */
/*    The length must describe at least one byte and must not run off the */
/*    top of the address space; either is TX_SIZE_ERROR. It need not be a */
/*    multiple of the granule, but the hardware grant is rounded up to    */
/*    one -- see the limit-address comment below for what the caller is   */
/*    therefore agreeing to hand over.                                    */
/*                                                                        */
/*  INPUT                                                                 */
/*                                                                        */
/*    module_instance                   Module instance pointer           */
/*    start_address                     Start address of memory           */
/*    length                            Length of external memory         */
/*    attributes                        Memory attributes (r/w)           */
/*                                                                        */
/*  OUTPUT                                                                */
/*                                                                        */
/*    status                            Completion status                 */
/*                                                                        */
/*  CALLS                                                                 */
/*                                                                        */
/*    _tx_mutex_get                     Get protection mutex              */
/*    _tx_mutex_put                     Release protection mutex          */
/*                                                                        */
/*  CALLED BY                                                             */
/*                                                                        */
/*    Application code                                                    */
/*                                                                        */
/**************************************************************************/
UINT  _txm_module_manager_external_memory_enable(TXM_MODULE_INSTANCE *module_instance,
                                                 VOID *start_address,
                                                 ULONG length,
                                                 UINT attributes)
{

ULONG   address;
ULONG   shared_index;

    /* Determine if the module manager has not been initialized yet.  */
    if (_txm_module_manager_ready != TX_TRUE)
    {
        /* Module manager has not been initialized.  */
        return(TX_NOT_AVAILABLE);
    }

    /* Determine if the module is valid.  */
    if (module_instance == TX_NULL)
    {
        /* Invalid module pointer.  */
        return(TX_PTR_ERROR);
    }

    /* Get module manager protection mutex.  */
    _tx_mutex_get(&_txm_module_manager_mutex, TX_WAIT_FOREVER);

    /* Determine if the module instance is valid.  */
    if (module_instance -> txm_module_instance_id != TXM_MODULE_ID)
    {
        /* Release the protection mutex.  */
        _tx_mutex_put(&_txm_module_manager_mutex);

        /* Invalid module pointer.  */
        return(TX_PTR_ERROR);
    }

    /* Determine if the module instance is in the loaded state.  */
    if (module_instance -> txm_module_instance_state != TXM_MODULE_LOADED)
    {
        /* Release the protection mutex.  */
        _tx_mutex_put(&_txm_module_manager_mutex);

        /* Return error if the module is not ready.  */
        return(TX_START_ERROR);
    }

    /* Determine if there are shared memory entries available.  */
    if(module_instance -> txm_module_instance_shared_memory_count >= TXM_MODULE_MPU_SHARED_ENTRIES)
    {
        /* Release the protection mutex.  */
        _tx_mutex_put(&_txm_module_manager_mutex);

        /* No more entries available.  */
        return(TX_NO_MEMORY);
    }

    /* Start address must adhere to Cortex-R52 MPU alignment.  */
    address = (ULONG) start_address;
    if(address != (address & ~(TXM_MODULE_MPU_ALIGNMENT - 1)))
    {
        /* Release the protection mutex.  */
        _tx_mutex_put(&_txm_module_manager_mutex);

        /* Return alignment error.  */
        return(TXM_MODULE_ALIGNMENT_ERROR);
    }

    /* Reject a grant that describes no memory, and one whose inclusive end
       address runs off the top of the address space.  Both produce a limit
       BELOW the base: a zero length computes address - 1 outright, and a
       wrapping end computes some low address.  Either would be programmed into
       PRLAR, returned as TX_SUCCESS, and would consume one of the five shared
       entries for a region the hardware cannot honour.

       Checked here rather than at the limit computation because a refused grant
       must cost the caller nothing -- no register written and no entry spent --
       and the entry count is incremented further down.

       The wrap test is written against the room left above the base rather than
       as (address + length) < address, which would have to commit the overflow
       in order to detect it.  length is known non-zero by then, so length - 1 is
       the number of bytes above the base the grant needs, and a grant ending
       exactly at the top of memory needs precisely the room there is and is
       accepted.

       TX_SIZE_ERROR for both: the portable API already defines it as the size
       fault, so neither case needs a new return code for callers to handle.  */

    if ((length == 0UL) || ((length - 1UL) > (((ULONG) ~0UL) - address)))
    {
        /* Release the protection mutex.  */
        _tx_mutex_put(&_txm_module_manager_mutex);

        /* Return size error.  */
        return(TX_SIZE_ERROR);
    }

    /* At this point, we have a valid address and length. Set up MPU registers.  */

    /* Pick up index into shared memory entries.  */
    shared_index = TXM_MODULE_MPU_SHARED_INDEX + module_instance -> txm_module_instance_shared_memory_count;

    /* Set base address register with start address, sanitized attributes and execute never.  */
    module_instance -> txm_module_instance_mpu_registers[shared_index].txm_module_mpu_region_base_address = address | (attributes & TXM_MODULE_ATTRIBUTE_MASK) | TXM_MODULE_ATTRIBUTE_EXECUTE_NEVER;

    /* Set the limit address (data start + length-1), attribute index, and enable bit.

       The limit is MASKED to the protection granule before the attributes are
       ORed in, exactly as txm_module_manager_mm_register_setup.c does for the
       code and data regions, and this is not cosmetic.  PRLAR holds LIMIT[31:6]
       with the low six bits carrying RES0[5:4], AttrIndx[3:1] and EN[0], and the
       hardware reads the limit back as LIMIT concatenated with 0x3F -- so the
       masked value describes exactly the same inclusive end address.  Without
       the mask, a granule-sized region ends in 0x3F and those bits land on top
       of the attributes: AttrIndx comes out 7 instead of 0, which selects an
       unwritten MAIR byte and gives the shared region Device memory type, and
       the two RES0 bits are set as well.  The region still works well enough to
       pass a functional test, which is why this was worth writing down.

       What the mask does NOT do is round the grant down.  PRLAR describes an
       inclusive end of LIMIT:0x3F, so the smallest region the hardware can
       express is one 64-byte granule and the effective grant is the requested
       range rounded UP to the next granule boundary: a one-byte grant hands the
       module 64 bytes, a 65-byte grant hands it 128.  The caller owns every byte
       of that rounded range and must intend the module to have it -- there is no
       length this function can accept that gives the module less.

       The length recorded below, and therefore the length
       _txm_module_manager_inside_data_check() validates kernel-call pointers
       against, is the UNROUNDED one the caller asked for.  So a module can reach
       the surplus bytes directly while a kernel call carrying a pointer into
       them is refused.  That asymmetry is deliberate and inherited: every other
       module port computes the same rounded-up grant, and one that did not would
       reject code moved from an Armv8-M part.  Pass a granule multiple and the
       two lengths agree.  */
    module_instance -> txm_module_instance_mpu_registers[shared_index].txm_module_mpu_region_limit_address = ((address + length - 1) & TXM_MODULE_MPU_ADDRESS_MASK) | TXM_MODULE_ATTRIBUTE_INDEX | TXM_MODULE_ATTRIBUTE_REGION_ENABLE;

    /* Keep track of shared memory address and length in module instance.  */
    module_instance -> txm_module_instance_shared_memory_address[module_instance -> txm_module_instance_shared_memory_count] = address;
    module_instance -> txm_module_instance_shared_memory_length[module_instance -> txm_module_instance_shared_memory_count] = length;

    /* Increment counter.  */
    module_instance -> txm_module_instance_shared_memory_count++;

    /* Release the protection mutex.  */
    _tx_mutex_put(&_txm_module_manager_mutex);

    /* Return success.  */
    return(TX_SUCCESS);
}
