/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  MODULE MANAGER                                          RELEASE       */
/*                                                                        */
/*    txm_module_manager_offset_check.c              Cortex-R52/GNU       */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Compile-time verification of the structure offsets that this port's  */
/*    assembly hard-codes.                                                */
/*                                                                        */
/*    tx_thread_schedule.S reaches into TX_THREAD and TXM_MODULE_INSTANCE  */
/*    with numeric offsets, because assembly has no other way to do it.    */
/*    Nothing in the toolchain connects those numbers to the structures     */
/*    they describe, so adding a field, reordering an extension or         */
/*    building with a different set of ThreadX options silently moves the   */
/*    target and the scheduler reads the wrong word.  The failure is a      */
/*    corrupted region table or a fault in a thread that did nothing wrong, */
/*    a long way from the change that caused it.                           */
/*                                                                        */
/*    This file exists so that becomes a build error instead.  It emits no  */
/*    code.                                                                */
/*                                                                        */
/*    The offsets here are not the same as the Armv8-M module port's, and   */
/*    that is the concrete case in point: there the module instance pointer */
/*    sits at 0x90, and here it is 0x94, because the Cortex-R52 port keeps  */
/*    tx_thread_vfp_enable ahead of the module fields in                    */
/*    TX_THREAD_EXTENSION_2.  Copying the Armv8-M numbers would have built  */
/*    cleanly and misbehaved on the board.                                  */
/*                                                                        */
/*    See eclipse-threadx/threadx issue #577, which proposes this check for */
/*    every port rather than only this one.                                */
/*                                                                        */
/**************************************************************************/

#include <stddef.h>
#include "tx_api.h"
#include "txm_module.h"

/* These must match the .equ values at the top of tx_thread_schedule.S.  */

#define TXM_THREAD_MODULE_INSTANCE      0x94
#define TXM_INSTANCE_DATA_START         0x2C
#define TXM_INSTANCE_MPU_REGISTERS      0x64

_Static_assert(offsetof(TX_THREAD, tx_thread_module_instance_ptr)
                   == TXM_THREAD_MODULE_INSTANCE,
               "tx_thread_schedule.S TXM_THREAD_MODULE_INSTANCE no longer matches "
               "TX_THREAD; the scheduler would read the wrong word");

_Static_assert(offsetof(TXM_MODULE_INSTANCE, txm_module_instance_data_start)
                   == TXM_INSTANCE_DATA_START,
               "tx_thread_schedule.S TXM_INSTANCE_DATA_START no longer matches "
               "TXM_MODULE_INSTANCE; the protection check would test the wrong field");

_Static_assert(offsetof(TXM_MODULE_INSTANCE, txm_module_instance_mpu_registers)
                   == TXM_INSTANCE_MPU_REGISTERS,
               "tx_thread_schedule.S TXM_INSTANCE_MPU_REGISTERS no longer matches "
               "TXM_MODULE_INSTANCE; the scheduler would load regions from the "
               "wrong address");

/* Offsets the fault capture hard-codes, from
   txm_module_manager_fault_capture.S.  Same hazard as the scheduler's: the
   capture runs in Abort mode with a fault in progress, and a wrong offset there
   writes the evidence into the wrong field of a structure the application is
   about to read.  */

#define FAULT_THREAD_PTR        0x00
#define FAULT_CODE_LOCATION     0x04
#define FAULT_DFSR              0x08
#define FAULT_DFAR              0x0C
#define FAULT_IFSR              0x10
#define FAULT_IFAR              0x14
#define FAULT_SP                0x18
#define FAULT_R0                0x1C
#define FAULT_LR                0x50
#define FAULT_SPSR              0x54

#define FAULT_OFF(f)  offsetof(TXM_MODULE_MANAGER_MEMORY_FAULT_INFO, \
                               txm_module_manager_memory_fault_info_##f)

_Static_assert(FAULT_OFF(thread_ptr)    == FAULT_THREAD_PTR,    "fault capture: thread_ptr offset moved");
_Static_assert(FAULT_OFF(code_location) == FAULT_CODE_LOCATION, "fault capture: code_location offset moved");
_Static_assert(FAULT_OFF(dfsr)          == FAULT_DFSR,          "fault capture: dfsr offset moved");
_Static_assert(FAULT_OFF(dfar)          == FAULT_DFAR,          "fault capture: dfar offset moved");
_Static_assert(FAULT_OFF(ifsr)          == FAULT_IFSR,          "fault capture: ifsr offset moved");
_Static_assert(FAULT_OFF(ifar)          == FAULT_IFAR,          "fault capture: ifar offset moved");
_Static_assert(FAULT_OFF(sp)            == FAULT_SP,            "fault capture: sp offset moved");
_Static_assert(FAULT_OFF(r0)            == FAULT_R0,            "fault capture: r0 offset moved");
_Static_assert(FAULT_OFF(lr)            == FAULT_LR,            "fault capture: lr offset moved");
_Static_assert(FAULT_OFF(spsr)          == FAULT_SPSR,          "fault capture: spsr offset moved");

/* The capture writes r4 through r11 as one block starting sixteen bytes past r0,
   and r12 thirty-two bytes past that, which assumes the registers are laid out
   in order with no padding.  */

_Static_assert(FAULT_OFF(r4)  == (FAULT_R0 + 16),   "fault capture: r4 is not four words past r0");
_Static_assert(FAULT_OFF(r12) == (FAULT_R0 + 0x30), "fault capture: r12 is not where the block store expects");

/* The scheduler loads exactly eight regions as sixteen consecutive words, with
   LDMIA walking the table two words at a time.  If the entry stops being two
   words, or the table stops holding eight of them, the unrolled sequence walks
   off the end of it.  */

_Static_assert(sizeof(TXM_MODULE_MPU_INFO) == (2U * sizeof(ULONG)),
               "TXM_MODULE_MPU_INFO is no longer two words; the unrolled LDMIA "
               "sequence in tx_thread_schedule.S would misread the region table");

_Static_assert(TXM_MODULE_MPU_TOTAL_ENTRIES == 8,
               "tx_thread_schedule.S has an unrolled sequence for exactly eight "
               "regions; change both together");

/* The block has to sit inside the directly addressable range.  Regions above 15
   are reachable only through PRSELR, which the scheduler does not use.  */

_Static_assert((TXM_MODULE_MPU_FIRST_REGION + TXM_MODULE_MPU_TOTAL_ENTRIES) <= 16,
               "the module region block extends past region 15, which has no "
               "direct PRBARn encoding; the scheduler cannot reach it");
