/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  MODULE MANAGER                                          RELEASE       */
/*                                                                        */
/*    txm_module_manager_offset_check.c              Cortex-R52/GNU       */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Compile-time verification of the structure offsets that this port's  */
/*    assembly hard-codes.                                                */
/*                                                                        */
/*    tx_thread_schedule.S reaches into TX_THREAD and TXM_MODULE_INSTANCE  */
/*    with numeric offsets, because assembly has no other way to do it.    */
/*    Nothing in the toolchain connects those numbers to the structures     */
/*    they describe, so adding a field, reordering an extension or         */
/*    building with a different set of ThreadX options silently moves the   */
/*    target and the scheduler reads the wrong word.  The failure is a      */
/*    corrupted region table or a fault in a thread that did nothing wrong, */
/*    a long way from the change that caused it.                           */
/*                                                                        */
/*    This file exists so that becomes a build error instead.  It emits no  */
/*    code.                                                                */
/*                                                                        */
/*    The offsets here are not the same as the Armv8-M module port's, and   */
/*    that is the concrete case in point: there the module instance pointer */
/*    sits at 0x90, and here it is 0x94, because the Cortex-R52 port keeps  */
/*    tx_thread_vfp_enable ahead of the module fields in                    */
/*    TX_THREAD_EXTENSION_2.  Copying the Armv8-M numbers would have built  */
/*    cleanly and misbehaved on the board.                                  */
/*                                                                        */
/*    See eclipse-threadx/threadx issue #577, which proposes this check for */
/*    every port rather than only this one.                                */
/*                                                                        */
/**************************************************************************/

#include <stddef.h>
#include "tx_api.h"
#include "txm_module.h"
#include "mpu.h"

/* These must match the .equ values at the top of tx_thread_schedule.S.  */

#define TXM_THREAD_MODULE_INSTANCE      0x94
#define TXM_INSTANCE_DATA_START         0x2C
#define TXM_INSTANCE_MPU_REGISTERS      0x64

_Static_assert(offsetof(TX_THREAD, tx_thread_module_instance_ptr)
                   == TXM_THREAD_MODULE_INSTANCE,
               "tx_thread_schedule.S TXM_THREAD_MODULE_INSTANCE no longer matches "
               "TX_THREAD; the scheduler would read the wrong word");

_Static_assert(offsetof(TXM_MODULE_INSTANCE, txm_module_instance_data_start)
                   == TXM_INSTANCE_DATA_START,
               "tx_thread_schedule.S TXM_INSTANCE_DATA_START no longer matches "
               "TXM_MODULE_INSTANCE; the protection check would test the wrong field");

_Static_assert(offsetof(TXM_MODULE_INSTANCE, txm_module_instance_mpu_registers)
                   == TXM_INSTANCE_MPU_REGISTERS,
               "tx_thread_schedule.S TXM_INSTANCE_MPU_REGISTERS no longer matches "
               "TXM_MODULE_INSTANCE; the scheduler would load regions from the "
               "wrong address");

/* Offset the module thread stack build hard-codes.  This one decides the mode a
   module thread starts in, so a wrong value starts it privileged when it asked
   not to be -- protection that is absent from the first instruction and looks
   present everywhere else.  The Cortex-R4 module port reads 0x9C here, which in
   this port is a different field.  */

_Static_assert(offsetof(TX_THREAD, tx_thread_module_user_mode) == 0xA0,
               "txm_module_manager_thread_stack_build.S THREAD_MODULE_USER_MODE "
               "no longer matches TX_THREAD; module threads could start in the "
               "wrong privilege mode");

_Static_assert(offsetof(TX_THREAD, tx_thread_module_user_mode)
                   != offsetof(TX_THREAD, tx_thread_module_current_user_mode),
               "the requested and current user-mode fields have collapsed onto "
               "one offset; the stack build and the SVC handler would be reading "
               "each other's field");

/* Offsets the supervisor call handler hard-codes, from
   txm_module_manager_svc_handler.S.  This is the privilege boundary, so a wrong
   offset here does not merely misbehave: writing the user-mode flag to the wrong
   word would leave a thread believing it is privileged when it is not, or the
   reverse, and swapping to a stack pointer read from the wrong field would put
   the kernel on memory the module can write.  */

#define THREAD_STACK_PTR        0x08
#define THREAD_STACK_START      0x0C
#define THREAD_STACK_END        0x10
#define THREAD_STACK_SIZE       0x14
#define THREAD_CUR_USER_MODE    0x9C
#define THREAD_KSTACK_START     0xA8
#define THREAD_KSTACK_END       0xAC
#define THREAD_KSTACK_SIZE      0xB0
#define THREAD_MSTACK_PTR       0xB4
#define THREAD_MSTACK_START     0xB8
#define THREAD_MSTACK_END       0xBC
#define THREAD_MSTACK_SIZE      0xC0

#define T_OFF(f)  offsetof(TX_THREAD, f)

_Static_assert(T_OFF(tx_thread_stack_ptr)   == THREAD_STACK_PTR,   "svc handler: stack_ptr moved");
_Static_assert(T_OFF(tx_thread_stack_start) == THREAD_STACK_START, "svc handler: stack_start moved");
_Static_assert(T_OFF(tx_thread_stack_end)   == THREAD_STACK_END,   "svc handler: stack_end moved");
_Static_assert(T_OFF(tx_thread_stack_size)  == THREAD_STACK_SIZE,  "svc handler: stack_size moved");

_Static_assert(T_OFF(tx_thread_module_current_user_mode) == THREAD_CUR_USER_MODE,
               "svc handler: the user-mode flag moved; a thread could be left "
               "believing it is privileged when it is not");

_Static_assert(T_OFF(tx_thread_module_kernel_stack_start) == THREAD_KSTACK_START, "svc handler: kernel_stack_start moved");
_Static_assert(T_OFF(tx_thread_module_kernel_stack_end)   == THREAD_KSTACK_END,
               "svc handler: kernel_stack_end moved; the kernel would run on a "
               "stack read from the wrong field");
_Static_assert(T_OFF(tx_thread_module_kernel_stack_size)  == THREAD_KSTACK_SIZE,  "svc handler: kernel_stack_size moved");
_Static_assert(T_OFF(tx_thread_module_stack_ptr)   == THREAD_MSTACK_PTR,   "svc handler: module stack_ptr moved");
_Static_assert(T_OFF(tx_thread_module_stack_start) == THREAD_MSTACK_START, "svc handler: module stack_start moved");
_Static_assert(T_OFF(tx_thread_module_stack_end)   == THREAD_MSTACK_END,   "svc handler: module stack_end moved");
_Static_assert(T_OFF(tx_thread_module_stack_size)  == THREAD_MSTACK_SIZE,  "svc handler: module stack_size moved");

/* Offsets the fault capture hard-codes, from
   txm_module_manager_fault_capture.S.  Same hazard as the scheduler's: the
   capture runs in Abort mode with a fault in progress, and a wrong offset there
   writes the evidence into the wrong field of a structure the application is
   about to read.  */

#define FAULT_THREAD_PTR        0x00
#define FAULT_CODE_LOCATION     0x04
#define FAULT_DFSR              0x08
#define FAULT_DFAR              0x0C
#define FAULT_IFSR              0x10
#define FAULT_IFAR              0x14
#define FAULT_SP                0x18
#define FAULT_R0                0x1C
#define FAULT_LR                0x50
#define FAULT_SPSR              0x54

#define FAULT_OFF(f)  offsetof(TXM_MODULE_MANAGER_MEMORY_FAULT_INFO, \
                               txm_module_manager_memory_fault_info_##f)

_Static_assert(FAULT_OFF(thread_ptr)    == FAULT_THREAD_PTR,    "fault capture: thread_ptr offset moved");
_Static_assert(FAULT_OFF(code_location) == FAULT_CODE_LOCATION, "fault capture: code_location offset moved");
_Static_assert(FAULT_OFF(dfsr)          == FAULT_DFSR,          "fault capture: dfsr offset moved");
_Static_assert(FAULT_OFF(dfar)          == FAULT_DFAR,          "fault capture: dfar offset moved");
_Static_assert(FAULT_OFF(ifsr)          == FAULT_IFSR,          "fault capture: ifsr offset moved");
_Static_assert(FAULT_OFF(ifar)          == FAULT_IFAR,          "fault capture: ifar offset moved");
_Static_assert(FAULT_OFF(sp)            == FAULT_SP,            "fault capture: sp offset moved");
_Static_assert(FAULT_OFF(r0)            == FAULT_R0,            "fault capture: r0 offset moved");
_Static_assert(FAULT_OFF(lr)            == FAULT_LR,            "fault capture: lr offset moved");
_Static_assert(FAULT_OFF(spsr)          == FAULT_SPSR,          "fault capture: spsr offset moved");

/* The capture writes r4 through r11 as one block starting sixteen bytes past r0,
   and r12 thirty-two bytes past that, which assumes the registers are laid out
   in order with no padding.  */

_Static_assert(FAULT_OFF(r4)  == (FAULT_R0 + 16),   "fault capture: r4 is not four words past r0");
_Static_assert(FAULT_OFF(r12) == (FAULT_R0 + 0x30), "fault capture: r12 is not where the block store expects");

/* The scheduler loads exactly eight regions as sixteen consecutive words, with
   LDMIA walking the table two words at a time.  If the entry stops being two
   words, or the table stops holding eight of them, the unrolled sequence walks
   off the end of it.  */

_Static_assert(sizeof(TXM_MODULE_MPU_INFO) == (2U * sizeof(ULONG)),
               "TXM_MODULE_MPU_INFO is no longer two words; the unrolled LDMIA "
               "sequence in tx_thread_schedule.S would misread the region table");

_Static_assert(TXM_MODULE_MPU_TOTAL_ENTRIES == 8,
               "tx_thread_schedule.S has an unrolled sequence for exactly eight "
               "regions; change both together");

/* The block has to sit inside the directly addressable range.  Regions above 15
   are reachable only through PRSELR, which the scheduler does not use.  */

_Static_assert((TXM_MODULE_MPU_FIRST_REGION + TXM_MODULE_MPU_TOTAL_ENTRIES) <= 16,
               "the module region block extends past region 15, which has no "
               "direct PRBARn encoding; the scheduler cannot reach it");

/* The kernel's window over the module area.  tx_thread_schedule.S hard-codes the
   region number in an MCR to PRSELR, because the assembler cannot include this
   board header, so the two spellings are checked against each other here.

   It also has to sit clear of the module's own block: the scheduler enables the
   window for a thread that owns no module and the block for a thread that does,
   and if the two ever named the same region one would silently be the other.  */

_Static_assert(MPU_MODULE_LOAD_REGION == 16,
               "tx_thread_schedule.S writes region 16 as the module window; "
               "change MPU_MODULE_WINDOW_REGION there to match");

_Static_assert(MPU_MODULE_LOAD_REGION >= (TXM_MODULE_MPU_FIRST_REGION
                                          + TXM_MODULE_MPU_TOTAL_ENTRIES),
               "the module window overlaps the regions handed to a module; the "
               "scheduler would enable one believing it was the other");
