/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    board.h                                          Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Declarations for the objects that cross the C/assembly boundary in  */
/*    this board support package.                                         */
/*                                                                        */
/*    These exist because assembly callers do not provide prototypes:     */
/*    entry.S calls bsp_main, _tx_initialize_low_level calls board_init,  */
/*    and __tx_irq_processing_return calls board_irq_handler.  Without a  */
/*    header the definitions have external linkage and no visible         */
/*    declaration, which MISRA C:2012 Rule 8.4 prohibits and which        */
/*    -Wmissing-prototypes reports.  Declaring them in one place also     */
/*    means a signature change cannot silently disagree with the assembly.*/
/*                                                                        */
/**************************************************************************/

#ifndef BOARD_H
#define BOARD_H

/* Application entry, called from entry.S after EL1 setup; never returns. */

void bsp_main(void);

/* Interrupt controller and periodic tick bring-up, called from
   _tx_initialize_low_level while interrupts are still masked.  */

void board_init(void);

/* Interrupt dispatch, called from __tx_irq_processing_return in entry.S
   after the interrupted context has been saved.  */

void board_irq_handler(void);

/* The nesting path splits the handler in three, because the acknowledge has to
   happen in IRQ mode before nesting starts and the end-of-interrupt after it
   finishes.  board_irq_service does the middle part on an INTID that has
   already been acknowledged, and does not acknowledge or EOI itself.  */

void board_irq_service(unsigned long intid);

/* Interrupt observability, maintained by board_irq_handler.              */

extern volatile unsigned long   board_irq_count;
extern volatile unsigned long   board_timer_intid;
extern volatile unsigned long   board_spurious_count;
extern volatile unsigned long   board_unexpected_intid;

/* Nesting observability, maintained by board_irq_handler.  All of this is inert
   unless the image was built with TX_ENABLE_IRQ_NESTING: without it the handler
   runs in IRQ mode with interrupts masked and can never be re-entered.  */

extern volatile unsigned long   board_nest_depth;
extern volatile unsigned long   board_nest_max;
extern volatile unsigned long   board_sgi_count;
extern volatile unsigned long   board_sgi_nested_count;

/* Set by demo_nesting to make the timer handler provoke a nested SGI.  Left at
   zero every other image behaves exactly as before.  */

extern volatile unsigned long   board_nest_provoke;

#define BOARD_NEST_SGI_INTID    8U

/* FIQ observability.  Two Group 0 SGIs, because FIQ nesting means an FIQ taken
   while an FIQ handler is running, so a single source cannot show it.  The
   higher-priority one is raised from inside the lower one's handler.  */

void board_fiq_handler(void);
void board_fiq_service(unsigned long intid);

extern volatile unsigned long   board_fiq_count;
extern volatile unsigned long   board_fiq_high_count;
extern volatile unsigned long   board_fiq_nested_count;
extern volatile unsigned long   board_fiq_depth;
extern volatile unsigned long   board_fiq_max_depth;
extern volatile unsigned long   board_fiq_unexpected;
extern volatile unsigned long   board_fiq_provoke;

#define BOARD_FIQ_LOW_INTID     10U
#define BOARD_FIQ_HIGH_INTID    11U

/* Counted by the EL2 hyp-trap handler in entry.S; the ZoneX seam.        */

extern volatile unsigned long   _hvc_call_count;

/* Recoverable data-abort support for the MPU enforcement self-test, handled
   in entry.S.  Setting mpu_expect_abort makes the next data abort resume at
   the instruction following the faulting one instead of halting.  */

extern volatile unsigned long   mpu_expect_abort;
extern volatile unsigned long   mpu_abort_count;

#endif /* BOARD_H */
