/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    bsp_boot.c                                       Cortex-R52/GNU     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    AR1 milestone M1 boot check.  Verifies that the reset path really    */
/*    configured EL2 and then dropped to EL1, and that the EL2 HVC seam    */
/*    used by ZoneX (AR3) is reachable from EL1 and returns correctly.     */
/*                                                                        */
/*    This deliberately asserts the resulting exception level rather than  */
/*    merely printing a message: "it printed something" does not prove a   */
/*    correct EL2-to-EL1 transition, and AR3 depends on that transition.   */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                    */
/*                                                                        */
/*    Directive 4.3 -- the two asm statements below read CPSR and issue     */
/*      HVC; neither has a standard C equivalent.  Both are encapsulated   */
/*      in dedicated one-line functions.                                   */
/*                                                                        */
/**************************************************************************/

#include "console.h"

/* AArch32 CPSR mode field encodings.  */

#define CPSR_MODE_MASK  0x1FUL
#define CPSR_MODE_SVC   0x13UL          /* Supervisor -- an EL1 mode        */
#define CPSR_MODE_HYP   0x1AUL          /* Hyp        -- EL2                */

/* Incremented by the EL2 HVC handler in entry.S.  */

extern volatile unsigned long _hvc_call_count;


/**************************************************************************/
/*  read_cpsr -- current program status, including the mode field.         */
/**************************************************************************/

static unsigned long read_cpsr(void)
{
    unsigned long value;

    __asm__ volatile("mrs %0, cpsr" : "=r"(value));

    return value;
}


/**************************************************************************/
/*  issue_hvc -- call into EL2 through the ZoneX seam and return.          */
/**************************************************************************/

static void issue_hvc(void)
{
    __asm__ volatile("hvc #0" : : : "memory");
}


/**************************************************************************/
/*  report -- print one labelled check result.                            */
/**************************************************************************/

static void report(const char *label_ptr, unsigned int passed)
{
    console_puts(label_ptr);
    console_puts(passed != 0U ? "PASS\n" : "FAIL\n");
}


/**************************************************************************/
/*  bsp_main -- entered at EL1 from entry.S.  Does not return.            */
/**************************************************************************/

void bsp_main(void)
{
    unsigned long cpsr;
    unsigned long mode;
    unsigned long hvc_before;
    unsigned long hvc_after;
    unsigned int  failures = 0U;

    console_puts("\n=== ThreadX AR1/M1 boot check "
                 "(Cortex-R52, Armv8-R AArch32, Armv8-R AEM FVP) ===\n");

    /* Check 1: we are executing at EL1, not still at EL2.  */

    cpsr = read_cpsr();
    mode = cpsr & CPSR_MODE_MASK;

    console_puts("[EL1] CPSR   = ");
    console_puthex(cpsr);
    console_puts("\n[EL1] CPSR.M = ");
    console_puthex(mode);
    console_puts("\n");

    if (mode == CPSR_MODE_SVC)
    {
        report("[EL1] running in Supervisor mode (EL1)            ", 1U);
    }
    else
    {
        failures++;
        if (mode == CPSR_MODE_HYP)
        {
            console_puts("[EL1] still in Hyp mode -- ERET to EL1 did not happen  FAIL\n");
        }
        else
        {
            report("[EL1] unexpected CPSR mode                        ", 0U);
        }
    }

    /* Check 2: the EL2 HVC seam is reachable from EL1 and returns.  This is
       what AR3 (ZoneX Phase-0) builds on, so it is verified from AR1.  */

    hvc_before = _hvc_call_count;
    issue_hvc();
    hvc_after = _hvc_call_count;

    console_puts("[EL1] HVC count before/after = ");
    console_puthex(hvc_before);
    console_puts(" / ");
    console_puthex(hvc_after);
    console_puts("\n");

    if (hvc_after == (hvc_before + 1UL))
    {
        report("[EL1] EL2 HVC seam reachable and returns to EL1   ", 1U);
    }
    else
    {
        failures++;
        report("[EL1] EL2 HVC seam did not take effect            ", 0U);
    }

    /* Summary.  The exact strings are what the automated runner greps for.  */

    if (failures == 0U)
    {
        console_puts("\nM1 RESULT: ALL CHECKS PASSED\n");
    }
    else
    {
        console_puts("\nM1 RESULT: FAILED\n");
    }

    console_exit(failures);
}
