/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    console.h                                        Cortex-R52/GNU     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Minimal console for the Armv8-R AEM FVP.  Backed by semihosting so   */
/*    that early bring-up needs no peripheral base addresses; the PL011    */
/*    UART implementation arrives in AR1/M3 behind this same interface.    */
/*                                                                        */
/**************************************************************************/

#ifndef CONSOLE_H
#define CONSOLE_H

/* Write a NUL-terminated string to the console.  */

void console_puts(const char *string_ptr);

/* Write value as 0x-prefixed, zero-padded 32-bit hexadecimal.  */

void console_puthex(unsigned long value);

/* Terminate the simulation (semihosting SYS_EXIT).  Does not return.
   Pass/fail is reported through the printed result line rather than a host
   exit status, because the AArch32 SYS_EXIT reason code is not a status.  */

void console_exit(unsigned int status);

#endif /* CONSOLE_H */
