/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  DEMONSTRATION                                          RELEASE        */
/*                                                                        */
/*    demo_verify.c                                    Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    AR1 milestone M4: verifies that the standard eight-thread ThreadX   */
/*    demo makes progress on Cortex-R52, then terminates the simulation   */
/*    so the run can be automated.                                        */
/*                                                                        */
/*    Where M3 proved the tick and a single preemption, this exercises    */
/*    the demo's full object set -- queue, semaphore, mutex, event flags, */
/*    byte pool and block pool -- across eight threads at five priorities.*/
/*    Each of the ten demo counters is required to have advanced: a       */
/*    stalled thread (a lost wakeup, a mishandled priority inversion)     */
/*    shows up as a counter still at zero rather than as a plausible-     */
/*    looking run.                                                        */
/*                                                                        */
/*    The verification thread runs at priority 0 so it can always preempt */
/*    the demo, and spends nearly all its life suspended.                 */
/*                                                                        */
/**************************************************************************/

#include "tx_api.h"
#include "board.h"
#include "console.h"
#include "demo_verify.h"

#define VERIFY_STACK_SIZE   2048

/* Ticks to let the demo run before checking.  thread_0 sleeps 10 ticks per
   iteration and thread_5 waits on the event flag it sets, so these two are
   the slowest; 300 ticks (3 s at 100 Hz) gives them ~30 iterations each.  */

#define VERIFY_SETTLE_TICKS 300UL

/* Counters defined by the standard demo.                                 */

extern ULONG    thread_0_counter;
extern ULONG    thread_1_counter;
extern ULONG    thread_1_messages_sent;
extern ULONG    thread_2_counter;
extern ULONG    thread_2_messages_received;
extern ULONG    thread_3_counter;
extern ULONG    thread_4_counter;
extern ULONG    thread_5_counter;
extern ULONG    thread_6_counter;
extern ULONG    thread_7_counter;

static TX_THREAD    verify_thread;
static ULONG        verify_stack[VERIFY_STACK_SIZE / sizeof(ULONG)];


/**************************************************************************/
/*  check_counter -- report one counter and whether it advanced.          */
/**************************************************************************/

static UINT check_counter(const char *label_ptr, ULONG value)
{
    console_puts(label_ptr);
    console_puthex(value);
    console_puts((value > 0UL) ? "  PASS\n" : "  FAIL\n");

    return (value > 0UL) ? 0U : 1U;
}


/**************************************************************************/
/*  verify_thread_entry                                                   */
/**************************************************************************/

static void verify_thread_entry(ULONG thread_input)
{
    UINT    failures = 0U;
    ULONG   elapsed;

    (void) thread_input;

    console_puts("[verify] letting the standard demo run for ");
    console_puthex(VERIFY_SETTLE_TICKS);
    console_puts(" ticks...\n");

    tx_thread_sleep(VERIFY_SETTLE_TICKS);

    elapsed = tx_time_get();

    console_puts("\n[verify] demo counters after settling:\n");

    failures += check_counter("  thread 0 counter            = ", thread_0_counter);
    failures += check_counter("  thread 1 counter            = ", thread_1_counter);
    failures += check_counter("  thread 1 messages sent      = ", thread_1_messages_sent);
    failures += check_counter("  thread 2 counter            = ", thread_2_counter);
    failures += check_counter("  thread 2 messages received  = ", thread_2_messages_received);
    failures += check_counter("  thread 3 counter            = ", thread_3_counter);
    failures += check_counter("  thread 4 counter            = ", thread_4_counter);
    failures += check_counter("  thread 5 counter            = ", thread_5_counter);
    failures += check_counter("  thread 6 counter            = ", thread_6_counter);
    failures += check_counter("  thread 7 counter            = ", thread_7_counter);

    /* The queue must not have silently dropped or duplicated messages.  */

    console_puts("\n[verify] queue balance (sent >= received) ");
    if (thread_1_messages_sent >= thread_2_messages_received)
    {
        console_puts("PASS\n");
    }
    else
    {
        failures++;
        console_puts("FAIL\n");
    }

    console_puts("[verify] elapsed ticks = ");
    console_puthex(elapsed);
    console_puts("\n[verify] tick advanced past the settle period ");
    if (elapsed >= VERIFY_SETTLE_TICKS)
    {
        console_puts("PASS\n");
    }
    else
    {
        failures++;
        console_puts("FAIL\n");
    }

    if (failures == 0U)
    {
        console_puts("\nM4 RESULT: ALL CHECKS PASSED\n");
    }
    else
    {
        console_puts("\nM4 RESULT: FAILED\n");
    }

    console_exit(failures);
}


/**************************************************************************/
/*  demo_verify_create                                                    */
/**************************************************************************/

void demo_verify_create(void)
{
    /* Priority 0 and its own static stack: the verification thread must be
       able to preempt every demo thread, and must not perturb the demo's
       byte-pool allocations.  */

    (void) tx_thread_create(&verify_thread, "verify", verify_thread_entry, 0UL,
                            verify_stack, sizeof(verify_stack),
                            0U, 0U, TX_NO_TIME_SLICE, TX_AUTO_START);
}


/**************************************************************************/
/*  bsp_main -- entered at EL1 from entry.S.  Does not return.            */
/**************************************************************************/

void bsp_main(void)
{
    console_puts("\n=== ThreadX AR1/M4 standard eight-thread demo "
                 "(Cortex-R52, Armv8-R AArch32, Armv8-R AEM FVP) ===\n");

    tx_kernel_enter();
}
