/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  DEMONSTRATION                                          RELEASE        */
/*                                                                        */
/*    demo_clz.c                                       Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Regression test for this port's CLZ implementation of               */
/*    TX_LOWEST_SET_BIT_CALCULATE, which replaces the portable loop in    */
/*    tx_thread.h and which the scheduler's priority search runs on       */
/*    every suspend and resume.                                           */
/*                                                                        */
/*    Why this image exists.  The macro was DEAD until 20 Aug 2026:       */
/*    tx_port.h guarded it with __TARGET_ARCH_ARM > 4, an Arm Compiler 5  */
/*    predefine that GCC never defines, so the test read 0 > 4 and the    */
/*    portable loop ran on a core that has had CLZ since Armv5.  Turning  */
/*    it on means hand-written inline assembly now decides which thread   */
/*    runs next, so it gets a test that pins the answer for every input   */
/*    class rather than a build that merely compiles.                     */
/*                                                                        */
/*    What is checked, against an obvious linear-scan reference rather    */
/*    than against the implementation being tested:                       */
/*                                                                        */
/*      1. Each of the 32 single-bit maps returns its own bit position.   */
/*      2. Each bit position with a deterministic spray of HIGHER bits    */
/*         set still returns that position -- the macro must find the     */
/*         LOWEST set bit, and a single-bit test cannot tell the          */
/*         difference between "lowest" and "only".                        */
/*      3. A table of hand-picked patterns, including the two the         */
/*         respelled isolation step could plausibly break: 0x80000000,    */
/*         the one input for which upstream's signed negation was         */
/*         undefined, and 0xFFFFFFFF.                                     */
/*      4. Every group is run twice, once through a UINT result and once  */
/*         through a ULONG one, because the kernel calls the macro with   */
/*         both and the closing 31 - b is where a width mistake would     */
/*         hide.                                                          */
/*      5. The m == 0 divergence is PINNED, not fixed.  CLZ(0) is 32, so  */
/*         this implementation yields 31 - 32 while the portable loop     */
/*         yields 0.  Every one of the twelve call sites in common/src     */
/*         reaches the macro only on a map already tested against zero,   */
/*         so the difference is unreachable -- and a test that records    */
/*         it is how it stays a decision instead of becoming a surprise.  */
/*                                                                        */
/*    The checks run inside a ThreadX thread on purpose.  By the time the */
/*    thread's entry is reached the scheduler has already executed the    */
/*    macro on the way to dispatching it, so a macro broken badly enough  */
/*    to misdirect the priority search shows up as a hang -- which the    */
/*    runner scores as a failure -- before any check is evaluated.        */
/*                                                                        */
/**************************************************************************/

#include "tx_api.h"
#include "console.h"
#include "board.h"

/* The port's definition must be the one in scope.  tx_thread.h supplies a
   portable fallback under #ifndef, so an image that reached this file with the
   macro undefined would be testing that fallback and reporting a pass for it --
   the exact failure mode this whole image exists to rule out.  */

#ifndef TX_LOWEST_SET_BIT_CALCULATE
#error "demo_clz: tx_port.h did not define TX_LOWEST_SET_BIT_CALCULATE, so this image would test the portable loop and call it a pass."
#endif

/* And it must be defined for the reason we think it is.  These are the two
   conditions tx_port.h uses; asserting them here means a future edit that
   silently drops the CLZ path cannot leave this image passing.  */

#if !defined(__ARM_FEATURE_CLZ)
#error "demo_clz: __ARM_FEATURE_CLZ is not defined, so the CLZ path in tx_port.h is not the definition under test."
#endif

#if defined(__thumb__)
#error "demo_clz: built for Thumb, where tx_port.h deliberately keeps the portable loop.  Build this image -marm."
#endif


#define DEMO_STACK_SIZE         2048

static TX_THREAD            check_thread;
static UCHAR                check_stack[DEMO_STACK_SIZE];

/* Failure detail, kept as counters rather than printed per case: 32 passing
   lines tell a reader nothing and would bury the one failing line.  */

static UINT                 failures;


/**************************************************************************/
/*  reference_lowest_bit                                                  */
/*                                                                        */
/*  The ground truth, written to be read rather than to be fast.  It is   */
/*  deliberately NOT the portable macro from tx_thread.h: comparing an    */
/*  implementation against a cleverer implementation of the same idea     */
/*  tests that they share their mistakes.  A linear scan has nowhere to   */
/*  hide one.                                                             */
/**************************************************************************/

static ULONG reference_lowest_bit(ULONG map)
{
    ULONG   index;
    ULONG   result = 0xFFFFFFFFUL;      /* No bit set.                    */

    for (index = 0UL; index < 32UL; index++)
    {
        if ((map & (1UL << index)) != 0UL)
        {
            result = index;
            break;
        }
    }

    return result;
}


/**************************************************************************/
/*  next_pattern                                                          */
/*                                                                        */
/*  A fixed linear congruential sequence.  A regression test must produce */
/*  the same inputs on every run, so the spray of high bits in group 2 is */
/*  pseudo-random and seeded, never actually random.                      */
/**************************************************************************/

static ULONG next_pattern(ULONG state)
{
    return (state * 1103515245UL) + 12345UL;
}


/**************************************************************************/
/*  check_one                                                             */
/*                                                                        */
/*  Runs one map through the macro twice, once landing in a UINT and once */
/*  in a ULONG, and compares both against the reference.  The macro       */
/*  CONSUMES its first argument -- both implementations rewrite the map    */
/*  in place -- so each call gets its own copy, which is also the trap a   */
/*  caller reusing the variable afterwards would fall into.               */
/**************************************************************************/

static void check_one(ULONG map, ULONG expected, const char *group_ptr)
{
    ULONG   working;
    UINT    bit_as_uint;
    ULONG   bit_as_ulong;

    working = map;
    TX_LOWEST_SET_BIT_CALCULATE(working, bit_as_uint)

    working = map;
    TX_LOWEST_SET_BIT_CALCULATE(working, bit_as_ulong)

    if (((ULONG) bit_as_uint != expected) || (bit_as_ulong != expected))
    {
        failures++;

        console_puts("[FAIL] ");
        console_puts(group_ptr);
        console_puts(" map=");
        console_puthex(map);
        console_puts(" expected=");
        console_puthex(expected);
        console_puts(" got UINT=");
        console_puthex((unsigned long) bit_as_uint);
        console_puts(" ULONG=");
        console_puthex(bit_as_ulong);
        console_puts("\n");
    }
}


/**************************************************************************/
/*  report                                                                */
/**************************************************************************/

static void report(const char *label_ptr, UINT failures_before)
{
    console_puts(label_ptr);
    console_puts((failures == failures_before) ? "PASS\n" : "FAIL\n");
}


/**************************************************************************/
/*  thread_check_entry                                                    */
/**************************************************************************/

static void thread_check_entry(ULONG thread_input)
{
    ULONG   index;
    ULONG   spray;
    ULONG   state;
    ULONG   map;
    ULONG   working;
    ULONG   bit;
    UINT    before;

    /* Hand-picked patterns.  0x80000000 is the one input for which upstream's
       (ULONG)(-((LONG) m)) isolation was undefined behaviour, and 0xFFFFFFFF is
       the densest map the scheduler can present.  */

    static const ULONG  patterns[] =
    {
        0xFFFFFFFFUL, 0x80000000UL, 0xAAAAAAAAUL, 0x55555555UL,
        0xF0F0F000UL, 0x00000003UL, 0x7FFFFFFFUL, 0xC0000000UL,
        0x00010000UL, 0xFFFF0000UL
    };

    (void) thread_input;

    console_puts("\n=== ThreadX Cortex-R52 CLZ lowest-set-bit regression ===\n\n");

    /* Group 1 -- every single-bit map.  */

    before = failures;
    for (index = 0UL; index < 32UL; index++)
    {
        check_one(1UL << index, index, "single bit");
    }
    report("[check] 32 single-bit maps ................ ", before);

    /* Group 2 -- every bit position with higher bits sprayed above it.  This is
       the group that distinguishes "lowest set bit" from "only set bit".  */

    before = failures;
    state = 0x12345678UL;
    for (index = 0UL; index < 32UL; index++)
    {
        state = next_pattern(state);

        /* Keep only bits strictly above index, then put index back.  Shifting a
           32-bit value by 32 is undefined, so the top position is special-cased
           to no spray at all -- there is nothing above bit 31 to set.  */

        if (index < 31UL)
        {
            spray = (state << (index + 1UL)) & 0xFFFFFFFFUL;
        }
        else
        {
            spray = 0UL;
        }

        check_one(spray | (1UL << index), index, "lowest of many");
    }
    report("[check] 32 sprayed maps, lowest bit wins .. ", before);

    /* Group 3 -- the hand-picked table.  */

    before = failures;
    for (index = 0UL; index < (ULONG) (sizeof(patterns) / sizeof(patterns[0])); index++)
    {
        check_one(patterns[index], reference_lowest_bit(patterns[index]), "pattern");
    }
    report("[check] 10 hand-picked patterns .......... ", before);

    /* Group 4 -- the pinned divergence at zero.  Not a fix: a record.  CLZ(0)
       is 32 and the closing subtraction is unsigned, so the answer is 31 - 32
       taken modulo 2^32.  The portable loop in tx_thread.h answers 0 for the
       same input.  Neither is reachable from the kernel, and this check exists
       so that changing which one is true has to be deliberate.  */

    before = failures;
    working = 0UL;
    TX_LOWEST_SET_BIT_CALCULATE(working, bit)

    if (bit != 0xFFFFFFFFUL)
    {
        failures++;
        console_puts("[FAIL] map=0 answered ");
        console_puthex(bit);
        console_puts(", documented answer for the CLZ implementation is 0xFFFFFFFF\n");
    }
    report("[check] map = 0 answers as documented .... ", before);

    /* Group 5 -- the macro consumes its first argument, in both
       implementations.  Stated as a check because it is a property callers rely
       on by never relying on it, and a "fix" that stopped rewriting the map
       would quietly change what every call site's variable holds afterwards.  */

    before = failures;
    map = 0x00000280UL;                 /* Lowest set bit is 7.           */
    working = map;
    TX_LOWEST_SET_BIT_CALCULATE(working, bit)

    if ((bit != 7UL) || (working != (1UL << 7)))
    {
        failures++;
        console_puts("[FAIL] expected bit 7 and map reduced to 0x80, got bit ");
        console_puthex(bit);
        console_puts(" map ");
        console_puthex(working);
        console_puts("\n");
    }
    report("[check] map is reduced to its lowest bit . ", before);

    console_puts("\n[info] 75 maps checked, each through a UINT and a ULONG result.\n");

    if (failures == 0U)
    {
        console_puts("\nCLZ RESULT: ALL CHECKS PASSED\n");
    }
    else
    {
        console_puts("\nCLZ RESULT: FAILED\n");
    }

    console_exit(failures);
}


/**************************************************************************/
/*  tx_application_define                                                 */
/**************************************************************************/

void tx_application_define(void *first_unused_memory)
{
    (void) first_unused_memory;

    tx_thread_create(&check_thread, "clz check", thread_check_entry, 0UL,
                     check_stack, DEMO_STACK_SIZE,
                     1U, 1U, TX_NO_TIME_SLICE, TX_AUTO_START);
}


/**************************************************************************/
/*  bsp_main -- entered at EL1 from entry.S.  Does not return.            */
/**************************************************************************/

void bsp_main(void)
{
    tx_kernel_enter();

    /* Not reached.  */

    for (;;)
    {
        /* Nothing.  */
    }
}
