/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  DEMONSTRATION                                          RELEASE        */
/*                                                                        */
/*    demo_verify.h                                    Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Verification harness for the standard ThreadX demo, kept separate   */
/*    so demo_threadx.c stays byte-identical to the shipped sample apart  */
/*    from its header note and a single call to demo_verify_create().     */
/*                                                                        */
/**************************************************************************/

#ifndef DEMO_VERIFY_H
#define DEMO_VERIFY_H

/* Create the verification thread.  Called from tx_application_define.    */

void demo_verify_create(void);

#endif /* DEMO_VERIFY_H */
