/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    demo_nesting.c                                   Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frederic Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Nested IRQ handling: _tx_thread_irq_nesting_start and               */
/*    _tx_thread_irq_nesting_end.                                         */
/*                                                                        */
/*    Those two routines have shipped in this port since it was written    */
/*    and nothing had ever called them.  They were compiled into every     */
/*    build, never entered by any image, on the model or on silicon.       */
/*    This is the image that enters them.                                 */
/*                                                                        */
/*  HOW NESTING IS PROVOKED                                               */
/*                                                                        */
/*    Two interrupt sources are needed and one must outrank the other.     */
/*    The generic timer PPI is already there; the second is an SGI, which  */
/*    a core can raise on itself, given a numerically lower priority so    */
/*    the GIC lets it preempt.                                            */
/*                                                                        */
/*    Inside the timer handler, after nesting_start has left IRQ mode for  */
/*    System mode and re-enabled IRQ, board_irq_handler raises the SGI and */
/*    spins briefly.  The SGI outranks the timer, so it is delivered       */
/*    immediately and re-enters el1_irq_entry while the timer handler is    */
/*    still on the stack.  That is nesting, and the depth counter sees 2.  */
/*                                                                        */
/*    The spin is bounded.  Without TX_ENABLE_IRQ_NESTING the SGI can      */
/*    never arrive, and a test that hangs in that configuration would be   */
/*    worse than one that fails.                                          */
/*                                                                        */
/*  WHAT EACH CHECK IS FOR                                                */
/*                                                                        */
/*    N1  the SGI arrives at all.  This is separate on purpose: it tests   */
/*        the ICC_SGI1R encoding, which does not transcribe from the       */
/*        AArch64 alias, so if N1 fails the fault is in gicv3_send_sgi and */
/*        not in the nesting routines.                                    */
/*    N2  the SGI arrived while another handler was active, depth 2.       */
/*    N3  depth returned to zero, so the pairing unwound.                  */
/*    N4  the tick still advances afterwards, so nesting did not damage    */
/*        the timer path.                                                 */
/*    N5  threads still run and preempt, so the context save and restore   */
/*        survived being re-entered.                                      */
/*                                                                        */
/**************************************************************************/

#include "tx_api.h"
#include "board.h"
#include "console.h"
#include "gicv3.h"

#define DEMO_STACK_SIZE     2048

static TX_THREAD    thread_check;
static TX_THREAD    thread_spin;

static ULONG        thread_check_stack[DEMO_STACK_SIZE / sizeof(ULONG)];
static ULONG        thread_spin_stack[DEMO_STACK_SIZE / sizeof(ULONG)];

static volatile ULONG   spin_runs;


static UINT report(const char *label_ptr, UINT passed)
{
    console_puts(label_ptr);
    console_puts((passed != 0U) ? "PASS\n" : "FAIL\n");
    return (passed != 0U) ? 0U : 1U;
}


static void report_hex(const char *label_ptr, unsigned long value)
{
    console_puts(label_ptr);
    console_puthex(value);
    console_puts("\n");
}


/* Lowest priority, never blocks: gives the tick something to preempt and shows
   the scheduler is still alive after handlers have been nested.  */

static void thread_spin_entry(ULONG thread_input)
{
    (void) thread_input;

    for (;;)
    {
        spin_runs++;
    }
}


static void thread_check_entry(ULONG thread_input)
{
    UINT    failures = 0U;
    ULONG   sgi_before;
    ULONG   ticks_start;
    ULONG   ticks_end;
    ULONG   spin_before;

    (void) thread_input;

    /* N1 first, with provocation still off, so this measures only whether an
       SGI raised from thread context is delivered and dispatched.  */

    console_puts("[check] raising an SGI from thread context\n");

    sgi_before = board_sgi_count;
    gicv3_send_sgi(BOARD_NEST_SGI_INTID);
    tx_thread_sleep(2);

    failures += report("[check] N1 SGI delivered and dispatched            ",
                       (board_sgi_count > sgi_before) ? 1U : 0U);

    if (board_sgi_count == sgi_before)
    {
        /* Everything below depends on the SGI working, so say so rather than
           reporting four more failures that all have the same cause.  */

        console_puts("[check] SGI never arrived; the remaining checks would\n"
                     "        only restate that, so they are skipped.\n");
        console_puts("\nNESTING RESULT: FAILED\n");
        console_exit(1U);
    }

    /* Now let the timer handler provoke a nested SGI, and give it time for a
       good number of ticks.  */

    console_puts("[check] enabling nested provocation in the timer handler\n");

    board_nest_provoke = 1UL;
    ticks_start = tx_time_get();
    spin_before = spin_runs;
    tx_thread_sleep(50);
    ticks_end = tx_time_get();
    board_nest_provoke = 0UL;

    report_hex("[check] max nesting depth observed = ", board_nest_max);
    report_hex("[check] nested SGI count           = ", board_sgi_nested_count);
    report_hex("[check] nesting depth now          = ", board_nest_depth);

    failures += report("[check] N2 SGI nested inside another handler       ",
                       (board_sgi_nested_count > 0UL) &&
                       (board_nest_max >= 2UL) ? 1U : 0U);

    failures += report("[check] N3 nesting unwound to depth zero           ",
                       (board_nest_depth == 0UL) ? 1U : 0U);

    failures += report("[check] N4 tick still advancing after nesting      ",
                       ((ticks_end - ticks_start) >= 40UL) ? 1U : 0U);

    failures += report("[check] N5 lower-priority thread still scheduled   ",
                       (spin_runs > spin_before) ? 1U : 0U);

    report_hex("[check] spurious interrupts        = ", board_spurious_count);
    report_hex("[check] unexpected INTID           = ", board_unexpected_intid);

    failures += report("[check] no spurious or unexpected interrupts       ",
                       ((board_spurious_count == 0UL) &&
                        (board_unexpected_intid == 0UL)) ? 1U : 0U);

    if (failures == 0U)
    {
        console_puts("\nNESTING RESULT: ALL CHECKS PASSED\n");
    }
    else
    {
        console_puts("\nNESTING RESULT: FAILED\n");
    }

    console_exit(failures);
}


void tx_application_define(void *first_unused_memory)
{
    (void) first_unused_memory;

    (void) tx_thread_create(&thread_check, "nest check", thread_check_entry,
                            0UL, thread_check_stack, sizeof(thread_check_stack),
                            10U, 10U, TX_NO_TIME_SLICE, TX_AUTO_START);

    (void) tx_thread_create(&thread_spin, "spinner", thread_spin_entry,
                            0UL, thread_spin_stack, sizeof(thread_spin_stack),
                            20U, 20U, TX_NO_TIME_SLICE, TX_AUTO_START);
}


void bsp_main(void)
{
    console_puts("\n=== ThreadX nested IRQ handling "
                 "(Cortex-R52, Armv8-R AArch32, Armv8-R AEM FVP) ===\n");

    tx_kernel_enter();
}
