/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  DEMONSTRATION                                          RELEASE        */
/*                                                                        */
/*    demo_mpu.c                                       Cortex-R52/GNU     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    AR1 milestone M5: PMSAv8-R protection and caches.                    */
/*                                                                        */
/*    The important check here is enforcement, not configuration.  Reading */
/*    SCTLR back only proves a bit was set; it says nothing about whether  */
/*    the region table actually describes memory correctly.  So the test    */
/*    provokes a real permission fault by writing to the read-only code     */
/*    region and requires the abort to arrive, then confirms a legal write  */
/*    to the data region still succeeds.  A region set that permitted       */
/*    everything would pass the first kind of check and fail this one.      */
/*                                                                        */
/**************************************************************************/

#include "tx_api.h"
#include "board.h"
#include "console.h"
#include "mpu.h"

#define DEMO_STACK_SIZE     2048

static TX_THREAD    thread_check;
static ULONG        thread_check_stack[DEMO_STACK_SIZE / sizeof(ULONG)];

/* Provided by entry.S and manipulated by its data-abort handler.  */


/* A known-writable location, used to show legal access still works.  */

static volatile unsigned long   writable_probe;


/**************************************************************************/
/*  report                                                                */
/**************************************************************************/

static UINT report(const char *label_ptr, UINT passed)
{
    console_puts(label_ptr);
    console_puts((passed != 0U) ? "PASS\n" : "FAIL\n");

    return (passed != 0U) ? 0U : 1U;
}


/**************************************************************************/
/*  thread_check_entry                                                    */
/**************************************************************************/

static void thread_check_entry(ULONG thread_input)
{
    UINT                failures = 0U;
    unsigned int        available;
    unsigned int        used;
    unsigned int        index;
    const MPU_REGION   *table;
    unsigned long       aborts_before;

    (void) thread_input;

    /* What the implementation provides.  */

    available = mpu_region_count();
    console_puts("[check] MPUIR regions available = ");
    console_puthex(available);
    console_puts("\n");
    failures += report("[check] implementation reports MPU regions         ",
                       (available > 0U) ? 1U : 0U);

    /* What this image programmed.  */

    table = mpu_region_table(&used);
    console_puts("[check] regions programmed = ");
    console_puthex(used);
    console_puts("\n");

    for (index = 0U; index < used; index++)
    {
        console_puts("          ");
        console_puts(table[index].mpu_region_name);
        console_puts("  base ");
        console_puthex(table[index].mpu_region_base);
        console_puts(" limit ");
        console_puthex(table[index].mpu_region_limit);
        console_puts("\n");
    }

    failures += report("[check] region table programmed                    ",
                       (used > 0U) ? 1U : 0U);

    /* Read the hardware back: if the register encodings were wrong the
       writes would be silently discarded and a permissive background map
       would make everything appear to work.  */

    for (index = 0U; index < used; index++)
    {
        unsigned long prbar = 0UL;
        unsigned long prlar = 0UL;

        mpu_read_region(index, &prbar, &prlar);
        console_puts("          region ");
        console_puthex(index);
        console_puts(" PRBAR=");
        console_puthex(prbar);
        console_puts(" PRLAR=");
        console_puthex(prlar);
        console_puts("\n");
        if ((prbar == 0UL) && (prlar == 0UL))
        {
            failures++;
        }
    }
    failures += report("[check] hardware holds the programmed regions      ",
                       (failures == 0U) ? 1U : 0U);

    failures += report("[check] MPU enabled (SCTLR.M)                      ",
                       mpu_is_enabled());
    failures += report("[check] caches enabled (SCTLR.C and SCTLR.I)       ",
                       mpu_caches_enabled());

    /* Enforcement, part 1: a legal write to the data region must work.  */

    writable_probe = 0xA5A5A5A5UL;
    failures += report("[check] legal write to data region succeeds        ",
                       (writable_probe == 0xA5A5A5A5UL) ? 1U : 0U);

    /* Enforcement, part 1b: an address covered by NO region must fault.
       This distinguishes "the MPU is not enforcing at all" from "the MPU
       enforces coverage but not the access permission".  0x40000000 lies
       between the end of the data region and the peripheral region.  */

    /* Enforcement, part 2: an address covered by no region must fault.  This
       distinguishes "not enforcing at all" from "enforcing coverage only".  */

    aborts_before = mpu_abort_count;
    mpu_expect_abort = 1UL;
    {
        volatile unsigned long *gap_ptr = (volatile unsigned long *) 0x40000000UL;

        *gap_ptr = 0x11223344UL;
    }
    failures += report("[check] write to unmapped address faulted          ",
                       (mpu_abort_count == (aborts_before + 1UL)) ? 1U : 0U);
    mpu_expect_abort = 0UL;

    /* Enforcement, part 3: the read-only code region must reject a write.
       This is the check that matters: region coverage is enforced even with a
       wrong access-permission encoding, so only a write-permission test can
       show that the permissions themselves are right.  */

    aborts_before = mpu_abort_count;
    mpu_expect_abort = 1UL;
    {
        volatile unsigned long *code_ptr =
            (volatile unsigned long *) table[0].mpu_region_base;

        *code_ptr = 0xDEADBEEFUL;
    }
    mpu_expect_abort = 0UL;

    console_puts("[check] aborts before/after write to code = ");
    console_puthex(aborts_before);
    console_puts(" / ");
    console_puthex(mpu_abort_count);
    console_puts("\n");

    failures += report("[check] write to read-only code region faulted     ",
                       (mpu_abort_count == (aborts_before + 1UL)) ? 1U : 0U);

    {
        volatile unsigned long *code_ptr =
            (volatile unsigned long *) table[0].mpu_region_base;

        failures += report("[check] code region contents unmodified            ",
                           (*code_ptr != 0xDEADBEEFUL) ? 1U : 0U);
    }

    /* And the kernel is still healthy afterwards.  */

    failures += report("[check] kernel still running after the fault       ",
                       (tx_thread_identify() == &thread_check) ? 1U : 0U);

    if (failures == 0U)
    {
        console_puts("\nMPU RESULT: ALL CHECKS PASSED\n");
    }
    else
    {
        console_puts("\nMPU RESULT: FAILED\n");
    }

    console_exit(failures);
}


/**************************************************************************/
/*  tx_application_define                                                 */
/**************************************************************************/

void tx_application_define(void *first_unused_memory)
{
    (void) first_unused_memory;

    (void) tx_thread_create(&thread_check, "mpu check", thread_check_entry,
                            0UL, thread_check_stack, sizeof(thread_check_stack),
                            10U, 10U, TX_NO_TIME_SLICE, TX_AUTO_START);
}


/**************************************************************************/
/*  bsp_main -- entered at EL1 from entry.S.  Does not return.            */
/**************************************************************************/

void bsp_main(void)
{
    console_puts("\n=== ThreadX AR1/M5 PMSAv8-R protection and caches "
                 "(Cortex-R52, Armv8-R AEM FVP) ===\n");

    tx_kernel_enter();
}
