/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    gicv3.h                                          Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    GICv3 interrupt controller for Cortex-R52.  The CPU interface is    */
/*    reached through AArch32 ICC_* system registers; the Distributor and */
/*    Redistributor are memory mapped.                                    */
/*                                                                        */
/**************************************************************************/

#ifndef GICV3_H
#define GICV3_H

/* Spurious interrupt ID returned by the CPU interface when no interrupt is
   pending.  It must be neither dispatched nor acknowledged with EOI.  */

#define GICV3_SPURIOUS_INTID    1023UL

/* Bring up the Distributor, this core's Redistributor and the CPU
   interface.  Interrupts remain masked at the PSTATE level.  */

void gicv3_init(void);

/* Enable one private peripheral interrupt (PPI, INTID 16-31) as a
   level-sensitive Group 1 interrupt at the given priority.  */

void gicv3_enable_ppi(unsigned int intid, unsigned int priority);

/* Enable a software-generated interrupt, INTID 0-15.  Same registers as a PPI:
   the redistributor's SGI/PPI frame covers INTIDs 0-31.  */

void gicv3_enable_sgi(unsigned int intid, unsigned int priority);

/* Raise an SGI on this core.  */

void gicv3_send_sgi(unsigned int intid);

/* Group 0 support, which is what produces FIQ rather than IRQ.  With a single
   security state the GIC routes Group 0 to FIQ and Group 1 to IRQ, so an
   interrupt has to be moved into Group 0 to arrive as an FIQ at all.  Group 0
   has its own acknowledge and end-of-interrupt registers; using the Group 1 ones
   on a Group 0 interrupt does not work.  */

void gicv3_enable_sgi_group0(unsigned int intid, unsigned int priority);
void gicv3_send_sgi_group0(unsigned int intid);
unsigned long gicv3_acknowledge_group0(void);
void gicv3_end_of_interrupt_group0(unsigned long intid);

/* Acknowledge the highest-priority pending Group 1 interrupt, returning its
   INTID (possibly GICV3_SPURIOUS_INTID).  */

unsigned long gicv3_acknowledge(void);

/* Signal completion of the interrupt previously acknowledged.            */

void gicv3_end_of_interrupt(unsigned long intid);

#endif /* GICV3_H */
