/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    mpu.h                                            Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    PMSAv8-R memory protection and cache enable for Cortex-R52.         */
/*                                                                        */
/*    The region set is described by a table rather than a sequence of    */
/*    register writes.  That is deliberate and is a roadmap decision, not */
/*    a style preference: AR2 programs a Stage-1 region set per ThreadX   */
/*    module and AR3 programs Stage-2 regions per ZoneX partition, and    */
/*    both reuse this shape.  A table can be swapped at a partition       */
/*    switch; open-coded register writes cannot.                          */
/*                                                                        */
/**************************************************************************/

#ifndef MPU_H
#define MPU_H

/* Access permissions, PRBAR.AP (bits [3:2]).
 *
 * These values were CALIBRATED AGAINST THE HARDWARE, not copied from a
 * reference, because the widely-published Armv8-R AArch64 macro set has the
 * two bits the other way round (its "read-only, no EL0 access" is 0x2).
 * Programming four disjoint regions, one per encoding, and attempting a
 * privileged write to each gave:
 *
 *     AP=0b00  write allowed        AP=0b01  write faulted
 *     AP=0b10  write allowed        AP=0b11  write faulted
 *
 * so the low bit is read-only and the high bit grants EL0 access.  Using the
 * AArch64 ordering here silently produces writable "read-only" regions: the
 * MPU still enforces region coverage, so everything appears to work and only
 * an explicit write-permission test exposes it.  Re-calibrate on S32Z280
 * silicon before trusting these values there.
 */

#define MPU_AP_RW_EL1       0U      /* EL1 read/write, EL0 no access       */
#define MPU_AP_RO_EL1       1U      /* EL1 read-only,  EL0 no access       */
#define MPU_AP_RW_EL1_EL0   2U      /* EL1 read/write, EL0 read/write      */
#define MPU_AP_RO_EL1_EL0   3U      /* EL1 read-only,  EL0 read-only       */

/* Shareability, PRBAR.SH.                                                */

#define MPU_SH_NON          0U
#define MPU_SH_OUTER        2U
#define MPU_SH_INNER        3U

/* Attribute indices into MAIR, PRLAR.AttrIndx.                           */

#define MPU_ATTR_NORMAL_WB  0U      /* Normal, inner/outer write-back      */
#define MPU_ATTR_DEVICE     1U      /* Device-nGnRnE                       */

/* One protection region.  The limit is inclusive, matching the hardware. */

typedef struct MPU_REGION_STRUCT
{
    unsigned long   mpu_region_base;
    unsigned long   mpu_region_limit;
    unsigned char   mpu_region_ap;
    unsigned char   mpu_region_execute_never;
    unsigned char   mpu_region_shareability;
    unsigned char   mpu_region_attr_index;
    const char     *mpu_region_name;
} MPU_REGION;

/* Number of regions this implementation provides, from MPUIR.            */

unsigned int mpu_region_count(void);

/* Program the region table, then enable the MPU and the caches.  Returns
   the number of regions programmed, or 0 if the table does not fit.  */

unsigned int mpu_init(void);

/* True once SCTLR reports the MPU and both caches enabled.               */

unsigned int mpu_is_enabled(void);
unsigned int mpu_caches_enabled(void);

/* The active table, for reporting.                                       */

const MPU_REGION *mpu_region_table(unsigned int *count_ptr);

/* Read back what the hardware holds for one region, so that programming can
   be verified rather than assumed.  */

void mpu_read_region(unsigned int index, unsigned long *prbar_ptr,
                     unsigned long *prlar_ptr);

#endif /* MPU_H */
