/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    mpu.h                                            Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    PMSAv8-R memory protection and cache enable for Cortex-R52.         */
/*                                                                        */
/*    The region set is described by a table rather than a sequence of    */
/*    register writes.  That is deliberate and is a roadmap decision, not */
/*    a style preference: AR2 programs a Stage-1 region set per ThreadX   */
/*    module and AR3 programs Stage-2 regions per ZoneX partition, and    */
/*    both reuse this shape.  A table can be swapped at a partition       */
/*    switch; open-coded register writes cannot.                          */
/*                                                                        */
/**************************************************************************/

#ifndef MPU_H
#define MPU_H

/* Access permissions, PRBAR.AP (bits [2:1]).
 *
 * AP[2] selects read-only, AP[1] grants EL0 access -- the standard Armv8-R
 * encoding, as published.  An earlier version of this file claimed the two
 * bits were reversed, on the strength of a calibration that programmed four
 * regions and attempted a privileged write to each:
 *
 *     AP=0b00  write allowed        AP=0b01  write faulted
 *     AP=0b10  write allowed        AP=0b11  write faulted
 *
 * That table is real, but the cause was not the AP ordering.  program_region()
 * shifted every PRBAR field one bit too far left, so the AP value's low bit
 * landed in the real AP[2] -- the read-only bit -- making writes fault exactly
 * when that bit was set.  The "high bit grants EL0 access" half was never
 * tested; under the old shift that bit landed in SH[0], programming a
 * shareability the TRM defines as UNPREDICTABLE.
 *
 * The shift is fixed in program_region().  These values are now the
 * architectural ones and need no calibration.  Verified on S32Z280 silicon:
 * a write to an RO region faults, and execution from an XN region takes a
 * prefetch abort -- the latter never worked under the old shift, because the
 * intended XN bit landed in AP[1] instead.
 */

#define MPU_AP_RW_EL1       0U      /* 0b00 EL1 read/write, no EL0         */
#define MPU_AP_RW_EL1_EL0   1U      /* 0b01 EL1 read/write, EL0 read/write */
#define MPU_AP_RO_EL1       2U      /* 0b10 EL1 read-only,  no EL0         */
#define MPU_AP_RO_EL1_EL0   3U      /* 0b11 EL1 read-only,  EL0 read-only  */

/* Shareability, PRBAR.SH.                                                */

#define MPU_SH_NON          0U
#define MPU_SH_OUTER        2U
#define MPU_SH_INNER        3U

/* Attribute indices into MAIR, PRLAR.AttrIndx.                           */

#define MPU_ATTR_NORMAL_WB  0U      /* Normal, inner/outer write-back      */
#define MPU_ATTR_DEVICE     1U      /* Device-nGnRnE                       */

/* One protection region.  The limit is inclusive, matching the hardware. */

typedef struct MPU_REGION_STRUCT
{
    unsigned long   mpu_region_base;
    unsigned long   mpu_region_limit;
    unsigned char   mpu_region_ap;
    unsigned char   mpu_region_execute_never;
    unsigned char   mpu_region_shareability;
    unsigned char   mpu_region_attr_index;
    const char     *mpu_region_name;
} MPU_REGION;

/* Number of regions this implementation provides, from MPUIR.            */

unsigned int mpu_region_count(void);

/* Program the region table, then enable the MPU and the caches.  Returns
   the number of regions programmed, or 0 if the table does not fit.  */

unsigned int mpu_init(void);

/* True once SCTLR reports the MPU and both caches enabled.               */

unsigned int mpu_is_enabled(void);
unsigned int mpu_caches_enabled(void);

/* The active table, for reporting.                                       */

const MPU_REGION *mpu_region_table(unsigned int *count_ptr);

/* Read back what the hardware holds for one region, so that programming can
   be verified rather than assumed.  */

void mpu_read_region(unsigned int index, unsigned long *prbar_ptr,
                     unsigned long *prlar_ptr);

#endif /* MPU_H */
