/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    platform.h                                       Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Memory map for the Armv8-R AEM FVP (BaseR platform).                */
/*                                                                        */
/*    Every address here was VERIFIED IN-MODEL, not taken from            */
/*    documentation or recollection.  The BaseR map is the Base platform  */
/*    map with its two 2 GB halves swapped (so a Base peripheral at X     */
/*    below 0x80000000 appears at X + 0x80000000), and each base was then */
/*    confirmed by reading its identification register:                   */
/*                                                                        */
/*      PL011 UART0   peripheral ID  0x11,0x10,0x24,0x00, and a marker    */
/*                    written to it appeared on the host console          */
/*      GIC           GICD_PIDR2 = 0x3B and GICR_PIDR2 = 0x3B, i.e.       */
/*                    architecture revision 3 = GICv3                     */
/*      Counter       CNTFID0 = 0x05F5E100 = 100 MHz, matching the        */
/*                    model's bp.refcounter.base_frequency parameter      */
/*                                                                        */
/*    Values are written without integer suffixes so that this header can */
/*    also be included from preprocessed assembly.                        */
/*                                                                        */
/**************************************************************************/

#ifndef PLATFORM_H
#define PLATFORM_H

/* PL011 UART0.                                                           */

#define PL011_UART0_BASE        0x9C090000

/* GICv3.  A redistributor is two consecutive 64 KB frames per core: the RD
   frame carries the identification and wake-up registers, the SGI frame the
   per-interrupt enable, priority and configuration registers for SGIs/PPIs. */

#define GICD_BASE               0xAF000000
#define GICR_RD_BASE            0xAF100000
#define GICR_SGI_BASE           0xAF110000

/* System counter control frame (CNTControlBase).                         */

#define CNT_CONTROL_BASE        0xAA430000

/* The model resets CNTFRQ to zero and leaves the system counter stopped --
   bp.refcounter.non_arch_start_at_default=0, documented as "firmware is
   expected to enable the timer at boot time".  This BSP therefore programs
   both.  The value is CNTFID0 read back from the counter control frame. */

#define SYSTEM_COUNTER_HZ       100000000

/* ---------------------------------------------------------------------------
   Memory for ThreadX modules.

   Only the module manager build uses this, but the addresses are stated here
   rather than in the module example because they are a property of the board's
   memory map: a module's code and data are handed to it as MPU regions, and
   PMSAv8-R will not allow those to overlap a kernel region.  So module memory
   has to be memory NO kernel region covers, and deciding that is the memory
   map's job.

   link_module.lds ends the kernel's DRAM region at this base and gives the
   64 KB above it to the module area; mpu.c covers exactly the same range with
   the manager's load window (region 16), which is the only mapping privileged
   code has over it.  The three have to agree, so all three read these two
   values.

   Chosen at 0x003F0000 -- just under 4 MB -- because the manager image with its
   stacks and its 1 MB of heap is far smaller than that, and the link script
   asserts the two do not meet rather than trusting the margin.  */

#define FVP_MODULE_AREA_BASE            0x003F0000
#define FVP_MODULE_AREA_SIZE            0x00010000      /* 64 KB             */

/* The shared granules the sample module reports its progress through, at the
   base of the module area.

   The first of them exists because the FVP has no debugger seam: on silicon a
   GDB harness reads the module's own progress variable out of its data area,
   and here nothing outside the image can read anything.  So the manager grants
   the module a shared region over this word and reads it back afterwards, which
   is what lets the FVP test judge what the module actually managed to do rather
   than only that it faulted.

   The rest exist to exercise the shared-region machinery itself.  A module may
   be granted TXM_MODULE_MPU_SHARED_ENTRIES regions, and one grant proves only
   that the first entry works, so the area holds one granule per entry -- plus
   one more that the manager NEVER grants, sandwiched between two that it does.
   A limit register masked the wrong way, or a base off by a granule, leaks into
   that gap from one side or the other, and a module that can write it is a
   module whose grant covered more than was asked for.

   FVP_MODULE_STATUS_SIZE is the size of ONE granule, which is the length of
   each individual grant; the area is FVP_MODULE_STATUS_GRANULES of them.

   Fixed addresses on both sides, and checked at run time rather than trusted:
   the manager grants the regions from the linker's symbol and refuses to
   continue if that symbol is not this address.  */

#define FVP_MODULE_STATUS_BASE          0x003F0000
#define FVP_MODULE_STATUS_SIZE          0x40            /* one MPU granule   */
#define FVP_MODULE_STATUS_GRANULES      6               /* five granted, one not */
#define FVP_MODULE_STATUS_UNGRANTED     2               /* the one never granted */

#ifndef __ASSEMBLER__

/* 32-bit device register access.                                         */

#define REG32(address)  (*(volatile unsigned long *)(unsigned long)(address))

#endif /* __ASSEMBLER__ */

#endif /* PLATFORM_H */
