/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    timer.h                                          Cortex-R52/GNU     */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Arm generic timer tick for Cortex-R52.                              */
/*                                                                        */
/**************************************************************************/

#ifndef TIMER_H
#define TIMER_H

/* PPI driven by the EL1 physical timer.
 *
 * This was not assumed.  Bring-up enabled the entire PPI range 25-31 and
 * recorded whichever INTID came back from ICC_IAR1; the model drove 30, which
 * matches the architectural assignment for the EL1 physical timer.  Only that
 * line is enabled now, and irq_dispatch.c still records any other INTID so a
 * different platform assignment would be reported rather than silently
 * mishandled.  Re-verify when moving to S32Z2 silicon.  */

#define TIMER_PPI_INTID     30U

/* Enable the system counter, then start the periodic tick at
   TX_TIMER_TICKS_PER_SECOND.  gicv3_init() must have run first.  */

void timer_init(void);

/* Re-arm the timer for the next tick.  Called from the interrupt path.  */

void timer_reload(void);

/* CNTFRQ as programmed by entry.S at EL2.  */

unsigned long timer_frequency(void);

/* Current 64-bit physical counter value, for verifying the counter runs.  */

unsigned long long timer_counter(void);

/* True once the counter control frame reports the counter enabled.  */

unsigned int timer_counter_enabled(void);

#endif /* TIMER_H */
