/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    uart_pl011.h                                     Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    PL011 UART console backend for the Armv8-R AEM FVP.                 */
/*                                                                        */
/**************************************************************************/

#ifndef UART_PL011_H
#define UART_PL011_H

/* Configure and enable UART0.  The model leaves it disabled at reset.    */

void pl011_init(void);

/* Send one character, expanding a newline into CR LF.                    */

void pl011_putc(char character);

/* Send a NUL-terminated string.                                          */

void pl011_puts(const char *string_ptr);

#endif /* UART_PL011_H */
