/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 * 
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 * 
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 * 
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/


/**************************************************************************/
/**************************************************************************/
/**                                                                       */
/** ThreadX Test                                                          */
/**                                                                       */
/**   Module Manager Cortex-A7 data range validation                      */
/**                                                                       */
/**************************************************************************/
/**************************************************************************/

/* This test exercises the Cortex-A7 module data range check through the same
   macros the module dispatchers use. The check normally asks the MMU about one
   page at a time, so the test stands a simulated page map behind that one
   architecture primitive and drives every outcome from the host build.

   No address in this test is dereferenced and none of them name a real target.
   They are labels in a table that the stubbed primitive answers questions about,
   which is what lets the test describe a range that leaves a module's mapping
   without ever building something that could read past one.  */

#include <stdio.h>

#define TX_SOURCE_CODE

#include "tx_api.h"
#include "txm_module.h"
#include "txm_module_manager_util.h"


/* Define the simulated address space.

   The module's recorded data region deliberately ends partway through its last
   page, because that is what the module manager's page-granular mapping does in
   practice: the mapping reaches to the end of the page while the recorded region
   does not. The bytes in between are the rounding slack, and the check must not
   hand them out.  */

#define TEST_PAGE_SIZE              4096

#define TEST_DATA_START             0x20001000UL
#define TEST_DATA_END               0x200027FFUL    /* Ends mid-page: slack follows. */
#define TEST_DATA_WINDOW_END        0x20002FFFUL    /* Last byte the MMU maps for it. */

#define TEST_CODE_START             0x10001000UL
#define TEST_CODE_END               0x10001FFFUL

#define TEST_SHARED_RW_START        0x20010000UL    /* Two contiguous read/write pages. */
#define TEST_SHARED_RW_END          0x20011FFFUL
#define TEST_GUARD_PAGE             0x20012000UL    /* Unmapped, directly after them.   */

#define TEST_SPLIT_FIRST_PAGE       0x20030000UL    /* Mapped.   */
#define TEST_SPLIT_MIDDLE_PAGE      0x20031000UL    /* Unmapped. */
#define TEST_SPLIT_LAST_PAGE        0x20032000UL    /* Mapped.   */

#define TEST_SHARED_RO_START        0x20020000UL    /* Readable, not writable. */
#define TEST_SHARED_RO_END          0x20020FFFUL

#define TEST_KERNEL_OBJECT          0x30000000UL    /* Unmapped for the module. */

#define TEST_MODULE_ASID            5UL
#define TEST_OTHER_MODULE_ASID      6UL


/* Define one entry of the simulated page map.  */

typedef struct TEST_PAGE_STRUCT
{
    ULONG   test_page_base;
    UINT    test_page_readable;
    UINT    test_page_writable;
} TEST_PAGE;


static TEST_PAGE    test_page_map[] =
{
    /* The module's own data pages, mapped read/write to the end of the page.  */
    {TEST_DATA_START,                       TX_TRUE,    TX_TRUE},
    {TEST_DATA_START + TEST_PAGE_SIZE,      TX_TRUE,    TX_TRUE},

    /* The module's code, readable but never writable from unprivileged mode.  */
    {TEST_CODE_START,                       TX_TRUE,    TX_FALSE},

    /* Read/write shared memory, followed by an unmapped guard page.  */
    {TEST_SHARED_RW_START,                  TX_TRUE,    TX_TRUE},
    {TEST_SHARED_RW_START + TEST_PAGE_SIZE, TX_TRUE,    TX_TRUE},

    /* Read-only shared memory.  */
    {TEST_SHARED_RO_START,                  TX_TRUE,    TX_FALSE},

    /* Two mapped pages with an unmapped page between them.  */
    {TEST_SPLIT_FIRST_PAGE,                 TX_TRUE,    TX_TRUE},
    {TEST_SPLIT_LAST_PAGE,                  TX_TRUE,    TX_TRUE}
};

#define TEST_PAGE_MAP_ENTRIES   (sizeof(test_page_map) / sizeof(test_page_map[0]))


/* Define the state the stubbed architecture primitives answer from.  */

static ULONG    test_current_asid = TEST_MODULE_ASID;
static ULONG    test_probe_count = 0UL;
static UINT     test_failures = 0U;


/* Stand in for the CP15 address translation the real port performs.  */
UINT  _txm_module_manager_address_probe(ULONG address, UINT write_request)
{

ULONG   page_base;
ULONG   index;
UINT    granted;


    test_probe_count++;

    page_base =  address & (~((ULONG) (TEST_PAGE_SIZE - 1)));
    granted =    TX_FALSE;

    for (index = 0UL; index < (ULONG) TEST_PAGE_MAP_ENTRIES; index++)
    {
        if (test_page_map[index].test_page_base == page_base)
        {
            if (write_request == TXM_MODULE_MANAGER_ACCESS_WRITE)
            {
                granted =  test_page_map[index].test_page_writable;
            }
            else
            {
                granted =  test_page_map[index].test_page_readable;
            }
        }
    }

    return(granted);
}


/* Stand in for the CONTEXTIDR read the real port performs.  */
ULONG  _txm_module_manager_current_asid_get(VOID)
{
    return(test_current_asid);
}


/* Model the implementation this test guards against. It translated the first
   address of the range and nothing else, and it only ever asked about reading.
   Keeping it here lets each boundary case show both answers side by side.  */
static UINT  test_first_address_only_check(ALIGN_TYPE obj_ptr)
{
    return(_txm_module_manager_address_probe((ULONG) obj_ptr, TXM_MODULE_MANAGER_ACCESS_READ));
}


/* Record the outcome of one expectation.  */
static VOID  test_expect(const char *description, UINT actual, UINT expected)
{
    if (actual != expected)
    {
        printf("FAIL: %s (expected %u, got %u)\n", description, expected, actual);
        test_failures++;
    }
}


/* Build a module instance describing the simulated module.  */
static VOID  test_module_build(TXM_MODULE_INSTANCE *module_instance)
{
    module_instance -> txm_module_instance_id =         TXM_MODULE_ID;
    module_instance -> txm_module_instance_data_start = (VOID *) TEST_DATA_START;
    module_instance -> txm_module_instance_data_end =   (VOID *) TEST_DATA_END;
    module_instance -> txm_module_instance_code_start = (VOID *) TEST_CODE_START;
    module_instance -> txm_module_instance_code_end =   (VOID *) TEST_CODE_END;
    module_instance -> txm_module_instance_asid =       TEST_MODULE_ASID;
}


int  main(void)
{

TXM_MODULE_INSTANCE     module;
TXM_MODULE_INSTANCE    *module_instance;
ALIGN_TYPE              address;
ULONG                   probes_before;
ULONG                   huge_size;


    printf("Cortex-A7 module data range validation test............................ ");

    module_instance =  &module;
    test_module_build(module_instance);

    /**********************************************************************/
    /* Normal valid behaviour.                                            */
    /**********************************************************************/

    test_expect("one byte inside module data is writable",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) TEST_DATA_START, 1UL), TX_TRUE);

    test_expect("one word inside module data is writable",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) TEST_DATA_START, (ULONG) sizeof(ULONG)), TX_TRUE);

    test_expect("one word inside module data is readable",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_READ(module_instance, (ALIGN_TYPE) TEST_DATA_START, (ULONG) sizeof(ULONG)), TX_TRUE);

    test_expect("a range spanning both module data pages is writable",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) TEST_DATA_START, 0x1800UL), TX_TRUE);

    /* The module's own data is answered from the manager's records, so it costs
       no translations at all. This is what keeps the common case deterministic.  */
    probes_before =  test_probe_count;
    (VOID) TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) TEST_DATA_START, 0x1800UL);
    test_expect("module data is answered without translating",
                (UINT) (test_probe_count == probes_before), TX_TRUE);

    /**********************************************************************/
    /* Null and invalid parameters.                                       */
    /**********************************************************************/

    /* A null buffer is how the dispatchers say "not supplied", and the macros
       accept it. Only the range check below it must reject a null module.  */
    test_expect("a null buffer pointer is accepted by the buffer macros",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) 0, (ULONG) sizeof(ULONG)), TX_TRUE);

    test_expect("a null module instance is rejected",
                _txm_module_manager_inside_data_check(TX_NULL, (ALIGN_TYPE) TEST_DATA_START, (ULONG) sizeof(ULONG), TXM_MODULE_MANAGER_ACCESS_WRITE), TX_FALSE);

    test_expect("a null module instance is not outside anything either",
                _txm_module_manager_outside_data_check(TX_NULL, (ALIGN_TYPE) TEST_KERNEL_OBJECT, (ULONG) sizeof(ULONG)), TX_FALSE);

    /* A module torn down to an empty data region owns nothing, and the address
       range must then be settled by the MMU rather than by stale records.  */
    module.txm_module_instance_data_start =  (VOID *) TEST_DATA_END;
    module.txm_module_instance_data_end =    (VOID *) TEST_DATA_START;
    test_expect("an inverted data region grants nothing from records",
                _txm_module_manager_inside_data_check(module_instance, (ALIGN_TYPE) TEST_KERNEL_OBJECT, (ULONG) sizeof(ULONG), TXM_MODULE_MANAGER_ACCESS_WRITE), TX_FALSE);
    test_module_build(module_instance);

    /**********************************************************************/
    /* Exact boundaries, and the one byte past each of them.              */
    /**********************************************************************/

    test_expect("a range starting exactly at data start is accepted",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) TEST_DATA_START, 4UL), TX_TRUE);

    test_expect("a range starting one byte before data start is rejected",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) (TEST_DATA_START - 1UL), 4UL), TX_FALSE);

    test_expect("a range ending exactly at data end is accepted",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) (TEST_DATA_END - 3UL), 4UL), TX_TRUE);

    test_expect("the last byte of data on its own is accepted",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) TEST_DATA_END, 1UL), TX_TRUE);

    /* One byte further is the rounding slack: mapped, but not the module's.  */
    address =  (ALIGN_TYPE) (TEST_DATA_END - 3UL);
    test_expect("a range ending one byte past data end is rejected",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, address, 5UL), TX_FALSE);
    test_expect("...and the first-address-only check would have accepted it",
                test_first_address_only_check(address), TX_TRUE);

    test_expect("the one-past-the-end byte is rejected on its own",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) (TEST_DATA_END + 1UL), 1UL), TX_FALSE);

    test_expect("the whole rounding slack is rejected",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) (TEST_DATA_END + 1UL), (ULONG) (TEST_DATA_WINDOW_END - TEST_DATA_END)), TX_FALSE);

    /* A word that straddles the recorded end crosses it by one word.  */
    address =  (ALIGN_TYPE) (TEST_DATA_END - 1UL);
    test_expect("a word straddling data end is rejected",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, address, (ULONG) sizeof(ULONG)), TX_FALSE);
    test_expect("...and the first-address-only check would have accepted it",
                test_first_address_only_check(address), TX_TRUE);

    /**********************************************************************/
    /* Integer overflow and underflow.                                    */
    /**********************************************************************/

    test_expect("a zero-length range is rejected",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) TEST_DATA_START, 0UL), TX_FALSE);

    /* A range whose end wraps must be refused before anything is computed from
       the wrapped address.  */
    probes_before =  test_probe_count;
    test_expect("a range whose end wraps past the top of memory is rejected",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) TEST_DATA_START, 0xFFFFFFFFUL), TX_FALSE);
    test_expect("...without translating the wrapped address",
                (UINT) (test_probe_count == probes_before), TX_TRUE);

    test_expect("a range starting at the very top of memory with size two is rejected",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) 0xFFFFFFFFUL, 2UL), TX_FALSE);

    test_expect("a one-byte range at the very top of memory does not wrap, and is simply unmapped",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) 0xFFFFFFFFUL, 1UL), TX_FALSE);

    test_expect("a zero-length range is not outside the module either",
                _txm_module_manager_outside_data_check(module_instance, (ALIGN_TYPE) TEST_KERNEL_OBJECT, 0UL), TX_FALSE);

    /**********************************************************************/
    /* Shared memory, guard pages, and holes.                             */
    /**********************************************************************/

    test_expect("a range inside read/write shared memory is writable",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) TEST_SHARED_RW_START, (ULONG) sizeof(ULONG)), TX_TRUE);

    test_expect("a range spanning two shared pages is writable",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) TEST_SHARED_RW_START, 0x1800UL), TX_TRUE);

    test_expect("a range ending exactly at the end of shared memory is accepted",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) (TEST_SHARED_RW_END - 3UL), 4UL), TX_TRUE);

    /* One byte more crosses into the guard page.  */
    address =  (ALIGN_TYPE) (TEST_SHARED_RW_END - 3UL);
    test_expect("a range crossing one byte into the guard page is rejected",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, address, 5UL), TX_FALSE);
    test_expect("...and the first-address-only check would have accepted it",
                test_first_address_only_check(address), TX_TRUE);

    test_expect("a three-page range with an unmapped middle page is rejected",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) TEST_SPLIT_FIRST_PAGE, (ULONG) ((TEST_SPLIT_LAST_PAGE + 4UL) - TEST_SPLIT_FIRST_PAGE)), TX_FALSE);

    test_expect("the first page of that range on its own is still accepted",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) TEST_SPLIT_FIRST_PAGE, 4UL), TX_TRUE);

    /**********************************************************************/
    /* Read intent versus write intent.                                   */
    /**********************************************************************/

    test_expect("read-only shared memory can be read from",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_READ(module_instance, (ALIGN_TYPE) TEST_SHARED_RO_START, (ULONG) sizeof(ULONG)), TX_TRUE);

    test_expect("read-only shared memory cannot be written to",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) TEST_SHARED_RO_START, (ULONG) sizeof(ULONG)), TX_FALSE);

    test_expect("a read-only shared range crossing its own end is rejected for reading too",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_READ(module_instance, (ALIGN_TYPE) (TEST_SHARED_RO_END - 3UL), 5UL), TX_FALSE);

    test_expect("module code can be read from",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_READ(module_instance, (ALIGN_TYPE) TEST_CODE_START, (ULONG) sizeof(ULONG)), TX_TRUE);

    test_expect("module code cannot be used as a kernel write destination",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) TEST_CODE_START, (ULONG) sizeof(ULONG)), TX_FALSE);

    test_expect("a string may be dereferenced out of module code",
                TXM_MODULE_MANAGER_PARAM_CHECK_DEREFERENCE_STRING(module_instance, (ALIGN_TYPE) TEST_CODE_START), TX_TRUE);

    test_expect("a range running off the end of module code is rejected",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_READ(module_instance, (ALIGN_TYPE) (TEST_CODE_END - 3UL), 5UL), TX_FALSE);

    /**********************************************************************/
    /* The outside direction.                                             */
    /**********************************************************************/

    test_expect("a kernel object clear of the module is outside it",
                TXM_MODULE_MANAGER_ENSURE_OUTSIDE_MODULE(module_instance, (ALIGN_TYPE) TEST_KERNEL_OBJECT, 64UL), TX_TRUE);

    test_expect("the module's own data is not outside it",
                TXM_MODULE_MANAGER_ENSURE_OUTSIDE_MODULE(module_instance, (ALIGN_TYPE) TEST_DATA_START, 64UL), TX_FALSE);

    test_expect("shared memory is not outside the module",
                TXM_MODULE_MANAGER_ENSURE_OUTSIDE_MODULE(module_instance, (ALIGN_TYPE) TEST_SHARED_RW_START, 64UL), TX_FALSE);

    test_expect("module code is not outside the module",
                TXM_MODULE_MANAGER_ENSURE_OUTSIDE_MODULE(module_instance, (ALIGN_TYPE) TEST_CODE_START, 64UL), TX_FALSE);

    /* A range that reaches into the module only partway is inside neither answer.
       Reporting it as outside would let it pass as a kernel object, which is the
       mirror image of the defect this test guards against.  */
    test_expect("a range straddling the end of module data is not outside it",
                TXM_MODULE_MANAGER_ENSURE_OUTSIDE_MODULE(module_instance, (ALIGN_TYPE) (TEST_DATA_END - 3UL), 16UL), TX_FALSE);

    test_expect("a range straddling the guard page after shared memory is not outside the module",
                TXM_MODULE_MANAGER_ENSURE_OUTSIDE_MODULE(module_instance, (ALIGN_TYPE) (TEST_SHARED_RW_END - 3UL), 16UL), TX_FALSE);

    /**********************************************************************/
    /* Cross-module and application-owned memory.                         */
    /**********************************************************************/

    /* Translation answers for whichever context is loaded. If another module's
       context is loaded, this module's records and the MMU disagree, so neither
       check may answer at all.  */
    test_current_asid =  TEST_OTHER_MODULE_ASID;

    test_expect("nothing is inside the module while another context is loaded",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) TEST_DATA_START, (ULONG) sizeof(ULONG)), TX_FALSE);

    test_expect("nothing is provably outside it either",
                TXM_MODULE_MANAGER_ENSURE_OUTSIDE_MODULE(module_instance, (ALIGN_TYPE) TEST_KERNEL_OBJECT, 64UL), TX_FALSE);

    test_current_asid =  TEST_MODULE_ASID;

    test_expect("the module is served again once its own context is loaded",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) TEST_DATA_START, (ULONG) sizeof(ULONG)), TX_TRUE);

    /**********************************************************************/
    /* The bound on how much work one request may ask for.                */
    /**********************************************************************/

    huge_size =  ((ULONG) TXM_MODULE_MANAGER_DATA_CHECK_MAX_PAGES) * ((ULONG) TEST_PAGE_SIZE);

    probes_before =  test_probe_count;
    test_expect("a range one page longer than the maximum is rejected",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) TEST_SHARED_RW_START, huge_size + 1UL), TX_FALSE);
    test_expect("...without translating any of it",
                (UINT) (test_probe_count == probes_before), TX_TRUE);

    test_expect("an over-long range is not outside the module either",
                _txm_module_manager_outside_data_check(module_instance, (ALIGN_TYPE) TEST_KERNEL_OBJECT, huge_size + 1UL), TX_FALSE);

    /* A range at exactly the maximum is still walked, and the walk stops at the
       first page that fails rather than translating all of it.  */
    probes_before =  test_probe_count;
    test_expect("a range of exactly the maximum length is walked and rejected here",
                TXM_MODULE_MANAGER_PARAM_CHECK_BUFFER_WRITE(module_instance, (ALIGN_TYPE) TEST_SHARED_RW_START, huge_size), TX_FALSE);
    test_expect("...stopping at the first page that fails",
                (UINT) ((test_probe_count - probes_before) == 3UL), TX_TRUE);

    /**********************************************************************/

    if (test_failures == 0U)
    {
        printf("SUCCESS!\n");
        return(0);
    }

    printf("ERROR: %u expectation(s) failed\n", test_failures);
    return(1);
}
