/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 * 
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 * 
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 * 
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/


/**************************************************************************/
/**************************************************************************/
/**                                                                       */
/** ThreadX Test                                                          */
/**                                                                       */
/**   Module Manager Cortex-A7 range validation, against a live MMU       */
/**                                                                       */
/**************************************************************************/
/**************************************************************************/

/* The host test for this check stands a simulated page map behind the port's
   one architecture primitive, which lets it run everywhere but leaves the CP15
   address translation itself unexercised: an encoding that named the wrong
   operation, or a PAR fault bit read the wrong way round, would pass it.

   This test closes that gap. It builds a short-descriptor translation table,
   turns the MMU on, and drives the real check through the real translation
   operations on a real Cortex-A7 translation regime. It is a bare-metal image,
   built and run by scripts/check_module_mmu_a7.sh under an emulator.

   The sections below are mapped for their access permissions only; nothing is
   dereferenced through them, and none of the addresses name a real target.  */

#include <stdio.h>

#define TX_SOURCE_CODE

#include "tx_api.h"
#include "txm_module.h"


/* Short-descriptor section entry fields. AP[2:0] selects the access
   permissions: 011 is unprivileged read/write, 010 is unprivileged read only,
   001 leaves the section privileged-only.  */

#define TEST_SECTION_TYPE           0x00000002
#define TEST_AP_LOW(value)          (((ULONG) (value)) << 10)
#define TEST_AP_USER_RW             TEST_AP_LOW(3)
#define TEST_AP_USER_RO             TEST_AP_LOW(2)
#define TEST_AP_PRIVILEGED_ONLY     TEST_AP_LOW(1)

#define TEST_LEVEL1_ENTRIES         4096
#define TEST_SECTION_SIZE           0x00100000

/* One section of each kind the check has to tell apart, plus an unmapped
   section immediately after the read-only one so a range can be made to leave
   its mapping partway through.  */

#define TEST_SHARED_RW              0x40000000
#define TEST_SHARED_RO              0x40100000
#define TEST_GUARD                  0x40200000
#define TEST_MODULE_DATA            0x41000000
#define TEST_MODULE_DATA_SIZE       0x00001000
#define TEST_KERNEL_ONLY            0x30000000

static ULONG    test_level1_table[TEST_LEVEL1_ENTRIES] __attribute__((aligned(16384)));
static UINT     test_failures = 0;


/* Reproduce the behaviour this check replaced: one translation of the first
   address, for reading, with the size discarded. Kept so the boundary cases
   can show both answers against the same live MMU.  */
static UINT  test_first_address_only_check(ALIGN_TYPE obj_ptr)
{
    return(_txm_module_manager_address_probe((ULONG) obj_ptr, TXM_MODULE_MANAGER_ACCESS_READ));
}


/* Build a flat translation table, then enable the MMU.  */
static VOID  test_mmu_enable(VOID)
{

ULONG   index;
ULONG   sctlr;
ULONG   zero = 0;
ULONG   dacr = 1;                       /* Domain 0 as a client, so AP is checked.  */


    /* Everything is privileged-only until a section below says otherwise.  */
    for (index = 0; index < TEST_LEVEL1_ENTRIES; index++)
    {
        test_level1_table[index] = (index * TEST_SECTION_SIZE) | TEST_SECTION_TYPE | TEST_AP_PRIVILEGED_ONLY;
    }

    test_level1_table[TEST_SHARED_RW / TEST_SECTION_SIZE] =
        TEST_SHARED_RW | TEST_SECTION_TYPE | TEST_AP_USER_RW;
    test_level1_table[TEST_SHARED_RO / TEST_SECTION_SIZE] =
        TEST_SHARED_RO | TEST_SECTION_TYPE | TEST_AP_USER_RO;
    test_level1_table[TEST_MODULE_DATA / TEST_SECTION_SIZE] =
        TEST_MODULE_DATA | TEST_SECTION_TYPE | TEST_AP_USER_RW;

    /* Leave the guard section faulting.  */
    test_level1_table[TEST_GUARD / TEST_SECTION_SIZE] = 0;

    __asm volatile ("MCR p15, 0, %0, c2, c0, 2" : : "r"(zero));                             /* TTBCR      */
    __asm volatile ("MCR p15, 0, %0, c2, c0, 0" : : "r"((ULONG) test_level1_table));        /* TTBR0      */
    __asm volatile ("MCR p15, 0, %0, c3, c0, 0" : : "r"(dacr));                             /* DACR       */
    __asm volatile ("MCR p15, 0, %0, c13, c0, 1" : : "r"(zero));                            /* CONTEXTIDR */
    __asm volatile ("MCR p15, 0, %0, c8, c7, 0" : : "r"(zero));                             /* TLBIALL    */
    __asm volatile ("DSB");
    __asm volatile ("ISB");

    __asm volatile ("MRC p15, 0, %0, c1, c0, 0" : "=r"(sctlr));
    sctlr = sctlr | ((ULONG) 1);                                                            /* SCTLR.M    */
    __asm volatile ("MCR p15, 0, %0, c1, c0, 0" : : "r"(sctlr));
    __asm volatile ("ISB");
}


static VOID  test_expect(const char *description, UINT actual, UINT expected)
{
    if (actual != expected)
    {
        printf("  FAIL: %s (expected %u, got %u)\n", description, expected, actual);
        test_failures++;
    }
}


int  main(VOID)
{

TXM_MODULE_INSTANCE     module;
TXM_MODULE_INSTANCE    *module_instance;
ALIGN_TYPE              straddle;


    printf("Cortex-A7 module range validation against a live MMU................... ");

    test_mmu_enable();

    module_instance = &module;
    module_instance -> txm_module_instance_id         = TXM_MODULE_ID;
    module_instance -> txm_module_instance_data_start = (VOID *) TEST_MODULE_DATA;
    module_instance -> txm_module_instance_data_end   = (VOID *) (TEST_MODULE_DATA + TEST_MODULE_DATA_SIZE - 1);
    module_instance -> txm_module_instance_code_start = (VOID *) 0;
    module_instance -> txm_module_instance_code_end   = (VOID *) 0;
    module_instance -> txm_module_instance_asid       = 0;

    /* The module's own data is answered from the manager's records.  */
    test_expect("recorded module data is writable",
                _txm_module_manager_inside_data_check(module_instance, (ALIGN_TYPE) TEST_MODULE_DATA, 4,
                                                      TXM_MODULE_MANAGER_ACCESS_WRITE), TX_TRUE);
    test_expect("a range crossing the recorded data end is rejected",
                _txm_module_manager_inside_data_check(module_instance,
                                                      (ALIGN_TYPE) (TEST_MODULE_DATA + TEST_MODULE_DATA_SIZE - 2), 4,
                                                      TXM_MODULE_MANAGER_ACCESS_WRITE), TX_FALSE);

    /* Shared memory is answered by the MMU, one page at a time.  */
    test_expect("shared read/write memory is writable",
                _txm_module_manager_inside_data_check(module_instance, (ALIGN_TYPE) TEST_SHARED_RW, 4,
                                                      TXM_MODULE_MANAGER_ACCESS_WRITE), TX_TRUE);
    test_expect("shared read-only memory is readable",
                _txm_module_manager_inside_data_check(module_instance, (ALIGN_TYPE) TEST_SHARED_RO, 4,
                                                      TXM_MODULE_MANAGER_ACCESS_READ), TX_TRUE);

    /* The write intent is the reason the port asks for two translations rather
       than one; a read-only mapping must not serve as a kernel destination.  */
    test_expect("shared read-only memory is not writable",
                _txm_module_manager_inside_data_check(module_instance, (ALIGN_TYPE) TEST_SHARED_RO, 4,
                                                      TXM_MODULE_MANAGER_ACCESS_WRITE), TX_FALSE);

    /* A range that leaves its mapping partway through. This is the case the
       replaced check accepted, and the reason this test exists.  */
    straddle = (ALIGN_TYPE) (TEST_GUARD - 2);
    test_expect("a range crossing into the guard section is rejected",
                _txm_module_manager_inside_data_check(module_instance, straddle, 4,
                                                      TXM_MODULE_MANAGER_ACCESS_READ), TX_FALSE);
    test_expect("...and translating only its first address would have accepted it",
                test_first_address_only_check(straddle), TX_TRUE);

    /* Privileged memory is reachable by neither intent, and is outside the module.  */
    test_expect("privileged-only memory is not readable",
                _txm_module_manager_inside_data_check(module_instance, (ALIGN_TYPE) TEST_KERNEL_ONLY, 4,
                                                      TXM_MODULE_MANAGER_ACCESS_READ), TX_FALSE);
    test_expect("privileged-only memory is outside the module",
                _txm_module_manager_outside_data_check(module_instance, (ALIGN_TYPE) TEST_KERNEL_ONLY, 64), TX_TRUE);
    test_expect("shared memory is not outside the module",
                _txm_module_manager_outside_data_check(module_instance, (ALIGN_TYPE) TEST_SHARED_RW, 64), TX_FALSE);

    if (test_failures == 0)
    {
        printf("SUCCESS!\n");
        return(0);
    }

    printf("ERROR: %u expectation(s) failed\n", test_failures);
    return(1);
}
