/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  MODULE MANAGER SAMPLE                                  RELEASE        */
/*                                                                        */
/*    sample_threadx_module_manager.c                  Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Loads the sample module three times, lets it misbehave every time,   */
/*    and reports what the hardware did about it -- on the Armv8-R AEM     */
/*    FVP, with no debugger and no person in the loop.                     */
/*                                                                        */
/*    This is the S32Z280 module demonstration turned into a regression.   */
/*    The silicon version is judged by a human reading a console and by a  */
/*    GDB harness that reads the module's memory between passes; neither    */
/*    exists here.  The model offers an Iris server and no GDB stub, so     */
/*    the image has to judge itself and say so in one line the runner can   */
/*    match.  Everything below that differs from the silicon sample         */
/*    differs for that reason.                                             */
/*                                                                        */
/*    THE RESULT THIS EXAMPLE EXISTS TO PRODUCE IS THE FAULT.  A module    */
/*    that starts and runs proves the loader works; a module that is       */
/*    stopped by the memory protection unit when it reaches outside its    */
/*    own memory proves the port works.  So the fault notification is not  */
/*    an error path here, it is the expected outcome, and its absence is   */
/*    the failure.                                                        */
/*                                                                        */
/*    TWO PASSES, because one proves nothing about relocation.  The module */
/*    is position independent: it is linked against nominal addresses it   */
/*    never runs at, and _gcc_setup rewrites its global offset table to    */
/*    wherever the manager actually put it.  A single run at the linked    */
/*    address would exercise a rebase whose input and output are the same  */
/*    number, and would look identical if the rebase did nothing at all.   */
/*                                                                        */
/*    So pass 1 loads the blob where the linker placed it and pass 2 loads */
/*    a byte-for-byte copy of it from the staging area, with pass 1 still  */
/*    holding its pool memory so that pass 2's data lands somewhere else    */
/*    too.  Both bases therefore differ between the passes, which is what   */
/*    makes the comparison at the end mean something.                      */
/*                                                                        */
/*    THEN A THIRD PASS, which faults the other way.  The two passes above */
/*    make the module read an address it does not own: a data abort,        */
/*    reported through DFSR and DFAR.  A module can equally leave its code  */
/*    region, which is a prefetch abort reported through IFSR and IFAR and  */
/*    arrives at the handler by a different vector.  Both halves of the     */
/*    port's fault path are therefore exercised, and neither is inferred    */
/*    from the other.  The third pass also runs after the first two have    */
/*    been unloaded, which is the other half of what this file shows: a     */
/*    module fault must leave the manager able to load and run the next     */
/*    module.                                                              */
/*                                                                        */
/*    AND WHAT THE MODULE ACHIEVED IS READ BACK, not inferred.  The manager */
/*    grants each pass a shared MPU region over one granule at a fixed      */
/*    address and the module records its progress there.  That is what      */
/*    replaces the GDB harness, and it is what lets this file fail on the   */
/*    two flags that matter -- SURVIVED_STEAL and SURVIVED_JUMP -- by name  */
/*    rather than only on the absence of a fault.  The two are the same     */
/*    event seen from both ends, and a regression that showed one without   */
/*    the other would be worth knowing about.                              */
/*                                                                        */
/*    WHAT A GREEN RUN HERE DOES NOT PROVE.  The model reports 32 EL1 MPU   */
/*    regions.  The Cortex-R52 TRM gives MPUIR.DREGION as 16, 20 or 24, so  */
/*    32 is not an architecturally permitted value for this core and the    */
/*    model is the generic AEMv8-R rather than an R52.  It is strictly more */
/*    permissive than every real part: this port needs seventeen regions,   */
/*    which the S32Z280's twenty supply and a legal 16-region R52 does not, */
/*    and no result from this image can tell you that.  The count is        */
/*    reported below so the log says what it was rather than implying it.   */
/*                                                                        */
/**************************************************************************/

#include "tx_api.h"
#include "txm_module.h"
#include "console.h"
#include "platform.h"
#include "mpu.h"
#include "cache.h"

/* The fault information the abort vector captured.  Declared here because the
   module manager expands it into the port's fault handler through the
   TXM_MODULE_MANAGER_FAULT_INFO macro rather than declaring it in a header, so an
   application that wants to read it has to say so itself.  */

extern TXM_MODULE_MANAGER_MEMORY_FAULT_INFO     _txm_module_manager_memory_fault_info;

/* Where the module image sits.  Provided by the linker script, which places the
   module's preamble first so this address is also the preamble address.  */

extern unsigned char    __module_image_start__;
extern unsigned char    __module_image_end__;

/* The second address the same blob is loaded from, so relocation can be shown
   rather than assumed.  Reserved by the linker script and left empty by it --
   see .module_stage in link_module.lds for why it is not pre-filled.  */

extern unsigned char    __module_stage_start__;
extern unsigned char    __module_stage_end__;

/* The shared status granule the module reports its progress through.  */

extern unsigned char    __module_status_start__;
extern unsigned char    __module_status_end__;

/* The kernel's own writable region, used to check that the address the module
   is told to reach for really is memory it must not have.  */

extern unsigned char    __data_start__;
extern unsigned char    __data_end__;

/* The address the module is going to reach for and must not be allowed to have.
   The value lives in the module's own initialised data, which is the point --
   the module reads it through its rebased GOT, so seeing it arrive in DFAR
   proves the rebase and the .data copy both worked.  Kept in step with
   sample_threadx_module.c by hand, and checked at run time twice: that it is
   what the module faulted on, and that it lies inside the kernel's data region
   in the first place.  An address in no region at all would fault too, and
   would prove much less.  */

#define MODULE_FORBIDDEN_ADDRESS    0x003EFFC0UL

/* The shared status word.  The same number is FVP_MODULE_STATUS_BASE in
   platform.h, ORIGIN(MODULE) in link_module.lds and MODULE_STATUS_ADDRESS in
   the module.  Three spellings of one address, checked against the linker
   symbol below rather than trusted.  */

#define MODULE_STATUS_ADDRESS       FVP_MODULE_STATUS_BASE
#define MODULE_STATUS_LENGTH        FVP_MODULE_STATUS_SIZE

/* The progress bits the module sets, mirrored from sample_threadx_module.c.
   The two SURVIVED flags can only ever be set if the hardware allowed an access
   it was configured to refuse, so they are checked for by name.  */

#define MODULE_PROGRESS_OWN_DATA        0x00000001UL
#define MODULE_PROGRESS_KERNEL_CALL     0x00000002UL
#define MODULE_PROGRESS_ATTEMPTED_STEAL 0x00000004UL
#define MODULE_PROGRESS_SURVIVED_STEAL  0x00000008UL
#define MODULE_PROGRESS_ATTEMPTED_JUMP  0x00000010UL
#define MODULE_PROGRESS_SURVIVED_JUMP   0x00000020UL

#define MODULE_PROGRESS_SURVIVED        (MODULE_PROGRESS_SURVIVED_STEAL | \
                                         MODULE_PROGRESS_SURVIVED_JUMP)

/* Which violation a pass tells the module to commit.  Written into the module
   instance's application-defined ID after the load and before the start, because
   that word is what the manager hands the module's start thread.  The high half
   is the fingerprint the preamble ships; only the low byte selects the test.  */

#define MODULE_ID_BASE              0x52520000UL
#define MODULE_TEST_DATA_ABORT      0x00000001UL
#define MODULE_TEST_PREFETCH_ABORT  0x00000002UL

/* Memory the manager hands out to modules: object memory, and the data region a
   module's own variables live in.  It has to be outside every region a module is
   given, or a module could reach another module's data.  */

#ifndef MODULE_POOL_SIZE
#define MODULE_POOL_SIZE    (16U * 1024U)
#endif

/* In the module area, not in .bss.  The manager carves a module's data out of
   this pool, and that data is handed to the module as an MPU region -- so if the
   pool lived in .bss it would sit inside the kernel's data region and the two
   would overlap, which PMSAv8-R does not allow.  */

static unsigned char    module_pool[MODULE_POOL_SIZE]
                            __attribute__((aligned(64), section(".module_pool")));

/* The object pool, which is a separate allocation from the module pool above and
   is not optional here.  A module that runs in User mode needs a kernel stack
   for the privileged side of each system call, and the manager allocates that
   from this pool -- txm_module_manager_initialize deliberately leaves the pool
   uncreated, so without this a User-mode module fails to start with
   TX_NOT_AVAILABLE from deep inside the thread create.  */

#ifndef MODULE_OBJECT_POOL_SIZE
#define MODULE_OBJECT_POOL_SIZE     (8U * 1024U)
#endif

static unsigned char    module_object_pool[MODULE_OBJECT_POOL_SIZE]
                            __attribute__((aligned(64)));

/* One instance per pass.  Passes 1 and 2 are loaded at once for part of the run:
   pass 1 is stopped but still holds its data allocation while pass 2 loads, which
   is what pushes pass 2's data base somewhere different.  */

#define MODULE_PASSES               3U
#define MODULE_RELOCATION_PASSES    2U

static TXM_MODULE_INSTANCE  demo_module[MODULE_PASSES];

/* What each pass produced.  Recorded rather than printed as it happens, because
   the comparison between the passes is the actual result and it cannot be made
   until they have all run.  */

typedef struct PASS_RESULT_STRUCT
{
    CHAR        *pass_name;
    ULONG        pass_test;              /* MODULE_TEST_*: which abort is expected */
    ULONG        pass_load_status;
    ULONG        pass_share_status;
    ULONG        pass_start_status;
    ULONG        pass_stop_status;
    ULONG        pass_code_start;
    ULONG        pass_code_end;
    ULONG        pass_data_start;
    ULONG        pass_data_end;
    ULONG        pass_data_base;
    ULONG        pass_faults;
    ULONG        pass_captured;
    ULONG        pass_progress;
    ULONG        pass_expect_progress;
    ULONG        pass_fault_r9;
    ULONG        pass_dfsr;
    ULONG        pass_dfar;
    ULONG        pass_ifsr;
    ULONG        pass_ifar;
    ULONG        pass_spsr;
    ULONG        pass_code_location;

    /* What the notify callback was told, against what it should have been told.
       Recorded as plain words rather than pointers so the console can print them
       and a mismatch names both values.  */

    ULONG        pass_notify_thread;
    ULONG        pass_notify_instance;
    ULONG        pass_expect_thread;
    ULONG        pass_expect_instance;
} PASS_RESULT;

static PASS_RESULT      pass_results[MODULE_PASSES];

/* What the fault handler saw.  Read by the reporting thread after the module has
   been terminated.  */

static volatile ULONG   fault_count;
static volatile ULONG   fault_notify_thread;
static volatile ULONG   fault_notify_instance;

static TX_THREAD        report_thread;
static unsigned char    report_stack[2048] __attribute__((aligned(8)));


/**************************************************************************/
/*  Fault notification.                                                   */
/*                                                                        */
/*  Called by the module manager after it has terminated the offending     */
/*  thread.  Records rather than prints: this runs in Abort mode on the     */
/*  Abort stack, which is a kilobyte and already carries the terminate      */
/*  underneath this frame.  A callback that printed would work here and     */
/*  would still be the wrong shape to copy.                               */
/*                                                                        */
/*  Its two arguments are the point of the hook, so they are recorded and  */
/*  checked rather than discarded: an application is being told WHICH      */
/*  thread and WHICH module faulted, and a callback that fires with the    */
/*  wrong pair is no more use than one that never fires.                   */
/**************************************************************************/

static void module_fault_notify(TX_THREAD *thread_ptr, TXM_MODULE_INSTANCE *module_instance)
{
    fault_count++;
    fault_notify_thread   = (ULONG) thread_ptr;
    fault_notify_instance = (ULONG) module_instance;
}


static void put_field(const char *label, unsigned long value)
{
    console_puts(label);
    console_puthex(value);
    console_puts("\n");
}


/**************************************************************************/
/*  The shared status word, reached through the manager's load window.     */
/*                                                                        */
/*  No kernel region covers the module area; region 16 does, and the       */
/*  scheduler enables it for every thread that owns no module.  This       */
/*  thread owns none, so the window is open on it and these two functions  */
/*  need no bracketing of their own -- which is the whole reason the       */
/*  window is owned by the scheduler rather than by whoever calls.         */
/*                                                                        */
/*  MISRA C:2012 Rule 11.6 is deliberately violated: the address is an     */
/*  agreement between two separately linked images.                       */
/**************************************************************************/

static void module_status_clear(void)
{
    *((volatile ULONG *) MODULE_STATUS_ADDRESS) = 0UL;
}


static ULONG module_status_read(void)
{
    return *((volatile ULONG *) MODULE_STATUS_ADDRESS);
}


/**************************************************************************/
/*  A byte copy, written out rather than called for.                      */
/*                                                                        */
/*  The manager links -nostartfiles and nothing else in this image reaches */
/*  for a C library, so calling memcpy would pull one in for a single      */
/*  copy.  The blob is under two kilobytes and this runs once.            */
/**************************************************************************/

static void copy_bytes(unsigned char *destination, const unsigned char *source,
                       unsigned long length)
{
    unsigned long   i;

    for (i = 0UL; i < length; i++)
    {
        destination[i] = source[i];
    }
}


/**************************************************************************/
/*  One pass: load the blob from a given address, grant it the status      */
/*  granule, start it, wait for the fault it is written to provoke, and    */
/*  stop it.                                                              */
/*                                                                        */
/*  The module is left loaded.  Its data allocation is what moves the next */
/*  pass's data base, and releasing it here would defeat half the test.    */
/**************************************************************************/

/* name is CHAR * and not const CHAR *, because txm_module_manager_in_place_load
   takes it that way -- the manager stores the pointer in the instance and the API
   has never promised not to write through it.  */

static void run_one_pass(UINT index, CHAR *name, VOID *location, ULONG test)
{
    PASS_RESULT            *result = &pass_results[index];
    TXM_MODULE_INSTANCE    *instance = &demo_module[index];
    unsigned int            waited;

    result -> pass_name = name;
    result -> pass_test = test;

    /* What the module should manage before the hardware stops it: its own data,
       a kernel call, and the attempt.  Not the SURVIVED bit for either test --
       that one is the failure.  */

    result -> pass_expect_progress = MODULE_PROGRESS_OWN_DATA
                                   | MODULE_PROGRESS_KERNEL_CALL
                                   | ((test == MODULE_TEST_PREFETCH_ABORT)
                                        ? MODULE_PROGRESS_ATTEMPTED_JUMP
                                        : MODULE_PROGRESS_ATTEMPTED_STEAL);

    /* Cleared before the module starts, so a fault or a progress bit counted
       here belongs to this pass and not the previous one.  */

    fault_count           = 0UL;
    fault_notify_thread   = 0UL;
    fault_notify_instance = 0UL;
    module_status_clear();

    result -> pass_load_status = (ULONG) txm_module_manager_in_place_load(instance, name, location);

    if (result -> pass_load_status != (ULONG) TX_SUCCESS)
    {
        return;
    }

    /* The shared granule the module reports through.  Granted while the module
       is LOADED and before it is STARTED, which is the only window the manager
       accepts, and granted per pass because each pass is its own instance with
       its own region table.  */

    result -> pass_share_status =
        (ULONG) txm_module_manager_external_memory_enable(instance,
                                                          (VOID *) &__module_status_start__,
                                                          MODULE_STATUS_LENGTH,
                                                          TXM_MODULE_ATTRIBUTE_READ_WRITE);

    if (result -> pass_share_status != (ULONG) TX_SUCCESS)
    {
        return;
    }

    /* Which violation this pass provokes.  Written after the load, which is what
       filled the field in from the preamble, and before the start, which is what
       hands it to the module's start thread.  */

    instance -> txm_module_instance_application_module_id = MODULE_ID_BASE | test;

    /* What the notify callback must be told, recorded before the module runs so
       the comparison afterwards is against an expectation and not against
       whatever the callback happened to write.  */

    result -> pass_expect_thread   = (ULONG) &(instance -> txm_module_instance_start_stop_thread);
    result -> pass_expect_instance = (ULONG) instance;

    /* Read from the instance rather than computed here.  Where the code ended up
       is what the manager decided, and the whole point of the comparison at the
       end is to check the module against the manager's own numbers.  */

    result -> pass_code_start  = (ULONG) instance -> txm_module_instance_code_start;
    result -> pass_code_end    = (ULONG) instance -> txm_module_instance_code_end;
    result -> pass_data_start  = (ULONG) instance -> txm_module_instance_data_start;
    result -> pass_data_end    = (ULONG) instance -> txm_module_instance_data_end;
    result -> pass_data_base   = (ULONG) instance -> txm_module_instance_module_data_base_address;

    result -> pass_start_status = (ULONG) txm_module_manager_start(instance);

    if (result -> pass_start_status != (ULONG) TX_SUCCESS)
    {
        return;
    }

    /* Wait for the abort vector to capture a fault belonging to THIS pass.

       The captured fault info is waited on rather than the notify callback, even
       though the callback works.  The capture happens in the abort vector before
       anything else runs, so it is the earliest and most direct evidence that a
       fault occurred; the callback is a later consequence of the same event, and
       this file checks it separately.  Waiting on the earlier of the two means a
       regression in the callback path shows up as "notified 0" next to a
       captured fault, rather than as "no fault occurred" -- which is the opposite
       of the truth.

       Attribution is by thread pointer: each pass has its own module instance and
       therefore its own start thread, so a captured fault naming this pass's
       thread cannot be a leftover from the previous pass.  */

    waited = 0U;
    while ((_txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_thread_ptr
                != &(instance -> txm_module_instance_start_stop_thread)) &&
           (waited < 50U))
    {
        tx_thread_sleep(2UL);
        waited++;
    }

    if (_txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_thread_ptr
            == &(instance -> txm_module_instance_start_stop_thread))
    {
        result -> pass_captured      = 1UL;
        result -> pass_dfsr          = _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_dfsr;
        result -> pass_dfar          = _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_dfar;
        result -> pass_ifsr          = _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_ifsr;
        result -> pass_ifar          = _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_ifar;
        result -> pass_spsr          = _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_spsr;
        result -> pass_fault_r9      = _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_r9;
        result -> pass_code_location = (ULONG) _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_code_location;
    }

    /* What the module reached, and what the notify callback saw.  Both read
       after the wait above, so what ran is recorded and what did not shows as
       zero.  The status word is read while THIS pass is still the last thing to
       have written it, which is the same discipline the silicon harness needs
       for a different reason: there, the byte pool reuses a freed block and a
       later pass's data lands where an earlier one's was.  */

    result -> pass_progress        = module_status_read();
    result -> pass_faults          = fault_count;
    result -> pass_notify_thread   = fault_notify_thread;
    result -> pass_notify_instance = fault_notify_instance;

    /* Stopped, not unloaded.  The fault terminated the module's start thread but
       left the module STARTED, and unload refuses anything that is not LOADED or
       STOPPED -- so this is required, not tidiness.  */

    result -> pass_stop_status = (ULONG) txm_module_manager_stop(instance);
}


static void report_one_pass(const PASS_RESULT *result)
{
    console_puts("\n--- ");
    console_puts(result -> pass_name);
    console_puts(" ---\n");

    console_puts("  expected abort   = ");
    if (result -> pass_test == MODULE_TEST_PREFETCH_ABORT)
    {
        console_puts("prefetch (IFSR/IFAR)\n");
    }
    else
    {
        console_puts("data (DFSR/DFAR)\n");
    }

    put_field("  load status      = ", result -> pass_load_status);
    put_field("  share status     = ", result -> pass_share_status);
    put_field("  start status     = ", result -> pass_start_status);
    put_field("  stop status      = ", result -> pass_stop_status);
    put_field("  code region      = ", result -> pass_code_start);
    put_field("       .. to        = ", result -> pass_code_end);
    put_field("  data region      = ", result -> pass_data_start);
    put_field("       .. to        = ", result -> pass_data_end);
    put_field("  data base (r9)   = ", result -> pass_data_base);
    put_field("  fault captured   = ", result -> pass_captured);
    put_field("  module progress  = ", result -> pass_progress);
    put_field("    should be      = ", result -> pass_expect_progress);
    put_field("  notify callbacks = ", result -> pass_faults);
    put_field("  notified thread  = ", result -> pass_notify_thread);
    put_field("    should be      = ", result -> pass_expect_thread);
    put_field("  notified module  = ", result -> pass_notify_instance);
    put_field("    should be      = ", result -> pass_expect_instance);
    put_field("  r9 at the fault  = ", result -> pass_fault_r9);
    put_field("  DFSR             = ", result -> pass_dfsr);
    put_field("  DFAR             = ", result -> pass_dfar);
    put_field("  IFSR             = ", result -> pass_ifsr);
    put_field("  IFAR             = ", result -> pass_ifar);
    put_field("  SPSR             = ", result -> pass_spsr);
    put_field("  faulting pc      = ", result -> pass_code_location);

    /* Meaningful for a data abort, where the module faulted inside its own code.
       A prefetch abort faults ON the address it branched to, so the faulting pc
       is outside the module and the difference is not an offset into it.  */

    if (result -> pass_test != MODULE_TEST_PREFETCH_ABORT)
    {
        put_field("  pc - code base   = ", result -> pass_code_location - result -> pass_code_start);
    }
}


/**************************************************************************/
/*  Per-pass verdict.  Returns the number of failures it found.           */
/**************************************************************************/

static UINT judge_one_pass(const PASS_RESULT *result)
{
    if ((result -> pass_load_status != (ULONG) TX_SUCCESS) ||
        (result -> pass_share_status != (ULONG) TX_SUCCESS) ||
        (result -> pass_start_status != (ULONG) TX_SUCCESS))
    {
        console_puts("FAIL ");
        console_puts(result -> pass_name);
        console_puts(": did not load, share and start\n");
        return 1U;
    }

    /* First, and named explicitly: the module must not have survived what it
       was told to attempt.  This is the one result that means the protection
       did not hold, and it is checked before anything else so that a run in
       which the MPU did nothing says so in those words rather than through
       some downstream symptom.  */

    if ((result -> pass_progress & MODULE_PROGRESS_SURVIVED) != 0UL)
    {
        console_puts("FAIL ");
        console_puts(result -> pass_name);
        console_puts(": the module SURVIVED its violation -- it is not protected\n");
        return 1U;
    }

    if (result -> pass_captured == 0UL)
    {
        console_puts("FAIL ");
        console_puts(result -> pass_name);
        console_puts(": reached outside its memory and was not stopped\n");
        return 1U;
    }

    /* What it did manage, from the shared granule.  A module that faulted
       without having read its own data or made a kernel call faulted for the
       wrong reason, and the fault alone would not have said so.  */

    if (result -> pass_progress != result -> pass_expect_progress)
    {
        console_puts("FAIL ");
        console_puts(result -> pass_name);
        console_puts(": did not reach the point it was supposed to fault at\n");
        return 1U;
    }

    /* r9 is the module's PIC base and the manager seeded it from the thread
       entry info.  If the value captured at the fault is not the data base the
       manager handed out, the seeding is wrong and every data reference the
       module made went somewhere unintended.  */

    if (result -> pass_fault_r9 != result -> pass_data_base)
    {
        console_puts("FAIL ");
        console_puts(result -> pass_name);
        console_puts(": r9 was not the module's data base\n");
        return 1U;
    }

    /* A fault from anywhere but User mode is not this test passing: the module
       runs unprivileged, so a privileged fault means the fault came from the
       kernel and something else is wrong.  */

    if ((result -> pass_spsr & 0x1FUL) != 0x10UL)
    {
        console_puts("FAIL ");
        console_puts(result -> pass_name);
        console_puts(": faulted, but not from User mode\n");
        return 1U;
    }

    /* The module got this address out of its own initialised data, through its
       rebased GOT.  Any other value means it faulted somewhere unintended --
       most likely on its own data, which is what a bad rebase looks like.

       Which register carries it depends on the abort: a data abort reports the
       address it tried to touch in DFAR, a prefetch abort reports the address it
       tried to fetch in IFAR.  Checking the wrong one of the two passes for a
       stale value left by an earlier fault, which is why this is selected on the
       expected type rather than on whichever register happens to be non-zero. */

    if (((result -> pass_test == MODULE_TEST_PREFETCH_ABORT)
            ? result -> pass_ifar : result -> pass_dfar) != MODULE_FORBIDDEN_ADDRESS)
    {
        console_puts("FAIL ");
        console_puts(result -> pass_name);
        console_puts(": faulted at the wrong address, so .data or the GOT is wrong\n");
        return 1U;
    }

    /* The notify callback is a public API of the module manager, so it is
       checked and not merely reported.  Zero here with a captured fault above
       means the fault path reached the hardware's evidence and never reached the
       application: on this port that used to be the case for every fault,
       because the shared fault handler terminates the offending thread before
       calling the hook and the terminate only returns if the abort vector has
       told the kernel it is inside an exception.  More than one means a single
       violation was reported twice.  */

    if (result -> pass_faults != 1UL)
    {
        console_puts("FAIL ");
        console_puts(result -> pass_name);
        console_puts(": the fault-notify callback did not run exactly once\n");
        return 1U;
    }

    /* Being told that something faulted is not the service; being told which
       thread and which module is.  */

    if ((result -> pass_notify_thread != result -> pass_expect_thread) ||
        (result -> pass_notify_instance != result -> pass_expect_instance))
    {
        console_puts("FAIL ");
        console_puts(result -> pass_name);
        console_puts(": notified about the wrong thread or module\n");
        return 1U;
    }

    console_puts("PASS ");
    console_puts(result -> pass_name);
    console_puts(": ran, faulted in User mode at the forbidden address, and was reported\n");

    return 0U;
}


/**************************************************************************/
/*  The manager thread.                                                   */
/**************************************************************************/

static void manager_entry(ULONG input)
{
    UINT            status;
    UINT            i;
    unsigned long   blob_size;
    ULONG           offset_0;
    ULONG           offset_1;
    UINT            failures = 0U;

    (void) input;

    /* Every manager call happens here, in a thread, and not in
       tx_application_define.  Loading a module takes the manager's mutex, and a
       service that can block cannot be called before the scheduler runs.  */

    /* ------------------------------------------------------------------
       What the platform actually provides.  Reported before anything is
       loaded, because a shortfall here explains every failure below it.
       ------------------------------------------------------------------ */

    put_field("MPUIR regions available = ", (unsigned long) mpu_region_count());
    put_field("regions this port needs = ", (unsigned long) MPU_MODULE_REGIONS_REQUIRED);
    put_field("D-cache line bytes      = ", cache_dcache_line_bytes());

    if (mpu_region_count() < MPU_MODULE_REGIONS_REQUIRED)
    {
        console_puts("FAIL the implementation has too few MPU regions for this port\n");
        failures++;
    }

    /* The three spellings of the shared status address, and the forbidden
       address, checked rather than trusted.  Both are constants agreed between
       separately linked images, and a disagreement in either would present as a
       module faulting somewhere unexpected -- which is exactly what the pass
       verdicts are trying to distinguish.  */

    if ((unsigned long) &__module_status_start__ != MODULE_STATUS_ADDRESS)
    {
        console_puts("FAIL the linker put the status word somewhere the module will not look\n");
        failures++;
    }

    if ((unsigned long) (&__module_status_end__ - &__module_status_start__)
            < MODULE_STATUS_LENGTH)
    {
        console_puts("FAIL the status granule is smaller than the region granted over it\n");
        failures++;
    }

    if ((MODULE_FORBIDDEN_ADDRESS < (unsigned long) &__data_start__) ||
        (MODULE_FORBIDDEN_ADDRESS >= (unsigned long) &__data_end__))
    {
        /* The point of the test is that a module cannot reach the KERNEL'S
           memory.  An address in no region at all would fault too, and would
           prove much less, so the address is checked to be inside the kernel's
           writable region before anything relies on the fault it causes.  */

        console_puts("FAIL the forbidden address is not inside the kernel's data region\n");
        failures++;
    }

    console_puts("\nM1 initialize\n");
    status = txm_module_manager_initialize((VOID *) module_pool, MODULE_POOL_SIZE);

    put_field("initialize         = ", status);
    put_field("ready              = ", (unsigned long) _txm_module_manager_ready);

    /* The pool the module's kernel stacks come from.  See module_object_pool. */

    status = txm_module_manager_object_pool_create((VOID *) module_object_pool,
                                                   MODULE_OBJECT_POOL_SIZE);

    put_field("object pool create = ", status);

    /* Registered before anything is loaded, so there is no window in which a
       module could fault with nobody listening.  */

    console_puts("M2 fault notify\n");
    txm_module_manager_memory_fault_notify(module_fault_notify);

    /* The copy that makes pass 2 a relocation test.  The staging area is left
       empty by the linker on purpose: if the blob were already there, a failure
       to copy would be invisible because the right bytes would be present.  */

    blob_size = (unsigned long) (&__module_image_end__ - &__module_image_start__);

    console_puts("M3 staging the blob\n");
    put_field("  blob size        = ", blob_size);
    put_field("  from             = ", (unsigned long) &__module_image_start__);
    put_field("  to               = ", (unsigned long) &__module_stage_start__);

    if (blob_size > (unsigned long) (&__module_stage_end__ - &__module_stage_start__))
    {
        /* Reported rather than allowed to overrun.  The staging area is a fixed
           size in the linker script and the module is free to grow.  */

        console_puts("FAIL the module image does not fit the staging area\n");
        failures++;
    }
    else
    {
        copy_bytes(&__module_stage_start__, &__module_image_start__, blob_size);

        /* Those were data writes to memory that is about to be fetched as
           instructions, and the module area is mapped Normal write-back.  So the
           copied bytes may sit in dirty D-cache lines while the instruction
           side, which is not coherent with the D cache on this core, fetches
           whatever main memory still holds.  Clean the range so memory is
           correct, then invalidate the I cache so no stale line from a previous
           image can be served.

           Not a precaution the passing run justifies: a cold I cache over a
           never-executed address happens to work, and keeps happening to work
           until the staging area is reused or an eviction lands differently.
           Any loader that copies code owes this pair.  */

        cache_clean_range(&__module_stage_start__, blob_size);
        cache_invalidate_icache_all();

        console_puts("M4 pass 1, at the linked address\n");
        run_one_pass(0U, "linked address, data abort", (VOID *) &__module_image_start__,
                     MODULE_TEST_DATA_ABORT);

        console_puts("M5 pass 2, relocated\n");
        run_one_pass(1U, "relocated, data abort", (VOID *) &__module_stage_start__,
                     MODULE_TEST_DATA_ABORT);

        /* Both relocation passes are done with their memory now.  Unloaded here
           rather than at the end, so that the pass below is a load that follows
           two faults and two unloads -- which is the state a manager is in after
           a module has misbehaved, and the state the next load has to work in. */

        for (i = 0U; i < MODULE_RELOCATION_PASSES; i++)
        {
            (void) txm_module_manager_unload(&demo_module[i]);
        }

        /* The other abort type, from the staging area so that it is also a
           relocated module: the address arriving in IFAR came out of the
           module's own initialised data through its rebased GOT, exactly as DFAR
           does above.  */

        console_puts("M6 pass 3, prefetch abort\n");
        run_one_pass(2U, "relocated, prefetch abort", (VOID *) &__module_stage_start__,
                     MODULE_TEST_PREFETCH_ABORT);

        (void) txm_module_manager_unload(&demo_module[2]);
    }

    /* ------------------------------------------------------------------
       The verdict.
       ------------------------------------------------------------------ */

    console_puts("\n=== ThreadX modules on the Armv8-R AEM FVP: "
                 "isolation and relocation ===\n");

    for (i = 0U; i < MODULE_PASSES; i++)
    {
        report_one_pass(&pass_results[i]);
    }

    console_puts("\n");

    /* Before anything else: a module's code, data and shared regions are enabled
       at the same time, and PMSAv8-R has no region priority -- two enabled
       regions that overlap are CONSTRAINED UNPREDICTABLE, and that means aborts
       from addresses that look perfectly legal.  Nothing in the manager checks
       for it, so this example does.

       The risk is real here and not theoretical: the image, the pool and the
       staging area all live in one 64 KB area.  A module grown large enough, or
       a pool sized differently, and two of them would meet.  */

    for (i = 0U; i < MODULE_PASSES; i++)
    {
        const PASS_RESULT *result = &pass_results[i];

        if (result -> pass_load_status != (ULONG) TX_SUCCESS)
        {
            continue;
        }

        if ((result -> pass_code_start <= result -> pass_data_end) &&
            (result -> pass_data_start <= result -> pass_code_end))
        {
            console_puts("FAIL ");
            console_puts(result -> pass_name);
            console_puts(": its code and data regions overlap\n");
            failures++;
        }

        if ((result -> pass_code_start <= (MODULE_STATUS_ADDRESS + MODULE_STATUS_LENGTH - 1UL)) &&
            (MODULE_STATUS_ADDRESS <= result -> pass_code_end))
        {
            console_puts("FAIL ");
            console_puts(result -> pass_name);
            console_puts(": the shared status region overlaps its code\n");
            failures++;
        }

        if ((result -> pass_data_start <= (MODULE_STATUS_ADDRESS + MODULE_STATUS_LENGTH - 1UL)) &&
            (MODULE_STATUS_ADDRESS <= result -> pass_data_end))
        {
            console_puts("FAIL ");
            console_puts(result -> pass_name);
            console_puts(": the shared status region overlaps its data\n");
            failures++;
        }
    }

    /* Each pass on its own.  */

    for (i = 0U; i < MODULE_PASSES; i++)
    {
        failures += judge_one_pass(&pass_results[i]);
    }

    /* And the first two passes against each other, which is the relocation
       result.  The third is not in this comparison: it faults on the address it
       branched to rather than inside its own code, so its faulting pc is not an
       offset into the module and there is nothing to compare.  */

    offset_0 = pass_results[0].pass_code_location - pass_results[0].pass_code_start;
    offset_1 = pass_results[1].pass_code_location - pass_results[1].pass_code_start;

    if ((pass_results[0].pass_captured == 0UL) || (pass_results[1].pass_captured == 0UL))
    {
        console_puts("FAIL relocation: a pass did not fault, nothing to compare\n");
        failures++;
    }
    else if (pass_results[0].pass_code_start == pass_results[1].pass_code_start)
    {
        console_puts("FAIL relocation: both passes ran from the same address\n");
        failures++;
    }
    else if (offset_0 != offset_1)
    {
        console_puts("FAIL relocation: the two passes faulted at different offsets\n");
        failures++;
    }
    else
    {
        console_puts("PASS relocation: the same blob ran correctly from two addresses\n");

        if (pass_results[0].pass_data_base == pass_results[1].pass_data_base)
        {
            /* Not a failure -- the code rebase is still proven -- but worth
               saying, because it means the data rebase produced the same numbers
               twice and was not exercised as thoroughly.  */

            console_puts("NOTE both passes shared a data base; the data rebase was not varied\n");
        }
    }

    /* Both abort types, stated as its own line.  Each pass above already checked
       its own registers; this says that between them the two vectors were both
       taken, which is the claim a reader of the log wants to be able to make
       without working out what each pass did.  */

    if ((pass_results[0].pass_captured != 0UL) && (pass_results[0].pass_dfsr != 0UL) &&
        (pass_results[2].pass_captured != 0UL) && (pass_results[2].pass_ifsr != 0UL))
    {
        console_puts("PASS both abort types: data through DFSR/DFAR, prefetch through IFSR/IFAR\n");
    }
    else
    {
        console_puts("FAIL only one kind of abort was exercised\n");
        failures++;
    }

    /* The manager is still alive to print this, which is itself the last
       result: three module faults did not take the kernel with them.  */

    put_field("\nfailures           = ", (unsigned long) failures);

    if (failures == 0U)
    {
        console_puts("\nMODULE RESULT: ALL CHECKS PASSED\n");
    }
    else
    {
        console_puts("\nMODULE RESULT: FAILED\n");
    }

    /* Terminates the model.  Every FVP image in this port exits through
       semihosting SYS_EXIT, so the runner needs no host-side timeout and a hang
       cannot be mistaken for a slow run.  */

    console_exit(failures);
}


/**************************************************************************/
/*  Application definition.                                               */
/**************************************************************************/

void tx_application_define(void *first_unused_memory)
{
    UINT    status;

    (void) first_unused_memory;

    console_puts("\n=== module manager starting ===\n");

    /* Nothing but the thread.  See manager_entry for why the manager cannot be
       driven from here.  */

    status = tx_thread_create(&report_thread, "module manager", manager_entry, 0UL,
                              report_stack, sizeof(report_stack),
                              20U, 20U, TX_NO_TIME_SLICE, TX_AUTO_START);

    /* Reported rather than discarded.  A thread that was never created and a
       thread that was created but never scheduled produce exactly the same
       silence on the console, and telling those two apart is most of the work
       when the port itself is what is under test.  */

    if (status == TX_SUCCESS)
    {
        console_puts("M0 thread created\n");
    }
    else
    {
        put_field("FAIL tx_thread_create status = ", (unsigned long) status);
    }
}


/**************************************************************************/
/*  bsp_main -- entered at EL1 from entry.S.  Does not return.            */
/**************************************************************************/

void bsp_main(void)
{
    console_puts("\n=== ThreadX modules :: Armv8-R AEM FVP (Cortex-R52) ===\n");
    console_puts("entering kernel\n");

    tx_kernel_enter();

    /* Not reached.  */

    console_puts("FAIL tx_kernel_enter returned\n");

    console_exit(1U);
}
