/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  SAMPLE MODULE                                          RELEASE        */
/*                                                                        */
/*    sample_threadx_module.c                          Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    A module that exercises the protection boundary rather than          */
/*    demonstrating features, for the Armv8-R AEM FVP.                     */
/*                                                                        */
/*    The S32Z280 copy of this file is the same module for the same port;   */
/*    what differs is the two addresses at the bottom and the board named   */
/*    here, so `diff` is the tool for telling whether the two have drifted. */
/*                                                                        */
/*    Four steps:                                                          */
/*                                                                        */
/*      1. Writes and reads its own data, which must succeed.             */
/*      2. Makes a kernel call, which must succeed -- proving a module in  */
/*         User mode can reach the kernel through the supervisor call      */
/*         boundary and come back.                                        */
/*      3. Violates its protection in one of three ways the manager        */
/*         selects, which must fault.                                     */
/*      4. Never reaches step 4, because step 3 terminates it.            */
/*                                                                        */
/*    THE THREE VIOLATIONS.  Two of them are the two aborts the hardware   */
/*    distinguishes: reading the kernel's data is a DATA abort reported     */
/*    through DFSR and DFAR, branching out of the code region is a         */
/*    PREFETCH abort reported through IFSR and IFAR.  The third writes a   */
/*    granule of the SHARED area that the manager deliberately did not     */
/*    grant, after writing and reading back every granule it did -- so it   */
/*    is the shared-region machinery under test rather than the kernel's    */
/*    own memory, and a grant that covered one granule too many is what it  */
/*    is looking for.                                                      */
/*                                                                        */
/*    Steps 1 and 2 passing without step 3 faulting would mean the module  */
/*    is running unprotected, which is the failure this example exists to  */
/*    detect.  A module that only ever touched its own memory would pass   */
/*    identically with the MPU switched off.                              */
/*                                                                        */
/*    HOW PROGRESS GETS OUT.  A module cannot print: the console belongs    */
/*    to the board support package, outside every region a module owns, so  */
/*    reaching it would fault as surely as step 3 does.  So progress is     */
/*    recorded twice -- in the module's own data, and in the first granule  */
/*    of the shared area the manager granted it.                           */
/*                                                                        */
/*    Which of the two can be read depends on the board.  On silicon a GDB  */
/*    harness reads the module's own copy out of the data area the manager  */
/*    allocated for it; the FVP has no such seam -- it exposes an Iris      */
/*    server and no GDB stub -- so there only the shared copy is readable    */
/*    and everything the run reports has to be reported by the image        */
/*    itself.  Both writes are kept on both boards deliberately: if the     */
/*    shared write were the only one, a module that could not reach its own */
/*    data would still report progress.                                    */
/*                                                                        */
/*    The shared address is a literal on this side.  The module has no      */
/*    loader to tell it anything and the manager deliberately knows no      */
/*    symbol of the module, so the two agree by convention -- and the       */
/*    manager checks that they do, against the linker's own symbol, rather  */
/*    than trusting them to.                                               */
/*                                                                        */
/**************************************************************************/

#include "txm_module.h"

/* Progress, recorded in two places.  See the header: the shared copy is what
   the manager reads, and the module's own copy is what proves it could write
   its own data at all.  */

#define MODULE_PROGRESS_OWN_DATA        0x00000001UL
#define MODULE_PROGRESS_KERNEL_CALL     0x00000002UL
#define MODULE_PROGRESS_ATTEMPTED_STEAL 0x00000004UL
#define MODULE_PROGRESS_SURVIVED_STEAL  0x00000008UL
#define MODULE_PROGRESS_ATTEMPTED_JUMP  0x00000010UL
#define MODULE_PROGRESS_SURVIVED_JUMP   0x00000020UL
#define MODULE_PROGRESS_SHARED_WROTE    0x00000040UL
#define MODULE_PROGRESS_ATTEMPTED_GAP   0x00000080UL
#define MODULE_PROGRESS_SURVIVED_GAP    0x00000100UL

/* Which violation to commit, taken from the low byte of the module ID the
   manager passes to the start thread.  The rest of that word is left alone: the
   preamble ships it as 0x52520001, so a manager that sets nothing still gets a
   working data-abort test rather than a module that does nothing.  */

#define MODULE_TEST_MASK                0x000000FFUL
#define MODULE_TEST_DATA_ABORT          0x00000001UL
#define MODULE_TEST_PREFETCH_ABORT      0x00000002UL
#define MODULE_TEST_SHARED_ABORT        0x00000003UL

/* The shared status word, at the base of the module area.

   A literal address rather than anything reached through the GOT, because it is
   not the module's own memory: it is memory the manager granted, and the module
   has no channel through which to be told where it is.  The same number is
   FVP_MODULE_STATUS_BASE in platform.h and ORIGIN(MODULE) in link_module.lds;
   the manager checks all three agree before it starts this module, so a
   disagreement is a reported failure rather than a fault at the first write.

   MISRA C:2012 Rule 11.6 (conversion between an integer and a pointer to void)
   is deliberately violated: an address agreed between two separately linked
   images can only be written as a literal, and there is no conforming way to
   express it.  */

#define MODULE_STATUS_ADDRESS           0x003F0000UL

#define MODULE_STATUS   (*((volatile ULONG *) MODULE_STATUS_ADDRESS))

/* And the rest of the shared area, which exists to exercise the shared-region
   machinery rather than to report anything.

   The manager may grant a module TXM_MODULE_MPU_SHARED_ENTRIES regions and one
   grant only ever proves the first entry works, so the area holds one granule
   per entry -- five granted, and a sixth that the manager never grants.  The
   ungranted one is index 2, which puts a granted granule on either side of it:
   a limit register masked the wrong way, or a base off by a granule, leaks into
   that gap from below or from above, and either way a module that can write it
   was given more than was asked for.

   The mark for each granule goes at WORD 1, because word 0 of granule 0 is the
   progress word above.  Uniform across all six so the address the gap write
   faults on is one expression on both sides of the agreement.  */

#define MODULE_STATUS_GRANULE           0x40UL
#define MODULE_STATUS_GRANULES          6UL
#define MODULE_STATUS_UNGRANTED         2UL
#define MODULE_STATUS_MARK_OFFSET       4UL

#define MODULE_SHARED_SIGNATURE         0x5A5A0000UL

#define MODULE_SHARED_MARK(index)                                             \
    (*((volatile ULONG *) (MODULE_STATUS_ADDRESS                              \
                            + ((index) * MODULE_STATUS_GRANULE)               \
                            + MODULE_STATUS_MARK_OFFSET)))

volatile ULONG  module_progress;
volatile ULONG  module_scratch[16];

/* An address the module has no business touching, used by step 3.

   The last protection granule below the module area, which on this map is
   inside the manager's data region: that region is EL1 read/write and
   execute-never, so a User-mode read of it is a permission fault and a
   User-mode instruction fetch from it is one too.  Both are what step 3 needs,
   and both prove the KERNEL'S memory is what a module cannot reach -- which is
   the property being demonstrated, rather than the absence of a mapping.

   Held in initialised data rather than written as a literal, deliberately and
   unlike the status address above.  The module reads it through its rebased
   GOT, so the value arriving in DFAR or IFAR also proves the GOT was rewritten
   and .data was copied.  The manager knows the same number and checks it.  */

volatile ULONG  module_forbidden_address = 0x003EFFC0UL;


void demo_module_start(ULONG id)
{
    ULONG   i;
    ULONG   sum = 0UL;
    ULONG   shared_ok = 1UL;

    /* 1. The module's own data.  If this faults, the data region is wrong and
          nothing else in this file will be reached.  */

    for (i = 0UL; i < 16UL; i++)
    {
        module_scratch[i] = i * 3UL;
    }

    for (i = 0UL; i < 16UL; i++)
    {
        sum += module_scratch[i];
    }

    if (sum == 360UL)                       /* 3 * (0 + 1 + ... + 15) */
    {
        module_progress |= MODULE_PROGRESS_OWN_DATA;
        MODULE_STATUS   |= MODULE_PROGRESS_OWN_DATA;
    }

    /* 2. A kernel call, which leaves User mode through the supervisor call
          boundary and must come back.  A sleep is used because it is the
          simplest service with an observable effect and it yields, so the
          scheduler runs a module thread and reloads its regions on the way
          back -- exercising the region switch as well as the call.  */

    if (tx_thread_sleep(2UL) == TX_SUCCESS)
    {
        module_progress |= MODULE_PROGRESS_KERNEL_CALL;
        MODULE_STATUS   |= MODULE_PROGRESS_KERNEL_CALL;
    }

    /* 3. The violation, and 4. the flag that says it was tolerated.  Each is
          marked before the access rather than after, because after is not
          reached if the port is working.  The SURVIVED flags are what the
          manager fails on: they can only appear if the hardware allowed an
          access it was configured to refuse.  */

    if ((id & MODULE_TEST_MASK) == MODULE_TEST_SHARED_ABORT)
    {
        /* Write every granule the manager granted, read all of them back, and
           then write the one it did not grant.

           The readback matters as much as the write.  A shared entry programmed
           with the wrong base still accepts a store -- it just lands somewhere
           else -- so a write that is never read back proves only that the core
           did not object.  Reading each granule's own mark out of its own
           granule is what says the five entries describe five distinct
           extents.  */

        for (i = 0UL; i < MODULE_STATUS_GRANULES; i++)
        {
            if (i != MODULE_STATUS_UNGRANTED)
            {
                MODULE_SHARED_MARK(i) = MODULE_SHARED_SIGNATURE | i;
            }
        }

        for (i = 0UL; i < MODULE_STATUS_GRANULES; i++)
        {
            if ((i != MODULE_STATUS_UNGRANTED) &&
                (MODULE_SHARED_MARK(i) != (MODULE_SHARED_SIGNATURE | i)))
            {
                shared_ok = 0UL;
            }
        }

        if (shared_ok != 0UL)
        {
            module_progress |= MODULE_PROGRESS_SHARED_WROTE;
            MODULE_STATUS   |= MODULE_PROGRESS_SHARED_WROTE;
        }

        /* The gap.  A WRITE rather than a read, so DFSR reports WnR set and the
           fault cannot be confused with the read the data-abort passes do.  It
           lies between two granules this module was granted, so surviving it
           means a grant covered a granule nobody asked for -- which is the
           whole reason this pass exists.  */

        module_progress |= MODULE_PROGRESS_ATTEMPTED_GAP;
        MODULE_STATUS   |= MODULE_PROGRESS_ATTEMPTED_GAP;

        MODULE_SHARED_MARK(MODULE_STATUS_UNGRANTED) =
            MODULE_SHARED_SIGNATURE | MODULE_STATUS_UNGRANTED;

        module_progress |= MODULE_PROGRESS_SURVIVED_GAP;
        MODULE_STATUS   |= MODULE_PROGRESS_SURVIVED_GAP;
    }
    else if ((id & MODULE_TEST_MASK) == MODULE_TEST_PREFETCH_ABORT)
    {
        /* Branch outside the code region: a prefetch abort, reported through
           IFSR and IFAR.  Nothing is executed at the target -- the fault is on
           the fetch itself, so the thread never arrives.  */

        module_progress |= MODULE_PROGRESS_ATTEMPTED_JUMP;
        MODULE_STATUS   |= MODULE_PROGRESS_ATTEMPTED_JUMP;

        /* MISRA C:2012 Rule 11.1 (no conversion between a pointer to a function
           and any other type) is deliberately violated here, and Rule 11.6
           (no conversion between an integer and a pointer to void) with it.
           Provoking a fetch from an address that holds no function is the entire
           purpose of these three lines; there is no conforming way to write it. */

        ((void (*)(void)) module_forbidden_address)();

        module_progress |= MODULE_PROGRESS_SURVIVED_JUMP;
        MODULE_STATUS   |= MODULE_PROGRESS_SURVIVED_JUMP;
    }
    else
    {
        /* Read outside the data region: a data abort, reported through DFSR and
           DFAR.  */

        module_progress |= MODULE_PROGRESS_ATTEMPTED_STEAL;
        MODULE_STATUS   |= MODULE_PROGRESS_ATTEMPTED_STEAL;

        sum += *((volatile ULONG *) module_forbidden_address);

        module_progress |= MODULE_PROGRESS_SURVIVED_STEAL;
        MODULE_STATUS   |= MODULE_PROGRESS_SURVIVED_STEAL;
    }

    /* Keep the compiler from discarding the read above.  */

    module_scratch[0] = sum;

    while (1)
    {
        (void) tx_thread_sleep(100UL);
    }
}
