/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  SAMPLE MODULE                                          RELEASE        */
/*                                                                        */
/*    sample_threadx_module.c                          Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    A module that exercises the protection boundary rather than          */
/*    demonstrating features, for the Armv8-R AEM FVP.                     */
/*                                                                        */
/*    The same four steps as the S32Z280 module, because it is the same    */
/*    port under test:                                                    */
/*                                                                        */
/*      1. Writes and reads its own data, which must succeed.             */
/*      2. Makes a kernel call, which must succeed -- proving a module in  */
/*         User mode can reach the kernel through the supervisor call      */
/*         boundary and come back.                                        */
/*      3. Violates its protection in one of the two ways the hardware     */
/*         distinguishes, which must fault.                               */
/*      4. Never reaches step 4, because step 3 terminates it.            */
/*                                                                        */
/*    Steps 1 and 2 passing without step 3 faulting would mean the module  */
/*    is running unprotected, which is the failure this example exists to  */
/*    detect.  A module that only ever touched its own memory would pass   */
/*    identically with the MPU switched off.                              */
/*                                                                        */
/*    ONE DIFFERENCE FROM THE SILICON MODULE, and it is what makes this    */
/*    one testable without a person: progress is written to a shared word  */
/*    as well as to the module's own data.                                */
/*                                                                        */
/*    A module cannot print -- the console belongs to the board support    */
/*    package, outside every region a module owns, so reaching it would    */
/*    fault as surely as step 3 does.  On silicon that is answered by a    */
/*    GDB harness, which reads the module's own progress variable out of   */
/*    the data area the manager allocated for it.  The FVP has no such     */
/*    seam: it exposes an Iris server and no GDB stub, so whatever the run  */
/*    is going to report has to be reported by the image itself.           */
/*                                                                        */
/*    So the manager grants this module a shared MPU region over one       */
/*    64-byte granule at a fixed address and the module records its        */
/*    progress there, where the manager can read it back after the fault.  */
/*    The address is a constant on both sides -- the module has no loader  */
/*    to tell it anything and the manager deliberately knows no symbol of   */
/*    the module -- and the manager checks the two agree rather than       */
/*    trusting them to.                                                    */
/*                                                                        */
/*    The module's own progress variable is kept as well, unread.  It      */
/*    costs nothing, it keeps this file next to the silicon one, and it    */
/*    means the two writes are the same code path: if the shared write     */
/*    were the only one, a module that could not reach its own data would   */
/*    still report progress.                                              */
/*                                                                        */
/**************************************************************************/

#include "txm_module.h"

/* Progress, recorded in two places.  See the header: the shared copy is what
   the manager reads, and the module's own copy is what proves it could write
   its own data at all.  */

#define MODULE_PROGRESS_OWN_DATA        0x00000001UL
#define MODULE_PROGRESS_KERNEL_CALL     0x00000002UL
#define MODULE_PROGRESS_ATTEMPTED_STEAL 0x00000004UL
#define MODULE_PROGRESS_SURVIVED_STEAL  0x00000008UL
#define MODULE_PROGRESS_ATTEMPTED_JUMP  0x00000010UL
#define MODULE_PROGRESS_SURVIVED_JUMP   0x00000020UL

/* Which violation to commit, taken from the low byte of the module ID the
   manager passes to the start thread.  The rest of that word is left alone: the
   preamble ships it as 0x52520001, so a manager that sets nothing still gets a
   working data-abort test rather than a module that does nothing.  */

#define MODULE_TEST_MASK                0x000000FFUL
#define MODULE_TEST_DATA_ABORT          0x00000001UL
#define MODULE_TEST_PREFETCH_ABORT      0x00000002UL

/* The shared status word, at the base of the module area.

   A literal address rather than anything reached through the GOT, because it is
   not the module's own memory: it is memory the manager granted, and the module
   has no channel through which to be told where it is.  The same number is
   FVP_MODULE_STATUS_BASE in platform.h and ORIGIN(MODULE) in link_module.lds;
   the manager checks all three agree before it starts this module, so a
   disagreement is a reported failure rather than a fault at the first write.

   MISRA C:2012 Rule 11.6 (conversion between an integer and a pointer to void)
   is deliberately violated: an address agreed between two separately linked
   images can only be written as a literal, and there is no conforming way to
   express it.  */

#define MODULE_STATUS_ADDRESS           0x003F0000UL

#define MODULE_STATUS   (*((volatile ULONG *) MODULE_STATUS_ADDRESS))

volatile ULONG  module_progress;
volatile ULONG  module_scratch[16];

/* An address the module has no business touching, used by step 3.

   The last protection granule below the module area, which on this map is
   inside the manager's data region: that region is EL1 read/write and
   execute-never, so a User-mode read of it is a permission fault and a
   User-mode instruction fetch from it is one too.  Both are what step 3 needs,
   and both prove the KERNEL'S memory is what a module cannot reach -- which is
   the property being demonstrated, rather than the absence of a mapping.

   Held in initialised data rather than written as a literal, deliberately and
   unlike the status address above.  The module reads it through its rebased
   GOT, so the value arriving in DFAR or IFAR also proves the GOT was rewritten
   and .data was copied.  The manager knows the same number and checks it.  */

volatile ULONG  module_forbidden_address = 0x003EFFC0UL;


void demo_module_start(ULONG id)
{
    ULONG   i;
    ULONG   sum = 0UL;

    /* 1. The module's own data.  If this faults, the data region is wrong and
          nothing else in this file will be reached.  */

    for (i = 0UL; i < 16UL; i++)
    {
        module_scratch[i] = i * 3UL;
    }

    for (i = 0UL; i < 16UL; i++)
    {
        sum += module_scratch[i];
    }

    if (sum == 360UL)                       /* 3 * (0 + 1 + ... + 15) */
    {
        module_progress |= MODULE_PROGRESS_OWN_DATA;
        MODULE_STATUS   |= MODULE_PROGRESS_OWN_DATA;
    }

    /* 2. A kernel call, which leaves User mode through the supervisor call
          boundary and must come back.  A sleep is used because it is the
          simplest service with an observable effect and it yields, so the
          scheduler runs a module thread and reloads its regions on the way
          back -- exercising the region switch as well as the call.  */

    if (tx_thread_sleep(2UL) == TX_SUCCESS)
    {
        module_progress |= MODULE_PROGRESS_KERNEL_CALL;
        MODULE_STATUS   |= MODULE_PROGRESS_KERNEL_CALL;
    }

    /* 3. The violation, and 4. the flag that says it was tolerated.  Each is
          marked before the access rather than after, because after is not
          reached if the port is working.  The SURVIVED flags are what the
          manager fails on: they can only appear if the hardware allowed an
          access it was configured to refuse.  */

    if ((id & MODULE_TEST_MASK) == MODULE_TEST_PREFETCH_ABORT)
    {
        /* Branch outside the code region: a prefetch abort, reported through
           IFSR and IFAR.  Nothing is executed at the target -- the fault is on
           the fetch itself, so the thread never arrives.  */

        module_progress |= MODULE_PROGRESS_ATTEMPTED_JUMP;
        MODULE_STATUS   |= MODULE_PROGRESS_ATTEMPTED_JUMP;

        /* MISRA C:2012 Rule 11.1 (no conversion between a pointer to a function
           and any other type) is deliberately violated here, and Rule 11.6
           (no conversion between an integer and a pointer to void) with it.
           Provoking a fetch from an address that holds no function is the entire
           purpose of these three lines; there is no conforming way to write it. */

        ((void (*)(void)) module_forbidden_address)();

        module_progress |= MODULE_PROGRESS_SURVIVED_JUMP;
        MODULE_STATUS   |= MODULE_PROGRESS_SURVIVED_JUMP;
    }
    else
    {
        /* Read outside the data region: a data abort, reported through DFSR and
           DFAR.  */

        module_progress |= MODULE_PROGRESS_ATTEMPTED_STEAL;
        MODULE_STATUS   |= MODULE_PROGRESS_ATTEMPTED_STEAL;

        sum += *((volatile ULONG *) module_forbidden_address);

        module_progress |= MODULE_PROGRESS_SURVIVED_STEAL;
        MODULE_STATUS   |= MODULE_PROGRESS_SURVIVED_STEAL;
    }

    /* Keep the compiler from discarding the read above.  */

    module_scratch[0] = sum;

    while (1)
    {
        (void) tx_thread_sleep(100UL);
    }
}
