/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Codex (gpt 5.4).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

// Some portions generated by Codex (gpt 5.4).

#define TX_SOURCE_CODE
#define TX_THREAD_SMP_SOURCE_CODE

#include "tx_api.h"
#include "tx_thread.h"
#include "tx_timer.h"

#include <mmsystem.h>
#include <stdio.h>

#pragma comment (lib, "Winmm.lib")

TX_WIN32_CRITICAL_SECTION       _tx_win32_critical_section;
HANDLE                          _tx_win32_scheduler_event;
DWORD                           _tx_win32_scheduler_id;
ULONG                           _tx_win32_global_int_disabled_flag;
LARGE_INTEGER                   _tx_win32_time_stamp;
ULONG                           _tx_win32_system_error;
HANDLE                          _tx_win32_timer_handle;
HANDLE                          _tx_win32_timer_thread_handle;
DWORD                           _tx_win32_timer_thread_id;
HANDLE                          _tx_win32_isr_semaphore;
UINT                            _tx_win32_timer_waiting;
TX_THREAD_SMP_CORE_MAPPING      _tx_win32_virtual_cores[TX_THREAD_SMP_MAX_CORES];
__declspec(thread) int          _tx_win32_threadx_thread =  0;
__declspec(thread) UINT         _tx_win32_current_virtual_core =  0U;

static VOID                     _tx_win32_timer_start(VOID);
static DWORD WINAPI             _tx_win32_timer_thread_entry(LPVOID thread_input);
static UINT                     _tx_win32_smp_current_core_get_internal(DWORD thread_id);
static UINT                     _tx_win32_smp_thread_core_get(DWORD thread_id);

#ifdef TX_WIN32_DEBUG_ENABLE

#ifndef TX_WIN32_DEBUG_EVENT_SIZE
#define TX_WIN32_DEBUG_EVENT_SIZE            400
#endif

typedef struct TX_WIN32_DEBUG_ENTRY_STRUCT
{
    char                    *tx_win32_debug_entry_action;
    DWORD                   tx_win32_debug_entry_running_id;
    UINT                    tx_win32_debug_entry_core;
    LARGE_INTEGER           tx_win32_debug_entry_timestamp;
    char                    *tx_win32_debug_entry_file;
    unsigned long           tx_win32_debug_entry_line;
    TX_WIN32_CRITICAL_SECTION tx_win32_debug_entry_critical_section;
    TX_THREAD_SMP_PROTECT   tx_win32_debug_protection;
    unsigned long           tx_win32_debug_entry_int_disabled_flag;
    UINT                    tx_win32_debug_entry_preempt_disable;
    ULONG                   tx_win32_debug_entry_system_state[TX_THREAD_SMP_MAX_CORES];
    TX_THREAD               *tx_win32_debug_entry_current_thread[TX_THREAD_SMP_MAX_CORES];
    DWORD                   tx_win32_debug_entry_current_thread_id[TX_THREAD_SMP_MAX_CORES];
    TX_THREAD               *tx_win32_debug_entry_execute_thread[TX_THREAD_SMP_MAX_CORES];
    DWORD                   tx_win32_debug_entry_execute_thread_id[TX_THREAD_SMP_MAX_CORES];
} TX_WIN32_DEBUG_ENTRY;

TX_WIN32_DEBUG_ENTRY   _tx_win32_debug_entry_array[TX_WIN32_DEBUG_EVENT_SIZE];
unsigned long          _tx_win32_debug_entry_index =  0;

void  _tx_win32_debug_entry_insert(char *action, char *file, unsigned long line)
{
UINT    i;
DWORD   thread_id;

    QueryPerformanceCounter((LARGE_INTEGER *) &_tx_win32_time_stamp);
    thread_id =  GetCurrentThreadId();

    _tx_win32_debug_entry_array[_tx_win32_debug_entry_index].tx_win32_debug_entry_action =             action;
    _tx_win32_debug_entry_array[_tx_win32_debug_entry_index].tx_win32_debug_entry_core =               _tx_win32_smp_current_core_get_internal(thread_id);
    if (_tx_win32_debug_entry_array[_tx_win32_debug_entry_index].tx_win32_debug_entry_core == TX_THREAD_SMP_MAX_CORES)
    {
        _tx_win32_debug_entry_array[_tx_win32_debug_entry_index].tx_win32_debug_entry_core =  0U;
    }
    _tx_win32_debug_entry_array[_tx_win32_debug_entry_index].tx_win32_debug_entry_timestamp =          _tx_win32_time_stamp;
    _tx_win32_debug_entry_array[_tx_win32_debug_entry_index].tx_win32_debug_entry_file =               file;
    _tx_win32_debug_entry_array[_tx_win32_debug_entry_index].tx_win32_debug_entry_line =               line;
    _tx_win32_debug_entry_array[_tx_win32_debug_entry_index].tx_win32_debug_protection =               _tx_thread_smp_protection;
    _tx_win32_debug_entry_array[_tx_win32_debug_entry_index].tx_win32_debug_entry_preempt_disable =    _tx_thread_preempt_disable;
    _tx_win32_debug_entry_array[_tx_win32_debug_entry_index].tx_win32_debug_entry_critical_section =   _tx_win32_critical_section;
    _tx_win32_debug_entry_array[_tx_win32_debug_entry_index].tx_win32_debug_entry_int_disabled_flag =  _tx_win32_global_int_disabled_flag;
    _tx_win32_debug_entry_array[_tx_win32_debug_entry_index].tx_win32_debug_entry_running_id =         thread_id;

    for (i = 0U; i < TX_THREAD_SMP_MAX_CORES; i++)
    {
        _tx_win32_debug_entry_array[_tx_win32_debug_entry_index].tx_win32_debug_entry_system_state[i] = _tx_thread_system_state[i];
        _tx_win32_debug_entry_array[_tx_win32_debug_entry_index].tx_win32_debug_entry_current_thread[i] = _tx_thread_current_ptr[i];
        if (_tx_thread_current_ptr[i] != TX_NULL)
        {
            _tx_win32_debug_entry_array[_tx_win32_debug_entry_index].tx_win32_debug_entry_current_thread_id[i] =
                _tx_thread_current_ptr[i] -> tx_thread_win32_thread_id;
        }
        else
        {
            _tx_win32_debug_entry_array[_tx_win32_debug_entry_index].tx_win32_debug_entry_current_thread_id[i] =  0U;
        }

        _tx_win32_debug_entry_array[_tx_win32_debug_entry_index].tx_win32_debug_entry_execute_thread[i] = _tx_thread_execute_ptr[i];
        if (_tx_thread_execute_ptr[i] != TX_NULL)
        {
            _tx_win32_debug_entry_array[_tx_win32_debug_entry_index].tx_win32_debug_entry_execute_thread_id[i] =
                _tx_thread_execute_ptr[i] -> tx_thread_win32_thread_id;
        }
        else
        {
            _tx_win32_debug_entry_array[_tx_win32_debug_entry_index].tx_win32_debug_entry_execute_thread_id[i] =  0U;
        }
    }

    _tx_win32_debug_entry_index++;
    if (_tx_win32_debug_entry_index >= TX_WIN32_DEBUG_EVENT_SIZE)
    {
        _tx_win32_debug_entry_index =  0U;
    }
}

#endif


void  _tx_timer_interrupt(void);
VOID  _tx_thread_context_save(VOID);
VOID  _tx_thread_context_restore(VOID);
VOID  _tx_win32_timer_interrupt(VOID);


VOID  _tx_initialize_low_level(VOID)
{
UINT        i;
TIMECAPS    tc;
UINT        timer_resolution;

    _tx_initialize_unused_memory =  malloc(TX_WIN32_MEMORY_SIZE);
    _tx_win32_scheduler_id =       GetCurrentThreadId();

    _tx_win32_critical_section.tx_win32_critical_section_mutex_handle =  CreateMutex(NULL, FALSE, NULL);
    _tx_win32_critical_section.tx_win32_critical_section_nested_count =  0U;
    _tx_win32_critical_section.tx_win32_critical_section_owner =         0U;
    if (_tx_win32_critical_section.tx_win32_critical_section_mutex_handle == NULL)
    {
        printf("ThreadX SMP Win64 error creating critical section mutex!\n");
        while (1)
        {
        }
    }

    _tx_win32_scheduler_event =      CreateEvent(NULL, FALSE, FALSE, NULL);
    _tx_win32_isr_semaphore =        CreateSemaphore(NULL, 0, 0x7FFFFFFF, NULL);
    if ((_tx_win32_scheduler_event == NULL) ||
        (_tx_win32_isr_semaphore == NULL))
    {
        printf("ThreadX SMP Win64 error creating semaphores!\n");
        while (1)
        {
        }
    }

    for (i = 0U; i < TX_THREAD_SMP_MAX_CORES; i++)
    {
        _tx_win32_virtual_cores[i].tx_thread_smp_core_mapping_thread_handle = NULL;
        _tx_win32_virtual_cores[i].tx_thread_smp_core_mapping_thread_id =     0U;
        _tx_win32_virtual_cores[i].tx_thread_smp_core_mapping_thread =        TX_NULL;
    }

    _tx_win32_global_int_disabled_flag =  TX_FALSE;
    _tx_win32_timer_waiting =             0U;

    if (timeGetDevCaps(&tc, sizeof(TIMECAPS)) != TIMERR_NOERROR)
    {
        printf("ThreadX SMP Win64 error querying timer resolution!\n");
        while (1)
        {
        }
    }

    timer_resolution = (UINT) min(max(tc.wPeriodMin, TX_TIMER_PERIODIC), tc.wPeriodMax);
    if (timeBeginPeriod(timer_resolution) != TIMERR_NOERROR)
    {
        printf("ThreadX SMP Win64 error configuring timer resolution!\n");
        while (1)
        {
        }
    }

    _tx_win32_timer_handle =  CreateWaitableTimer(NULL, FALSE, NULL);
    if (_tx_win32_timer_handle == NULL)
    {
        printf("ThreadX SMP Win64 error creating timer handle!\n");
        while (1)
        {
        }
    }

    _tx_win32_timer_thread_handle =  CreateThread(NULL, 0, _tx_win32_timer_thread_entry, NULL, 0, &_tx_win32_timer_thread_id);
    if (_tx_win32_timer_thread_handle == NULL)
    {
        printf("ThreadX SMP Win64 error creating timer thread!\n");
        while (1)
        {
        }
    }

    SetThreadPriority(GetCurrentThread(), TX_WIN32_PRIORITY_SCHEDULE);
    SetThreadPriority(_tx_win32_timer_thread_handle, TX_WIN32_PRIORITY_ISR);
}


void  _tx_initialize_start_interrupts(void)
{
    _tx_win32_timer_start();
}


void  _tx_win32_critical_section_obtain(TX_WIN32_CRITICAL_SECTION *critical_section)
{
DWORD       thread_id;
LONG        previous_owner;

    thread_id =  GetCurrentThreadId();

    if (critical_section -> tx_win32_critical_section_owner == thread_id)
    {
        critical_section -> tx_win32_critical_section_nested_count++;
    }
    else
    {
        do
        {
            previous_owner =  InterlockedCompareExchange((LONG *) &(critical_section -> tx_win32_critical_section_owner), (LONG) thread_id, 0L);

            if (previous_owner != 0L)
            {
                Sleep(0);
            }
        } while (previous_owner != 0L);

        critical_section -> tx_win32_critical_section_nested_count =  1U;
    }
}


void  _tx_win32_critical_section_release(TX_WIN32_CRITICAL_SECTION *critical_section)
{
DWORD       thread_id;

    thread_id =  GetCurrentThreadId();

    if (critical_section -> tx_win32_critical_section_owner == thread_id)
    {
        if (critical_section -> tx_win32_critical_section_nested_count != 0U)
        {
            critical_section -> tx_win32_critical_section_nested_count--;

            if (critical_section -> tx_win32_critical_section_nested_count == 0U)
            {
                InterlockedExchange((LONG *) &(critical_section -> tx_win32_critical_section_owner), 0L);
            }
        }
    }
    else
    {
        _tx_win32_system_error++;
    }
}


void  _tx_win32_critical_section_release_all(TX_WIN32_CRITICAL_SECTION *critical_section)
{
DWORD       thread_id;
    
    thread_id =  GetCurrentThreadId();

    if (critical_section -> tx_win32_critical_section_owner == thread_id)
    {
        if (critical_section -> tx_win32_critical_section_nested_count != 0U)
        {
            critical_section -> tx_win32_critical_section_nested_count =  0U;
            InterlockedExchange((LONG *) &(critical_section -> tx_win32_critical_section_owner), 0L);
        }
    }
    else
    {
        _tx_win32_system_error++;
    }
}


UINT  _tx_win32_smp_current_core_get(void)
{
UINT    core;
DWORD   thread_id;
UINT    critical_section_owned;

    thread_id =  GetCurrentThreadId();
    critical_section_owned =  (UINT) (_tx_win32_critical_section.tx_win32_critical_section_owner == thread_id);

    if (critical_section_owned == TX_FALSE)
    {
        _tx_win32_critical_section_obtain(&_tx_win32_critical_section);
    }

    if (_tx_win32_threadx_thread != 0)
    {
        core =  _tx_win32_smp_thread_core_get(thread_id);

        if (core == TX_THREAD_SMP_MAX_CORES)
        {
            core =  _tx_win32_current_virtual_core;
        }
        else
        {
            _tx_win32_current_virtual_core =  core;
        }
    }
    else
    {
        core =  _tx_win32_smp_current_core_get_internal(thread_id);
        if (core == TX_THREAD_SMP_MAX_CORES)
        {
            core =  0U;
        }
    }

    if (critical_section_owned == TX_FALSE)
    {
        _tx_win32_critical_section_release(&_tx_win32_critical_section);
    }

    return(core);
}


static UINT  _tx_win32_smp_thread_core_get(DWORD thread_id)
{
UINT        core;
UINT        i;
TX_THREAD   *thread_ptr;

    core =  TX_THREAD_SMP_MAX_CORES;

    for (i = 0U; i < TX_THREAD_SMP_MAX_CORES; i++)
    {
        if (_tx_win32_virtual_cores[i].tx_thread_smp_core_mapping_thread_id == thread_id)
        {
            core =  i;
            break;
        }
    }

    if (core == TX_THREAD_SMP_MAX_CORES)
    {
        for (i = 0U; i < TX_THREAD_SMP_MAX_CORES; i++)
        {
            thread_ptr =  _tx_thread_current_ptr[i];
            if ((thread_ptr != TX_NULL) && (thread_ptr -> tx_thread_win32_thread_id == thread_id))
            {
                core =  i;
                break;
            }
        }
    }

    return(core);
}


static UINT  _tx_win32_smp_current_core_get_internal(DWORD thread_id)
{
UINT    core;
UINT    i;
TX_THREAD *thread_ptr;

    core =  _tx_win32_smp_thread_core_get(thread_id);

    if (core == TX_THREAD_SMP_MAX_CORES)
    {
        for (i = 0U; i < TX_THREAD_SMP_MAX_CORES; i++)
        {
            thread_ptr =  _tx_thread_execute_ptr[i];
            if ((thread_ptr != TX_NULL) && (thread_ptr -> tx_thread_win32_thread_id == thread_id))
            {
                core =  i;
                break;
            }
        }
    }

    return(core);
}


void  _tx_win32_thread_suspend(HANDLE thread_handle)
{
    if (SuspendThread(thread_handle) == (DWORD) -1)
    {
        _tx_win32_system_error++;
        while (1)
        {
        }
    }
}


void  _tx_win32_thread_resume(HANDLE thread_handle)
{
    DWORD suspend_count;

    do
    {
        suspend_count =  ResumeThread(thread_handle);
        if (suspend_count == (DWORD) -1)
        {
            _tx_win32_system_error++;
            while (1)
            {
            }
        }
    } while (suspend_count > 1U);
}


void  _tx_win32_thread_sleep(ULONG milliseconds)
{
    if (milliseconds == 0U)
    {
        milliseconds =  1U;
    }

    Sleep((DWORD) milliseconds);
}


void  _tx_win32_semaphore_reset(HANDLE semaphore_handle)
{
    while (WaitForSingleObject(semaphore_handle, 0) == WAIT_OBJECT_0)
    {
    }
}


static DWORD WINAPI  _tx_win32_timer_thread_entry(LPVOID thread_input)
{
    TX_PARAMETER_NOT_USED(thread_input);

    while (1)
    {
        WaitForSingleObject(_tx_win32_timer_handle, INFINITE);
        _tx_win32_timer_interrupt();
        _tx_win32_timer_start();
    }
}


VOID  _tx_win32_timer_interrupt(VOID)
{
    _tx_thread_context_save();
    _tx_timer_interrupt();
    _tx_thread_context_restore();
}


static VOID  _tx_win32_timer_start(VOID)
{
LARGE_INTEGER   due_time;

    due_time.QuadPart =  -(((LONGLONG) TX_TIMER_PERIODIC) * 10000LL);
    if (SetWaitableTimer(_tx_win32_timer_handle, &due_time, 0, NULL, NULL, FALSE) == 0)
    {
        printf("ThreadX SMP Win64 error starting timer!\n");
        while (1)
        {
        }
    }
}
