#!/usr/bin/env python3
#
# Copyright (c) 2026-present Eclipse ThreadX contributors
# SPDX-License-Identifier: MIT
# Some portions generated by Claude Code (Opus 5).
#
"""Run a Cortex-R52 image on the Armv8-R AEM FVP and assert its result.

This runner is deliberately much simpler than the RISC-V/QEMU one, because
the platform allows it: the FVP exposes only an Iris server and no GDB stub,
so there is nothing to script through a debugger, and every image terminates
itself with a semihosting SYS_EXIT.  The runner therefore just launches the
model, captures its console, and judges the self-reported result.

A missing result line is treated as FAILURE, never as success: a silent hang
or a crash before the first check must not be able to masquerade as a pass.
"""

import argparse
import subprocess
import sys

PASS_MARK = "ALL CHECKS PASSED"
FAIL_MARK = "RESULT: FAILED"
FAULT_MARK = "[FAULT]"


def as_text(stream):
    """Normalise a captured stream to str.

    subprocess.TimeoutExpired carries its partial output undecoded even when
    the call used text=True, so the timeout path can hand us bytes where the
    normal path hands us str.  Decoding defensively here keeps the hang
    report readable instead of raising TypeError inside the error handler.
    """
    if stream is None:
        return ""
    if isinstance(stream, bytes):
        return stream.decode(errors="replace")
    return stream


def run(elf, fvp, timeout):
    command = [
        fvp,
        "-C", "cluster0.NUM_CORES=1",
        "-C", "bp.vis.disable_visualisation=1",
        "-C", "bp.terminal_0.start_telnet=0",
        "-a", elf,
    ]

    print("Running:", " ".join(command), flush=True)

    try:
        completed = subprocess.run(
            command, capture_output=True, text=True, timeout=timeout
        )
        output = as_text(completed.stdout) + as_text(completed.stderr)
    except subprocess.TimeoutExpired as expired:
        print(as_text(expired.stdout) + as_text(expired.stderr))
        print(
            f"FAIL: the simulation did not terminate within {timeout}s. "
            "Every image is expected to exit through semihosting SYS_EXIT, "
            "so this is a hang, not a slow run.",
            file=sys.stderr,
        )
        return 1

    print(output)

    if FAULT_MARK in output:
        faults = [line for line in output.splitlines() if FAULT_MARK in line]
        print("FAIL: unhandled exception reported:", file=sys.stderr)
        for line in faults:
            print("   " + line.strip(), file=sys.stderr)
        return 1

    if FAIL_MARK in output:
        print("FAIL: the image reported failing checks.", file=sys.stderr)
        return 1

    if PASS_MARK not in output:
        print(
            "FAIL: no result line found. The image neither passed nor "
            "reported failure, so it did not reach its checks.",
            file=sys.stderr,
        )
        return 1

    print("PASS")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--elf", required=True, help="image to run")
    parser.add_argument("--fvp", default="FVP_BaseR_AEMv8R", help="model binary")
    parser.add_argument(
        "--timeout", type=int, default=180, help="seconds before declaring a hang"
    )
    arguments = parser.parse_args()

    return run(arguments.elf, arguments.fvp, arguments.timeout)


if __name__ == "__main__":
    sys.exit(main())
