;/***************************************************************************
; * Copyright (c) 2024 Microsoft Corporation
; * Copyright (c) 2026 Eclipse ThreadX contributors
; *
; * This program and the accompanying materials are made available under the
; * terms of the MIT License which is available at
; * https://opensource.org/licenses/MIT.
; *
; * SPDX-License-Identifier: MIT
; **************************************************************************/
; Some portions generated by Copilot (Opus 5).
;
;
;/**************************************************************************/
;/**************************************************************************/
;/**                                                                       */
;/** ThreadX Component                                                     */
;/**                                                                       */
;/**   Thread - Low Level SMP Support                                      */
;/**                                                                       */
;/**************************************************************************/
;/**************************************************************************/
;
;
;#define TX_SOURCE_CODE
;#define TX_THREAD_SMP_SOURCE_CODE
;
;/* Include necessary system files.  */
;
;#include "tx_api.h"
;#include "tx_thread.h"
;#include "tx_timer.h"
;
;


    IMPORT     _tx_thread_current_ptr
    IMPORT     _tx_thread_smp_protection

        AREA ||.text||, CODE, READONLY
        PRESERVE8
;/**************************************************************************/
;/*                                                                        */
;/*  FUNCTION                                               RELEASE        */
;/*                                                                        */
;/*    _tx_thread_smp_protect                          SMP/Cortex-A9/AC5   */
;/*                                                            6.1         */
;/*  AUTHOR                                                                */
;/*                                                                        */
;/*    William E. Lamie, Microsoft Corporation                             */
;/*                                                                        */
;/*  DESCRIPTION                                                           */
;/*                                                                        */
;/*    This function gets protection for running inside the ThreadX        */
;/*    source. This is acomplished by a combination of a test-and-set      */
;/*    flag and periodically disabling interrupts.                         */
;/*                                                                        */
;/*  INPUT                                                                 */
;/*                                                                        */
;/*    None                                                                */
;/*                                                                        */
;/*  OUTPUT                                                                */
;/*                                                                        */
;/*    Previous Status Register                                            */
;/*                                                                        */
;/*  CALLS                                                                 */
;/*                                                                        */
;/*    None                                                                */
;/*                                                                        */
;/*  CALLED BY                                                             */
;/*                                                                        */
;/*    ThreadX Source                                                      */
;/*                                                                        */
;/**************************************************************************/
    EXPORT  _tx_thread_smp_protect
_tx_thread_smp_protect
;VOID  _tx_thread_smp_protect(VOID)
;{
;
;    /* Disable interrupts so we don't get preempted.  */
;
    MRS     r3, CPSR                            ; Pickup current CPSR

    IF  :DEF:TX_ENABLE_FIQ_SUPPORT
    CPSID   if                                  ; Disable IRQ and FIQ interrupts
    ELSE
    CPSID   i                                   ; Disable IRQ interrupts
    ENDIF
;
;    /* Pickup the CPU ID.  */
;
    MRC     p15, 0, r2, c0, c0, 5               ; Read CPU ID register
    AND     r2, r2, #0x03                       ; Mask off, leaving the CPU ID field
;
;    /* Do we already have protection?  */
;    if (this_core == _tx_thread_smp_protection.tx_thread_smp_protect_core)
;    {
;
    LDR     r0, =_tx_thread_smp_protection      ; Build address to protection structure
    LDR     r1, [r0, #8]                        ; Pickup the owning core
    CMP     r1, r2                              ; Is it this core?
    BEQ     _owned                              ; Yes, the protection is already owned
;
;    }
;
;    /* Is the lock available?  */
;    if (_tx_thread_smp_protection.tx_thread_smp_protect_in_force == 0)
;    {
;
    LDREX   r1, [r0]                            ; Pickup the protection flag
    CMP     r1, #0                              ; Is it available?
    BEQ     _get_protection                     ; Yes, attempt to get the protection
;
;    }
;
;    /* The protection is held elsewhere. Restore interrupts so this core can be
;       preempted while it waits, then try the whole sequence again.  */
;
    MSR     CPSR_c, r3                          ; Restore CPSR
    IF  :DEF:TX_ENABLE_WFE
    WFE                                         ; Go into standby
    ENDIF
    B       _tx_thread_smp_protect              ; On waking, restart the protection attempt

_get_protection
;
;    /* Try to get the lock.  */
;    if (write_exclusive(&_tx_thread_smp_protection.tx_thread_smp_protect_in_force, 1) == SUCCESS)
;    {
;
    MOV     r1, #1                              ; Build lock value
    STREX   r2, r1, [r0]                        ; Attempt to get the protection
    CMP     r2, #0                              ; Check whether the store succeeded (0 = success)
    BEQ     _got_protection                     ; Yes, we have the protection
;
;    }
;
;    /* Another core beat us to it. Restore interrupts and try again.  */
;
    MSR     CPSR_c, r3                          ; Restore CPSR
    B       _tx_thread_smp_protect              ; Try the whole process again

_got_protection
;
;    /* Got the lock. Record the owning core.  */
;    _tx_thread_smp_protection.tx_thread_smp_protect_core = this_core;
;
    DMB                                         ; Ensure the protection write completes before it is used
    MRC     p15, 0, r2, c0, c0, 5               ; Read CPU ID register
    AND     r2, r2, #0x03                       ; Mask off, leaving the CPU ID field
    STR     r2, [r0, #8]                        ; Save the owning core

    IF  :DEF:TX_MPCORE_DEBUG_ENABLE
    LSL     r2, r2, #2                          ; Build offset to array indexes
    LDR     r1, =_tx_thread_current_ptr         ; Pickup start of the current thread array
    ADD     r1, r1, r2                          ; Build index into the current thread array
    LDR     r2, [r1]                            ; Pickup current thread for this core
    STR     r2, [r0, #4]                        ; Save current thread pointer
    STR     LR, [r0, #16]                       ; Save caller's return address
    STR     r3, [r0, #20]                       ; Save CPSR
    ENDIF

_owned
;
;    /* Increment the protection count.  */
;    _tx_thread_smp_protection.tx_thread_smp_protect_count++;
;
    LDR     r1, [r0, #12]                       ; Pickup ownership count
    ADD     r1, r1, #1                          ; Increment ownership count
    STR     r1, [r0, #12]                       ; Store new ownership count
    DMB                                         ;

    MOV     r0, r3                              ; Return the previous CPSR
;
;}
;
    IF  {INTER} = {TRUE}
    BX      lr                                  ; Return to caller
    ELSE
    MOV     pc, lr                              ; Return to caller
    ENDIF

    END
