#!/usr/bin/env bash
# /***************************************************************************/
# /* Copyright (C) 2026 Eclipse ThreadX contributors
#  *
#  * This program and the accompanying materials are made available under the
#  * terms of the MIT License which is available at
#  * https://opensource.org/licenses/MIT.
#  *
#  * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
#  * The AI-generated portions may be considered public domain (CC0-1.0)
#  * and not subject to the project's licence.
#  *
#  * SPDX-License-Identifier: MIT AND CC0-1.0
#  ***************************************************************************/

# install_deps.sh -- Install Linux build/debug dependencies for the CORE-V MCU ThreadX port.
#
# Supported: Ubuntu 20.04 / 22.04 / 24.04 and Debian derivatives.
# Run as a regular user; sudo is invoked internally where needed.
#
# Usage:
#   bash install_deps.sh

set -euo pipefail

die()  { echo "[ERROR] $*" >&2; exit 1; }
info() { echo "[INFO]  $*"; }

command -v apt-get >/dev/null 2>&1 || die "This script requires apt-get (Ubuntu/Debian)."

PACKAGES=(
    cmake
    ninja-build
    gcc-riscv64-unknown-elf
    binutils-riscv64-unknown-elf
    gdb-multiarch
    openocd
    usbutils
    git
)

info "Updating package lists ..."
sudo apt-get update -qq

info "Installing: ${PACKAGES[*]}"
sudo apt-get install -y "${PACKAGES[@]}"

info ""
info "All dependencies installed."
info ""
info "Next steps:"
info "  1. Run scripts/setup_opella.sh to configure udev rules for the Ashling Opella LD."
info "  2. (WSL only) Follow the usbipd-win instructions printed by setup_opella.sh."
