/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

#ifndef GPIO_H
#define GPIO_H

#include <stdint.h>

/* PULP GPIO register offsets */
#define GPIO_DIR_OFFSET    0x000U
#define GPIO_EN_OFFSET     0x004U
#define GPIO_IN_OFFSET     0x008U
#define GPIO_OUT_OFFSET    0x00CU
#define GPIO_SET_OFFSET    0x010U
#define GPIO_CLR_OFFSET    0x014U
#define GPIO_TOGGLE_OFFSET 0x018U

void gpio_init(void);
void gpio_set_output(uint32_t pin_mask);
void gpio_toggle(uint32_t pin_mask);
void gpio_set(uint32_t pin_mask);
void gpio_clear(uint32_t pin_mask);

#endif /* GPIO_H */
