/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

#ifndef SYSTEM_CORE_V_MCU_H
#define SYSTEM_CORE_V_MCU_H

#include <stdint.h>

extern void (*isr_table[32])(void);
extern volatile uint32_t system_core_clock;

void system_init(void);
void tx_trap_handler(uint32_t mcause, uint32_t mepc, uint32_t mtval);
void tx_timer_irq_handler(void);
void tx_undefined_irq_handler(void);

#endif /* SYSTEM_CORE_V_MCU_H */
