/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

#ifndef TEMP_SENSOR_H
#define TEMP_SENSOR_H

#include <stdint.h>

/* Read ADT7420 temperature sensor on I2CM1 (Nexys A7 on-board sensor).
 * Returns temperature in tenths of degrees Celsius (e.g. 213 = 21.3°C).
 * Returns INT16_MIN on I2C error. */
int16_t temp_read_celsius_x10(void);

/* Initialize the temperature sensor I2C channel. Call once at startup. */
void temp_sensor_init(void);

#endif /* TEMP_SENSOR_H */
