/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

#ifndef TIMER_IRQ_H
#define TIMER_IRQ_H

#include <stdint.h>

int timer_irq_init(uint32_t ticks);
int timer_irq_set_timeout(uint32_t ticks);
uint32_t timer_irq_clock_elapsed(void);
uint32_t timer_irq_cycle_get_32(void);

#endif /* TIMER_IRQ_H */
