/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026-present Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/

// Some portions generated by Claude Code (Opus 5).


/**************************************************************************/
/**************************************************************************/
/**                                                                       */
/** ThreadX Component                                                     */
/**                                                                       */
/**   Module                                                              */
/**                                                                       */
/**************************************************************************/
/**************************************************************************/


/**************************************************************************/
/*                                                                        */
/*  APPLICATION INTERFACE DEFINITION                       RELEASE        */
/*                                                                        */
/*    txm_module_port.h                                 Cortex-R52/GNU    */
/*                                                           6.1.10       */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Scott Larson, Microsoft Corporation                                 */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    This file defines the basic module constants, interface structures, */
/*    and function prototypes.                                            */
/*                                                                        */
/**************************************************************************/

#ifndef TXM_MODULE_PORT_H
#define TXM_MODULE_PORT_H

/* Determine if the optional Modules user define file should be used.  */

#ifdef TXM_MODULE_INCLUDE_USER_DEFINE_FILE

/* Yes, include the user defines in txm_module_user.h. The defines in this file may
   alternately be defined on the command line.  */

#include "txm_module_user.h"
#endif

/* It is assumed that the base ThreadX tx_port.h file has been modified to add the
  following extensions to the ThreadX thread control block (this code should replace
  the corresponding macro define in tx_port.h):

#define TX_THREAD_EXTENSION_2                   VOID    *tx_thread_module_instance_ptr;         \
                                                VOID    *tx_thread_module_entry_info_ptr;       \
                                                ULONG   tx_thread_module_current_user_mode;     \
                                                ULONG   tx_thread_module_user_mode;             \
                                                ULONG   tx_thread_module_saved_lr;              \
                                                VOID    *tx_thread_module_kernel_stack_start;   \
                                                VOID    *tx_thread_module_kernel_stack_end;     \
                                                ULONG   tx_thread_module_kernel_stack_size;     \
                                                VOID    *tx_thread_module_stack_ptr;            \
                                                VOID    *tx_thread_module_stack_start;          \
                                                VOID    *tx_thread_module_stack_end;            \
                                                ULONG   tx_thread_module_stack_size;            \
                                                VOID    *tx_thread_module_reserved;

The following extensions must also be defined in tx_port.h:

#define TX_EVENT_FLAGS_GROUP_EXTENSION          VOID    *tx_event_flags_group_module_instance; \
                                                VOID   (*tx_event_flags_group_set_module_notify)(struct TX_EVENT_FLAGS_GROUP_STRUCT *group_ptr);

#define TX_QUEUE_EXTENSION                      VOID    *tx_queue_module_instance; \
                                                VOID   (*tx_queue_send_module_notify)(struct TX_QUEUE_STRUCT *queue_ptr);

#define TX_SEMAPHORE_EXTENSION                  VOID    *tx_semaphore_module_instance; \
                                                VOID   (*tx_semaphore_put_module_notify)(struct TX_SEMAPHORE_STRUCT *semaphore_ptr);

#define TX_TIMER_EXTENSION                      VOID    *tx_timer_module_instance; \
                                                VOID   (*tx_timer_module_expiration_function)(ULONG id);
*/

/* Define the kernel stack size for a module thread.  */
#ifndef TXM_MODULE_KERNEL_STACK_SIZE
#define TXM_MODULE_KERNEL_STACK_SIZE            768
#endif

/* Define constants specific to the tools the module can be built with for this particular modules port.  */

#define TXM_MODULE_IAR_COMPILER                 0x00000000
#define TXM_MODULE_RVDS_COMPILER                0x01000000
#define TXM_MODULE_GNU_COMPILER                 0x02000000
#define TXM_MODULE_COMPILER_MASK                0xFF000000
#define TXM_MODULE_OPTIONS_MASK                 0x000000FF


/* Define the properties for this particular module port.  */

/* No port dispatch.  It exists so a port can service kernel requests specific to
   it, and this one has none: the only calls the Armv8-M port dispatches are its
   secure-stack allocate and free, which belong to the security extension this core
   does not have.  Defining it would have the module manager call a
   _txm_module_manager_port_dispatch that does not exist.  The Cortex-R4 module
   port leaves it undefined for the same reason.  */

/* #define TXM_MODULE_PORT_DISPATCH */

#define TXM_MODULE_MEMORY_PROTECTION_ENABLED

#ifdef  TXM_MODULE_MEMORY_PROTECTION_ENABLED
#define TXM_MODULE_REQUIRE_ALLOCATED_OBJECT_MEMORY
#else
#define TXM_MODULE_REQUIRE_LOCAL_OBJECT_MEMORY
#endif

#define TXM_MODULE_USER_MODE                        0x00000001
#define TXM_MODULE_MEMORY_PROTECTION                0x00000002
#define TXM_MODULE_SHARED_EXTERNAL_MEMORY_ACCESS    0x00000004


/* Define the supported options for this module.

   TXM_MODULE_SHARED_EXTERNAL_MEMORY_ACCESS is supported and optional: a module
   that does not ask for it simply never has a shared region granted to it, and
   everything else about it works.

   TXM_MODULE_USER_MODE and TXM_MODULE_MEMORY_PROTECTION are supported and
   REQUIRED, together, which every other module port in the tree leaves at 0.
   The divergence is a property of PMSAv8-R rather than a policy choice, and the
   alternative is not a module that runs unprotected -- it is a module that
   cannot run at all:

     - TXM_MODULE_MANAGER_MODULE_SETUP below programs the eight-entry region
       table only when both bits are set, so for any other accepted combination
       the table stays as the load memset it, all zeros.

     - tx_thread_schedule.S closes the kernel's window over the module area
       before it dispatches a module thread, because PMSAv8-R has no region
       priority and the window covers the same memory the module's own regions
       do.  A zeroed table therefore leaves nothing enabled over module memory.

     - There is no background region to fall back on.  Per the Cortex-R52 TRM
       section 8.2.1, the EL1-controlled background region is used only when the
       MPU is disabled or when SCTLR.BR is set, and accesses from EL0 are
       faulted whenever the MPU is enabled.  Neither example board support
       package sets SCTLR.BR, and a board that did would still not help a
       User-mode module.

   So a module asking for user mode without protection, or for neither, is
   accepted by the portable loader, started, and aborts on the fetch of its own
   first instruction.  Requiring both bits turns that into
   TXM_MODULE_INVALID_PROPERTIES from txm_module_manager_in_place_load, at the
   point where the property word can still be corrected.

   Supporting them for real -- a privileged module mapped through the kernel's
   window, or an unprotected User-mode module -- needs a second mapping path in
   the scheduler and its own tests.  Until that exists this is the honest
   contract rather than a restriction.  */

#define TXM_MODULE_MANAGER_SUPPORTED_OPTIONS    (TXM_MODULE_USER_MODE | TXM_MODULE_MEMORY_PROTECTION | TXM_MODULE_SHARED_EXTERNAL_MEMORY_ACCESS)
#define TXM_MODULE_MANAGER_REQUIRED_OPTIONS     (TXM_MODULE_USER_MODE | TXM_MODULE_MEMORY_PROTECTION)


/* Define offset adjustments according to the compiler used to build the module.  */

#define TXM_MODULE_IAR_SHELL_ADJUST             24
#define TXM_MODULE_IAR_START_ADJUST             28
#define TXM_MODULE_IAR_STOP_ADJUST              32
#define TXM_MODULE_IAR_CALLBACK_ADJUST          44

#define TXM_MODULE_RVDS_SHELL_ADJUST            0
#define TXM_MODULE_RVDS_START_ADJUST            0
#define TXM_MODULE_RVDS_STOP_ADJUST             0
#define TXM_MODULE_RVDS_CALLBACK_ADJUST         0

#define TXM_MODULE_GNU_SHELL_ADJUST             24
#define TXM_MODULE_GNU_START_ADJUST             28
#define TXM_MODULE_GNU_STOP_ADJUST              32
#define TXM_MODULE_GNU_CALLBACK_ADJUST          44


/* Define other module port-specific constants.  */

/* Define INLINE_DECLARE to inline for ARM compiler.  */

#define INLINE_DECLARE inline

/* Define the number of MPU entries assigned to the code and data sections.

   PMSAv8-R gives this core many more regions than Armv8-M gives an M33, and that
   changes the design rather than just the numbers.  MPUIR on the S32Z280 reports
   20 EL1 regions, where an M33 has 8 in total and the kernel and a module must
   therefore share them.  Here the kernel's map can keep its own regions
   permanently and the manager owns a separate block, so a module switch
   reprograms only the module's regions and never rebuilds the kernel's.

   Eight entries are reserved, laid out as on the M33 -- one for the kernel entry
   function, one for module code, one for module data, five for shared memory --
   starting at TXM_MODULE_MPU_FIRST_REGION.  The indices below are relative to
   that base.

   TXM_MODULE_MPU_FIRST_REGION is 8, and the choice is not arbitrary.  The TRM
   provides direct access to PRBAR0 through PRBAR15 and PRLAR0 through PRLAR15
   at CP15 op1 0, encoded CRn c6, CRm 0b1rrr where rrr is region_number[3:1],
   opc2 0 and 1 for an even region and 4 and 5 for an odd one.  Regions 16
   through 24 have direct encodings as well, at op1 1 with the same CRm and opc2
   rule (8.4, Table 8-9), so no region on this core is reachable only through
   PRSELR.  PRSELR remains the indirect route: it selects a region for the
   unnumbered PRBAR and PRLAR view and needs an ISB before those can be written,
   per region.

   The TRM contradicts itself on this and the disagreement is worth recording,
   so that a reader who checks only one half does not correct it back.  The
   register descriptions at 3.3.85 and 3.3.86 say flatly "Direct access is
   provided to PRBAR0 to PRBAR15" and give only the op1 0 form; 8.4 and Table
   8-9 give both forms.  Table 8-9 is itself imprecise -- it prints opc2 0 for
   the even limit registers where the prose of 8.4 says 1 -- so the op1 1
   encoding has to be proven on the part before anything relies on it.

   What 8 through 15 buys is that all eight regions sit in the op1 0 range, the
   form already exercised on this part, and that they are contiguous, so a
   module switch writes them as one unrolled block with a single barrier pair.
   Measured on this part: programming one region through PRSELR costs 542 to 604
   cycles, and the same region written directly costs 434 to 470.  Most of what
   remains is the closing dsb and isb rather than the writes, so a block of
   regions written directly with one barrier pair at the end is far cheaper than
   the per-region figure suggests, while the PRSELR route pays an ISB every time.

   The board support package's map occupies 0 through 7.  A board needing more
   than eight kernel regions has to either shrink this block or move it, and
   moving it past 15 changes the op1 the scheduler's MCR encodings carry.  */

#define TXM_MODULE_MPU_FIRST_REGION             8
#define TXM_MODULE_MPU_TOTAL_ENTRIES            8
#define TXM_MODULE_MPU_KERNEL_ENTRY_INDEX       0
#define TXM_MODULE_MPU_CODE_INDEX               1
#define TXM_MODULE_MPU_DATA_INDEX               2

#define TXM_MODULE_MPU_SHARED_INDEX             3
#define TXM_MODULE_MPU_SHARED_ENTRIES           5

#define TXM_MODULE_ATTRIBUTE_NON_SHAREABLE      0x00
#define TXM_MODULE_ATTRIBUTE_OUTER_SHAREABLE    0x10
#define TXM_MODULE_ATTRIBUTE_INNER_SHAREABLE    0x18
#define TXM_MODULE_ATTRIBUTE_READ_WRITE         0x02
#define TXM_MODULE_ATTRIBUTE_READ_ONLY          0x06
#define TXM_MODULE_ATTRIBUTE_EXECUTE_NEVER      0x01
#define TXM_MODULE_ATTRIBUTE_REGION_ENABLE      0x01
#define TXM_MODULE_ATTRIBUTE_MASK               0x1E
#define TXM_MODULE_ATTRIBUTE_INDEX              0x00

/* The attribute encodings above are the PMSAv8 field layout and are the same on
   this core as on an M33: shareability in PRBAR[4:3], access permission in
   PRBAR[2:1], execute-never in PRBAR[0], attribute index in PRLAR[3:1] and the
   region enable in PRLAR[0].  What differs is the granule -- 64 bytes here
   against 32 on Armv8-M, so the base and limit fields are [31:6] rather than
   [31:5] -- and that the registers are reached through CP15, either by a
   region's own direct encoding or through PRSELR, rather than being memory
   mapped.  */

/* MAIR_ATTR settings
Device-nGnRE : 0b [Outer]0000 [Inner]0100
Code WT   RA : 0b [Outer]1010 [Inner]1010
DATA WBWA RA : 0b [Outer]1111 [Inner]1111
*/

/* Data aligned to 8 bytes (stacks must be 8-byte aligned).  */
#define TXM_MODULE_DATA_ALIGNMENT               8

/* MPU regions must be 64-byte aligned on PMSAv8-R, where Armv8-M requires 32.
   Getting this wrong is silent: the low bits of PRBAR and PRLAR hold attributes,
   so an under-aligned base does not fault, it changes the shareability and
   permissions of the region instead.

   Unsigned, and that is not decoration.  Every use of this macro is a mask over
   an address or a size -- both ULONG -- and the useful form is the complement,
   ~(TXM_MODULE_MPU_ALIGNMENT - 1).  Spelled as a plain 64 that complement is a
   signed -64 converted to 0xFFFFFFC0 on the way into the expression, which is
   what MISRA C:2012 Rule 7.2 requires a U suffix to prevent and what
   -Wsign-conversion reports.  The value is identical either way here; the
   suffix is what keeps the essential type of the mask unsigned.  */
#define TXM_MODULE_MPU_ALIGNMENT                64UL

/* Mask that keeps only the address bits of PRBAR and PRLAR.  The low six bits
   hold attributes on this core, so every base and limit written into the region
   table must be masked with this and not with the Armv8-M 32-byte equivalent.  */

#define TXM_MODULE_MPU_ADDRESS_MASK             0xFFFFFFC0

/* No secure-stack extension calls.  Those are the Armv8-M security extension,
   which this core does not have: privilege here is the ARM mode, EL1 against
   EL0, and there is no secure world to allocate a second stack in.  */

/* Two registers set up each MPU region: PRBAR and PRLAR, reached either by the
   region's own direct encoding or through PRSELR.
   Held per module so a switch is a sequence of register writes with nothing to
   compute -- the cost measured on this part is dominated by the barriers, not
   the writes, so a switch should program every region and issue one dsb and isb
   at the end rather than a pair per region.  */
typedef struct TXM_MODULE_MPU_INFO_STRUCT
{
    ULONG   txm_module_mpu_region_base_address;
    ULONG   txm_module_mpu_region_limit_address;
} TXM_MODULE_MPU_INFO;

/* Define the port-extensions to the module manager instance structure.  */
#define TXM_MODULE_MANAGER_PORT_EXTENSION                                                               \
    TXM_MODULE_MPU_INFO     txm_module_instance_mpu_registers[TXM_MODULE_MPU_TOTAL_ENTRIES];            \
    ULONG                   txm_module_instance_shared_memory_count;                                    \
    ULONG                   txm_module_instance_shared_memory_address[TXM_MODULE_MPU_SHARED_ENTRIES];   \
    ULONG                   txm_module_instance_shared_memory_length[TXM_MODULE_MPU_SHARED_ENTRIES];


/* Define the memory fault information structure that is populated when a memory fault occurs.  */

typedef struct TXM_MODULE_MANAGER_MEMORY_FAULT_INFO_STRUCT
{
    TX_THREAD           *txm_module_manager_memory_fault_info_thread_ptr;
    VOID                *txm_module_manager_memory_fault_info_code_location;
    /* Fault status and address, read through CP15.  Armv8-M reports a memory
       fault in SHCSR, CFSR, MMFAR and BFAR; this core splits it by access type
       instead -- DFSR and DFAR for a data abort, IFSR and IFAR for a prefetch
       abort -- and both pairs are recorded because a module can fault either
       way: writing outside its data region, or branching outside its code
       region.  */

    ULONG               txm_module_manager_memory_fault_info_dfsr;
    ULONG               txm_module_manager_memory_fault_info_dfar;
    ULONG               txm_module_manager_memory_fault_info_ifsr;
    ULONG               txm_module_manager_memory_fault_info_ifar;
    ULONG               txm_module_manager_memory_fault_info_sp;
    ULONG               txm_module_manager_memory_fault_info_r0;
    ULONG               txm_module_manager_memory_fault_info_r1;
    ULONG               txm_module_manager_memory_fault_info_r2;
    ULONG               txm_module_manager_memory_fault_info_r3;
    ULONG               txm_module_manager_memory_fault_info_r4;
    ULONG               txm_module_manager_memory_fault_info_r5;
    ULONG               txm_module_manager_memory_fault_info_r6;
    ULONG               txm_module_manager_memory_fault_info_r7;
    ULONG               txm_module_manager_memory_fault_info_r8;
    ULONG               txm_module_manager_memory_fault_info_r9;
    ULONG               txm_module_manager_memory_fault_info_r10;
    ULONG               txm_module_manager_memory_fault_info_r11;
    ULONG               txm_module_manager_memory_fault_info_r12;
    ULONG               txm_module_manager_memory_fault_info_lr;
    /* SPSR rather than xPSR: the mode the faulting code was running in is what
       says whether it was the module in user mode or the kernel.  */

    ULONG               txm_module_manager_memory_fault_info_spsr;
} TXM_MODULE_MANAGER_MEMORY_FAULT_INFO;


#define TXM_MODULE_MANAGER_FAULT_INFO                                               \
    TXM_MODULE_MANAGER_MEMORY_FAULT_INFO    _txm_module_manager_memory_fault_info;


/* Define the macro to check the code alignment.  */

#define TXM_MODULE_MANAGER_CHECK_CODE_ALIGNMENT(module_location, code_alignment)    \
    {                                                                               \
        ULONG   temp;                                                               \
        temp =  (ULONG) module_location;                                            \
        temp =  temp & (code_alignment - 1);                                        \
        if (temp)                                                                   \
        {                                                                           \
            _tx_mutex_put(&_txm_module_manager_mutex);                              \
            return(TXM_MODULE_ALIGNMENT_ERROR);                                     \
        }                                                                           \
    }


/* Define the macro to adjust the alignment and size for code/data areas.  */

#define TXM_MODULE_MANAGER_ALIGNMENT_ADJUST(module_preamble, code_size, code_alignment, data_size, data_alignment)   _txm_module_manager_alignment_adjust(module_preamble, &code_size, &code_alignment, &data_size, &data_alignment);


/* Define the macro to adjust the symbols in the module preamble.  */

#define TXM_MODULE_MANAGER_CALCULATE_ADJUSTMENTS(properties, shell_function_adjust, start_function_adjust, stop_function_adjust, callback_function_adjust) \
    if ((properties & TXM_MODULE_COMPILER_MASK) == TXM_MODULE_IAR_COMPILER)         \
    {                                                                               \
        shell_function_adjust =     TXM_MODULE_IAR_SHELL_ADJUST;                    \
        start_function_adjust =     TXM_MODULE_IAR_START_ADJUST;                    \
        stop_function_adjust =      TXM_MODULE_IAR_STOP_ADJUST;                     \
        callback_function_adjust =  TXM_MODULE_IAR_CALLBACK_ADJUST;                 \
    }                                                                               \
    else if ((properties & TXM_MODULE_COMPILER_MASK) == TXM_MODULE_RVDS_COMPILER)   \
    {                                                                               \
        shell_function_adjust =     TXM_MODULE_RVDS_SHELL_ADJUST;                   \
        start_function_adjust =     TXM_MODULE_RVDS_START_ADJUST;                   \
        stop_function_adjust =      TXM_MODULE_RVDS_STOP_ADJUST;                    \
        callback_function_adjust =  TXM_MODULE_RVDS_CALLBACK_ADJUST;                \
    }                                                                               \
    else                                                                            \
    {                                                                               \
        shell_function_adjust =     TXM_MODULE_GNU_SHELL_ADJUST;                    \
        start_function_adjust =     TXM_MODULE_GNU_START_ADJUST;                    \
        stop_function_adjust =      TXM_MODULE_GNU_STOP_ADJUST;                     \
        callback_function_adjust =  TXM_MODULE_GNU_CALLBACK_ADJUST;                 \
    }


/* Define the macro to populate the thread control block with module port-specific information.
   Check if the module is in user mode and set up txm_module_thread_entry_info_kernel_call_dispatcher accordingly.
*/

#define TXM_MODULE_MANAGER_THREAD_SETUP(thread_ptr, module_instance)                                                                    \
    thread_ptr -> tx_thread_module_current_user_mode =  module_instance -> txm_module_instance_property_flags & TXM_MODULE_USER_MODE;   \
    thread_ptr -> tx_thread_module_user_mode =          module_instance -> txm_module_instance_property_flags & TXM_MODULE_USER_MODE;   \
    if (thread_ptr -> tx_thread_module_user_mode)                                                                                       \
    {                                                                                                                                   \
        thread_entry_info -> txm_module_thread_entry_info_kernel_call_dispatcher =   _txm_module_manager_user_mode_entry;               \
    }                                                                                                                                   \
    else                                                                                                                                \
    {                                                                                                                                   \
        thread_entry_info -> txm_module_thread_entry_info_kernel_call_dispatcher =   _txm_module_manager_kernel_dispatch;               \
    }


/* Define the macro to populate the module control block with module port-specific information.
   If memory protection is enabled, set up the MPU registers.

   TXM_MODULE_MANAGER_REQUIRED_OPTIONS makes both tests below true for every
   module the loader accepts, so the nesting is redundant today.  It is kept
   because it is the only thing that decides whether the region table is
   programmed: a future port that learned to map a privileged module would relax
   REQUIRED_OPTIONS, and this macro is where the second path would go.
*/
#define TXM_MODULE_MANAGER_MODULE_SETUP(module_instance)                                            \
    if (module_instance -> txm_module_instance_property_flags & TXM_MODULE_USER_MODE)               \
    {                                                                                               \
        if (module_instance -> txm_module_instance_property_flags & TXM_MODULE_MEMORY_PROTECTION)   \
        {                                                                                           \
            _txm_module_manager_mm_register_setup(module_instance);                                 \
        }                                                                                           \
    }                                                                                               \
    else                                                                                            \
    {                                                                                               \
        /* Do nothing.  */                                                                          \
    }

/* Define the macro to perform port-specific functions when unloading the module.  */
/* Nothing needs to be done for this port.  */
#define TXM_MODULE_MANAGER_MODULE_UNLOAD(module_instance)


/* Define the macros to perform port-specific checks when passing pointers to the kernel.  */

/* Define macro to make sure object is inside the module's data.  */
#define TXM_MODULE_MANAGER_CHECK_INSIDE_DATA(module_instance, obj_ptr, obj_size) \
    _txm_module_manager_inside_data_check(module_instance, obj_ptr, obj_size)

/* Define some internal prototypes to this module port.  */

#ifndef TX_SOURCE_CODE
#define txm_module_manager_memory_fault_notify              _txm_module_manager_memory_fault_notify
#endif


#ifdef TX_SOURCE_CODE

#endif

#define TXM_MODULE_MANAGER_ADDITIONAL_PROTOTYPES                                                                                \
VOID  _txm_module_manager_alignment_adjust(TXM_MODULE_PREAMBLE *module_preamble, ULONG *code_size, ULONG *code_alignment, ULONG *data_size, ULONG *data_alignment);   \
VOID  _txm_module_manager_memory_fault_handler(VOID);                                                                           \
UINT  _txm_module_manager_memory_fault_notify(VOID (*notify_function)(TX_THREAD *, TXM_MODULE_INSTANCE *));                     \
VOID  _txm_module_manager_mm_register_setup(TXM_MODULE_INSTANCE *module_instance);                                              \
UINT  _txm_module_manager_inside_data_check(TXM_MODULE_INSTANCE *module_instance, ALIGN_TYPE obj_ptr, UINT obj_size);           \
ALIGN_TYPE _txm_module_manager_port_dispatch(TXM_MODULE_INSTANCE *module_instance, ULONG kernel_request, ALIGN_TYPE param_0, ALIGN_TYPE param_1, ALIGN_TYPE param_2);


#define TXM_MODULE_MANAGER_VERSION_ID   \
CHAR                            _txm_module_manager_version_id[] =  \
                                    "Copyright (c) 2024 Microsoft Corporation. * ThreadX Module Cortex-R52/GNU Version 6.5.0.202601 *";

#endif
