#!/bin/bash
##############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT and CC0-1.0
##############################################################################

# Builds the sample image for the AArch64 port this script sits in. Run
# build_threadx.sh first, which produces tx.a.
#
#     ./build_threadx_sample.sh
#     TOOLCHAIN=atfe ATFE_CLANG=/path/to/clang ./build_threadx_sample.sh
#
# The sample targets a fixed virtual platform: a GICv3 interrupt controller and
# an SP804 timer at the Base platform addresses. It is not expected to run on
# other models or on hardware without changing those addresses.

set -eu

cd "$(dirname "$(realpath "$0")")"

core="$(basename "$(cd ../.. && pwd)")"
case "${core}" in
    *_smp) cpu="${core%_smp}"; common="common_smp" ;;
    *)     cpu="${core}";      common="common" ;;
esac
cpu="${cpu//_/-}"

: "${TOOLCHAIN:=gnu}"
case "${TOOLCHAIN}" in
    gnu)
        CC="aarch64-none-elf-gcc"
        TARGET_FLAGS=""
        # rdimon supplies the semihosting syscalls and, with them, the real
        # initialise_monitor_handles that startup.S calls.
        SYSCALL_LIB="--specs=rdimon.specs"
        SEMIHOST_STUB=""
        # crti.o defines _init and _fini; crtn.o closes them. The link below
        # passes -nostartfiles, which is right for a port with its own reset
        # path but also drops these two, and startup.S calls
        # __libc_init_array, whose newlib implementation calls _init. Without
        # them every AArch64 sample failed to link:
        #
        #   libg.a(libc_a-init.o): in function `__libc_init_array':
        #       undefined reference to `_init'
        #   relocation truncated to fit: R_AARCH64_CALL26 against undefined
        #       symbol `_init'
        #
        # crti.o must precede every other .init contribution and crtn.o must
        # follow all of them, which is why they bracket the object list rather
        # than sitting with the other flags. The AArch32 scripts need none of
        # this: they use nosys.specs and never reach __libc_init_array.
        CRT_BEGIN="$("${CC}" -mcpu="${cpu}" -print-file-name=crti.o)"
        CRT_END="$("${CC}" -mcpu="${cpu}" -print-file-name=crtn.o)"
        ;;
    atfe)
        CC="${ATFE_CLANG:-clang}"
        TARGET_FLAGS="--target=aarch64-none-elf"
        SYSCALL_LIB="-lsemihost"
        # picolibc has no initialise_monitor_handles, and neither does the
        # toolchain's semihosting library, so the weak stub stands in for it.
        SEMIHOST_STUB="sample_threadx/semihost_stub.S"
        # Deliberately empty. picolibc's __libc_init_array does not call _init,
        # so these images link today and adding crti.o would change a working
        # link for no reason.
        CRT_BEGIN=""
        CRT_END=""
        ;;
    *)
        echo "Unknown TOOLCHAIN '${TOOLCHAIN}'; expected gnu or atfe" >&2
        exit 1
        ;;
esac

CFLAGS="-g -mcpu=${cpu} -I../../../../${common}/inc -I../inc -Isample_threadx"

echo "Building the sample for ${cpu} with ${TOOLCHAIN}"

objects=""
for src in sample_threadx/startup.S sample_threadx/vectors.S \
           sample_threadx/v8_aarch64.S sample_threadx/v8_utils.S \
           sample_threadx/MP_Mutexes.S ${SEMIHOST_STUB} \
           sample_threadx/GICv3_gicd.c sample_threadx/GICv3_gicr.c \
           sample_threadx/sp804_timer.c sample_threadx/timer_interrupts.c \
           sample_threadx/sample_threadx.c; do
    [ -n "${src}" ] || continue
    obj="$(basename "${src}")"
    obj="${obj%.*}.o"
    "${CC}" ${TARGET_FLAGS} -c ${CFLAGS} "${src}" -o "${obj}"
    objects="${objects} ${obj}"
done

"${CC}" ${TARGET_FLAGS} -g -mcpu="${cpu}" -nostartfiles \
    -T sample_threadx/sample_threadx.ld ${SYSCALL_LIB} \
    -o sample_threadx.out -Wl,-Map=sample_threadx.map \
    ${CRT_BEGIN} ${objects} tx.a ${CRT_END}

rm -f ${objects}

echo "Done: $(basename "$(pwd)")/sample_threadx.out"
