/***************************************************************************
 * Copyright (C) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

#include <stdint.h>

#include "pulp_mem_map.h"
#include "io.h"
#include "gpio.h"

void gpio_init(void)
{
    /* GPIO clocking is handled by platform boot code on CORE-V MCU. */
}

void gpio_set_output(uint32_t pin_mask)
{
    uint32_t value = readw((uintptr_t)(PULP_GPIO_ADDR + GPIO_DIR_OFFSET));

    writew(value | pin_mask, (uintptr_t)(PULP_GPIO_ADDR + GPIO_DIR_OFFSET));
}

void gpio_toggle(uint32_t pin_mask)
{
    uint32_t value = readw((uintptr_t)(PULP_GPIO_ADDR + GPIO_OUT_OFFSET));

    writew(value ^ pin_mask, (uintptr_t)(PULP_GPIO_ADDR + GPIO_OUT_OFFSET));
}

void gpio_set(uint32_t pin_mask)
{
    writew(pin_mask, (uintptr_t)(PULP_GPIO_ADDR + GPIO_SET_OFFSET));
}

void gpio_clear(uint32_t pin_mask)
{
    writew(pin_mask, (uintptr_t)(PULP_GPIO_ADDR + GPIO_CLR_OFFSET));
}
