/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This test asks the timer information service for the time remaining on a
   timer whose entry sits behind the current position in the timer list.

   The active timer list is a ring of TX_TIMER_ENTRIES slots and the current
   pointer walks it one slot a tick, wrapping at the end. A timer activated for
   close to a full lap lands on a slot the current pointer has already passed,
   and the service then has to count the distance in two parts -- from the start
   of the list to the timer's slot, and from the current position to the end.
   That is the arm this test drives.

   Which slot a timer lands on is decided by where the current pointer happens
   to be when it is activated, so an ordinary timer test reaches this arm only
   when the two coincide. Here the position is read first and the activation is
   chosen from it, both inside one SMP protection so the tick cannot move the
   pointer in between, and the geometry is asserted before the service is
   called. The assertion is on the arrangement rather than on the answer: the
   two arms compute the same number of ticks by design, so a test that only
   checked the returned count would pass without reaching either one in
   particular.  */


#include   <stdio.h>
#include   "tx_api.h"
#define    TX_SOURCE_CODE
#include   "tx_timer.h"


#define TEST_PRIORITY               16

/* A timer activated for a whole lap of the list lands one slot behind the
   current position, wherever that position is.  */

#define WRAPPED_TICKS               TX_TIMER_ENTRIES

/* The same, for a timer carrying more ticks than the list can hold: the service
   adds the laps it cannot represent to the distance it measures.  */

#define WRAPPED_LONG_TICKS          (TX_TIMER_ENTRIES + ((ULONG) 8))

/* A timer activated for one tick lands on the current position itself, which is
   the arm the wrapped one is being distinguished from.  */

#define AHEAD_TICKS                 ((ULONG) 1)

/* The current pointer is at the start of the list for one tick in
   TX_TIMER_ENTRIES, and no slot is behind it there. One tick's wait is enough
   to move it; the rest of the budget is so that a tick that never arrives fails
   the test rather than hanging it.  */

#define POSITION_ATTEMPTS           ((UINT) 8)


static unsigned long   thread_0_counter =  0;
static TX_THREAD       thread_0;

static TX_TIMER        timer_0;
static unsigned long   timer_0_counter =  0;


/* Define thread prototypes.  */

static void    thread_0_entry(ULONG thread_input);


/* Prototype for test control return.  */

void  test_control_return(UINT status);


/* The timer is deactivated before it can expire, so this only runs if the test
   is held off for longer than a lap of the list.  */

static void  timer_0_entry(ULONG timer_input)
{

    timer_0_counter++;
}


/* Activate the timer for the given number of ticks and interrogate it, with the
   whole arrangement held under one SMP protection so that the current pointer
   cannot move between the activation that places the timer and the service that
   measures the distance to it.

   `behind` says which side of the current pointer the timer's slot has to land
   on. The check is made before the service is called, so the arm the service
   then takes is known rather than inferred from what it returned.  */

static UINT  drive_one_arm(ULONG ticks, UINT behind, ULONG *ticks_left)
{

TX_INTERRUPT_SAVE_AREA

UINT                status;
UINT                active;
CHAR               *name;
ULONG               reschedule_ticks;
TX_TIMER           *next_timer;
TX_TIMER_INTERNAL **list_head;


    TX_DISABLE

    /* No slot is behind the current pointer when it is at the start of the
       list. Report that, so the caller waits a tick and asks again.  */
    if ((behind == TX_TRUE) && (_tx_timer_current_ptr == _tx_timer_list_start))
    {

        TX_RESTORE
        return(TX_NOT_DONE);
    }

    status =  tx_timer_change(&timer_0, ticks, ((ULONG) 0));

    if (status == TX_SUCCESS)
    {

        status =  tx_timer_activate(&timer_0);
    }

    if (status == TX_SUCCESS)
    {

        list_head =  timer_0.tx_timer_internal.tx_timer_internal_list_head;

        /* The timer has to be on the active list at all, and on the side of the
           current pointer the caller asked for.  */
        if ((list_head < _tx_timer_list_start) || (list_head >= _tx_timer_list_end))
        {

            status =  TX_NOT_DONE;
        }
        else if (behind == TX_TRUE)
        {

            if (list_head >= _tx_timer_current_ptr)
            {

                status =  TX_NOT_DONE;
            }
        }
        else
        {

            if (list_head < _tx_timer_current_ptr)
            {

                status =  TX_NOT_DONE;
            }
        }
    }

    if (status == TX_SUCCESS)
    {

        status =  tx_timer_info_get(&timer_0, &name, &active, ticks_left,
                        &reschedule_ticks, &next_timer);

        if ((status == TX_SUCCESS) && (active != TX_TRUE))
        {

            status =  TX_NOT_DONE;
        }
    }

    /* Leave the timer inactive, whatever happened, so the next attempt starts
       from the state this one did.  */
    (VOID) tx_timer_deactivate(&timer_0);

    TX_RESTORE

    return(status);
}


/* Drive one arm, waiting a tick and asking again while the current pointer is
   somewhere the arrangement cannot be built.  */

static UINT  drive_arm_with_retry(ULONG ticks, UINT behind, ULONG *ticks_left)
{

UINT    attempt;
UINT    status =  TX_NOT_DONE;


    for (attempt = ((UINT) 0); attempt < POSITION_ATTEMPTS; attempt++)
    {

        status =  drive_one_arm(ticks, behind, ticks_left);

        if (status != TX_NOT_DONE)
        {

            break;
        }

        tx_thread_sleep(((ULONG) 1));
    }

    return(status);
}


static void    thread_0_entry(ULONG thread_input)
{

UINT    status;
ULONG   ticks_left;


    /* Increment thread 0 counter.  */
    thread_0_counter++;

    /* Inform user of success getting to this test.  */
    printf("Running Timer Wrapped List Test................................... ");

    /* The timer's slot is the current position: the service measures the
       distance forwards and this is the arm the wrapped one is not.  */
    status =  drive_arm_with_retry(AHEAD_TICKS, TX_FALSE, &ticks_left);

    if (status != TX_SUCCESS)
    {

        printf("ERROR #2\n");
        test_control_return(1);
    }

    if (ticks_left != AHEAD_TICKS)
    {

        printf("ERROR #3\n");
        test_control_return(1);
    }

    /* A whole lap of the list puts the timer's slot one behind the current
       position, so the service measures the distance in two parts.  */
    status =  drive_arm_with_retry(WRAPPED_TICKS, TX_TRUE, &ticks_left);

    if (status != TX_SUCCESS)
    {

        printf("ERROR #4\n");
        test_control_return(1);
    }

    if (ticks_left != WRAPPED_TICKS)
    {

        printf("ERROR #5\n");
        test_control_return(1);
    }

    /* The same slot, with more ticks on the timer than the list can represent,
       so the service adds the remainder of the last full pass to it.  */
    status =  drive_arm_with_retry(WRAPPED_LONG_TICKS, TX_TRUE, &ticks_left);

    if (status != TX_SUCCESS)
    {

        printf("ERROR #6\n");
        test_control_return(1);
    }

    if (ticks_left != WRAPPED_LONG_TICKS)
    {

        printf("ERROR #7\n");
        test_control_return(1);
    }

    /* The timer never expired, which is what says the measurements above were
       taken on a timer that was still waiting.  */
    if (timer_0_counter != 0)
    {

        printf("ERROR #8\n");
        test_control_return(1);
    }

    /* Success!  */
    printf("SUCCESS!\n");
    test_control_return(0);
}


/* Define what the initial system looks like.  */

#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void    threadx_timer_wrapped_list_application_define(void *first_unused_memory)
#endif
{

UINT    status;
CHAR    *pointer;


    /* Put first available memory address into a character pointer.  */
    pointer =  (CHAR *) first_unused_memory;

    status =  tx_thread_create(&thread_0, "thread 0", thread_0_entry, 0,
            pointer, TEST_STACK_SIZE_PRINTF,
            TEST_PRIORITY, TEST_PRIORITY, TX_NO_TIME_SLICE, TX_AUTO_START);
    pointer =  pointer + TEST_STACK_SIZE_PRINTF;

    /* Check for status.  */
    if (status != TX_SUCCESS)
    {

        printf("Running Timer Wrapped List Test................................... ERROR #1\n");
        test_control_return(1);
    }

    /* The timer the test activates and interrogates. It is created inactive and
       every attempt leaves it that way.  */
    status =  tx_timer_create(&timer_0, "timer 0", timer_0_entry, 0,
            WRAPPED_TICKS, ((ULONG) 0), TX_NO_ACTIVATE);

    /* Check for status.  */
    if (status != TX_SUCCESS)
    {

        printf("Running Timer Wrapped List Test................................... ERROR #1\n");
        test_control_return(1);
    }
}
