/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This test drives the byte pool search's multiple block search limit.

   The SMP search walks the pool holding the protection and gives it up every
   TX_BYTE_POOL_MULTIPLE_BLOCK_SEARCH blocks, so that a long walk does not lock
   every other core out for its whole duration. Reaching the release therefore
   needs a single search that examines more blocks than that limit, which needs
   a pool broken into more fragments than the limit counts.

   The monoprocessor search gives the protection up on every block and has no
   counter, so this region exists only in common_smp and there is no
   monoprocessor test to port. The limit is not a feature gate: tx_api.h defines
   it to 20 unless the application overrides it, so the region is compiled in
   all eight configurations and the test reads the constant rather than
   repeating the number.

   The pool is filled with small fragments until it refuses another one, which
   leaves it with more fragments than the limit and no free block large enough
   to satisfy a further request. The request that follows therefore walks every
   fragment in the pool and crosses the limit several times over. The walk
   length is a property of the pool rather than of timing: nothing else runs
   here, and the search examines the pool's fragments plus one.  */


#include   <stdio.h>
#include   "tx_api.h"


/* The pool is sized so that fragments of BYTE_CHUNK_SIZE break it into
   comfortably more than the search limit. Each fragment costs its own header as
   well as its bytes, which is why the pool is larger than the product of the
   two numbers below.  */

#define BYTE_POOL_SIZE                  2048
#define BYTE_CHUNK_SIZE                 24
#define BYTE_CHUNKS_MAX                 64

/* The walk has to cross the limit rather than just reach it, so the test
   insists on a pool fragmented to twice the limit before it draws any
   conclusion from the search that follows.  */

#define BYTE_CHUNKS_REQUIRED            (2 * TX_BYTE_POOL_MULTIPLE_BLOCK_SEARCH)


static unsigned long   thread_0_counter =  0;
static TX_THREAD       thread_0;

static TX_BYTE_POOL    pool_0;
static UCHAR           pool_0_memory[BYTE_POOL_SIZE];

/* One spare slot: the fill loop can use every one of BYTE_CHUNKS_MAX, and the
   request that follows it needs somewhere to point.  */

static VOID            *chunks[BYTE_CHUNKS_MAX + 1];


/* Define thread prototypes.  */

static void    thread_0_entry(ULONG thread_input);


/* Prototype for test control return.  */

void  test_control_return(UINT status);


/* Define what the initial system looks like.  */

#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void    threadx_byte_pool_multiple_block_search_application_define(void *first_unused_memory)
#endif
{

UINT    status;
CHAR    *pointer;


    /* Put first available memory address into a character pointer.  */
    pointer =  (CHAR *) first_unused_memory;

    /* Put system definition stuff in here, e.g. thread creates and other assorted
       create information.  */
    status =  tx_thread_create(&thread_0, "thread 0", thread_0_entry, 1,
            pointer, TEST_STACK_SIZE_PRINTF,
            16, 16, TX_NO_TIME_SLICE, TX_AUTO_START);
    pointer =  pointer + TEST_STACK_SIZE_PRINTF;

    /* Check for status.  */
    if (status != TX_SUCCESS)
    {

        printf("Running Byte Pool Multiple Block Search Test....................... ERROR #1\n");
        test_control_return(1);
    }

    /* Create the pool the search is driven against.  */
    status =  tx_byte_pool_create(&pool_0, "pool 0", pool_0_memory, sizeof(pool_0_memory));

    /* Check for status.  */
    if (status != TX_SUCCESS)
    {

        printf("Running Byte Pool Multiple Block Search Test....................... ERROR #2\n");
        test_control_return(1);
    }
}


/* Define the test thread.  */

static void    thread_0_entry(ULONG thread_input)
{

UINT    status;
UINT    chunk;
UINT    allocated;


    /* Increment thread 0 counter.  */
    thread_0_counter++;

    /* Inform user of success getting to this test.  */
    printf("Running Byte Pool Multiple Block Search Test....................... ");

    /* Break the pool into fragments, one allocation at a time, until it has no
       room for another.  */
    allocated =  0;

    for (chunk = 0; chunk < BYTE_CHUNKS_MAX; chunk++)
    {

        if (tx_byte_allocate(&pool_0, &chunks[chunk], BYTE_CHUNK_SIZE, TX_NO_WAIT) != TX_SUCCESS)
        {

            /* The pool is full.  */
            break;
        }

        allocated++;
    }

    /* The walk the next request performs is as long as the pool has fragments,
       so a pool that did not break into enough of them would leave the limit
       unreached and the rest of the test proving nothing.  */
    if (allocated < BYTE_CHUNKS_REQUIRED)
    {

        printf("ERROR #3\n");
        test_control_return(1);
    }

    /* Ask for one more fragment. Every block in the pool is either in use or
       too small, so the search examines all of them and gives the protection up
       once per limit's worth of blocks on the way.  */
    status =  tx_byte_allocate(&pool_0, &chunks[allocated], BYTE_CHUNK_SIZE, TX_NO_WAIT);

    if (status != TX_NO_MEMORY)
    {

        printf("ERROR #4\n");
        test_control_return(1);
    }

    /* Give the pool back, so the test leaves the system as it found it.  */
    for (chunk = 0; chunk < allocated; chunk++)
    {

        if (tx_byte_release(chunks[chunk]) != TX_SUCCESS)
        {

            printf("ERROR #5\n");
            test_control_return(1);
        }
    }

    /* Everything came back, so the pool is whole and a full-sized request that
       could not have been met a moment ago now can be.  */
    status =  tx_byte_allocate(&pool_0, &chunks[0], BYTE_CHUNK_SIZE * BYTE_CHUNKS_REQUIRED, TX_NO_WAIT);

    if (status != TX_SUCCESS)
    {

        printf("ERROR #6\n");
        test_control_return(1);
    }

    status =  tx_byte_release(chunks[0]);

    if (status != TX_SUCCESS)
    {

        printf("ERROR #7\n");
        test_control_return(1);
    }

    printf("SUCCESS!\n");
    test_control_return(0);
}
