/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    board.h                                          Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Interface between the S32Z280 reset path and the C code it enters,  */
/*    plus the layout of the structure a debugger reads to confirm what   */
/*    the core reported about itself.                                     */
/*                                                                        */
/*    Field order here is load-bearing: the debug script reads the        */
/*    structure by offset, so members must not be reordered without       */
/*    updating tools/read_identity.gdb alongside.                         */
/*                                                                        */
/**************************************************************************/

#ifndef BOARD_H
#define BOARD_H

/* Written to r52_identity.magic only after every other field is set, so a
   reader can tell a complete structure from a half-filled one.  */

#define R52_IDENTITY_MAGIC              0x52520001UL

/* What the core reports about itself.  EL2-only registers are captured by
   entry.S before the drop to EL1; the rest are read in bsp_main.  */

typedef struct r52_identity_struct
{
    unsigned int    magic;
    unsigned int    midr;               /* expect part 0xD13 = Cortex-R52   */
    unsigned int    mpuir;              /* EL1 MPU, DREGION in bits [15:8]  */
    unsigned int    ctr;
    unsigned int    mpidr;
    unsigned int    id_pfr0;
    unsigned int    id_pfr1;            /* virtualisation field => EL2      */
    unsigned int    sctlr_el1;          /* MPU and cache enables as found   */
    unsigned int    hmpuir_el2;         /* EL2 MPU, captured at EL2         */
    unsigned int    cntfrq_el2;         /* recorded, not programmed         */
    unsigned int    cpsr_el2;           /* mode bits should read 0x1A, Hyp  */
    unsigned int    cpsr_el1;           /* mode bits should read 0x13, SVC  */
    unsigned int    mpu_regions_el1;    /* decoded from mpuir               */
    unsigned int    console_status;     /* linflexd_init() result, 0 = OK    */
} r52_identity_t;

extern r52_identity_t   r52_identity;

/* Entered from entry.S once EL1 is set up; never returns.  Declared here to
   satisfy MISRA Rule 8.4, which entry.S cannot do for itself.  */

void    bsp_main(void);

/* Breakpoint target for the debug script; reached once r52_identity is
   complete.  Declared here so it has a prototype (MISRA Rule 8.4).  */

void    bsp_done(void);

/* SCTLR as it reads after mpu_init(); M should be set.                   */

unsigned int    read_sctlr_after_mpu(void);

#endif /* BOARD_H */
