/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    bsp_boot.c                                       Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    First-boot verification for the NXP S32Z280-594EVB.  Records what   */
/*    the core reports about itself into a structure a debugger reads.    */
/*                                                                        */
/*    There is no console on this board yet: LIN9 reaches the host through*/
/*    the daughtercard USB-UART, but its baud rate depends on clock       */
/*    configuration that is not yet established, and a console that prints*/
/*    at the wrong rate produces garbage indistinguishable from a crash.  */
/*    So this milestone reports through memory instead, which cannot be   */
/*    mis-configured.  The console arrives in the next step.              */
/*                                                                        */
/*    Only EL1-accessible registers are read here.  EL2-only ones         */
/*    (HMPUIR, CNTFRQ) are captured by entry.S before the drop to EL1,    */
/*    because reading them at EL1 would trap rather than return a value.  */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                   */
/*                                                                        */
/*    Dir 4.3 -- assembly language shall be encapsulated and isolated.    */
/*      Each MRC is wrapped in its own single-statement static function   */
/*      below, which is the encapsulation the directive asks for.  There  */
/*      is no other way to read a coprocessor register from C.            */
/*                                                                        */
/*    Rule 8.4 -- bsp_main is called from assembly and so has no C caller */
/*      to provide a prototype; it is declared in board.h, which entry.S  */
/*      cannot include.                                                   */
/*                                                                        */
/**************************************************************************/

#include "board.h"
#include "platform.h"
#include "linflexd.h"
#include "timer.h"
#include "gic_probe.h"
#include "mpu.h"

/* Captured at EL2 by entry.S, before the drop to EL1.                    */

extern unsigned int  boot_stage;
extern unsigned int  cpsr_at_el2;
extern unsigned int  cpsr_at_el1;
extern unsigned int  cntfrq_at_el2;
extern unsigned int  hmpuir_at_el2;
extern unsigned int  probe_stage;

/* Mirror of the console markers into memory.  The UART has twice gone away at
   the moment a marker mattered -- once when a stalled access took the debug
   connection down with it, once when the USB passthrough detached -- and a
   stalled access records no fault, so boot_stage alone cannot say how far the
   risky sequence got.  This can be read post-mortem without a console.  */

#define MARK(n)     do { probe_stage = (unsigned int)(n); } while (0)

/* Filled in below and read by the debugger.  Not static: the whole point is
   for something outside this translation unit to find it.  */

r52_identity_t  r52_identity;


/* One MRC per function, each isolated, per MISRA Dir 4.3.                */

static unsigned int read_midr(void)
{
    unsigned int value;
    __asm volatile ("mrc p15, 0, %0, c0, c0, 0" : "=r" (value));
    return value;
}

static unsigned int read_mpuir(void)
{
    unsigned int value;
    __asm volatile ("mrc p15, 0, %0, c0, c0, 4" : "=r" (value));
    return value;
}

static unsigned int read_ctr(void)
{
    unsigned int value;
    __asm volatile ("mrc p15, 0, %0, c0, c0, 1" : "=r" (value));
    return value;
}

static unsigned int read_mpidr(void)
{
    unsigned int value;
    __asm volatile ("mrc p15, 0, %0, c0, c0, 5" : "=r" (value));
    return value;
}

static unsigned int read_id_pfr0(void)
{
    unsigned int value;
    __asm volatile ("mrc p15, 0, %0, c0, c1, 0" : "=r" (value));
    return value;
}

static unsigned int read_id_pfr1(void)
{
    unsigned int value;
    __asm volatile ("mrc p15, 0, %0, c0, c1, 1" : "=r" (value));
    return value;
}

static unsigned int read_sctlr(void)
{
    unsigned int value;
    __asm volatile ("mrc p15, 0, %0, c1, c0, 0" : "=r" (value));
    return value;
}


/**************************************************************************/
/*  report -- one "NAME = VALUE" line on the console.                     */
/**************************************************************************/

static void report(const char *name, unsigned int value)
{
    linflexd_puts(name);
    linflexd_puts(" = 0x");
    linflexd_put_hex32(value);
    linflexd_putc('\n');
}


/**************************************************************************/
/*  bsp_done -- breakpoint target, reached once the structure is complete.*/
/*                                                                        */
/*  Deliberately not static and deliberately not inlined: it exists purely*/
/*  so a debugger can break on a symbol.  An optimising build would remove*/
/*  an empty static function, and then the script would have nothing to   */
/*  attach to.                                                            */
/**************************************************************************/

unsigned int read_sctlr_after_mpu(void)
{
    return read_sctlr();
}


void bsp_done(void)
{
    __asm volatile ("nop");
}


/**************************************************************************/
/*  bsp_main -- entered at EL1 (Supervisor) from entry.S.  Never returns. */
/**************************************************************************/

void bsp_main(void)
{
    /* Written last, so a debugger that finds the magic knows every other
       field is already valid.  A partially filled structure would otherwise
       be indistinguishable from a complete one.  */

    r52_identity.magic        = 0U;

    r52_identity.midr         = read_midr();
    r52_identity.mpuir        = read_mpuir();
    r52_identity.ctr          = read_ctr();
    r52_identity.mpidr        = read_mpidr();
    r52_identity.id_pfr0      = read_id_pfr0();
    r52_identity.id_pfr1      = read_id_pfr1();
    r52_identity.sctlr_el1    = read_sctlr();

    r52_identity.hmpuir_el2   = hmpuir_at_el2;
    r52_identity.cntfrq_el2   = cntfrq_at_el2;
    r52_identity.cpsr_el2     = cpsr_at_el2;
    r52_identity.cpsr_el1     = cpsr_at_el1;

    /* Derived counts, so the debugger script does not have to know where the
       field sits in each register.  MPUIR reports DREGION in bits [15:8].
       HMPUIR is recorded raw as well, because on this part the count appears
       in bits [7:0] instead and that layout still needs confirming against
       the Armv8-R specification.  */

    r52_identity.mpu_regions_el1 = (r52_identity.mpuir >> 8) & 0xFFU;

    r52_identity.magic        = R52_IDENTITY_MAGIC;

    /* Report over the console as well as through memory.  The memory copy
       stays: it is what proved the boot path before a console existed, and it
       still works if the console itself is misconfigured.  */

    r52_identity.console_status = linflexd_init();
    linflexd_puts("\n=== ThreadX Cortex-R52 :: NXP S32Z280-594EVB ===\n");
    report("MIDR     ", r52_identity.midr);
    report("MPUIR    ", r52_identity.mpuir);
    report("HMPUIR   ", r52_identity.hmpuir_el2);
    report("CTR      ", r52_identity.ctr);
    report("MPIDR    ", r52_identity.mpidr);
    report("ID_PFR0  ", r52_identity.id_pfr0);
    report("ID_PFR1  ", r52_identity.id_pfr1);
    report("SCTLR    ", r52_identity.sctlr_el1);
    report("CNTFRQ   ", r52_identity.cntfrq_el2);
    report("CPSR@EL2 ", r52_identity.cpsr_el2);
    report("CPSR@EL1 ", r52_identity.cpsr_el1);
    linflexd_puts("EL1 MPU regions: ");
    linflexd_put_hex32(r52_identity.mpu_regions_el1);
    linflexd_putc('\n');
    report("CONSOLE  ", r52_identity.console_status);

    /* --- generic timer ----------------------------------------------------
       CNTFRQ is now programmed at EL2 (8 MHz, measured and cross-checked
       against CFG_CNTDV and FXOSC).  Prove the timer end to end: read it back,
       then arm a one-second one-shot and poll for it, bracketed by CNTPCT
       samples.  If the counter and the compare agree, the elapsed count is
       CNTFRQ; if the host also sees one second pass, the rate itself is right
       rather than merely self-consistent.

       Interrupt stays masked -- no GIC yet.  Polling first means a later
       interrupt problem cannot be confused with the timer being wrong.  */

    report("CNTFRQ   ", timer_read_cntfrq());

    {
        unsigned long long before;
        unsigned long long after;
        unsigned int       hz = timer_read_cntfrq();

        /* Sample AFTER the message, not before: at 115200 the line itself is
           about 2 ms, and sampling first puts that inside the measurement.  */

        linflexd_puts("TIMER arming 1s one-shot\n");
        before = timer_read_cntpct();
        timer_start_oneshot(hz);

        while (timer_fired() == 0U)
        {
            /* poll */
        }

        after = timer_read_cntpct();
        timer_stop();

        linflexd_puts("TIMER fired, elapsed counts = 0x");
        linflexd_put_hex32((unsigned int)((after - before) >> 32));
        linflexd_put_hex32((unsigned int)(after - before));
        linflexd_puts("\n");
    }

    /* --- where is the GIC, and is the port to it open? ---------------------
       System-register reads only: a load from the GIC window stalls the core,
       so nothing here touches memory.  */

    report("IMP_CBAR ", gic_read_cbar());
    report("PERIPHPRG", gic_read_periphpregionr());

    /* The peripheral port is now enabled at EL2, so RTU peripheral space
       should be reachable.  Marker first: if this still stalls, the run dies
       here and says so.  */

    linflexd_puts("P1 RTU0.GPR CFG_CNTDV via LLPP\n");
    report("CFG_CNTDV", *(volatile unsigned int *)S32Z_RTU0_GPR_CFG_CNTDV);

    /* --- MPU, then the GIC ------------------------------------------------
       The GIC needs its region mapped Device nGnRnE (Cortex-R52 TRM), which
       needs the MPU on.  Markers around the enable: if the console survives it,
       the UART region is right; if it does not, that is the answer.  */

    MARK(0x10);
    linflexd_puts("M1 enabling MPU\n");
    {
        unsigned int regions = mpu_init();

        MARK(0x11);

        report("MPU rgns ", regions);
        report("SCTLR    ", read_sctlr_after_mpu());
        MARK(0x12);
        linflexd_puts("M2 MPU enabled, console alive\n");

        linflexd_puts("M3 GICD_PIDR2 (was stalling before the MPU)\n");
        MARK(0x13);
        report("GICD_PIDR2", *(volatile unsigned int *)(S32Z_GIC_BASE + 0xFFE8UL));
        MARK(0x14);
        report("GICD_TYPER", *(volatile unsigned int *)(S32Z_GIC_BASE + 0x0004UL));
        MARK(0x15);
        report("GICR_PIDR2", *(volatile unsigned int *)(S32Z_GIC_BASE + 0x10FFE8UL));
        MARK(0x16);
        linflexd_puts("M4 GIC reachable\n");
    }

    /* --- GIC: not reachable yet, probe deliberately removed ----------------
       The GIC window NXP's memory map gives for this cluster, 0x47800000, is
       unreachable from BOTH paths in the current state.  The debugger cannot
       read any of it, and a load from the core stalls the core outright: the
       run dies at the marker before the access, with no fault recorded and the
       debug connection dropped -- the same signature as RTU0.GPR.

       The Reference Manual contains no GIC base address anywhere, so that
       address rests entirely on NXP's debugger script.  What the manual does
       mention is the R52's "Arm low-latency peripheral port".  On Cortex-R52
       the LLPP is an implementation-defined region that software programs and
       enables; if it is disabled out of reset, or covers a different base,
       accesses to a peripheral in that window stall exactly like this.
       Settling it needs the Cortex-R52 TRM, which documents the region
       registers -- NXP's manual does not.

       The probe is removed rather than left disabled: while it was present the
       image stalled here every run, which costs the timer and console results
       that come before it.  */

    /* Deliberate breakpoint target.  The debug script sets a hardware
       breakpoint here, so "the image ran to completion" is something the script
       observes rather than infers from a timeout.  */

    bsp_done();

    /* Park.  The debugger halts the core and reads r52_identity.
       A busy loop rather than WFI: this core's debug behaviour is still being
       characterised, and a core sitting in a low-power state is one more
       variable between "the code ran" and "the debugger sees it".  The nop
       also stops the compiler discarding a side-effect-free infinite loop.  */

    for (;;)
    {
        __asm volatile ("nop");
    }
}
