/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    cache.c                                          Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frederic Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Cache maintenance and enable for the S32Z280-594EVB.                */
/*                                                                        */
/*    The FVP example enables SCTLR.C and SCTLR.I but only invalidates the*/
/*    instruction cache, with a note that a data-cache set/way sweep      */
/*    belongs with silicon bring-up "where it can be verified against the */
/*    real cache geometry".  This is that: the sweep here reads CLIDR and */
/*    CCSIDR and walks every set and way the hardware reports, rather than*/
/*    assuming a size.                                                    */
/*                                                                        */
/*    The sweep matters more here than on a model.  This image is written */
/*    into SRAM by a debugger with the caches off, so nothing has been    */
/*    allocated yet -- but the caches are not architecturally guaranteed  */
/*    to be invalid out of reset, and enabling a write-back data cache    */
/*    holding stale valid lines would evict them over live memory.        */
/*                                                                        */
/*  A CONSEQUENCE WORTH KNOWING                                           */
/*                                                                        */
/*    With the write-back data cache on, values this image writes may sit */
/*    dirty in cache where a DEBUGGER READING SRAM CANNOT SEE THEM.  The  */
/*    memory-resident progress markers and fault records used throughout  */
/*    this bring-up are read exactly that way.  They stay reliable only   */
/*    because cache_clean_all() is called before parking; without that a  */
/*    post-mortem read could report stale values and look like a fault    */
/*    that never happened.                                                */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                   */
/*                                                                        */
/*    Dir 4.3 -- assembly encapsulated one operation per function.        */
/*                                                                        */
/**************************************************************************/

#include "cache.h"

#define SCTLR_C                 (1UL << 2)
#define SCTLR_I                 (1UL << 12)


static unsigned long read_sctlr(void)
{
    unsigned long value;
    __asm volatile ("mrc p15, 0, %0, c1, c0, 0" : "=r" (value));
    return value;
}

static void write_sctlr(unsigned long value)
{
    __asm volatile ("mcr p15, 0, %0, c1, c0, 0" :: "r" (value));
}

static void data_sync_barrier(void)
{
    __asm volatile ("dsb sy" ::: "memory");
}

static void instruction_barrier(void)
{
    __asm volatile ("isb sy" ::: "memory");
}


unsigned long cache_read_clidr(void)
{
    unsigned long value;
    __asm volatile ("mrc p15, 1, %0, c0, c0, 1" : "=r" (value));
    return value;
}


unsigned long cache_read_ccsidr(void)
{
    unsigned long value;
    __asm volatile ("mrc p15, 1, %0, c0, c0, 0" : "=r" (value));
    return value;
}


/* Select a cache level and type for CCSIDR to describe.  Level is zero-based;
   type 0 is data/unified, 1 is instruction.  */

static void select_cache(unsigned long level, unsigned long instruction)
{
    unsigned long csselr = (level << 1) | (instruction & 1UL);

    __asm volatile ("mcr p15, 2, %0, c0, c0, 0" :: "r" (csselr));
    instruction_barrier();
}


void cache_invalidate_icache_all(void)
{
    unsigned long zero = 0UL;

    __asm volatile ("mcr p15, 0, %0, c7, c5, 0" :: "r" (zero));
    data_sync_barrier();
    instruction_barrier();
}


/**************************************************************************/
/*  cache_invalidate_dcache_all -- set/way sweep over real geometry       */
/**************************************************************************/

void cache_invalidate_dcache_all(void)
{
    unsigned long clidr = cache_read_clidr();
    unsigned long level;

    for (level = 0UL; level < 7UL; level++)
    {
        unsigned long ctype = (clidr >> (level * 3UL)) & 7UL;
        unsigned long ccsidr;
        unsigned long line_shift;
        unsigned long ways;
        unsigned long sets;
        unsigned long way_shift;
        unsigned long way;

        /* 0 = none, 1 = instruction only: neither needs a data sweep.  */

        if ((ctype == 0UL) || (ctype == 1UL))
        {
            continue;
        }

        select_cache(level, 0UL);
        ccsidr = cache_read_ccsidr();

        line_shift = (ccsidr & 7UL) + 4UL;              /* log2 line bytes  */
        ways       = ((ccsidr >> 3) & 0x3FFUL) + 1UL;
        sets       = ((ccsidr >> 13) & 0x7FFFUL) + 1UL;

        /* Way number sits in the top bits of the DCISW operand, positioned by
           the associativity: log2(ways) rounded up.  */

        way_shift = 32UL;
        {
            unsigned long probe = ways - 1UL;
            way_shift = 0UL;
            while (probe != 0UL)
            {
                probe >>= 1;
                way_shift++;
            }
            way_shift = 32UL - way_shift;
        }

        for (way = 0UL; way < ways; way++)
        {
            unsigned long set;

            for (set = 0UL; set < sets; set++)
            {
                unsigned long operand = (way << way_shift)
                                      | (set << line_shift)
                                      | (level << 1);

                /* DCISW: invalidate data cache line by set/way.  */

                __asm volatile ("mcr p15, 0, %0, c7, c6, 2" :: "r" (operand));
            }
        }
    }

    data_sync_barrier();
    instruction_barrier();
}


/**************************************************************************/
/*  cache_clean_all -- write dirty lines back to memory                   */
/*                                                                        */
/*  Needed before a debugger reads anything this image wrote: with a      */
/*  write-back cache the value may exist only in cache.                   */
/**************************************************************************/

void cache_clean_all(void)
{
    unsigned long clidr = cache_read_clidr();
    unsigned long level;

    for (level = 0UL; level < 7UL; level++)
    {
        unsigned long ctype = (clidr >> (level * 3UL)) & 7UL;
        unsigned long ccsidr;
        unsigned long line_shift;
        unsigned long ways;
        unsigned long sets;
        unsigned long way_shift;
        unsigned long way;

        if ((ctype == 0UL) || (ctype == 1UL))
        {
            continue;
        }

        select_cache(level, 0UL);
        ccsidr = cache_read_ccsidr();

        line_shift = (ccsidr & 7UL) + 4UL;
        ways       = ((ccsidr >> 3) & 0x3FFUL) + 1UL;
        sets       = ((ccsidr >> 13) & 0x7FFFUL) + 1UL;

        {
            unsigned long probe = ways - 1UL;
            way_shift = 0UL;
            while (probe != 0UL)
            {
                probe >>= 1;
                way_shift++;
            }
            way_shift = 32UL - way_shift;
        }

        for (way = 0UL; way < ways; way++)
        {
            unsigned long set;

            for (set = 0UL; set < sets; set++)
            {
                unsigned long operand = (way << way_shift)
                                      | (set << line_shift)
                                      | (level << 1);

                /* DCCSW: clean data cache line by set/way.  */

                __asm volatile ("mcr p15, 0, %0, c7, c10, 2" :: "r" (operand));
            }
        }
    }

    data_sync_barrier();
}


/**************************************************************************/
/*  cache_enable -- invalidate both caches, then turn them on             */
/**************************************************************************/

void cache_enable(void)
{
    unsigned long sctlr;

    cache_invalidate_dcache_all();
    cache_invalidate_icache_all();

    sctlr = read_sctlr();
    sctlr |= SCTLR_C | SCTLR_I;
    write_sctlr(sctlr);

    data_sync_barrier();
    instruction_barrier();
}


/* L1 data cache geometry, decoded from CCSIDR with level 0 selected.     */

static unsigned long dcache_ccsidr(void)
{
    select_cache(0UL, 0UL);
    return cache_read_ccsidr();
}


unsigned long cache_dcache_line_bytes(void)
{
    return 1UL << ((dcache_ccsidr() & 7UL) + 4UL);
}


unsigned long cache_dcache_ways(void)
{
    return ((dcache_ccsidr() >> 3) & 0x3FFUL) + 1UL;
}


unsigned long cache_dcache_sets(void)
{
    return ((dcache_ccsidr() >> 13) & 0x7FFFUL) + 1UL;
}


unsigned long cache_dcache_bytes(void)
{
    return cache_dcache_line_bytes() * cache_dcache_ways() * cache_dcache_sets();
}


unsigned int cache_enabled(void)
{
    unsigned long sctlr = read_sctlr();

    return (((sctlr & SCTLR_C) != 0UL) && ((sctlr & SCTLR_I) != 0UL)) ? 1U : 0U;
}
