/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    cache.h                                          Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frederic Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Cache maintenance and enable for the S32Z280-594EVB.                */
/*                                                                        */
/**************************************************************************/

#ifndef CACHE_H
#define CACHE_H

/* Geometry as the hardware reports it; printed during bring-up so the sweep
   below can be checked against real numbers rather than assumed ones.  */

unsigned long   cache_read_clidr(void);
unsigned long   cache_read_ccsidr(void);

void            cache_invalidate_icache_all(void);
void            cache_invalidate_dcache_all(void);

/* Write dirty lines back.  Call before a debugger reads memory this image
   wrote: with a write-back cache the value may exist only in cache.  */

void            cache_clean_all(void);

/* Invalidate both caches, then set SCTLR.C and SCTLR.I.                  */

void            cache_enable(void);

unsigned int    cache_enabled(void);

/* Decoded L1 data-cache geometry, from CCSIDR.  Sizing a cache benchmark
   against real numbers rather than a guess is the difference between measuring
   the cache and measuring nothing.  */

unsigned long   cache_dcache_line_bytes(void);
unsigned long   cache_dcache_ways(void);
unsigned long   cache_dcache_sets(void);
unsigned long   cache_dcache_bytes(void);

#endif /* CACHE_H */
