/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    demo_s32z280.c                                   Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frederic Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    ThreadX running on S32Z280 silicon: threads, preemption and the     */
/*    timer tick.                                                         */
/*                                                                        */
/*    The demo judges itself and says why it failed, because a hang and a */
/*    wrong answer are equally likely on first silicon and look the same  */
/*    from a console.  Each check is separate:                            */
/*                                                                        */
/*      ticks     -- the tick advanced, so the GIC delivers the timer PPI */
/*                   and _tx_timer_interrupt is reached                   */
/*      sleeper   -- tx_thread_sleep returned, so tick-driven scheduling  */
/*                   works, not merely the interrupt                      */
/*      spinner   -- the low-priority thread ran, so the sleeper actually */
/*                   yielded the core rather than blocking it             */
/*      preempt   -- the sleeper resumed while the spinner was runnable,  */
/*                   which is preemption rather than cooperative handoff  */
/*                                                                        */
/*    Counting alone would not distinguish these: a demo that only checked*/
/*    that both threads ran would pass with a broken tick if the threads  */
/*    happened to yield to each other.                                    */
/*                                                                        */
/**************************************************************************/

#include "tx_api.h"
#include "linflexd.h"
#include "board.h"

#define DEMO_STACK_SIZE         2048

static TX_THREAD    sleeper_thread;
static TX_THREAD    spinner_thread;
static TX_THREAD    judge_thread;

/* One stack in BTCM, the rest in DRAM0, so a run exercises both and the
   difference is visible if one of them is wrong.

   BTCM is 16 KB at zero wait states and is never cached, whatever the MPU says
   about it.  That is the point for a stack: access cost does not depend on
   whether a line happens to be resident, which is what a determinism argument
   needs.  Measured on this part, uncached BTCM comes within 6.6% of the best
   cached case, where uncached DRAM0 is 22% off it.

   entry.S writes every location in the bank before any C runs, which is
   required before a read because ECC is enabled (TRM 6.2.2).  A stack is read
   before it is written -- the first context restore pops what tx_thread_create
   built -- so that preload is not optional here.  */

__attribute__((section(".btcm_bss"), aligned(8)))
static unsigned char sleeper_stack[DEMO_STACK_SIZE];
static unsigned char spinner_stack[DEMO_STACK_SIZE];
static unsigned char judge_stack[DEMO_STACK_SIZE];

static volatile unsigned long   sleeper_runs;
static volatile unsigned long   spinner_runs;
static volatile unsigned long   preempt_observed;


/* Breakpoint target for tools/read_identity.gdb.  Defined here rather than
   pulled from bsp_boot.c, whose bsp_main would collide with this file's.
   Not static and not empty, so an optimising build cannot discard it.  */

void bsp_done(void)
{
    __asm volatile ("nop");
}


static void report(const char *name, unsigned long value)
{
    linflexd_puts(name);
    linflexd_puts(" = 0x");
    linflexd_put_hex32((unsigned int) value);
    linflexd_putc('\n');
}


/* Highest priority.  Sleeps, so it can only run again if the tick advances
   and the scheduler resumes it.  */

static void sleeper_entry(ULONG input)
{
    unsigned long spinner_before;

    (void) input;

    for (;;)
    {
        spinner_before = spinner_runs;

        tx_thread_sleep(5UL);           /* 50 ms at a 10 ms tick */

        sleeper_runs++;

        /* If the spinner advanced while this thread slept, and this thread is
           the higher priority of the two, then resuming it took the core away
           from a runnable lower-priority thread.  That is preemption.  */

        if (spinner_runs != spinner_before)
        {
            preempt_observed++;
        }
    }
}


/* Lowest priority.  Never blocks, so it only runs when nothing else can. */

static void spinner_entry(ULONG input)
{
    (void) input;

    for (;;)
    {
        spinner_runs++;
    }
}


/* Middle priority.  Waits, then judges and reports.                      */

static void judge_entry(ULONG input)
{
    ULONG   ticks_start;
    ULONG   ticks_end;
    UINT    failures = 0U;

    (void) input;

    ticks_start = tx_time_get();
    tx_thread_sleep(100UL);             /* about one second */
    ticks_end = tx_time_get();

    linflexd_puts("\n=== ThreadX on S32Z280: results ===\n");
    report("ticks    ", (unsigned long) (ticks_end - ticks_start));
    report("sleeper  ", sleeper_runs);
    report("spinner  ", spinner_runs);
    report("preempt  ", preempt_observed);

    if ((ticks_end - ticks_start) < 50UL)
    {
        linflexd_puts("FAIL tick did not advance as expected\n");
        failures++;
    }

    if (sleeper_runs == 0UL)
    {
        linflexd_puts("FAIL sleeper never resumed\n");
        failures++;
    }

    if (spinner_runs == 0UL)
    {
        linflexd_puts("FAIL spinner never ran\n");
        failures++;
    }

    if (preempt_observed == 0UL)
    {
        linflexd_puts("FAIL no preemption observed\n");
        failures++;
    }

    if (failures == 0U)
    {
        linflexd_puts("PASS threads, tick and preemption all verified\n");
    }

    linflexd_puts("=== demo complete ===\n");

    bsp_done();

    for (;;)
    {
        tx_thread_sleep(100UL);
    }
}


void tx_application_define(void *first_unused_memory)
{
    (void) first_unused_memory;

    linflexd_puts("stacks: sleeper 0x");
    linflexd_put_hex32((unsigned int) (unsigned long) sleeper_stack);
    linflexd_puts(" (BTCM)  spinner 0x");
    linflexd_put_hex32((unsigned int) (unsigned long) spinner_stack);
    linflexd_puts("  judge 0x");
    linflexd_put_hex32((unsigned int) (unsigned long) judge_stack);
    linflexd_puts("\n");

    (void) tx_thread_create(&sleeper_thread, "sleeper", sleeper_entry, 0UL,
                            sleeper_stack, DEMO_STACK_SIZE,
                            1U, 1U, TX_NO_TIME_SLICE, TX_AUTO_START);

    (void) tx_thread_create(&judge_thread, "judge", judge_entry, 0UL,
                            judge_stack, DEMO_STACK_SIZE,
                            10U, 10U, TX_NO_TIME_SLICE, TX_AUTO_START);

    (void) tx_thread_create(&spinner_thread, "spinner", spinner_entry, 0UL,
                            spinner_stack, DEMO_STACK_SIZE,
                            20U, 20U, TX_NO_TIME_SLICE, TX_AUTO_START);
}


/**************************************************************************/
/*  bsp_main -- entered at EL1 from entry.S; hands over to the kernel.    */
/**************************************************************************/

void bsp_main(void)
{
    unsigned int console_status = linflexd_init();

    linflexd_puts("\n=== ThreadX Cortex-R52 :: S32Z280-594EVB ===\n");
    report("console  ", (unsigned long) console_status);
    linflexd_puts("entering kernel\n");

    tx_kernel_enter();

    /* Not reached.  */

    linflexd_puts("FAIL tx_kernel_enter returned\n");

    for (;;)
    {
        __asm volatile ("nop");
    }
}
