/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    gic_probe.c                                      Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frederic Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Asks the core where its GIC is, and whether it can be reached.      */
/*                                                                        */
/*    A load from the GIC window NXP documents for this cluster stalls    */
/*    the core outright, so nothing here touches memory.  Both values     */
/*    below are system registers: reading them cannot hang the bus.       */
/*                                                                        */
/*    IMP_CBAR holds the physical base address of the memory-mapped GIC   */
/*    distributor -- bits [31:21], wired by the SoC's CFGPERIPHBASE       */
/*    input.  That is the authoritative answer, as against an address     */
/*    taken from a vendor debugger script.                                */
/*                                                                        */
/*    IMP_PERIPHPREGIONR describes the low-latency peripheral port: base  */
/*    address in [31:12], size in [6:2], and separate enables for EL2     */
/*    (bit 1) and EL1/0 (bit 0).  If the port is disabled, accesses in    */
/*    its window go nowhere, which is what a stalled load looks like.     */
/*                                                                        */
/*    Both from the Cortex-R52 TRM r1p3 (100026_0103_00_en), sections     */
/*    3.3.17 and 3.3.80 -- the SoC reference manual documents neither.    */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                   */
/*                                                                        */
/*    Dir 4.3 -- assembly encapsulated one access per function.           */
/*                                                                        */
/**************************************************************************/

#include "gic_probe.h"

unsigned int gic_read_cbar(void)
{
    unsigned int value;

    __asm volatile ("mrc p15, 1, %0, c15, c3, 0" : "=r" (value));

    return value;
}


unsigned int gic_read_periphpregionr(void)
{
    unsigned int value;

    __asm volatile ("mrc p15, 0, %0, c15, c0, 0" : "=r" (value));

    return value;
}
