/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    gic_probe.h                                      Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frederic Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Where the GIC is, and whether the peripheral port reaches it.       */
/*                                                                        */
/**************************************************************************/

#ifndef GIC_PROBE_H
#define GIC_PROBE_H

/* IMP_CBAR[31:21] = PERIPHBASE, the GIC distributor base.                */

unsigned int    gic_read_cbar(void);

/* IMP_PERIPHPREGIONR: LLPP base [31:12], size [6:2], EL2 enable bit 1,
   EL1/0 enable bit 0.                                                    */

unsigned int    gic_read_periphpregionr(void);

#endif /* GIC_PROBE_H */
