/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    irq_dispatch.c                                   Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frederic Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Interrupt dispatch for the S32Z280-594EVB, standalone.              */
/*                                                                        */
/*    Called from el1_irq_entry in entry.S.  Unlike the FVP example this  */
/*    does not call _tx_timer_interrupt: the image does not link ThreadX, */
/*    so a failure here is a board or GIC problem and not a kernel one.   */
/*    It counts ticks instead, which is what makes the interrupt visible. */
/*                                                                        */
/*    Every count is volatile and read by the debugger as well as printed.*/
/*    An interrupt that never arrives and an interrupt that arrives and is*/
/*    mishandled look identical from the console alone, and the separate  */
/*    spurious and unexpected counters distinguish them.                  */
/*                                                                        */
/**************************************************************************/

#include "gicv3.h"
#include "timer.h"
#include "board.h"

/* Observable from both the console and a debugger.                       */

volatile unsigned long  board_irq_count;
volatile unsigned long  board_timer_intid;
volatile unsigned long  board_spurious_count;
volatile unsigned long  board_unexpected_intid;
volatile unsigned long  board_first_intid = 0xFFFFFFFFUL;

/* The EL1 physical timer PPI.  30 is the architectural assignment and is what
   the FVP turned out to use, but it was discovered there by enabling the whole
   PPI range and recording whichever INTID arrived in ICC_IAR1 rather than by
   assuming.  board_timer_intid records what actually arrives here, so a wrong
   value shows up as an unexpected INTID rather than as silence.  */

#define TIMER_PPI_INTID         30U

/* Only the top priority bits are implemented; hence a multiple of 8.     */

#define TIMER_PPI_PRIORITY      0xA0U


void board_irq_handler(void)
{
    unsigned long intid = gicv3_acknowledge();

    if (intid == GICV3_SPURIOUS_INTID)
    {
        /* Nothing was actually pending.  Must not be acknowledged with an
           end-of-interrupt write, so return without one.  */

        board_spurious_count++;
        return;
    }

    if (board_first_intid == 0xFFFFFFFFUL)
    {
        board_first_intid = intid;      /* whatever actually arrived */
    }

    if (intid == (unsigned long) TIMER_PPI_INTID)
    {
        board_timer_intid = intid;
        board_irq_count++;

        /* Re-arm first.  The generic timer output is level-sensitive, so until
           the compare is moved forward the condition stays asserted and the
           interrupt would be taken again immediately on return.  */

        timer_start_oneshot_irq(timer_read_cntfrq() / 100U);
    }
    else
    {
        board_unexpected_intid = intid;
    }

    gicv3_end_of_interrupt(intid);
}
