/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    linflexd.h                                       Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Polled transmit-only console on LINFlexD, for the S32Z280-594EVB.   */
/*                                                                        */
/**************************************************************************/

#ifndef LINFLEXD_H
#define LINFLEXD_H

/* Configure LINFlex_9 for 115200 8N1 and enable the transmitter.         */

void    linflexd_init(void);

/* Blocking single character.  Translates \n to \r\n so the output is
   readable on a terminal that does not add the carriage return itself.  */

void    linflexd_putc(char c);

void    linflexd_puts(const char *string);

/* Eight hex digits, no 0x prefix.  Printing register values is the whole
   reason this console exists, and a printf would drag in a C library this
   image deliberately does not link.  */

void    linflexd_put_hex32(unsigned int value);

#endif /* LINFLEXD_H */
