/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    mpu.c                                            Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    PMSAv8-R memory protection for the NXP S32Z280-594EVB.              */
/*                                                                        */
/*    Register model (AArch32): a region is selected through PRSELR and   */
/*    then described by PRBAR (base, shareability, access permission,     */
/*    execute-never) and PRLAR (inclusive limit, attribute index, enable).*/
/*    Both addresses have a 64-byte granule, so the low six bits of each  */
/*    register hold attributes rather than address.  Memory types come    */
/*    from MAIR through the attribute index, not from the region itself.  */
/*                                                                        */
/*    Caches are invalidated before being enabled.  On this model they    */
/*    come out of reset invalid, but silicon does not guarantee that, and */
/*    this code is meant to be the template the S32Z280 port starts from. */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                   */
/*                                                                        */
/*    Directive 4.3 -- the MPU, MAIR, SCTLR and cache maintenance are only*/
/*      reachable through CP15; every access is encapsulated in a one-line*/
/*      accessor below.                                                   */
/*                                                                        */
/**************************************************************************/

#include "platform.h"

/* Progress marker, mirrored into memory.  Enabling the MPU can take the core
   down in a way that records no fault and takes the console with it, so each
   step here is stamped where a debugger can read it afterwards.  */

extern unsigned int probe_stage;
#define MARK(n)     do { probe_stage = (unsigned int)(n); } while (0)
#include "mpu.h"
#include "platform.h"

/* Progress marker, mirrored into memory.  Enabling the MPU can take the core
   down in a way that records no fault and takes the console with it, so each
   step here is stamped where a debugger can read it afterwards.  */

extern unsigned int probe_stage;
#define MARK(n)     do { probe_stage = (unsigned int)(n); } while (0)

/* SCTLR bits.                                                            */

#define SCTLR_M             (1UL << 0)      /* MPU enable                  */
#define SCTLR_C             (1UL << 2)      /* data cache enable           */
#define SCTLR_I             (1UL << 12)     /* instruction cache enable    */

/* MAIR attribute bytes.  Index 0 is Normal write-back read/write-allocate,
   index 1 is Device-nGnRnE, matching MPU_ATTR_* in the header.  */

#define MAIR_ATTR_NORMAL_WB 0xFFUL
#define MAIR_ATTR_DEVICE    0x00UL

/* Boundaries supplied by the linker script, all 64-byte aligned.         */

extern char __code_end__;
extern char __data_start__;
extern char __data_end__;


/**************************************************************************/
/*  The region table.                                                     */
/*                                                                        */
/*  Deliberately minimal and readable: code is read-only and executable,  */
/*  everything writable is non-executable, and the peripheral half of the */
/*  address map is Device.  A write-protected code region is the point -- */
/*  it is what makes the MPU do something observable, and AR2 extends the */
/*  same table with per-module regions.                                   */
/**************************************************************************/

/* Table capacity.  The FVP example this file came from declared this as [3],
   matching the three regions it programs; a five-region table then wrote past
   the end of it, and the region-3 base assignment landed outside the array.
   The region read back with base 0 and limit 0x763FFFFF, overlapping regions
   0-2, and PMSAv8-R makes overlapping regions UNPREDICTABLE -- which is what
   killed the core on the SCTLR.M write.  Named and guarded so the next map
   cannot repeat it.  */

#define MPU_TABLE_REGIONS   16U

static MPU_REGION mpu_regions[MPU_TABLE_REGIONS];
static unsigned int mpu_regions_used;


/**************************************************************************/
/*  CP15 accessors.                                                       */
/**************************************************************************/

static unsigned long read_mpuir(void)
{
    unsigned long value;
    __asm__ volatile("mrc p15, 0, %0, c0, c0, 4" : "=r"(value));
    return value;
}

static unsigned long read_sctlr(void)
{
    unsigned long value;
    __asm__ volatile("mrc p15, 0, %0, c1, c0, 0" : "=r"(value));
    return value;
}

static void write_sctlr(unsigned long value)
{
    __asm__ volatile("mcr p15, 0, %0, c1, c0, 0" : : "r"(value) : "memory");
}

static void write_prselr(unsigned long value)
{
    __asm__ volatile("mcr p15, 0, %0, c6, c2, 1" : : "r"(value) : "memory");
}

static void write_prbar(unsigned long value)
{
    __asm__ volatile("mcr p15, 0, %0, c6, c3, 0" : : "r"(value) : "memory");
}

static void write_prlar(unsigned long value)
{
    __asm__ volatile("mcr p15, 0, %0, c6, c3, 1" : : "r"(value) : "memory");
}

static unsigned long read_prbar(void)
{
    unsigned long value;
    __asm__ volatile("mrc p15, 0, %0, c6, c3, 0" : "=r"(value));
    return value;
}

static unsigned long read_prlar(void)
{
    unsigned long value;
    __asm__ volatile("mrc p15, 0, %0, c6, c3, 1" : "=r"(value));
    return value;
}

static void write_mair0(unsigned long value)
{
    __asm__ volatile("mcr p15, 0, %0, c10, c2, 0" : : "r"(value) : "memory");
}

static void write_mair1(unsigned long value)
{
    __asm__ volatile("mcr p15, 0, %0, c10, c2, 1" : : "r"(value) : "memory");
}

static void invalidate_icache_all(void)
{
    __asm__ volatile("mcr p15, 0, r0, c7, c5, 0" : : : "memory");  /* ICIALLU */
}

static void data_sync_barrier(void)
{
    __asm__ volatile("dsb" : : : "memory");
}

static void instruction_barrier(void)
{
    __asm__ volatile("isb" : : : "memory");
}


/**************************************************************************/
/*  mpu_region_count                                                      */
/**************************************************************************/

unsigned int mpu_region_count(void)
{
    /* MPUIR.REGION occupies bits [15:8].  */

    return (unsigned int) ((read_mpuir() >> 8) & 0xFFUL);
}


/**************************************************************************/
/*  mpu_is_enabled / mpu_caches_enabled                                   */
/**************************************************************************/

unsigned int mpu_is_enabled(void)
{
    return ((read_sctlr() & SCTLR_M) != 0UL) ? 1U : 0U;
}

unsigned int mpu_caches_enabled(void)
{
    unsigned long sctlr = read_sctlr();

    return (((sctlr & SCTLR_C) != 0UL) && ((sctlr & SCTLR_I) != 0UL)) ? 1U : 0U;
}


/**************************************************************************/
/*  mpu_region_table                                                      */
/**************************************************************************/

const MPU_REGION *mpu_region_table(unsigned int *count_ptr)
{
    if (count_ptr != 0)
    {
        *count_ptr = mpu_regions_used;
    }

    return mpu_regions;
}


/**************************************************************************/
/*  mpu_read_region                                                       */
/**************************************************************************/

void mpu_read_region(unsigned int index, unsigned long *prbar_ptr,
                     unsigned long *prlar_ptr)
{
    write_prselr((unsigned long) index);
    instruction_barrier();

    if (prbar_ptr != 0)
    {
        *prbar_ptr = read_prbar();
    }
    if (prlar_ptr != 0)
    {
        *prlar_ptr = read_prlar();
    }
}


/**************************************************************************/
/*  build_table -- describe this image's memory.                          */
/**************************************************************************/

/* Bisection switch.  probe_stage stops at 0x42 with the real five-region map,
   meaning the SCTLR.M write itself kills the core with no exception taken.
   That has two very different causes: the map is wrong for the first fetch or
   stack access, or enabling the MPU on this part needs something we have not
   done at all.  A single region spanning the whole address space, permissive
   and Normal, distinguishes them: if the core survives with this, the map is
   at fault; if it dies anyway, enabling M is.  */

static void build_table(void)
{
    /* Protection map: narrow regions with real permissions, so that anything
       this image should not do actually faults.
       *
       * This supersedes the permissive bring-up map (everything Normal RW X,
       * whole address space covered).  That map existed because a narrow one
       * had failed and the reason was unknown -- the failure looked like a
       * stall with nothing recorded, and coverage was blamed.  Coverage was
       * never the problem: an out-of-bounds write to a [3]-sized table put a
       * region at base 0 overlapping everything, and SCTLR.TE being set meant
       * the resulting abort could not run a handler.  Both are fixed, so a
       * narrow map is now both correct and diagnosable: if something outside
       * these regions is touched, the fault handler records vector, syndrome
       * and faulting address instead of hanging mutely.
       *
       * Anything not described below is unmapped and faults on access.  That
       * is the point.
       */

    /* Code: read-only and executable.  A write here must fault.  */

    mpu_regions[0].mpu_region_base          = S32Z_CODE_SRAM_BASE;
    mpu_regions[0].mpu_region_limit         = (unsigned long) &__code_end__ - 1UL;
    mpu_regions[0].mpu_region_ap            = MPU_AP_RO_EL1;
    mpu_regions[0].mpu_region_execute_never = 0U;
    mpu_regions[0].mpu_region_shareability  = MPU_SH_NON;
    mpu_regions[0].mpu_region_attr_index    = MPU_ATTR_NORMAL_WB;
    mpu_regions[0].mpu_region_name          = "code  RO X  normal-wb";

    /* Data, bss and every per-mode stack: writable, never executable.  Sized
       from the SRAM banks, not from __data_end__: the stacks are NOLOAD and sit
       above that symbol, so sizing from it would leave them unmapped and the
       first push after enabling the MPU would abort.

       This covers DRAM0 and DRAM1 together -- 512 KB, contiguous, both at full
       core speed.  DRAM1 went undeclared until the banks were read out of the
       Reference Manual and confirmed on the board.  */

    mpu_regions[1].mpu_region_base          = S32Z_DATA_SRAM_BASE;
    mpu_regions[1].mpu_region_limit         = S32Z_DATA_SRAM_BASE
                                            + S32Z_DATA_SRAM_SIZE - 1UL;
    mpu_regions[1].mpu_region_ap            = MPU_AP_RW_EL1;
    mpu_regions[1].mpu_region_execute_never = 1U;
    mpu_regions[1].mpu_region_shareability  = MPU_SH_NON;
    mpu_regions[1].mpu_region_attr_index    = MPU_ATTR_NORMAL_WB;
    mpu_regions[1].mpu_region_name          = "data  RW NX normal-wb";

    /* Console.  Mapped narrowly: one 64 KB LINFlexD instance.  */

    mpu_regions[2].mpu_region_base          = S32Z_LINFLEX_9_BASE;
    mpu_regions[2].mpu_region_limit         = S32Z_LINFLEX_9_BASE + 0xFFFFUL;
    mpu_regions[2].mpu_region_ap            = MPU_AP_RW_EL1;
    mpu_regions[2].mpu_region_execute_never = 1U;
    mpu_regions[2].mpu_region_shareability  = MPU_SH_NON;
    mpu_regions[2].mpu_region_attr_index    = MPU_ATTR_DEVICE;
    mpu_regions[2].mpu_region_name          = "uart  RW NX device";

    /* GIC.  Device nGnRnE is required by the Cortex-R52 TRM, and confirmed
       here: mapped Normal the distributor stalls the core.  */

    mpu_regions[3].mpu_region_base          = S32Z_GIC_BASE;
    mpu_regions[3].mpu_region_limit         = S32Z_GIC_BASE + S32Z_GIC_SIZE - 1UL;
    mpu_regions[3].mpu_region_ap            = MPU_AP_RW_EL1;
    mpu_regions[3].mpu_region_execute_never = 1U;
    mpu_regions[3].mpu_region_shareability  = MPU_SH_NON;
    mpu_regions[3].mpu_region_attr_index    = MPU_ATTR_DEVICE;
    mpu_regions[3].mpu_region_name          = "gic   RW NX device";

    /* RTU peripheral window behind the low-latency peripheral port.  */

    mpu_regions[4].mpu_region_base          = S32Z_RTU_PERIPH_BASE;
    mpu_regions[4].mpu_region_limit         = S32Z_RTU_PERIPH_BASE
                                            + S32Z_RTU_PERIPH_SIZE - 1UL;
    mpu_regions[4].mpu_region_ap            = MPU_AP_RW_EL1;
    mpu_regions[4].mpu_region_execute_never = 1U;
    mpu_regions[4].mpu_region_shareability  = MPU_SH_NON;
    mpu_regions[4].mpu_region_attr_index    = MPU_ATTR_DEVICE;
    mpu_regions[4].mpu_region_name          = "rtu   RW NX device";

    /* DRAM2.  Deliberately mapped so the cache benchmark has slower memory to
       work against: this bank runs at half the core frequency, where region 1's
       banks run at full speed and caching them shows little.  Normal write-back
       and never executable.

       Sized 512 KB, which is the whole bank.  An earlier revision mapped 2 MB
       here; the upper 1.5 MB of that aliased back onto the bank, so anything
       placed above 0x31880000 would have silently shared storage with the
       bottom of the region -- no fault, just two objects on one address.  */

    mpu_regions[5].mpu_region_base          = S32Z_DRAM2_BASE;
    mpu_regions[5].mpu_region_limit         = S32Z_DRAM2_BASE
                                            + S32Z_DRAM2_SIZE - 1UL;
    mpu_regions[5].mpu_region_ap            = MPU_AP_RW_EL1;
    mpu_regions[5].mpu_region_execute_never = 1U;
    mpu_regions[5].mpu_region_shareability  = MPU_SH_NON;
    mpu_regions[5].mpu_region_attr_index    = MPU_ATTR_NORMAL_WB;
    mpu_regions[5].mpu_region_name          = "dram2 RW NX normal-wb";

    /* One region per TCM bank.  The TRM is explicit that an enabled TCM still
       needs an MPU region before it can be used, and that an enabled TCM always
       behaves as Non-cacheable Non-shareable Normal memory whatever attributes
       the MPU carries -- so the attribute index below does not describe the TCM,
       only the permissions do.  Kept as three regions rather than one spanning
       0x30000000 to 0x30203FFF, because a single region would also make the
       1MB gaps between banks accessible, and those are not TCM.

       Left executable on purpose: the point of TCM is deterministic access for
       code as much as data, so an image that wants a TCM-resident handler can
       have one.  That makes these regions writable and executable, which for
       tightly-coupled memory is the normal arrangement rather than an
       oversight.  */

    mpu_regions[6].mpu_region_base          = S32Z_ATCM_BASE;
    mpu_regions[6].mpu_region_limit         = S32Z_ATCM_BASE + S32Z_ATCM_SIZE - 1UL;
    mpu_regions[6].mpu_region_ap            = MPU_AP_RW_EL1;
    mpu_regions[6].mpu_region_execute_never = 0U;
    mpu_regions[6].mpu_region_shareability  = MPU_SH_NON;
    mpu_regions[6].mpu_region_attr_index    = MPU_ATTR_NORMAL_WB;
    mpu_regions[6].mpu_region_name          = "atcm  RW X  tcm";

    /* No regions for BTCM and CTCM: entry.S leaves those banks disabled, and a
       region covering a disabled TCM would map its address range to whatever
       AXIM provides there, which is not TCM and would read as success.  See the
       measurement in entry.S.  */

    /* BTCM.  Data only, so execute-never, unlike the ATCM region above which
       holds code.  An enabled TCM behaves as Non-cacheable Non-shareable Normal
       memory whatever the MPU says, so the attribute index below describes the
       permissions and nothing else -- but a region is still required before the
       bank can be touched at all.  */

    mpu_regions[7].mpu_region_base          = S32Z_BTCM_BASE;
    mpu_regions[7].mpu_region_limit         = S32Z_BTCM_BASE + S32Z_BTCM_SIZE - 1UL;
    mpu_regions[7].mpu_region_ap            = MPU_AP_RW_EL1;
    mpu_regions[7].mpu_region_execute_never = 1U;
    mpu_regions[7].mpu_region_shareability  = MPU_SH_NON;
    mpu_regions[7].mpu_region_attr_index    = MPU_ATTR_NORMAL_WB;
    mpu_regions[7].mpu_region_name          = "btcm  RW NX tcm";

    mpu_regions_used = 8U;
}


/**************************************************************************/
/*  program_region                                                        */
/**************************************************************************/

static void program_region(unsigned int index, const MPU_REGION *region_ptr)
{
    unsigned long prbar;
    unsigned long prlar;

    /* PRBAR: BASE[31:6], RES0[5], SH[4:3], AP[2:1], XN[0].
       *
       * Per Cortex-R52 TRM r1p3 figure 3-39.  Note the field positions: the
       * FVP example this file came from shifts every field one bit too far
       * left -- SH<<4, AP<<2, XN<<1 -- which silently produces a different
       * region than intended.  With XN written to bit 1 it lands in the real
       * AP[1] (EL0 access) and the region stays EXECUTABLE, which is how this
       * board ended up running instructions out of .data.
       *
       * That bug is also the origin of the "PRBAR.AP bit order is reversed"
       * claim recorded during the FVP work.  Calibrating AP empirically under
       * the wrong shift puts the intended AP's low bit into the real AP[2]
       * (the read-only bit) and the intended XN into the real AP[1], which
       * looks exactly like a reversed encoding.  The architectural order is
       * correct as published; there was no reversal.
       */

    prbar = (region_ptr->mpu_region_base & 0xFFFFFFC0UL)
          | (((unsigned long) region_ptr->mpu_region_shareability & 0x3UL) << 3)
          | (((unsigned long) region_ptr->mpu_region_ap & 0x3UL) << 1)
          | ((unsigned long) region_ptr->mpu_region_execute_never & 0x1UL);

    prlar = (region_ptr->mpu_region_limit & 0xFFFFFFC0UL)
          | (((unsigned long) region_ptr->mpu_region_attr_index & 0x7UL) << 1)
          | 1UL;                                    /* region enable        */

    write_prselr((unsigned long) index);
    instruction_barrier();
    write_prbar(prbar);
    write_prlar(prlar);
}


/**************************************************************************/
/*  mpu_init                                                              */
/**************************************************************************/

unsigned int mpu_init(void)
{
    unsigned long sctlr;
    unsigned int  index;
    unsigned int  available = mpu_region_count();

    build_table();

    if (mpu_regions_used > MPU_TABLE_REGIONS)
    {
        return 0U;              /* build_table overran the table */
    }

    if (available < mpu_regions_used)
    {
        return 0U;              /* hardware has fewer regions than we need */
    }

    /* Memory types first: a region's attribute index is meaningless until
       MAIR is populated.  */

    MARK(0x20);
    write_mair0((MAIR_ATTR_DEVICE << 8) | MAIR_ATTR_NORMAL_WB);
    write_mair1(0UL);
    MARK(0x21);

    for (index = 0U; index < mpu_regions_used; index++)
    {
        program_region(index, &mpu_regions[index]);
        MARK(0x30U + index);
    }

    /* Disable any regions this image does not use, so that stale enables
       cannot grant access we did not intend.  */

    for (index = mpu_regions_used; index < available; index++)
    {
        write_prselr((unsigned long) index);
        instruction_barrier();
        write_prlar(0UL);
    }

    MARK(0x40);
    data_sync_barrier();

    /* Caches are invalidated before enabling.  The instruction cache has a
       single invalidate-all; the data cache is left to the model's reset
       state, which is invalid, because a set/way sweep belongs with the
       silicon bring-up where it can be verified against the real cache
       geometry.  */

    invalidate_icache_all();
    data_sync_barrier();
    instruction_barrier();

    /* MPU only.  Caches are deliberately left off on this first pass: the
       point here is reaching the GIC, and enabling caches at the same time
       would add coherency questions -- the debugger writes this image straight
       into SRAM behind the caches' back -- to a change whose result is meant to
       be unambiguous.  C and I are a separate step with their own check.  */

    MARK(0x41);
    sctlr = read_sctlr();
    MARK(0x42);
#if !defined(MPU_READBACK_ONLY)
    sctlr |= SCTLR_M;
    write_sctlr(sctlr);
#else
    (void) sctlr;       /* readback experiment: MPU deliberately NOT enabled */
#endif

    /* If the map is wrong, the core dies HERE -- the next instruction fetch or
       the next stack access is the first thing the new map has to satisfy.  A
       marker written after this point therefore proves the map holds.  */

    MARK(0x43);
    data_sync_barrier();
    instruction_barrier();
    MARK(0x44);

    return mpu_regions_used;
}
