/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    mpu.h                                            Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    PMSAv8-R memory protection and cache enable for Cortex-R52.         */
/*                                                                        */
/*    The region set is described by a table rather than a sequence of    */
/*    register writes.  That is deliberate and is a roadmap decision, not */
/*    a style preference: AR2 programs a Stage-1 region set per ThreadX   */
/*    module and AR3 programs Stage-2 regions per ZoneX partition, and    */
/*    both reuse this shape.  A table can be swapped at a partition       */
/*    switch; open-coded register writes cannot.                          */
/*                                                                        */
/**************************************************************************/

#ifndef MPU_H
#define MPU_H

/* Access permissions, PRBAR.AP (bits [3:2]).
 *
 * These values were CALIBRATED AGAINST THE HARDWARE, not copied from a
 * reference, because the widely-published Armv8-R AArch64 macro set has the
 * two bits the other way round (its "read-only, no EL0 access" is 0x2).
 * Programming four disjoint regions, one per encoding, and attempting a
 * privileged write to each gave:
 *
 *     AP=0b00  write allowed        AP=0b01  write faulted
 *     AP=0b10  write allowed        AP=0b11  write faulted
 *
 * so the low bit is read-only and the high bit grants EL0 access.  Using the
 * AArch64 ordering here silently produces writable "read-only" regions: the
 * MPU still enforces region coverage, so everything appears to work and only
 * an explicit write-permission test exposes it.  Re-calibrate on S32Z280
 * silicon before trusting these values there.
 */

/* PRBAR.AP[2:1] as the architecture defines it: AP[2] selects read-only,
   AP[1] grants EL0 access.  These are the published values -- the "reversed
   bit order" recorded during the FVP work was an artefact of that code
   shifting AP into the wrong bits, not a property of the hardware.  */

#define MPU_AP_RW_EL1       0U      /* 0b00 EL1 read/write, no EL0         */
#define MPU_AP_RW_EL1_EL0   1U      /* 0b01 EL1 read/write, EL0 read/write */
#define MPU_AP_RO_EL1       2U      /* 0b10 EL1 read-only,  no EL0         */
#define MPU_AP_RO_EL1_EL0   3U      /* 0b11 EL1 read-only,  EL0 read-only  */

/* Shareability, PRBAR.SH.                                                */

#define MPU_SH_NON          0U
#define MPU_SH_OUTER        2U
#define MPU_SH_INNER        3U

/* Attribute indices into MAIR, PRLAR.AttrIndx.                           */

#define MPU_ATTR_NORMAL_WB  0U      /* Normal, inner/outer write-back      */
#define MPU_ATTR_DEVICE     1U      /* Device-nGnRnE                       */

/* One protection region.  The limit is inclusive, matching the hardware. */

typedef struct MPU_REGION_STRUCT
{
    unsigned long   mpu_region_base;
    unsigned long   mpu_region_limit;
    unsigned char   mpu_region_ap;
    unsigned char   mpu_region_execute_never;
    unsigned char   mpu_region_shareability;
    unsigned char   mpu_region_attr_index;
    const char     *mpu_region_name;
} MPU_REGION;

/* Number of regions this implementation provides, from MPUIR.            */

unsigned int mpu_region_count(void);

/* Program the region table, then enable the MPU and the caches.  Returns
   the number of regions programmed, or 0 if the table does not fit.  */

unsigned int mpu_init(void);

/* True once SCTLR reports the MPU and both caches enabled.               */

unsigned int mpu_is_enabled(void);
unsigned int mpu_caches_enabled(void);

/* The active table, for reporting.                                       */

const MPU_REGION *mpu_region_table(unsigned int *count_ptr);

/* Read back what the hardware holds for one region, so that programming can
   be verified rather than assumed.  */

void mpu_read_region(unsigned int index, unsigned long *prbar_ptr,
                     unsigned long *prlar_ptr);

/* Region index for the manager's load window over the module area.  Above the
   kernel's 0-7 and above the eight the manager hands to a module, so neither
   the boot table nor the scheduler's per-thread region load can disturb it.  */

#define MPU_MODULE_LOAD_REGION  16U

/* The module area window, which is what lets privileged code reach module
   memory at all -- no other kernel region covers it.

   PMSAv8-R has no region priority, so this must never be enabled at the same
   time as the regions a module is given, which cover the same memory.  That is
   guaranteed by who owns it rather than by careful calling: the scheduler turns
   this region on for every thread that is not a module thread and off for every
   thread that is, so the window is enabled exactly when no module regions are
   loaded.  The two register words are published for it below.

   Enabled here at boot, because everything before the first module thread is
   privileged code that may need to reach module memory.  */

void mpu_module_window_init(void);

extern unsigned long mpu_module_window_prbar;
extern unsigned long mpu_module_window_prlar;

#endif /* MPU_H */
