/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    platform.h                                       Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Memory map and peripheral addresses for the NXP S32Z280-594EVB,     */
/*    RTU0 core 0 (R52_0_0).                                              */
/*                                                                        */
/*    Every address below was either read out of the S32Z2 Reference      */
/*    Manual (S32Z27RM Rev. 5.1) or confirmed on the board itself, and    */
/*    each is marked accordingly.  The distinction matters because this   */
/*    part differs from the Armv8-R AEM FVP in ways that are silent       */
/*    rather than loud: an address that is merely wrong tends to read     */
/*    back zero instead of faulting.                                      */
/*                                                                        */
/*  MEMORY                                                                */
/*                                                                        */
/*    The RTU exposes its code SRAM through two windows onto the same     */
/*    physical memory: 0x79900000 for instruction fetch (AXI-F) and       */
/*    0x32100000 as data.  Confirmed by writing a sentinel to one and     */
/*    reading it back through the other.  NXP's debugger memory map       */
/*    declares the fetch window read-only, but it is writable over the    */
/*    debug AXI port -- verified -- so a debugger-loaded image can be     */
/*    placed there directly and no load-address alias is needed.  A       */
/*    self-booting image loaded from flash would still need the data      */
/*    alias, since the core's own data side may not write through AXI-F.  */
/*                                                                        */
/*    The TCMs need care, and the earlier note here was wrong about why.  */
/*    Reads of 0x30000000, 0x30100000 and 0x30200000 do fault, but not    */
/*    because the TCMs are disabled.  Reading the region registers on     */
/*    this part gives:                                                    */
/*                                                                        */
/*      ATCM  0x0000011F   64KB, 1 wait state, ENABLED at EL2 and EL1/0   */
/*      BTCM  0x00000014   16KB, 0 wait states, disabled                  */
/*      CTCM  0x00000114   16KB, 1 wait state, disabled                   */
/*                                                                        */
/*    Every BASEADDRESS field is zero, so ATCM is live as 64KB at address */
/*    0x00000000 -- not at 0x30000000.  The faulting reads were of an     */
/*    address the TCM is not at.  ATCM's enables reset set because        */
/*    CFGTCMBOOTx is tied high on this part (Cortex-R52 TRM r1p3 3.3.94). */
/*    The sizes and wait states match the S32Z2 reference manual exactly. */
/*                                                                        */
/*    ECC is implemented and enabled: IMP_MEMPROTCTLR reads 0x00000011,   */
/*    so RAMPROTIMP and RAMPROTEN are both set.  TRM 6.2.2 therefore      */
/*    applies -- a TCM location must be written before it is read, and    */
/*    ATCM needs 64-bit aligned stores where BTCM and CTCM accept 32-bit. */
/*                                                                        */
/*    The DDR window at 0x7A000000 is dark until DDR is initialised.      */
/*                                                                        */
/**************************************************************************/

#ifndef PLATFORM_H
#define PLATFORM_H

/* TCM bases.  The values the S32Z2 reference manual documents, which the core
   does not use until they are programmed -- ATCM boots at 0x00000000 and the
   other two boot disabled with an UNKNOWN base.  Each must be size-aligned
   (Cortex-R52 TRM r1p3 6.2), which these are: 64KB, 16KB and 16KB banks at
   64KB, 1MB and 1MB alignment respectively.  Programming ATCM here also moves
   it off address 0, so a null-pointer write faults instead of quietly landing
   in tightly-coupled memory.  */

#define S32Z_ATCM_BASE          0x30000000UL
#define S32Z_ATCM_SIZE          0x00010000UL    /* 64 KB, 1 wait state  */
#define S32Z_BTCM_BASE          0x30100000UL
#define S32Z_BTCM_SIZE          0x00004000UL    /* 16 KB, 0 wait states */
#define S32Z_CTCM_BASE          0x30200000UL
#define S32Z_CTCM_SIZE          0x00004000UL    /* 16 KB, 1 wait state  */

/* Memory-mapped register access.  Kept here rather than per-driver so that
   every peripheral in this BSP goes through one definition.
   MISRA C:2012 Rule 11.4/11.6 deviation: casting an integer address to a
   volatile pointer is inherent to memory-mapped device access.  */

#define REG32(address)  (*(volatile unsigned long *)(unsigned long)(address))

/* Code SRAM, instruction-fetch view.  7 MB.  This is where the core      */
/* resets to, and where .text is linked and loaded.  [verified on board]  */

#define S32Z_CODE_SRAM_BASE             0x79900000UL
#define S32Z_CODE_SRAM_SIZE             0x00700000UL

/* The same physical SRAM seen as data.  Kept here because the boot-from- */
/* flash path will need it, and because it is how the core's reset        */
/* instruction is planted by an external debugger.  [verified on board]   */

#define S32Z_CODE_SRAM_DATA_ALIAS       0x32100000UL

/* RTU data SRAM.  The RTU has 1 MB of it, in three contiguous banks that */
/* are all RTU-local -- when an RTU accesses its own blocks the traffic   */
/* stays inside the RTU.  The banks differ in speed, not in locality:     */
/*                                                                        */
/*     DRAM0  0x31780000  256 KB  full core speed                         */
/*     DRAM1  0x317C0000  256 KB  full core speed                         */
/*     DRAM2  0x31800000  512 KB  half core speed                         */
/*                                                                        */
/* S32Z2 Reference Manual Rev. 5, section 6.3.6 and Table 13.  Confirmed  */
/* on the board: writing distinct values to all three banks and reading   */
/* them back shows 1 MB of independent storage, and the first address     */
/* past DRAM2 aliases back onto its base, which is what fixes its size at */
/* 512 KB rather than the 2 MB an earlier revision of this file claimed.  */
/*                                                                        */
/* Note that NXP's own debugger memory map, s32z2e2_memory_regions.py in  */
/* S32 Design Studio, describes this last bank as 2 MB.  The Reference    */
/* Manual and the silicon agree it is 512 KB; the script is wrong here.   */

#define S32Z_DRAM0_BASE                 0x31780000UL
#define S32Z_DRAM0_SIZE                 0x00040000UL
#define S32Z_DRAM1_BASE                 0x317C0000UL
#define S32Z_DRAM1_SIZE                 0x00040000UL
#define S32Z_DRAM2_BASE                 0x31800000UL
#define S32Z_DRAM2_SIZE                 0x00080000UL

/* The full-speed pair, contiguous, and the right home for stacks and     */
/* .data.  This is what link.lds calls DATA.                              */

#define S32Z_DATA_SRAM_BASE             S32Z_DRAM0_BASE
#define S32Z_DATA_SRAM_SIZE             (S32Z_DRAM0_SIZE + S32Z_DRAM1_SIZE)

/* Console.  The EVB user guide (UG10268) dedicates LIN9 to the           */
/* daughtercard USB-UART, selected by jumper J248, so LINFlex_9 is the    */
/* instance that reaches the host -- not LINFlex_0, which is the first    */
/* one in the Reference Manual's list and the tempting wrong choice.      */
/* Base addresses from the RM; LINFlex_0's LINCR1 reset value 0x00000082  */
/* was read back from the board, which is what confirms the address space.*/

#define S32Z_LINFLEX_9_BASE             0x42980000UL    /* USB-UART  [RM]  */
#define S32Z_LINFLEX_0_BASE             0x40170000UL    /* [RM+board]      */

/* Mode Entry and Reset Generation, used by the debugger's init sequence  */
/* to release and clock the RTU cores.  Recorded because their contents   */
/* were what proved the core was released rather than held in reset.  [RM]*/

#define S32Z_MC_ME_PRTN0_PCONF          0x41900300UL
#define S32Z_MC_ME_PRTN0_CORE0_ADDR     0x4190034CUL
#define S32Z_RGM_PRST0                  0x41850048UL

/* Debug system as seen from a core: MDM-AP holds the per-core external   */
/* debug request bits that must be clear for the core to execute at all.  */
/* Reachable from the core context only.  [RM + verified on board]        */

/* RTU0 general-purpose registers.  CFG_CNTDV holds the divider that makes*/
/* the Cortex-R52 generic timer clock-enable, CNTCLKEN, from a cluster    */
/* clock. Reset value of the CNTDV field is 4.  [RM section 9.2.1.6]      */

/* RTU peripheral window, as described by IMP_PERIPHPREGIONR: 4 MB at     */
/* 0x76000000, reached through the low-latency peripheral port.           */

#define S32Z_RTU_PERIPH_BASE            0x76000000UL
#define S32Z_RTU_PERIPH_SIZE            0x00400000UL

#define S32Z_RTU0_GPR_BASE              0x76120000UL
#define S32Z_RTU0_GPR_CFG_CNTDV         (S32Z_RTU0_GPR_BASE + 0x10UL)

/* GICv3 for this R52 cluster.  IMP_CBAR reports the distributor base in  */
/* bits [31:21] and reads 0x47800000 on this board, confirming NXP's map  */
/* from the hardware -- the SoC reference manual gives no GIC address at  */
/* all, and its note that the "R52 Cluster set addr [31:21]" is just      */
/* CFGPERIPHBASE[31:21] restated.  Frame layout from Cortex-R52 TRM Table */
/* 9-1: distributor at +0x000000, redistributor control at +0x100000,     */
/* redistributor SGI/PPI at +0x110000, then +0x20000 per further core.    */
/* The region must be mapped Device nGnRnE before it can be read; with the*/
/* MPU disabled an access stalls the core.                                */

#define S32Z_GIC_BASE                   0x47800000UL
#define S32Z_GIC_SIZE                   0x00200000UL

/* Frames within that window, from Cortex-R52 TRM Table 9-1: distributor at
   +0x000000, redistributor control at +0x100000, redistributor SGI/PPI at
   +0x110000, then +0x20000 per further core.  Both frames verified on the
   board -- GICD_PIDR2 and GICR_PIDR2 both read 0x3B.

   These must be mapped Device nGnRnE before use.  With the region Normal, or
   with the MPU disabled, an access stalls the core outright: no abort, no
   fault handler, and the debug connection drops.  mpu.c maps them.  */

#define GICD_BASE                       (S32Z_GIC_BASE + 0x000000UL)
#define GICR_RD_BASE                    (S32Z_GIC_BASE + 0x100000UL)
#define GICR_SGI_BASE                   (S32Z_GIC_BASE + 0x110000UL)

#define S32Z_MDM_AP_BASE                0x4DC11000UL
#define S32Z_MDM_AP_CONTROL2            (S32Z_MDM_AP_BASE + 0x44UL)
#define S32Z_MDM_AP_RTU0_CORE0_EDBGREQ  0x00010000UL

#endif /* PLATFORM_H */
