/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    platform.h                                       Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Memory map and peripheral addresses for the NXP S32Z280-594EVB,     */
/*    RTU0 core 0 (R52_0_0).                                              */
/*                                                                        */
/*    Every address below was either read out of the S32Z2 Reference      */
/*    Manual (S32Z27RM Rev. 5.1) or confirmed on the board itself, and    */
/*    each is marked accordingly.  The distinction matters because this   */
/*    part differs from the Armv8-R AEM FVP in ways that are silent       */
/*    rather than loud: an address that is merely wrong tends to read     */
/*    back zero instead of faulting.                                      */
/*                                                                        */
/*  MEMORY                                                                */
/*                                                                        */
/*    The RTU exposes its code SRAM through two windows onto the same     */
/*    physical memory: 0x79900000 for instruction fetch (AXI-F) and       */
/*    0x32100000 as data.  Confirmed by writing a sentinel to one and     */
/*    reading it back through the other.  NXP's debugger memory map       */
/*    declares the fetch window read-only, but it is writable over the    */
/*    debug AXI port -- verified -- so a debugger-loaded image can be     */
/*    placed there directly and no load-address alias is needed.  A       */
/*    self-booting image loaded from flash would still need the data      */
/*    alias, since the core's own data side may not write through AXI-F.  */
/*                                                                        */
/*    The TCMs (0x30000000, 0x30100000, 0x30200000) are NOT accessible    */
/*    at reset -- reads fault -- because nothing has programmed the TCM   */
/*    region registers yet.  They are therefore unusable for early boot   */
/*    and are deliberately absent from this map.  The DDR window at       */
/*    0x7A000000 is likewise dark until DDR is initialised.               */
/*                                                                        */
/**************************************************************************/

#ifndef PLATFORM_H
#define PLATFORM_H

/* Code SRAM, instruction-fetch view.  7 MB.  This is where the core      */
/* resets to, and where .text is linked and loaded.  [verified on board]  */

#define S32Z_CODE_SRAM_BASE             0x79900000UL
#define S32Z_CODE_SRAM_SIZE             0x00700000UL

/* The same physical SRAM seen as data.  Kept here because the boot-from- */
/* flash path will need it, and because it is how the core's reset        */
/* instruction is planted by an external debugger.  [verified on board]   */

#define S32Z_CODE_SRAM_DATA_ALIAS       0x32100000UL

/* RTU-local data SRAM.  The Reference Manual notes that when an RTU      */
/* accesses its own blocks the traffic stays inside the RTU, so this is   */
/* the right home for stacks and .data.  256 KB.  [verified writable]     */

#define S32Z_DATA_SRAM_BASE             0x31780000UL
#define S32Z_DATA_SRAM_SIZE             0x00040000UL

/* Larger but not RTU-local: 2 MB, for images that outgrow the above.     */
/* [verified writable]                                                    */

#define S32Z_EXT_SRAM_BASE              0x31800000UL
#define S32Z_EXT_SRAM_SIZE              0x00200000UL

/* Console.  The EVB user guide (UG10268) dedicates LIN9 to the           */
/* daughtercard USB-UART, selected by jumper J248, so LINFlex_9 is the    */
/* instance that reaches the host -- not LINFlex_0, which is the first    */
/* one in the Reference Manual's list and the tempting wrong choice.      */
/* Base addresses from the RM; LINFlex_0's LINCR1 reset value 0x00000082  */
/* was read back from the board, which is what confirms the address space.*/

#define S32Z_LINFLEX_9_BASE             0x42980000UL    /* USB-UART  [RM]  */
#define S32Z_LINFLEX_0_BASE             0x40170000UL    /* [RM+board]      */

/* Mode Entry and Reset Generation, used by the debugger's init sequence  */
/* to release and clock the RTU cores.  Recorded because their contents   */
/* were what proved the core was released rather than held in reset.  [RM]*/

#define S32Z_MC_ME_PRTN0_PCONF          0x41900300UL
#define S32Z_MC_ME_PRTN0_CORE0_ADDR     0x4190034CUL
#define S32Z_RGM_PRST0                  0x41850048UL

/* Debug system as seen from a core: MDM-AP holds the per-core external   */
/* debug request bits that must be clear for the core to execute at all.  */
/* Reachable from the core context only.  [RM + verified on board]        */

#define S32Z_MDM_AP_BASE                0x4DC11000UL
#define S32Z_MDM_AP_CONTROL2            (S32Z_MDM_AP_BASE + 0x44UL)
#define S32Z_MDM_AP_RTU0_CORE0_EDBGREQ  0x00010000UL

#endif /* PLATFORM_H */
