/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    tcm.c                                            Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frederic Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Reads what the TCM hardware reports about itself.  See tcm.h for    */
/*    the register layouts and where they come from; nothing here is      */
/*    inferred from a neighbouring register's shape.                      */
/*                                                                        */
/*    Reading only.  Programming a base address and setting the enables    */
/*    comes after these values have been seen and agree with both the      */
/*    Cortex-R52 TRM and the S32Z2 reference manual, because a disagreement*/
/*    would mean one of the two documents does not describe this part and  */
/*    guessing which would be the whole PRBAR mistake again.              */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                   */
/*                                                                        */
/*    Dir 4.3 -- assembly encapsulated one operation per function.        */
/*                                                                        */
/**************************************************************************/

#include "tcm.h"

#define TCM_SIZE_SHIFT          2U
#define TCM_SIZE_MASK           0x1FUL
#define TCM_WAITSTATES_SHIFT    8U
#define TCM_ENABLE_EL2          (1UL << 1)
#define TCM_ENABLE_EL10         (1UL << 0)
#define TCM_BASE_SHIFT          13U     /* TRM table 3-136: [31:13] */

#define MEMPROT_RAMPROTIMP      (1UL << 4)
#define MEMPROT_RAMPROTEN       (1UL << 0)


static unsigned long read_atcmregionr(void)
{
    unsigned long value;
    __asm volatile ("mrc p15, 0, %0, c9, c1, 0" : "=r" (value));
    return value;
}

static unsigned long read_btcmregionr(void)
{
    unsigned long value;
    __asm volatile ("mrc p15, 0, %0, c9, c1, 1" : "=r" (value));
    return value;
}

static unsigned long read_ctcmregionr(void)
{
    unsigned long value;
    __asm volatile ("mrc p15, 0, %0, c9, c1, 2" : "=r" (value));
    return value;
}


/* SIZE is an encoding, not a shift count: 4 means 8KB and each step doubles,
   so 8KB << (field - 4).  Anything outside the documented range yields 0
   rather than a plausible-looking wrong number.  */

static unsigned long decode_size(unsigned int field)
{
    unsigned long bytes = 0UL;

    if ((field >= 4U) && (field <= 11U))
    {
        bytes = 0x2000UL << (field - 4U);
    }

    return bytes;
}


void tcm_read_bank(unsigned int index, tcm_bank_t *bank_ptr)
{
    unsigned long raw;

    if (bank_ptr == 0)
    {
        return;
    }

    switch (index)
    {
        case 0U:  raw = read_atcmregionr(); break;
        case 1U:  raw = read_btcmregionr(); break;
        case 2U:  raw = read_ctcmregionr(); break;
        default:  raw = 0UL;                break;
    }

    bank_ptr->raw         = raw;
    bank_ptr->base        = raw & ~((1UL << TCM_BASE_SHIFT) - 1UL);
    bank_ptr->size_field  = (unsigned int) ((raw >> TCM_SIZE_SHIFT) & TCM_SIZE_MASK);
    bank_ptr->size_bytes  = decode_size(bank_ptr->size_field);
    bank_ptr->wait_states = (unsigned int) ((raw >> TCM_WAITSTATES_SHIFT) & 1UL);
    bank_ptr->enable_el2  = ((raw & TCM_ENABLE_EL2) != 0UL) ? 1U : 0U;
    bank_ptr->enable_el10 = ((raw & TCM_ENABLE_EL10) != 0UL) ? 1U : 0U;
}


unsigned long tcm_read_memprotctlr(void)
{
    unsigned long value;

    /* Note opc1 is 1 here, not 0 as for the region registers.  */

    __asm volatile ("mrc p15, 1, %0, c9, c1, 2" : "=r" (value));
    return value;
}


unsigned int tcm_ecc_implemented(void)
{
    return ((tcm_read_memprotctlr() & MEMPROT_RAMPROTIMP) != 0UL) ? 1U : 0U;
}


unsigned int tcm_ecc_enabled(void)
{
    unsigned long ctlr = tcm_read_memprotctlr();

    /* RAMPROTEN is ignored when RAMPROTIMP is 0: the TRM says the design
       behaves as if it were 0, so report it that way rather than echoing a
       bit that has no effect.  */

    if ((ctlr & MEMPROT_RAMPROTIMP) == 0UL)
    {
        return 0U;
    }

    return ((ctlr & MEMPROT_RAMPROTEN) != 0UL) ? 1U : 0U;
}
