/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    thread_mpu.c                                     Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Per-thread memory protection.  See thread_mpu.h for what this is    */
/*    and is not.                                                        */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                   */
/*                                                                        */
/*    Directive 4.3 -- the MPU is only reachable through CP15; every      */
/*      access is encapsulated in a one-line accessor below.              */
/*                                                                        */
/**************************************************************************/

#include "tx_api.h"
#include "platform.h"
#include "mpu.h"
#include "timer.h"
#include "thread_mpu.h"

/* The region reprogrammed on every thread entry.  mpu.c programs 0 to 7, and
   MPUIR on this part reports 20, so 8 is free.  Chosen high on purpose: the
   shared regions keep their indices, so a thread that reaches this hook with no
   window still has code, stacks, console and GIC exactly as before.  */

#define THREAD_MPU_REGION       8UL

typedef struct
{
    TX_THREAD      *owner;
    unsigned long   base;
} thread_window_t;

static thread_window_t  windows[S32Z_THREAD_WINDOW_COUNT];

static unsigned long    switch_count;
static unsigned int     last_cycles;
static unsigned int     min_cycles = 0xFFFFFFFFU;
static unsigned int     max_cycles;


/**************************************************************************/
/*  CP15 accessors.                                                       */
/**************************************************************************/

/* Direct per-region access rather than PRSELR.

   The Cortex-R52 TRM 8.4 encodes the region number into CRm and opc2: CRm is
   0b1rrr where rrr is region_number[3:1], with opc2 0 and 1 for an even region
   and 4 and 5 for an odd one.  Regions 0 through 15 take CP15 op1 0 and regions
   16 through 24 take op1 1.  PRBAR and PRLAR without a number are the indirect
   view selected by PRSELR.

   Region 8 is therefore op1 0, CRm c12, opc2 0 and 1.  Using it removes the
   PRSELR write and, more importantly, the ISB that has to follow PRSELR before
   the region registers can be written.

   Measured on this part: 542 to 604 cycles through PRSELR against 434 to 470
   direct, for the same region and the same isolation result.  The saving matters
   most where several regions are programmed at once, which is what a module
   switch does -- there the PRSELR route pays an ISB per region while the direct
   route pays one barrier pair for the whole block.

   The TRM disagrees with itself about the range, and the next reader should not
   have to rediscover that.  The register descriptions at 3.3.85 and 3.3.86 say
   "Direct access is provided to PRBAR0 to PRBAR15" and list only the op1 0
   form; 8.4 and Table 8-9 list both forms.  Table 8-9 also prints opc2 0 for
   the even limit registers where the prose of 8.4 says 1.  What is written here
   uses op1 0 only, which is the half of the manual this part has been measured
   against.  */

/* Kept for regions 16 and above.  Those have direct op1 1 encodings in TRM 8.4,
   but only the selector route is proven on this part, and nothing here needs a
   region that high while the per-thread window lives at region 8.  */

__attribute__((unused))
static void write_prselr(unsigned long value)
{
    __asm__ volatile("mcr p15, 0, %0, c6, c2, 1" : : "r"(value) : "memory");
}

static void write_prbar8_direct(unsigned long value)
{
    __asm__ volatile("mcr p15, 0, %0, c6, c12, 0" : : "r"(value) : "memory");
}

static void write_prlar8_direct(unsigned long value)
{
    __asm__ volatile("mcr p15, 0, %0, c6, c12, 1" : : "r"(value) : "memory");
}

__attribute__((unused))
static void write_prbar(unsigned long value)
{
    __asm__ volatile("mcr p15, 0, %0, c6, c3, 0" : : "r"(value) : "memory");
}

__attribute__((unused))
static void write_prlar(unsigned long value)
{
    __asm__ volatile("mcr p15, 0, %0, c6, c3, 1" : : "r"(value) : "memory");
}


/**************************************************************************/
/*  Registration.                                                         */
/**************************************************************************/

unsigned long thread_mpu_window_base(unsigned int window)
{
    if ((unsigned long) window >= S32Z_THREAD_WINDOW_COUNT)
    {
        return 0UL;
    }

    return S32Z_THREAD_WINDOW_BASE
           + ((unsigned long) window * S32Z_THREAD_WINDOW_SIZE);
}

unsigned long thread_mpu_grant(TX_THREAD *thread_ptr, unsigned int window)
{
    unsigned long base = thread_mpu_window_base(window);

    if ((base == 0UL) || (thread_ptr == TX_NULL))
    {
        return 0UL;
    }

    windows[window].owner = thread_ptr;
    windows[window].base  = base;

    return base;
}


/**************************************************************************/
/*  Activation.                                                           */
/*                                                                        */
/*  Called explicitly by a thread rather than from the scheduler, and that */
/*  is a deliberate limitation of this step rather than the intended       */
/*  design.                                                              */
/*                                                                        */
/*  The port's scheduler does call _tx_execution_thread_enter under        */
/*  TX_ENABLE_EXECUTION_CHANGE_NOTIFY, which would make this automatic on  */
/*  every switch.  That macro is read by the port assembly compiled into   */
/*  the shared threadx library, so enabling it would oblige all nine       */
/*  example targets in this port -- including the FVP ones -- to supply    */
/*  the four execution hooks.  A ThreadX module port carries its own       */
/*  copies of the port assembly for exactly this reason, and that is where */
/*  the switch belongs.                                                   */
/*                                                                        */
/*  What this step establishes without that machinery: that a PMSAv8-R     */
/*  region can be reprogrammed per thread on this part, what it costs, and */
/*  that a violation faults.  Those are the questions worth answering      */
/*  before writing a module manager on top of them.                       */
/**************************************************************************/

void thread_mpu_activate(TX_THREAD *thread_ptr)
{
    unsigned int    before;
    unsigned int    after;
    unsigned int    delta;
    unsigned int    i;
    unsigned long   base = 0UL;

    before = timer_read_cycles();

    for (i = 0U; (unsigned long) i < S32Z_THREAD_WINDOW_COUNT; i++)
    {
        if (windows[i].owner == thread_ptr)
        {
            base = windows[i].base;
            break;
        }
    }

    if (base == 0UL)
    {
        /* No window for this thread: disable the region rather than leaving the
           previous thread's window in place.  Forgetting this is how per-thread
           protection silently becomes no protection -- the last thread to run
           would leave its window open to whatever ran next.  */

        write_prlar8_direct(0UL);
    }
    else
    {
        write_prbar8_direct((base & ~0x3FUL)
                    | ((unsigned long) MPU_SH_NON << 3)
                    | ((unsigned long) MPU_AP_RW_EL1 << 1)
                    | 1UL);                         /* XN: data only        */

        write_prlar8_direct(((base + S32Z_THREAD_WINDOW_SIZE - 1UL) & ~0x3FUL)
                    | ((unsigned long) MPU_ATTR_NORMAL_WB << 1)
                    | 1UL);                         /* EN                   */
    }

    __asm__ volatile("dsb sy" ::: "memory");
    __asm__ volatile("isb" ::: "memory");

    after = timer_read_cycles();
    delta = after - before;

    switch_count++;
    last_cycles = delta;
    if (delta < min_cycles) { min_cycles = delta; }
    if (delta > max_cycles) { max_cycles = delta; }
}


unsigned long thread_mpu_switch_count(void)  { return switch_count; }
unsigned int  thread_mpu_last_cycles(void)   { return last_cycles; }
unsigned int  thread_mpu_min_cycles(void)    { return min_cycles; }
unsigned int  thread_mpu_max_cycles(void)    { return max_cycles; }
