/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    thread_mpu.h                                     Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Per-thread memory protection for the NXP S32Z280-594EVB.            */
/*                                                                        */
/*    One MPU region is reprogrammed on every thread entry to grant the    */
/*    incoming thread access to its own window and nothing else.  A thread */
/*    with no window registered runs with that region disabled, so it      */
/*    reaches none of them.                                               */
/*                                                                        */
/*    This is a step towards a ThreadX module port for this core, not a    */
/*    substitute for one.  It demonstrates that PMSAv8-R regions can be    */
/*    switched per thread on this part, at a measured cost, and that a     */
/*    violation faults -- which are the questions worth answering before   */
/*    building a module manager on top of them.  There is no user mode, no */
/*    syscall boundary and no loader here.                                */
/*                                                                        */
/*    The hook is _tx_execution_thread_enter, which the port's scheduler   */
/*    already calls under TX_ENABLE_EXECUTION_CHANGE_NOTIFY, after the     */
/*    stack pointer has been switched.  No port assembly is modified.      */
/*                                                                        */
/**************************************************************************/

#ifndef THREAD_MPU_H
#define THREAD_MPU_H

#include "tx_api.h"

/* Apply a thread's window, or disable the region if it has none.  Called by the
   thread itself in this step; see the comment in thread_mpu.c for why it is not
   yet driven from the scheduler.  */

void            thread_mpu_activate(TX_THREAD *thread_ptr);

/* Give a thread exclusive access to one of the per-thread windows.  The index
   selects the window, 0 to S32Z_THREAD_WINDOW_COUNT - 1.  Returns the window's
   base address, or 0 if the index is out of range or the table is full.  */

unsigned long   thread_mpu_grant(TX_THREAD *thread_ptr, unsigned int window);

/* Base address of a window, whether or not it is granted to anyone.  Lets a
   test reach for a window it does not own.  */

unsigned long   thread_mpu_window_base(unsigned int window);

/* How many thread entries have reprogrammed the region, and what the last one
   cost in cycles.  The cost is the price of per-thread protection on this core
   and is the reason the hook records it.  */

unsigned long   thread_mpu_switch_count(void);
unsigned int    thread_mpu_last_cycles(void);
unsigned int    thread_mpu_min_cycles(void);
unsigned int    thread_mpu_max_cycles(void);

#endif
