/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    timer.c                                          Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Arm generic timer access for the S32Z280-594EVB.                    */
/*                                                                        */
/*    CNTFRQ reads zero on this silicon, exactly as it does on the        */
/*    Armv8-R AEM FVP.  CNTFRQ is only a software-populated constant --   */
/*    nothing derives the counter's real rate from it -- so a zero there  */
/*    says nothing about whether the counter is running.  The only way to */
/*    find that out is to read CNTPCT twice and see whether it moved,     */
/*    which is what this file exists to support.                          */
/*                                                                        */
/*    The rate itself is measured rather than computed.  The RTU divides  */
/*    a cluster clock by RTU.GPR CFG_CNTDV to generate the timer's        */
/*    clock-enable, so deriving it needs the divider AND the cluster clock*/
/*    AND the PLL configuration feeding it -- three places to be wrong.   */
/*    Sampling CNTPCT against host wall-clock time needs none of them and */
/*    is checkable against the clock tree afterwards.                     */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                   */
/*                                                                        */
/*    Dir 4.3 -- assembly language shall be encapsulated and isolated.    */
/*      Each coprocessor access is wrapped in its own function below.     */
/*                                                                        */
/**************************************************************************/

#include "timer.h"

unsigned long long timer_read_cntpct(void)
{
    unsigned int    low;
    unsigned int    high;

    /* CNTPCT is 64-bit and read as a pair through MRRC.  The read is
       atomic in the architecture, so no high/low re-read dance is needed.  */

    __asm volatile ("mrrc p15, 0, %0, %1, c14" : "=r" (low), "=r" (high));

    return ((unsigned long long)high << 32) | (unsigned long long)low;
}


unsigned int timer_read_cntfrq(void)
{
    unsigned int value;

    __asm volatile ("mrc p15, 0, %0, c14, c0, 0" : "=r" (value));

    return value;
}


void timer_spin(unsigned int iterations)
{
    unsigned int i;

    for (i = 0U; i < iterations; i++)
    {
        /* Kept from being optimised away, and kept from being turned into
           something clever: the loop's only job is to burn a repeatable
           amount of time between two counter samples.  */

        __asm volatile ("nop" ::: "memory");
    }
}


/* CNTP_CTL bits.  IMASK is set so the compare raises no interrupt: there is
   no GIC configured yet, and an unhandled PPI would be taken as an exception
   rather than politely ignored.  */

#define CNTP_CTL_ENABLE         (1U << 0)
#define CNTP_CTL_IMASK          (1U << 1)
#define CNTP_CTL_ISTATUS        (1U << 2)


void timer_start_oneshot_irq(unsigned int ticks)
{
    /* Same as timer_start_oneshot but with IMASK CLEAR, so the compare raises
       an interrupt instead of only setting ISTATUS.  Keeping the two arming
       functions separate rather than adding a flag: the polled path must never
       accidentally unmask before the GIC is up, and an interrupt-driven path
       that silently leaves IMASK set produces a timer that fires internally
       while no interrupt is ever delivered -- IRQ count 0 with no spurious and
       no unexpected INTID, which is exactly how that mistake presents.  */

    unsigned int control = CNTP_CTL_ENABLE;

    __asm volatile ("mcr p15, 0, %0, c14, c2, 0" :: "r" (ticks));
    __asm volatile ("mcr p15, 0, %0, c14, c2, 1" :: "r" (control));
    __asm volatile ("isb");
}


void timer_start_oneshot(unsigned int ticks)
{
    unsigned int control = CNTP_CTL_ENABLE | CNTP_CTL_IMASK;

    /* TVAL is a down-counter loaded relative to now, which avoids the 64-bit
       read-modify-write that setting CVAL absolutely would need.  */

    __asm volatile ("mcr p15, 0, %0, c14, c2, 0" :: "r" (ticks));
    __asm volatile ("mcr p15, 0, %0, c14, c2, 1" :: "r" (control));
    __asm volatile ("isb");
}


unsigned int timer_fired(void)
{
    unsigned int control;

    __asm volatile ("mrc p15, 0, %0, c14, c2, 1" : "=r" (control));

    return ((control & CNTP_CTL_ISTATUS) != 0U) ? 1U : 0U;
}


void timer_stop(void)
{
    unsigned int control = 0U;

    __asm volatile ("mcr p15, 0, %0, c14, c2, 1" :: "r" (control));
    __asm volatile ("isb");
}


/**************************************************************************/
/*  PMU cycle counter.                                                    */
/*                                                                        */
/*  PMCR.E gates all counters including the dedicated cycle counter, and   */
/*  PMCNTENSET bit 31 enables that counter specifically.  Both are needed. */
/*  PMCR.D is left clear so the counter advances every cycle rather than   */
/*  every 64th, which is the resolution these measurements want.          */
/**************************************************************************/

#define PMCR_E      (1UL << 0)      /* enable all counters                 */
#define PMCR_P      (1UL << 1)      /* reset event counters                */
#define PMCR_C      (1UL << 2)      /* reset cycle counter                 */
#define PMCNTENSET_C (1UL << 31)    /* cycle counter enable                */

void timer_cycles_enable(void)
{
    unsigned long pmcr;

    /* Allow EL0/EL1 access and enable, resetting the counter as we go.  */

    __asm__ volatile("mrc p15, 0, %0, c9, c12, 0" : "=r"(pmcr));
    pmcr |= (PMCR_E | PMCR_C);
    __asm__ volatile("mcr p15, 0, %0, c9, c12, 0" : : "r"(pmcr) : "memory");

    __asm__ volatile("mcr p15, 0, %0, c9, c12, 1"
                     : : "r"((unsigned long) PMCNTENSET_C) : "memory");

    __asm__ volatile("isb" ::: "memory");
}

unsigned int timer_read_cycles(void)
{
    unsigned long value;
    __asm__ volatile("mrc p15, 0, %0, c9, c13, 0" : "=r"(value));
    return (unsigned int) value;
}
