/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    timer.h                                          Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Arm generic timer access for the S32Z280-594EVB.                    */
/*                                                                        */
/**************************************************************************/

#ifndef TIMER_H
#define TIMER_H

/* The physical count, CNTPCT.  64-bit, read as a pair.  Reading it is the
   only way to find out whether the system counter is running at all: CNTFRQ
   reads zero on this part and so says nothing about the counter itself.  */

unsigned long long  timer_read_cntpct(void);

/* CNTFRQ as currently programmed.  Zero out of reset on this silicon.    */

unsigned int        timer_read_cntfrq(void);

/* Crude calibrated-by-nothing delay, used only to separate counter samples
   far enough apart to measure a rate.  Not a time delay: the core clock is
   not yet established, which is precisely what the measurement is for.  */

void                timer_spin(unsigned int iterations);

/* One-shot compare on the EL1 physical timer, interrupt masked.  Polled
   deliberately: this proves the timer counts and fires before the GIC is
   configured, so a later interrupt failure cannot be confused with the timer
   itself being wrong.  */

void                timer_start_oneshot(unsigned int ticks);

/* Arms with the interrupt UNMASKED, for the interrupt-driven path.       */

void                timer_start_oneshot_irq(unsigned int ticks);
unsigned int        timer_fired(void);
void                timer_stop(void);

/* PMU cycle counter.  CNTPCT runs at 8 MHz on this part, so its 125 ns
   granularity is too coarse to resolve interrupt latency, let alone the jitter
   in it.  The cycle counter runs at the core clock and is what those
   measurements use.  timer_cycles_enable must be called before any read.  */

void                timer_cycles_enable(void);
unsigned int        timer_read_cycles(void);

#endif /* TIMER_H */
