/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  BOARD SUPPORT                                          RELEASE        */
/*                                                                        */
/*    timer.c                                          Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Arm generic timer access for the S32Z280-594EVB.                    */
/*                                                                        */
/*    CNTFRQ reads zero on this silicon, exactly as it does on the        */
/*    Armv8-R AEM FVP.  CNTFRQ is only a software-populated constant --   */
/*    nothing derives the counter's real rate from it -- so a zero there  */
/*    says nothing about whether the counter is running.  The only way to */
/*    find that out is to read CNTPCT twice and see whether it moved,     */
/*    which is what this file exists to support.                          */
/*                                                                        */
/*    The rate itself is measured rather than computed.  The RTU divides  */
/*    a cluster clock by RTU.GPR CFG_CNTDV to generate the timer's        */
/*    clock-enable, so deriving it needs the divider AND the cluster clock*/
/*    AND the PLL configuration feeding it -- three places to be wrong.   */
/*    Sampling CNTPCT against host wall-clock time needs none of them and */
/*    is checkable against the clock tree afterwards.                     */
/*                                                                        */
/*  MISRA C:2012 deviations (justified)                                   */
/*                                                                        */
/*    Dir 4.3 -- assembly language shall be encapsulated and isolated.    */
/*      Each coprocessor access is wrapped in its own function below.     */
/*                                                                        */
/**************************************************************************/

#include "timer.h"

unsigned long long timer_read_cntpct(void)
{
    unsigned int    low;
    unsigned int    high;

    /* CNTPCT is 64-bit and read as a pair through MRRC.  The read is
       atomic in the architecture, so no high/low re-read dance is needed.  */

    __asm volatile ("mrrc p15, 0, %0, %1, c14" : "=r" (low), "=r" (high));

    return ((unsigned long long)high << 32) | (unsigned long long)low;
}


unsigned int timer_read_cntfrq(void)
{
    unsigned int value;

    __asm volatile ("mrc p15, 0, %0, c14, c0, 0" : "=r" (value));

    return value;
}


void timer_spin(unsigned int iterations)
{
    unsigned int i;

    for (i = 0U; i < iterations; i++)
    {
        /* Kept from being optimised away, and kept from being turned into
           something clever: the loop's only job is to burn a repeatable
           amount of time between two counter samples.  */

        __asm volatile ("nop" ::: "memory");
    }
}


/* CNTP_CTL bits.  IMASK is set so the compare raises no interrupt: there is
   no GIC configured yet, and an unhandled PPI would be taken as an exception
   rather than politely ignored.  */

#define CNTP_CTL_ENABLE         (1U << 0)
#define CNTP_CTL_IMASK          (1U << 1)
#define CNTP_CTL_ISTATUS        (1U << 2)


void timer_start_oneshot(unsigned int ticks)
{
    unsigned int control = CNTP_CTL_ENABLE | CNTP_CTL_IMASK;

    /* TVAL is a down-counter loaded relative to now, which avoids the 64-bit
       read-modify-write that setting CVAL absolutely would need.  */

    __asm volatile ("mcr p15, 0, %0, c14, c2, 0" :: "r" (ticks));
    __asm volatile ("mcr p15, 0, %0, c14, c2, 1" :: "r" (control));
    __asm volatile ("isb");
}


unsigned int timer_fired(void)
{
    unsigned int control;

    __asm volatile ("mrc p15, 0, %0, c14, c2, 1" : "=r" (control));

    return ((control & CNTP_CTL_ISTATUS) != 0U) ? 1U : 0U;
}


void timer_stop(void)
{
    unsigned int control = 0U;

    __asm volatile ("mcr p15, 0, %0, c14, c2, 1" :: "r" (control));
    __asm volatile ("isb");
}
