/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  MODULE MANAGER SAMPLE                                  RELEASE        */
/*                                                                        */
/*    sample_threadx_module_manager.c                  Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    Loads the sample module three times, lets it misbehave every time,   */
/*    and reports what the hardware did about it.                          */
/*                                                                        */
/*    The result this example exists to produce is the fault.  A module    */
/*    that starts and runs proves the loader works; a module that is       */
/*    stopped by the memory protection unit when it reaches outside its    */
/*    own memory proves the port works.  So the fault notification is not  */
/*    an error path here, it is the expected outcome, and its absence is   */
/*    the failure.                                                        */
/*                                                                        */
/*    TWO passes, because one proves nothing about relocation.  The module */
/*    is position independent: it is linked against nominal addresses it   */
/*    never runs at, and _gcc_setup rewrites its global offset table to    */
/*    wherever the manager actually put it.  A single run at the linked    */
/*    address would exercise a rebase whose input and output are the same  */
/*    number, and would look identical if the rebase did nothing at all.   */
/*                                                                        */
/*    So pass 1 loads the blob where the linker placed it and pass 2 loads */
/*    a byte-for-byte copy of it from the staging area, with pass 1 still  */
/*    holding its pool memory so that pass 2's data lands somewhere else    */
/*    too.  Both the code base and the data base therefore differ between  */
/*    the passes, which is what makes the comparison at the end mean       */
/*    something:                                                          */
/*                                                                        */
/*      * the same instruction faults in both passes -- equal offsets from */
/*        each pass's own code base, at two different absolute addresses.  */
/*        The module ran relocated.                                       */
/*      * DFAR is the forbidden address in both passes.  The module got    */
/*        that value by reading one of its own initialised globals through */
/*        the rebased GOT, so this single register proves the GOT was      */
/*        rewritten and .data was copied.                                 */
/*      * SPSR says User mode in both passes.  The boundary held.         */
/*                                                                        */
/*    All of which is checked on the console, with no help from a debugger */
/*    and without the manager needing to know one symbol of the module.    */
/*                                                                        */
/*    THEN A THIRD PASS, which faults the other way.  The two passes above */
/*    make the module read an address it does not own: a data abort,        */
/*    reported through DFSR and DFAR.  A module can equally leave its code  */
/*    region, which is a prefetch abort reported through IFSR and IFAR and  */
/*    arrives at the handler by a different vector.  Both halves of the     */
/*    port's fault path are therefore exercised, and neither is inferred    */
/*    from the other.                                                      */
/*                                                                        */
/*    Which violation a pass commits is chosen here, not in the module: the */
/*    manager writes the application-defined module ID in the instance      */
/*    after loading it, and the manager passes that word to the module's    */
/*    start thread.  So one blob covers both cases and the manager needs no */
/*    symbol of the module to select between them.                         */
/*                                                                        */
/*    The third pass runs after the first two have been unloaded, which is  */
/*    the other half of what this file demonstrates: a module fault must    */
/*    leave the manager able to load and run the next module.  A fault that */
/*    kills the manager is not isolation, and a fault that leaves the MPU   */
/*    in a state where the next load misbehaves is not either.             */
/*                                                                        */
/*    AND THE NOTIFICATION IS CHECKED, not merely printed.  The manager     */
/*    registers a fault-notify callback, and every pass must see it run     */
/*    exactly once with the faulting thread and the right module instance.  */
/*    That path used to be dead on this port -- the shared fault handler    */
/*    terminates the thread before calling the hook, which only returns if  */
/*    the port's abort vector tells the kernel it is inside an exception,    */
/*    and this port's did not.  It does now, so the hook is a result rather */
/*    than a known defect.                                                 */
/*                                                                        */
/*    What the module image is and where it comes from: it is linked into  */
/*    this application as a separate section and loaded in place, so       */
/*    nothing is copied and no filesystem or download path is needed.     */
/*    The manager still maps it with its own MPU regions, which is what    */
/*    matters -- loading in place changes where the code lives, not        */
/*    whether it is protected.                                            */
/*                                                                        */
/**************************************************************************/

#include "tx_api.h"
#include "txm_module.h"
#include "linflexd.h"
#include "platform.h"
#include "thread_mpu.h"
#include "cache.h"

/* The fault information the abort vector captured.  Declared here because the
   module manager expands it into the port's fault handler through the
   TXM_MODULE_MANAGER_FAULT_INFO macro rather than declaring it in a header, so an
   application that wants to read it has to say so itself.  */

extern TXM_MODULE_MANAGER_MEMORY_FAULT_INFO     _txm_module_manager_memory_fault_info;

/* Where the module image sits.  Provided by the linker script, which places the
   module's preamble first so this address is also the preamble address.  */

extern unsigned char    __module_image_start__;
extern unsigned char    __module_image_end__;

/* The second address the same blob is loaded from, so relocation can be shown
   rather than assumed.  Reserved by the linker script and left empty by it --
   see .module_stage in link_module.lds for why it is not pre-filled.  */

extern unsigned char    __module_stage_start__;
extern unsigned char    __module_stage_end__;

/* The address the module is going to reach for and must not be allowed to have.
   Declared here only so the console check can name it; the value lives in the
   module's own initialised data, which is the point -- the module reads it
   through its rebased GOT, so seeing it arrive in DFAR proves the rebase and
   the .data copy both worked.  Kept in step with sample_threadx_module.c by
   hand, and checked at run time rather than trusted: if the two ever disagree
   the relocation verdict says so instead of quietly passing.  */

#define MODULE_FORBIDDEN_ADDRESS    0x31780000UL

/* Which violation a pass tells the module to commit.  Written into the module
   instance's application-defined ID after the load and before the start, because
   that word is what the manager hands the module's start thread.  The high half
   is the fingerprint the preamble ships; only the low byte selects the test, so a
   module started without this still runs the data-abort case.  */

#define MODULE_ID_BASE              0x52520000UL
#define MODULE_TEST_DATA_ABORT      0x00000001UL
#define MODULE_TEST_PREFETCH_ABORT  0x00000002UL

/* Memory the manager hands out to modules: object memory, and the data region a
   module's own variables live in.  It has to be outside every region a module is
   given, or a module could reach another module's data.  */

#ifndef MODULE_POOL_SIZE
#define MODULE_POOL_SIZE    (16U * 1024U)
#endif

/* In the module area, not in .bss.  The manager carves a module's data out of
   this pool, and that data is handed to the module as an MPU region -- so if the
   pool lived in .bss it would sit inside the kernel's data region and the two
   would overlap, which PMSAv8-R does not allow.  Keeping the pool in the module
   area is what makes a module's data disjoint from every kernel region.  */

static unsigned char    module_pool[MODULE_POOL_SIZE]
                            __attribute__((aligned(64), section(".module_pool")));

/* The object pool, which is a separate allocation from the module pool above and
   is not optional here.  A module that runs in User mode needs a kernel stack
   for the privileged side of each system call, and the manager allocates that
   from this pool -- txm_module_manager_initialize deliberately leaves the pool
   uncreated, so without this a User-mode module fails to start with
   TX_NOT_AVAILABLE from deep inside the thread create, which is not an obvious
   way to be told that a pool is missing.  */

#ifndef MODULE_OBJECT_POOL_SIZE
#define MODULE_OBJECT_POOL_SIZE     (8U * 1024U)
#endif

static unsigned char    module_object_pool[MODULE_OBJECT_POOL_SIZE]
                            __attribute__((aligned(64)));

/* One instance per pass.  Passes 1 and 2 are loaded at once for part of the run:
   pass 1 is stopped but still holds its data allocation while pass 2 loads, which
   is what pushes pass 2's data base somewhere different.  Pass 3 runs after both
   have been unloaded, which is deliberate -- see the header.  */

#define MODULE_PASSES       3U
#define MODULE_RELOCATION_PASSES    2U

static TXM_MODULE_INSTANCE  demo_module[MODULE_PASSES];

/* What each pass produced.  Recorded rather than printed as it happens, because
   the comparison between the two passes is the actual result and it cannot be
   made until both have run.  */

typedef struct PASS_RESULT_STRUCT
{
    CHAR        *pass_name;
    ULONG        pass_test;              /* MODULE_TEST_*: which abort is expected */
    ULONG        pass_load_status;
    ULONG        pass_start_status;
    ULONG        pass_stop_status;
    ULONG        pass_code_start;
    ULONG        pass_code_end;
    ULONG        pass_data_start;
    ULONG        pass_data_end;
    ULONG        pass_data_base;
    ULONG        pass_faults;
    ULONG        pass_captured;
    ULONG        pass_fault_r9;
    ULONG        pass_dfsr;
    ULONG        pass_dfar;
    ULONG        pass_ifsr;
    ULONG        pass_ifar;
    ULONG        pass_spsr;
    ULONG        pass_code_location;

    /* What the notify callback was told, against what it should have been told.
       Recorded as plain words rather than pointers so the console can print them
       and a mismatch names both values.  */

    ULONG        pass_notify_thread;
    ULONG        pass_notify_instance;
    ULONG        pass_expect_thread;
    ULONG        pass_expect_instance;
} PASS_RESULT;

static PASS_RESULT      pass_results[MODULE_PASSES];

/* What the fault handler saw.  Read by the reporting thread after the module has
   been terminated.  */

static volatile ULONG   fault_count;
static volatile ULONG   fault_dfsr;
static volatile ULONG   fault_dfar;
static volatile ULONG   fault_ifsr;
static volatile ULONG   fault_ifar;
static volatile ULONG   fault_spsr;
static volatile ULONG   fault_code_location;
static volatile ULONG   fault_notify_thread;
static volatile ULONG   fault_notify_instance;

static TX_THREAD        report_thread;
static unsigned char    report_stack[2048] __attribute__((aligned(8)));

/* The two symbols the debug harness stops on, declared here because they have
   external linkage and are called before they are defined -- MISRA C:2012 Rule
   8.4 wants a visible declaration either way.  Both are defined below; see each
   for why it exists rather than a line number in a loop.  */

void    manager_done(void);
void    pass_done(void);


/**************************************************************************/
/*  Fault notification.                                                   */
/*                                                                        */
/*  Called by the module manager after it has terminated the offending     */
/*  thread.  Records rather than prints, for two reasons: this runs in the */
/*  fault path, where the console is a polled driver that spins waiting    */
/*  for a transmit to complete -- and it runs in Abort mode on the Abort    */
/*  stack, which is a kilobyte on this board and already carries the       */
/*  terminate underneath this frame.  A callback that printed would work    */
/*  and would still be the wrong shape to copy.                           */
/*                                                                        */
/*  Its two arguments are the point of the hook, so they are recorded and  */
/*  checked rather than discarded: an application is being told WHICH      */
/*  thread and WHICH module faulted, and a callback that fires with the    */
/*  wrong pair is no more use than one that never fires.                   */
/**************************************************************************/

static void module_fault_notify(TX_THREAD *thread_ptr, TXM_MODULE_INSTANCE *module_instance)
{
    fault_count++;
    fault_notify_thread   = (ULONG) thread_ptr;
    fault_notify_instance = (ULONG) module_instance;
    fault_dfsr          = _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_dfsr;
    fault_dfar          = _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_dfar;
    fault_ifsr          = _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_ifsr;
    fault_ifar          = _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_ifar;
    fault_spsr          = _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_spsr;
    fault_code_location = (ULONG) _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_code_location;
}


static void put_hex(unsigned long value)
{
    linflexd_put_hex32((unsigned int) value);
}


static void put_field(const char *label, unsigned long value)
{
    linflexd_puts(label);
    put_hex(value);
    linflexd_puts("\n");
}


/**************************************************************************/
/*  A byte copy, written out rather than called for.                      */
/*                                                                        */
/*  The manager links -nostdlib, and reaching for memcpy would pull in a   */
/*  libc whose presence this example does not otherwise depend on.  The    */
/*  blob is under two kilobytes and this runs once.                       */
/**************************************************************************/

static void copy_bytes(unsigned char *destination, const unsigned char *source,
                       unsigned long length)
{
    unsigned long   i;

    for (i = 0UL; i < length; i++)
    {
        destination[i] = source[i];
    }
}


/**************************************************************************/
/*  One pass: load the blob from a given address, start it, wait for the   */
/*  fault it is written to provoke, and stop it.                          */
/*                                                                        */
/*  The module is left loaded.  Its data allocation is what moves the next */
/*  pass's data base, and releasing it here would defeat half the test.    */
/*  Unloading happens after both passes have run.                         */
/**************************************************************************/

/* name is CHAR * and not const CHAR *, because txm_module_manager_in_place_load
   takes it that way -- the manager stores the pointer in the instance and the API
   has never promised not to write through it.  */

static void run_one_pass(UINT index, CHAR *name, VOID *location, ULONG test)
{
    PASS_RESULT            *result = &pass_results[index];
    TXM_MODULE_INSTANCE    *instance = &demo_module[index];
    unsigned int            waited;

    result -> pass_name = name;
    result -> pass_test = test;

    /* Cleared before the module starts, so a fault counted here belongs to this
       pass and not the previous one.  */

    fault_count           = 0UL;
    fault_notify_thread   = 0UL;
    fault_notify_instance = 0UL;

    result -> pass_load_status = (ULONG) txm_module_manager_in_place_load(instance, name, location);

    if (result -> pass_load_status != (ULONG) TX_SUCCESS)
    {
        return;
    }

    /* Which violation this pass provokes.  Written after the load, which is what
       filled the field in from the preamble, and before the start, which is what
       hands it to the module's start thread.  */

    instance -> txm_module_instance_application_module_id = MODULE_ID_BASE | test;

    /* What the notify callback must be told, recorded before the module runs so
       the comparison afterwards is against an expectation and not against
       whatever the callback happened to write.  */

    result -> pass_expect_thread   = (ULONG) &(instance -> txm_module_instance_start_stop_thread);
    result -> pass_expect_instance = (ULONG) instance;

    /* Read from the instance rather than computed here.  Where the code ended up
       is what the manager decided, and the whole point of the comparison at the
       end is to check the module against the manager's own numbers.  */

    result -> pass_code_start  = (ULONG) instance -> txm_module_instance_code_start;
    result -> pass_code_end    = (ULONG) instance -> txm_module_instance_code_end;
    result -> pass_data_start  = (ULONG) instance -> txm_module_instance_data_start;
    result -> pass_data_end    = (ULONG) instance -> txm_module_instance_data_end;
    result -> pass_data_base   = (ULONG) instance -> txm_module_instance_module_data_base_address;

    result -> pass_start_status = (ULONG) txm_module_manager_start(instance);

    if (result -> pass_start_status != (ULONG) TX_SUCCESS)
    {
        return;
    }

    /* Wait for the abort vector to capture a fault belonging to THIS pass.

       The captured fault info is waited on rather than the notify callback, even
       though the callback now works.  The capture happens in the abort vector
       before anything else runs, so it is the earliest and most direct evidence
       that a fault occurred; the callback is a later consequence of the same
       event, and this file checks it separately.  Waiting on the earlier of the
       two means a regression in the callback path shows up as "notified 0" next
       to a captured fault, rather than as "no fault occurred" -- which is the
       opposite of the truth and is exactly what an earlier version of this file
       reported.

       Attribution is by thread pointer: each pass has its own module instance and
       therefore its own start thread, so a captured fault naming this pass's
       thread cannot be a leftover from the previous pass.  */

    waited = 0U;
    while ((_txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_thread_ptr
                != &(instance -> txm_module_instance_start_stop_thread)) &&
           (waited < 50U))
    {
        tx_thread_sleep(2UL);
        waited++;
    }

    if (_txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_thread_ptr
            == &(instance -> txm_module_instance_start_stop_thread))
    {
        result -> pass_captured      = 1UL;
        result -> pass_dfsr          = _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_dfsr;
        result -> pass_dfar          = _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_dfar;
        result -> pass_ifsr          = _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_ifsr;
        result -> pass_ifar          = _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_ifar;
        result -> pass_spsr          = _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_spsr;
        result -> pass_fault_r9      = _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_r9;
        result -> pass_code_location = (ULONG) _txm_module_manager_memory_fault_info.txm_module_manager_memory_fault_info_code_location;
    }

    /* What the notify callback saw.  Read after the wait above, so a callback
       that ran is recorded and one that did not shows as zero.  */

    result -> pass_faults          = fault_count;
    result -> pass_notify_thread   = fault_notify_thread;
    result -> pass_notify_instance = fault_notify_instance;

    /* Stopped, not unloaded.  The fault terminated the module's start thread but
       left the module STARTED, and unload refuses anything that is not LOADED or
       STOPPED -- so this is required, not tidiness.  */

    result -> pass_stop_status = (ULONG) txm_module_manager_stop(instance);

    /* Still loaded, so the module's own memory is still where this pass's data
       base says it is.  See pass_done.  */

    pass_done();
}


static void report_one_pass(const PASS_RESULT *result)
{
    linflexd_puts("\n--- ");
    linflexd_puts(result -> pass_name);
    linflexd_puts(" ---\n");

    linflexd_puts("  expected abort   = ");
    if (result -> pass_test == MODULE_TEST_PREFETCH_ABORT)
    {
        linflexd_puts("prefetch (IFSR/IFAR)\n");
    }
    else
    {
        linflexd_puts("data (DFSR/DFAR)\n");
    }

    put_field("  load status      = ", result -> pass_load_status);
    put_field("  start status     = ", result -> pass_start_status);
    put_field("  stop status      = ", result -> pass_stop_status);
    put_field("  code region      = ", result -> pass_code_start);
    put_field("       .. to        = ", result -> pass_code_end);
    put_field("  data region      = ", result -> pass_data_start);
    put_field("       .. to        = ", result -> pass_data_end);
    put_field("  data base (r9)   = ", result -> pass_data_base);
    put_field("  fault captured   = ", result -> pass_captured);
    put_field("  notify callbacks = ", result -> pass_faults);
    put_field("  notified thread  = ", result -> pass_notify_thread);
    put_field("    should be      = ", result -> pass_expect_thread);
    put_field("  notified module  = ", result -> pass_notify_instance);
    put_field("    should be      = ", result -> pass_expect_instance);
    put_field("  r9 at the fault  = ", result -> pass_fault_r9);
    put_field("  DFSR             = ", result -> pass_dfsr);
    put_field("  DFAR             = ", result -> pass_dfar);
    put_field("  IFSR             = ", result -> pass_ifsr);
    put_field("  IFAR             = ", result -> pass_ifar);
    put_field("  SPSR             = ", result -> pass_spsr);
    put_field("  faulting pc      = ", result -> pass_code_location);

    /* Meaningful for a data abort, where the module faulted inside its own code.
       A prefetch abort faults ON the address it branched to, so the faulting pc
       is outside the module and the difference is not an offset into it.  */

    if (result -> pass_test != MODULE_TEST_PREFETCH_ABORT)
    {
        put_field("  pc - code base   = ", result -> pass_code_location - result -> pass_code_start);
    }
}


/**************************************************************************/
/*  Where the debugger stops.                                             */
/*                                                                        */
/*  A symbol and not a line number in the report loop.  The harness used   */
/*  to break on sample_threadx_module_manager.c:259, and every edit to     */
/*  this file moved that line -- after which the run stops somewhere       */
/*  arbitrary and reports whatever memory happens to hold, which looks     */
/*  like a result rather than a mistake.  This does not move.              */
/*                                                                        */
/*  Not static, and noinline, so it survives to the symbol table with an   */
/*  address a breakpoint can be set on.                                   */
/**************************************************************************/

__attribute__((noinline)) void manager_done(void)
{
    __asm__ volatile("nop");
}


/**************************************************************************/
/*  Where the debugger stops after each pass.                             */
/*                                                                        */
/*  A module's data is read back by the harness, not by the manager: the   */
/*  manager deliberately knows no symbol of the module, so it cannot find  */
/*  module_progress, while a debugger can compute its offset from the      */
/*  module's ELF and add it to the data base this pass recorded.           */
/*                                                                        */
/*  But it has to read it WHILE THIS PASS STILL HOLDS THAT MEMORY.  The    */
/*  byte pool reuses a freed block, so once a later pass has loaded, an     */
/*  earlier pass's data base points at the later pass's data -- and reading */
/*  every pass at the end of the run reports the last writer's progress for */
/*  all of them.  That is not a hypothetical: pass 3 loads after passes 1   */
/*  and 2 are unloaded and lands exactly where pass 1 was.                 */
/*                                                                        */
/*  So this exists to be broken on, once per pass, after the pass has       */
/*  faulted and been stopped and before anything is unloaded.              */
/**************************************************************************/

__attribute__((noinline)) void pass_done(void)
{
    __asm__ volatile("nop");
}


/**************************************************************************/
/*  Reporting.                                                            */
/**************************************************************************/

static void manager_entry(ULONG input)
{
    UINT            status;
    UINT            i;
    unsigned long   blob_size;
    ULONG           offset_0;
    ULONG           offset_1;
    UINT            failures = 0U;

    (void) input;

    /* Every manager call happens here, in a thread, and not in
       tx_application_define.  Loading a module takes the manager's mutex, and a
       service that can block cannot be called before the scheduler runs: the
       first version of this drove the manager from tx_application_define,
       printed its way as far as the load, and stopped there for ever.  The
       Armv8-M sample does all of this from a thread for the same reason.  */

    linflexd_puts("M1 initialize\n");
    status = txm_module_manager_initialize((VOID *) module_pool, MODULE_POOL_SIZE);

    linflexd_puts("initialize         = ");
    put_hex(status);
    linflexd_puts("  ready = ");
    put_hex((ULONG) _txm_module_manager_ready);
    linflexd_puts("\n");

    /* The pool the module's kernel stacks come from.  See module_object_pool.  */

    status = txm_module_manager_object_pool_create((VOID *) module_object_pool,
                                                  MODULE_OBJECT_POOL_SIZE);

    linflexd_puts("object pool create = ");
    put_hex(status);
    linflexd_puts("\n");

    /* Registered before anything is loaded, so there is no window in which a
       module could fault with nobody listening.  */

    linflexd_puts("M2 fault notify\n");
    txm_module_manager_memory_fault_notify(module_fault_notify);

    /* The copy that makes pass 2 a relocation test.  The staging area is left
       empty by the linker on purpose: if the blob were already there, a failure
       to copy would be invisible because the right bytes would be present
       anyway.  */

    blob_size = (unsigned long) (&__module_image_end__ - &__module_image_start__);

    linflexd_puts("M3 staging the blob\n");
    put_field("  blob size        = ", blob_size);
    put_field("  from             = ", (unsigned long) &__module_image_start__);
    put_field("  to               = ", (unsigned long) &__module_stage_start__);

    if (blob_size > (unsigned long) (&__module_stage_end__ - &__module_stage_start__))
    {
        /* Reported rather than allowed to overrun.  The staging area is a fixed
           size in the linker script and the module is free to grow.  */

        linflexd_puts("FAIL the module image does not fit the staging area\n");
        failures++;
    }
    else
    {
        copy_bytes(&__module_stage_start__, &__module_image_start__, blob_size);

        /* Those were data writes to memory that is about to be fetched as
           instructions, and the module area is mapped Normal write-back
           (MAIR attribute 0 is 0xFF).  So the copied bytes may sit in dirty D
           cache lines while the instruction side, which is not coherent with
           the D cache on this core, fetches whatever main memory still holds.
           Clean first so memory is correct, then invalidate the I cache so no
           stale line from a previous image can be served.

           This is not a precaution the passing run justifies.  It ran correctly
           before this was added, which is exactly the problem: a cold I cache
           over a never-executed address happens to work, and it keeps happening
           to work until the staging area is reused or an eviction lands
           differently.  Any loader that copies code owes this pair of
           operations, and by-range variants would be tighter than these
           all-cache sweeps -- fine here, where it runs once at startup.  */

        cache_clean_all();
        cache_invalidate_icache_all();

        /* Nothing to bracket for the MPU here.  No kernel region covers the
           module area, but the window that reaches it is owned by the scheduler,
           which enables it for every thread that does not own a module and
           disables it for every thread that does -- so it is already open on
           this thread and cannot be open while a module's own regions are.  */

        linflexd_puts("M4 pass 1, at the linked address\n");
        run_one_pass(0U, "linked address, data abort", (VOID *) &__module_image_start__,
                     MODULE_TEST_DATA_ABORT);

        linflexd_puts("M5 pass 2, relocated\n");
        run_one_pass(1U, "relocated, data abort", (VOID *) &__module_stage_start__,
                     MODULE_TEST_DATA_ABORT);

        /* Both relocation passes are done with their memory now.  Unloaded here
           rather than at the end, so that the pass below is a load that follows
           two faults and two unloads -- which is the state a manager is in after
           a module has misbehaved, and the state the next load has to work in.  */

        for (i = 0U; i < MODULE_RELOCATION_PASSES; i++)
        {
            (void) txm_module_manager_unload(&demo_module[i]);
        }

        /* The other abort type, from the staging area so that it is also a
           relocated module: the address arriving in IFAR came out of the module's
           own initialised data through its rebased GOT, exactly as DFAR does
           above.  */

        linflexd_puts("M6 pass 3, prefetch abort\n");
        run_one_pass(2U, "relocated, prefetch abort", (VOID *) &__module_stage_start__,
                     MODULE_TEST_PREFETCH_ABORT);

        (void) txm_module_manager_unload(&demo_module[2]);
    }

    /* ------------------------------------------------------------------
       The verdict.
       ------------------------------------------------------------------ */

    linflexd_puts("\n=== ThreadX modules on S32Z280: relocation and protection ===\n");

    for (i = 0U; i < MODULE_PASSES; i++)
    {
        report_one_pass(&pass_results[i]);
    }

    linflexd_puts("\n");

    /* Before anything else: a module's code and data regions are enabled at the
       same time, and PMSAv8-R has no region priority -- two enabled regions that
       overlap are CONSTRAINED UNPREDICTABLE, and on this part that means aborts
       from addresses that look perfectly legal.  Nothing in the manager checks
       for it, so this example does.

       The risk is real here and not theoretical: pass 2 loads its code from the
       staging area, which sits in the same 64 KB as the byte pool its data comes
       out of.  A module grown large enough, or a pool sized differently, and the
       two would meet.  */

    for (i = 0U; i < MODULE_PASSES; i++)
    {
        const PASS_RESULT *result = &pass_results[i];

        if (result -> pass_load_status != (ULONG) TX_SUCCESS)
        {
            continue;
        }

        if ((result -> pass_code_start <= result -> pass_data_end) &&
            (result -> pass_data_start <= result -> pass_code_end))
        {
            linflexd_puts("FAIL ");
            linflexd_puts(result -> pass_name);
            linflexd_puts(": its code and data regions overlap\n");
            failures++;
        }
    }

    /* Each pass on its own: it has to have loaded, started, faulted once, and
       faulted in User mode at the address it was told not to touch.  */

    for (i = 0U; i < MODULE_PASSES; i++)
    {
        const PASS_RESULT *result = &pass_results[i];

        if ((result -> pass_load_status != (ULONG) TX_SUCCESS) ||
            (result -> pass_start_status != (ULONG) TX_SUCCESS))
        {
            linflexd_puts("FAIL ");
            linflexd_puts(result -> pass_name);
            linflexd_puts(": did not load and start\n");
            failures++;
        }
        else if (result -> pass_captured == 0UL)
        {
            linflexd_puts("FAIL ");
            linflexd_puts(result -> pass_name);
            linflexd_puts(": reached outside its memory and was not stopped\n");
            failures++;
        }
        else if (result -> pass_fault_r9 != result -> pass_data_base)
        {
            /* r9 is the module's PIC base and the manager seeded it from the
               thread entry info.  If the value captured at the fault is not the
               data base the manager handed out, the seeding is wrong and every
               data reference the module made went somewhere unintended -- so
               check it explicitly rather than inferring it from a symptom.  */

            linflexd_puts("FAIL ");
            linflexd_puts(result -> pass_name);
            linflexd_puts(": r9 was not the module's data base\n");
            failures++;
        }
        else if ((result -> pass_spsr & 0x1FUL) != 0x10UL)
        {
            /* A fault from anywhere but User mode is not this test passing: the
               module runs unprivileged, so a privileged fault means the fault
               came from the kernel and something else is wrong.  */

            linflexd_puts("FAIL ");
            linflexd_puts(result -> pass_name);
            linflexd_puts(": faulted, but not from User mode\n");
            failures++;
        }
        else if (((result -> pass_test == MODULE_TEST_PREFETCH_ABORT) ?
                        result -> pass_ifar : result -> pass_dfar)
                            != MODULE_FORBIDDEN_ADDRESS)
        {
            /* The module got this address out of its own initialised data,
               through its rebased GOT.  Any other value means it faulted
               somewhere unintended -- most likely on its own data, which is what
               a bad rebase looks like.

               Which register carries it depends on the abort: a data abort
               reports the address it tried to touch in DFAR, a prefetch abort
               reports the address it tried to fetch in IFAR.  Checking the wrong
               one of the two passes for a stale value left by an earlier fault,
               which is why this is selected on the expected type rather than on
               whichever register happens to be non-zero.  */

            linflexd_puts("FAIL ");
            linflexd_puts(result -> pass_name);
            linflexd_puts(": faulted at the wrong address, so .data or the GOT is wrong\n");
            failures++;
        }
        else if (result -> pass_faults != 1UL)
        {
            /* The notify callback is a public API of the module manager, so it is
               checked and not merely reported.  Zero here with a captured fault
               above means the fault path reached the hardware's evidence and
               never reached the application: on this port that used to be the
               case for every fault, because the shared fault handler terminates
               the offending thread before calling the hook and the terminate only
               returns if the abort vector has told the kernel it is inside an
               exception.  More than one means a single violation was reported
               twice.  */

            linflexd_puts("FAIL ");
            linflexd_puts(result -> pass_name);
            linflexd_puts(": the fault-notify callback did not run exactly once\n");
            failures++;
        }
        else if ((result -> pass_notify_thread != result -> pass_expect_thread) ||
                 (result -> pass_notify_instance != result -> pass_expect_instance))
        {
            /* Being told that something faulted is not the service; being told
               which thread and which module is.  */

            linflexd_puts("FAIL ");
            linflexd_puts(result -> pass_name);
            linflexd_puts(": notified about the wrong thread or module\n");
            failures++;
        }
        else
        {
            linflexd_puts("PASS ");
            linflexd_puts(result -> pass_name);
            linflexd_puts(": faulted in User mode at the forbidden address, and was reported\n");
        }
    }

    /* And the first two passes against each other, which is the relocation
       result.  The third is not in this comparison: it faults on the address it
       branched to rather than inside its own code, so its faulting pc is not an
       offset into the module and there is nothing to compare.  */

    offset_0 = pass_results[0].pass_code_location - pass_results[0].pass_code_start;
    offset_1 = pass_results[1].pass_code_location - pass_results[1].pass_code_start;

    if ((pass_results[0].pass_captured == 0UL) || (pass_results[1].pass_captured == 0UL))
    {
        linflexd_puts("FAIL relocation: a pass did not fault, nothing to compare\n");
        failures++;
    }
    else if (pass_results[0].pass_code_start == pass_results[1].pass_code_start)
    {
        linflexd_puts("FAIL relocation: both passes ran from the same address\n");
        failures++;
    }
    else if (offset_0 != offset_1)
    {
        linflexd_puts("FAIL relocation: the two passes faulted at different offsets\n");
        failures++;
    }
    else
    {
        linflexd_puts("PASS relocation: the same blob ran correctly from two addresses\n");

        if (pass_results[0].pass_data_base == pass_results[1].pass_data_base)
        {
            /* Not a failure -- the code rebase is still proven -- but worth
               saying, because it means the data rebase produced the same
               numbers twice and was not exercised as thoroughly.  */

            linflexd_puts("NOTE both passes shared a data base; the data rebase was not varied\n");
        }
    }

    /* Both abort types, stated as its own line.  Each pass above already checked
       its own registers; this says that between them the two vectors were both
       taken, which is the claim a reader of the log wants to be able to make
       without working out what each pass did.  */

    if ((pass_results[0].pass_captured != 0UL) && (pass_results[0].pass_dfsr != 0UL) &&
        (pass_results[2].pass_captured != 0UL) && (pass_results[2].pass_ifsr != 0UL))
    {
        linflexd_puts("PASS both abort types: data through DFSR/DFAR, prefetch through IFSR/IFAR\n");
    }
    else
    {
        linflexd_puts("FAIL only one kind of abort was exercised\n");
        failures++;
    }

    put_field("\nfailures           = ", (unsigned long) failures);

    if (failures == 0U)
    {
        linflexd_puts("=== PASS ===\n");
    }
    else
    {
        linflexd_puts("=== FAIL ===\n");
    }

    linflexd_puts("=== end ===\n");

    /* Everything worth reading is in memory now.  */

    manager_done();

    while (1)
    {
        tx_thread_sleep(100UL);
    }
}


/**************************************************************************/
/*  Application definition.                                               */
/**************************************************************************/

/**************************************************************************/
/*  Board entry.                                                          */
/*                                                                        */
/*  entry.S calls this once the core is at EL1 with the MPU and caches     */
/*  configured.  Same shape as the other examples on this board: bring the */
/*  console up, say so, and enter the kernel.                              */
/**************************************************************************/

void bsp_main(void)
{
    (void) linflexd_init();

    linflexd_puts("\n=== ThreadX modules :: S32Z280-594EVB ===\n");
    linflexd_puts("entering kernel\n");

    tx_kernel_enter();

    /* Not reached.  */

    linflexd_puts("FAIL tx_kernel_enter returned\n");

    for (;;)
    {
        __asm__ volatile("nop");
    }
}


void tx_application_define(void *first_unused_memory)
{
    UINT    status;

    (void) first_unused_memory;

    linflexd_puts("\n=== module manager starting ===\n");

    /* Nothing but the thread.  See manager_entry for why the manager cannot be
       driven from here.  */

    status = tx_thread_create(&report_thread, "module manager", manager_entry, 0UL,
                              report_stack, sizeof(report_stack),
                              20U, 20U, TX_NO_TIME_SLICE, TX_AUTO_START);

    /* Reported rather than discarded.  A thread that was never created and a
       thread that was created but never scheduled produce exactly the same
       silence on the console, and telling those two apart is most of the work
       when the port itself is what is under test.  */

    if (status == TX_SUCCESS)
    {
        linflexd_puts("M0 thread created\n");
    }
    else
    {
        linflexd_puts("FAIL tx_thread_create status 0x");
        put_hex((ULONG) status);
        linflexd_puts("\n");
    }
}
