/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/**************************************************************************/
/*                                                                        */
/*  SAMPLE MODULE                                          RELEASE        */
/*                                                                        */
/*    sample_threadx_module.c                          Cortex-R52/GNU     */
/*                                                           6.5.2        */
/*  AUTHOR                                                                */
/*                                                                        */
/*    Frédéric Desbiens, Eclipse Foundation                               */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    A module that exercises the protection boundary rather than          */
/*    demonstrating features.                                             */
/*                                                                        */
/*    The Armv8-M sample module creates eight threads, a queue, a          */
/*    semaphore, a mutex, event flags and two pools.  That shows the API   */
/*    works; it does not show that the boundary works, and the boundary is */
/*    the only thing this port adds.  So this module does four things and  */
/*    stops:                                                              */
/*                                                                        */
/*      1. Writes and reads its own data, which must succeed.             */
/*      2. Makes a kernel call, which must succeed -- proving a module in  */
/*         User mode can reach the kernel through the supervisor call      */
/*         boundary and come back.                                        */
/*      3. Reads the manager's memory, which must fault.                   */
/*      4. Never reaches step 4, because step 3 terminates it.            */
/*                                                                        */
/*    Steps 1 and 2 passing without step 3 faulting would mean the module  */
/*    is running unprotected, which is the failure this example exists to  */
/*    detect.  A module that only ever touched its own memory would pass   */
/*    identically with the MPU switched off.                              */
/*                                                                        */
/*    The module cannot print.  The console belongs to the board support   */
/*    package, outside every region a module owns, so reaching it would    */
/*    fault as surely as step 3 does.  Progress is recorded in the         */
/*    module's own data and read back by the manager, which can print.     */
/*                                                                        */
/**************************************************************************/

#include "txm_module.h"

/* Progress, in the module's own data.  The manager reads this after the module
   faults, which is how a module with no console reports what it managed to do.  */

#define MODULE_PROGRESS_OWN_DATA        0x00000001UL
#define MODULE_PROGRESS_KERNEL_CALL     0x00000002UL
#define MODULE_PROGRESS_ATTEMPTED_STEAL 0x00000004UL
#define MODULE_PROGRESS_SURVIVED_STEAL  0x00000008UL

volatile ULONG  module_progress;
volatile ULONG  module_scratch[16];

/* An address the module has no business touching, used by step 3.

   It defaults to the base of DRAM0, which is where the manager's own data and
   stacks live on this board and is covered by a region the module does not own.
   The manager can overwrite this before starting the module if it wants to aim
   the test somewhere else, but it does not have to: locating a symbol inside a
   loaded module means walking its image, and an example should not need that to
   make its point.

   Whatever it holds must be outside every region the module owns, or step 3
   succeeds and the test silently proves nothing.  */

volatile ULONG  module_forbidden_address = 0x31780000UL;


void demo_module_start(ULONG id)
{
    ULONG   i;
    ULONG   sum = 0UL;

    (void) id;

    /* 1. The module's own data.  If this faults, the data region is wrong and
          nothing else in this file will be reached.  */

    for (i = 0UL; i < 16UL; i++)
    {
        module_scratch[i] = i * 3UL;
    }

    for (i = 0UL; i < 16UL; i++)
    {
        sum += module_scratch[i];
    }

    if (sum == 360UL)                       /* 3 * (0 + 1 + ... + 15) */
    {
        module_progress |= MODULE_PROGRESS_OWN_DATA;
    }

    /* 2. A kernel call, which leaves User mode through the supervisor call
          boundary and must come back.  A sleep is used because it is the
          simplest service with an observable effect and it yields, so the
          scheduler runs a module thread and reloads its regions on the way
          back -- exercising the region switch as well as the call.  */

    if (tx_thread_sleep(2UL) == TX_SUCCESS)
    {
        module_progress |= MODULE_PROGRESS_KERNEL_CALL;
    }

    /* 3. Somebody else's memory.  This must fault, and the fault must terminate
          this thread.  Marked before the access rather than after, because after
          is not reached if the port is working.  */

    module_progress |= MODULE_PROGRESS_ATTEMPTED_STEAL;

    sum += *((volatile ULONG *) module_forbidden_address);

    /* 4. Only reached if the access above was permitted, which means the module
          is running unprotected.  The manager treats this flag as a failure.  */

    module_progress |= MODULE_PROGRESS_SURVIVED_STEAL;

    /* Keep the compiler from discarding the read above.  */

    module_scratch[0] = sum;

    while (1)
    {
        (void) tx_thread_sleep(100UL);
    }
}
