#!/bin/bash
##############################################################################
# Copyright (c) 2026 Eclipse ThreadX contributors
#
# This program and the accompanying materials are made available under the
# terms of the MIT License which is available at
# https://opensource.org/licenses/MIT.
#
# AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
# The AI-generated portions may be considered public domain (CC0-1.0)
# and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.
#
# SPDX-License-Identifier: MIT and CC0-1.0
##############################################################################

# Builds the sample image for the AArch64 port this script sits in. Run
# build_threadx.sh first, which produces tx.a.
#
#     ./build_threadx_sample.sh
#     TOOLCHAIN=atfe ATFE_CLANG=/path/to/clang ./build_threadx_sample.sh
#
# The sample targets a fixed virtual platform: a GICv3 interrupt controller and
# an SP804 timer at the Base platform addresses. It is not expected to run on
# other models or on hardware without changing those addresses.

set -eu

cd "$(dirname "$(realpath "$0")")"

core="$(basename "$(cd ../.. && pwd)")"
case "${core}" in
    *_smp) cpu="${core%_smp}"; common="common_smp" ;;
    *)     cpu="${core}";      common="common" ;;
esac
cpu="${cpu//_/-}"

: "${TOOLCHAIN:=gnu}"
case "${TOOLCHAIN}" in
    gnu)
        CC="aarch64-none-elf-gcc"
        TARGET_FLAGS=""
        # rdimon supplies the semihosting syscalls and, with them, the real
        # initialise_monitor_handles that startup.S calls.
        SYSCALL_LIB="--specs=rdimon.specs"
        SEMIHOST_STUB=""
        ;;
    atfe)
        CC="${ATFE_CLANG:-clang}"
        TARGET_FLAGS="--target=aarch64-none-elf"
        SYSCALL_LIB="-lsemihost"
        # picolibc has no initialise_monitor_handles, and neither does the
        # toolchain's semihosting library, so the weak stub stands in for it.
        SEMIHOST_STUB="sample_threadx/semihost_stub.S"
        ;;
    *)
        echo "Unknown TOOLCHAIN '${TOOLCHAIN}'; expected gnu or atfe" >&2
        exit 1
        ;;
esac

CFLAGS="-g -mcpu=${cpu} -I../../../../${common}/inc -I../inc -Isample_threadx"

echo "Building the sample for ${cpu} with ${TOOLCHAIN}"

objects=""
for src in sample_threadx/startup.S sample_threadx/vectors.S \
           sample_threadx/v8_aarch64.S sample_threadx/v8_utils.S \
           sample_threadx/MP_Mutexes.S ${SEMIHOST_STUB} \
           sample_threadx/GICv3_gicd.c sample_threadx/GICv3_gicr.c \
           sample_threadx/sp804_timer.c sample_threadx/timer_interrupts.c \
           sample_threadx/sample_threadx.c; do
    [ -n "${src}" ] || continue
    obj="$(basename "${src}")"
    obj="${obj%.*}.o"
    "${CC}" ${TARGET_FLAGS} -c ${CFLAGS} "${src}" -o "${obj}"
    objects="${objects} ${obj}"
done

"${CC}" ${TARGET_FLAGS} -g -mcpu="${cpu}" -nostartfiles \
    -T sample_threadx/sample_threadx.ld ${SYSCALL_LIB} \
    -o sample_threadx.out -Wl,-Map=sample_threadx.map \
    ${objects} tx.a

rm -f ${objects}

echo "Done: $(basename "$(pwd)")/sample_threadx.out"
