/***************************************************************************
 * Copyright (c) 2024 Microsoft Corporation
 * Copyright (c) 2026-present Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **************************************************************************/

// Some portions generated by Copilot (Opus 5).


/**************************************************************************/
/**************************************************************************/
/**                                                                       */
/** ThreadX Component                                                     */
/**                                                                       */
/**   Thread                                                              */
/**                                                                       */
/**************************************************************************/
/**************************************************************************/


#define TX_SOURCE_CODE


/* Include necessary system files.  */

#include "tx_api.h"
#include "tx_thread.h"
#include <stdio.h>


/* Prototype for new thread entry function.  */

DWORD WINAPI _tx_win32_thread_entry(LPVOID p);


/**************************************************************************/
/*                                                                        */
/*  FUNCTION                                               RELEASE        */
/*                                                                        */
/*    _tx_thread_stack_build                            Win32/Visual      */
/*                                                           6.1          */
/*  AUTHOR                                                                */
/*                                                                        */
/*    William E. Lamie, Microsoft Corporation                             */
/*                                                                        */
/*  DESCRIPTION                                                           */
/*                                                                        */
/*    This function builds a stack frame on the supplied thread's stack.  */
/*    The stack frame results in a fake interrupt return to the supplied  */
/*    function pointer.                                                   */
/*                                                                        */
/*  INPUT                                                                 */
/*                                                                        */
/*    thread_ptr                            Pointer to thread control blk */
/*    function_ptr                          Pointer to return function    */
/*                                                                        */
/*  OUTPUT                                                                */
/*                                                                        */
/*    None                                                                */
/*                                                                        */
/*  CALLS                                                                 */
/*                                                                        */
/*    CreateThread                          Win32 create thread           */
/*    ResumeThread                          Win32 resume thread           */
/*    SetThreadPriority                     Win32 set thread priority     */
/*                                                                        */
/*  CALLED BY                                                             */
/*                                                                        */
/*    _tx_thread_create                     Create thread service         */
/*    _tx_thread_reset                      Reset thread service          */
/*                                                                        */
/**************************************************************************/
VOID   _tx_thread_stack_build(TX_THREAD *thread_ptr, VOID (*function_ptr)(VOID))
{
ALIGN_TYPE  fake_stack_ptr;

    /* Create a Win32 thread for the application thread.  */
    thread_ptr -> tx_thread_win32_thread_handle =
        CreateThread(NULL, 0, _tx_win32_thread_entry, (LPVOID) thread_ptr, CREATE_SUSPENDED,
                        &(thread_ptr -> tx_thread_win32_thread_id));

    /* Check for a good thread create.  */
    if (!thread_ptr -> tx_thread_win32_thread_handle)
    {

        /* Display an error message.  */
        printf("ThreadX Win32 error creating thread!\n");
        while(1)
        {
        }
    }

    /* Otherwise, we have a good thread create.  Now set the priority to
       a lower level.  */
    SetThreadPriority(thread_ptr -> tx_thread_win32_thread_handle, THREAD_PRIORITY_LOWEST);

    /* Create the run semaphore for the thread.  This will allow the scheduler
       control over when the thread actually runs.  */
    thread_ptr -> tx_thread_win32_thread_run_semaphore =  CreateSemaphore(NULL, 0, 1, NULL);

    /* Determine if the run semaphore was created successfully.  */
    if (!thread_ptr -> tx_thread_win32_thread_run_semaphore)
    {

        /* Display an error message.  */
        printf("ThreadX Win32 error creating thread running semaphore!\n");
        while(1)
        {
        }
    }

    /* Setup the thread suspension type to solicited thread suspension.
       Pseudo interrupt handlers will suspend with this field set to 1.  */
    thread_ptr -> tx_thread_win32_suspension_type =  0;

    /* Clear the disabled count that will keep track of the
       tx_interrupt_control nesting.  */
    thread_ptr -> tx_thread_win32_int_disabled_flag =  0;

    /* Setup a fake thread stack pointer.  The stack end points at the last byte of the
       thread's stack area and is therefore not necessarily aligned, so round the result
       down to a ULONG boundary.  This pointer is dereferenced as a ULONG below and is
       also the starting value of the stack checking logic's highest used pointer.  */
    fake_stack_ptr =  TX_POINTER_TO_ALIGN_TYPE_CONVERT(((CHAR *) thread_ptr -> tx_thread_stack_end) - 8);
    fake_stack_ptr =  fake_stack_ptr & (~((ALIGN_TYPE) (sizeof(ULONG) - 1)));
    thread_ptr -> tx_thread_stack_ptr =  TX_ALIGN_TYPE_TO_POINTER_CONVERT(fake_stack_ptr);

    /* Clear the first word of the stack.  */
    *(((ULONG *) thread_ptr -> tx_thread_stack_ptr) - 1) =  0;

    /* Make the thread initially ready so it will run to the initial wait on
       its run semaphore.  */
    ResumeThread(thread_ptr -> tx_thread_win32_thread_handle);
}


DWORD WINAPI _tx_win32_thread_entry(LPVOID ptr)
{

TX_THREAD  *thread_ptr;

    /* Pickup the current thread pointer.  */
    thread_ptr =  (TX_THREAD *) ptr;

    /* Now suspend the thread initially.  If the thread has already
       been scheduled, this will return immediately.  */
    WaitForSingleObject(thread_ptr -> tx_thread_win32_thread_run_semaphore, INFINITE);

    /* Call ThreadX thread entry point.  */
    _tx_thread_shell_entry();

    return EXIT_SUCCESS;
}

