# /***************************************************************************
#  * Copyright (C) 2026 Eclipse ThreadX contributors
#  *
#  * This program and the accompanying materials are made available under the
#  * terms of the MIT License which is available at
#  * https://opensource.org/licenses/MIT.
#  *
#  * AI Disclosure: This file was largely AI-generated by Copilot (Sonnet 4.6).
#  * The AI-generated portions may be considered public domain (CC0-1.0)
#  * and not subject to the project's licence. The human contributor has
#  * reviewed and verified that the code is correct.
#  *
#  * SPDX-License-Identifier: MIT and CC0-1.0
#  ***************************************************************************/

# CMake toolchain file for CORE-V MCU (CV32E40P, RV32IMC)
#
# Uses the Ubuntu gcc-riscv64-unknown-elf package (gcc-riscv64-unknown-elf) to
# cross-compile for a 32-bit RISC-V target.  This package ships a full multilib
# tree including rv32im/ilp32/libgcc.a which is required for soft-float linking.
# Do NOT use the riscv-collab riscv64-unknown-elf toolchain from /opt/riscv —
# it does not ship rv32 multilib and will produce __clzsi2 linker errors.
#
# Target ISA : rv32imc_zicsr  (integer, multiply, compressed, Zicsr)
# ABI        : ilp32           (32-bit int/long/ptr, no hardware FP)
# Code model : medlow          (addresses in [0, 2 GiB))

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv)

set(THREADX_ARCH "risc-v32")
set(THREADX_TOOLCHAIN "gnu")

set(ARCH_FLAGS "-march=rv32imc_zicsr -mabi=ilp32 -mcmodel=medlow")
set(CFLAGS   "${ARCH_FLAGS}")
set(ASFLAGS  "${ARCH_FLAGS}")
set(LDFLAGS  "${ARCH_FLAGS}")

# Toolchain binaries: use the Ubuntu gcc-riscv64-unknown-elf package, which ships
# full multilib libraries (including rv32im/ilp32/libgcc.a with __clzsi2 etc.).
# The riscv-collab riscv64-unknown-elf toolchain (typically at /opt/riscv) does
# NOT ship an rv32 multilib and will cause __clzsi2 linker errors with -nodefaultlibs.
# Using the absolute path avoids picking up a non-multilib toolchain via PATH.
#
# Install with:  sudo apt-get install gcc-riscv64-unknown-elf
# or run:        ports/risc-v32/gnu/example_build/core_v_mcu/install_deps.sh
set(CMAKE_C_COMPILER    /usr/bin/riscv64-unknown-elf-gcc)
set(CMAKE_CXX_COMPILER  /usr/bin/riscv64-unknown-elf-g++)
set(AS                  /usr/bin/riscv64-unknown-elf-as)
set(AR                  /usr/bin/riscv64-unknown-elf-ar)
set(OBJCOPY             /usr/bin/riscv64-unknown-elf-objcopy)
set(OBJDUMP             /usr/bin/riscv64-unknown-elf-objdump)
set(SIZE                /usr/bin/riscv64-unknown-elf-size)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Use static library for compiler feature probing (no linker script yet)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_FLAGS   "${CFLAGS}"  CACHE INTERNAL "c compiler flags")
set(CMAKE_CXX_FLAGS "${CFLAGS}"  CACHE INTERNAL "cxx compiler flags")
set(CMAKE_ASM_FLAGS "${ASFLAGS} -D__ASSEMBLER__" CACHE INTERNAL "asm compiler flags")
set(CMAKE_EXE_LINKER_FLAGS "${LDFLAGS}" CACHE INTERNAL "exe link flags")

set(CMAKE_C_FLAGS_DEBUG   "-Og -g -ggdb3" CACHE INTERNAL "c debug flags")
set(CMAKE_CXX_FLAGS_DEBUG "-Og -g -ggdb3" CACHE INTERNAL "cxx debug flags")
set(CMAKE_ASM_FLAGS_DEBUG "-g -ggdb3"     CACHE INTERNAL "asm debug flags")

set(CMAKE_C_FLAGS_RELEASE   "-Os" CACHE INTERNAL "c release flags")
set(CMAKE_CXX_FLAGS_RELEASE "-Os" CACHE INTERNAL "cxx release flags")
set(CMAKE_ASM_FLAGS_RELEASE ""    CACHE INTERNAL "asm release flags")
