# This is a basic workflow to help you get started with Actions

name: ports_arch_check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
    paths:
      - ".github/workflows/ports_arch_check.yml"
      - 'common/**'
      - 'common_modules/**'
      - 'common_smp/**'
      - 'ports/**'
      - 'ports_modules/**'
      - 'ports_smp/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout sources recursively
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_SCOPED_TOKEN }}
        submodules: true

    # Copy ports arch
    - name: Copy ports arch
      run: |
        scripts/copy_armv7_m.sh && scripts/copy_armv8_m.sh && scripts/copy_module_armv7_m.sh
        if [[ -n $(git status --porcelain) ]]; then
          echo "Ports for ARM architecture is not updated"
          exit 1
        fi



